### ISSUE TITLE
Authorization Successful and then nothing happens

### ISSUE THREAD

**Issue by Poseidon444** [KRTirtho/spotube#10]
**Describe the bug**
Authorization is successful but after that nothing happens, it stays stuck on the screen where it asks for credentials
**To Reproduce**
Steps to reproduce the behaviour:
1. launch the app
2. Add credentials
3. authorize yourself

**Installation Source/Method**
- Package Manager: pacman
- Community Repo: aur
- Binary Source: https://aur.archlinux.org/packages/spotube/

**Desktop (please complete the following information):**
 - OS: Arch
 - Version :2022.01.01

**Comment by KRTirtho** [comment]
Do you have any modern browser installed? There must something wrong in your OS's dbus configuration

Run following in terminal:
```shell
xdg-open https://google.com
``` 
It should open a browser window and navigate to `google.com`. If nothing happens in this case too then something is definitely wrong in your OS's dbus configuration or x-org/wayland configuration

**Comment by Poseidon444** [comment]
it Opens up firefox with google.com

**Comment by KRTirtho** [comment]
Well, I found the issue. The same issue was occurring while I was packaging for flatpak. The `canLaunch` function of `url_launcher` package isn't that stable in linux & returns false even if the link is launchable
Don't worry it'll be fixed in the next release

**Comment by Poseidon444** [comment]
Glad I could be of help! and thanks a lot for making something this awesome!
I will be closing the issue since it will be fixed
Thank you!

**Comment by subdavis** [comment]
I've just hit this.  I see the issue is closed, but there hasn't been a new release.

Please notify the thread when this lands in a release.  Thanks!

**Comment by CyberWorrior2222** [comment]
May I add that for me Opera GX was causing the error. I had to change my browser to Edge for it to work.
