### ISSUE TITLE
Issues on User Experience | Usability Or UI's Bugs - Enhancement

### ISSUE THREAD

**Issue by milanshresta** [KRTirtho/spotube#1005]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Inconsistent Design and need to improvement the User Experience. It will make it more approachable if the UI changeimprovechanges improve changes

### Expected Behavior

Solving Usability Issues with updating UI'sby

### Steps to reproduce

I Explored it and Found out the room for improvement

### Operating System

Windows

### Spotube version

v3.4.0

### Installation source

WinGet (Windows), Scoop (Windows)

### Additional information

Will update the UX side

**Comment by KRTirtho** [comment]
Duplicate of #395
