### ISSUE TITLE
Vertical Scrollbar respond to horizontal content and vertical content 

### ISSUE THREAD

**Issue by yanisallouch** [KRTirtho/spotube#1017]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On the search screen I experienced an unusual visual bug related to the vertical Scrollbar (VS).
The VS is responding as usual to vertical content. But also respond to horizontal content.

### Expected Behavior

I expected the vertical Scrollbar to respond and act upon vertical content only.

### Steps to reproduce

Probably steps 2 through 7 are useless
1. Opened the app.
2. I connected my Spotify account
3. I moved around some screen
4. I've opened and closed the app multiple times
5. I've moved around again 
6. I've played a music from the home screen
7. Again step 4 and 5
8. I searched for 'royality free' music
9. Scrolled down vertically to 'playlist'
10. Scrolled down horizontally on playlist content.
11. Noticed that the Scrollbar is responding to VS and HS

### Operating System

Android 11, One Plus : Oxygen 11.1.2.2

### Spotube version

3.4.0

### Installation source

GitHub Releases (Binary)

**Comment by KRTirtho** [comment]
Wow, that's a great find tbh. I didn't notice it until now😂

**Comment by KRTirtho** [comment]
Please include a screen recording if possible for Future easiness

**Comment by yanisallouch** [comment]
Hello @KRTirtho 

Here is the screen recording :
https://github.com/KRTirtho/spotube/assets/75087263/b177fab5-bf39-40e8-a95e-f3b892347b5b

**Comment by KRTirtho** [comment]
Fixed it
