### ISSUE TITLE
Pitch Black mode doesn't appear to be working 

### ISSUE THREAD

**Issue by jnobbe** [KRTirtho/spotube#1019]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Toggling Pitch Black mode doesn't seem to change anything.

### Expected Behavior

I expect the gray areas to turn completely black.

### Steps to reproduce

Enable Pitch Black mode.

### Operating System

Android

### Spotube version

3.3.0

### Installation source

F-Droid (Android)

### Additional information

Pixel 7 Pro, Android 14 build UQ1A.231205.015.
Spotube build 26.

**Comment by KRTirtho** [comment]
Upgrade to 3.4.0. It has been fixed
