### ISSUE TITLE
New Releases is just boilerplate

### ISSUE THREAD

**Issue by jnobbe** [KRTirtho/spotube#1021]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The New Releases row shows boilerplate entries and not real ones.

### Expected Behavior

The entries should be what I would expect to see on Spotify.

### Steps to reproduce

Open the application and navigate to the homepage.

### Operating System

Windows 11 & Android 14.

### Spotube version

3.4.0 & 3.3.0

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev)

### Additional information

I'm seeing this on both Windows (using 3.4.0) and Android (using 3.3.0). Android version was installed from F-Droid and is build 26.

Windows info:
Edition	Windows 11 Pro
Version	23H2
OS build	22635.2915
Experience	Windows Feature Experience Pack 1000.22682.1000.0

Pixel 7 Pro, Android 14 build UQ1A.231205.015.
Spotube build 26.

**Comment by taha-ghadirian** [comment]
Hello @jnobbe, I hope this message founds you well. 
Have you tried changing the source on player? If not please check this option :D 
![image](https://github.com/KRTirtho/spotube/assets/36773254/8929e065-d517-4fc4-885f-91ed3fcc78c7)

**Comment by jnobbe** [comment]
Hi @taha-ghadirian, I checked this morning, and it looks to be working as expected now.

![image](https://github.com/KRTirtho/spotube/assets/1395529/199683aa-4d5e-42a0-a05d-b4897605470a)

**Comment by taha-ghadirian** [comment]
> Hi @taha-ghadirian, I checked this morning, and it looks to be working as expected now.

That's great! I'm happy to hear that. I believe it takes some extra time for the API to sync with YouTube, and since it's a third-party API for YouTube, it's beyond Spotube's control to expedite this synchronization.
You can always use `Alternative track sources` option in the application to check if there is new sources available.

**Comment by jnobbe** [comment]
@taha-ghadirian, I think this can be closed -- I will open a new ticket if I see anything off with it again. Thanks!
