### ISSUE TITLE
"The unfollowed artist" issue

### ISSUE THREAD

**Issue by Silvere717** [KRTirtho/spotube#1033]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![Screenshot_2024-01-07-11-17-19-095_oss krtirtho spotube](https://github.com/KRTirtho/spotube/assets/155870532/4fc355b7-3fab-418f-902f-624b7bf19608)

### Expected Behavior

It was expected that the page would open without any error and I would be able to follow the artist whom I don't follow on Spotify. 

### Steps to reproduce

1. I opened the app
2. I wanted to listen to King's songs (Indian artist), but on Spotify I don't used to follow him. 
3. I searched king, and the opened his profile 
4. But then the error occurred
5. I tried opening the other artists accounts, whom I didn't follow on Spotify and the same error repeated. 

### Operating System

Android

### Spotube version

v3. 4.0

### Installation source

Play Store (Android)

### Additional information

Would request to fix this issue as soon as possible, cause I can't live without songs and ads in between are the worst.

**Comment by taha-ghadirian** [comment]
Duplicate #1018.
