### ISSUE TITLE
Individual track selection

### ISSUE THREAD

**Issue by asuka-405** [KRTirtho/spotube#1035]
### Pain

I cant select individual track in any playlist.
Track selection is only possible with select all button at the top.
![2024-01-07 13-33-48](https://github.com/KRTirtho/spotube/assets/97630173/f2fab48b-6c18-4269-9c92-362383aea05c)

### Suggested solution

If possible please add a checkbox in front of every track and a shortcut to same, eg ctrl + left click

**Comment by taha-ghadirian** [comment]
You should Hold on music you want to select.
