### ISSUE TITLE
Only 80 Songs in playslist

### ISSUE THREAD

**Issue by Carbon-Axion** [KRTirtho/spotube#1039]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Playlists are limited to 80 songs

### Expected Behavior

have all of them

### Steps to reproduce

1. open
2. log into spotify
3. playlist has only 80 songs

### Operating System

Windows 11

### Spotube version

v3.4.0

### Installation source

GitHub Releases (Binary)

**Comment by KRTirtho** [comment]
Here's a 10,000+ songs playlist https://open.spotify.com/playlist/4xHmVFfa1xBKaCBrefgVRv which loads as much as you want.

**Comment by EpicGamer243** [comment]
------- DEVICE INFO -------
computerName: Axion
numberOfCores: 20
systemMemoryInMegabytes: 16384
------- APP INFO -------
environment: release
version: 3.4.0
appName: spotube
buildNumber: 
packageName: spotube
---------- ERROR ----------
type 'Null' is not a subtype of type 'Map<String, dynamic>'
------- STACK TRACE -------
#0      Playlists.getTracksByPlaylistId.<anonymous closure> (package:spotify/src/endpoints/playlists.dart:41)
#1      MappedIterable.elementAt (dart:_internal/iterable.dart:385)
#2      ListIterator.moveNext (dart:_internal/iterable.dart:354)
#3      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189)
#4      new _GrowableList.of (dart:core-patch/growable_array.dart:150)
#5      new List.of (dart:core-patch/array_patch.dart:39)
#6      SetBase.toList (dart:collection/set.dart:119)
#7      PlaylistQueries.tracksOf (package:spotube/services/queries/playlist.dart:220)
<asynchronous suspension>
#8      _AsyncCompleter.complete (dart:async/future_impl.dart:41)
<asynchronous suspension>
#9      Retryer.retryOperation (package:fl_query/src/core/mixins/retryer.dart:17)
<asynchronous suspension>
#10     CancelableCompleter.complete.<anonymous closure> (package:async/src/cancelable_operation.dart:425)
<asynchronous suspension>
------- CUSTOM INFO -------

this is the log, for one reason its only mine and a couple others

**Comment by EpicGamer243** [comment]
heres the playlist with the problem
https://open.spotify.com/playlist/7DNvHhBG0CuQXGGQZHuWzk?si=b0d0f150f8d14c02

**Comment by KRTirtho** [comment]
Looks like a rare case. It only happens for a small amount of playlists.

**Comment by EpicGamer243** [comment]
I made a copy but now the newest added order is fucked
