### ISSUE TITLE
Target of URI doesn't exist: 'package:spotube/models/generated_secrets.dart'.

### ISSUE THREAD

**Issue by Wusssy** [KRTirtho/spotube#105]
The proejct does't have the file which is "generated_secrets.dart".

[.gitignore](https://github.com/KRTirtho/spotube/blob/26652d37349318393d5b640696d90853e01b9f09/.gitignore)
This file have a rule "lib/models/generated_secrets.dart". Can you delete the rule, please.

**Comment by KRTirtho** [comment]
Please read [CONTRIBUTION.md](https://github.com/KRTirtho/spotube/blob/master/CONTRIBUTION.md#your-first-code-contribution) first then run the project locally
