### ISSUE TITLE
Bug by piped proxy

### ISSUE THREAD

**Issue by Pinguin10000** [KRTirtho/spotube#1057]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Piped proxy error 

### Expected Behavior

Error when playing songs

### Steps to reproduce

1. Open app. 
2. Navigate to Settings
3. Scroll down to "Audio Source"
4. Select piped Off
5. Can't Find Anything "Invalid Arguments" 

### Operating System

Android 14

### Spotube version

3.4.0

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev), GitHub Releases (Binary)

**Comment by KRTirtho** [comment]
This has been fixed in v3.5.0
