### ISSUE TITLE
Search for alternative sources not working

### ISSUE THREAD

**Issue by Sommergoldhaehnchen** [KRTirtho/spotube#1059]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When opening the alternative source popup in playback there is a search icon in the top right corner. If you type, it shows up the right song. But clicking on them results in nothing.

### Expected Behavior

The song I click in the alternative source popup after using the search feature within, should be playing.

### Steps to reproduce

1. Start a song or a playlist.
2. During playback click on the alternative source button.
3. Within at the top right there is a search icon. Click it.
4. Type a song title so that it appears below.
5. Click on the title.

### Operating System

Windows 11

### Spotube version

v3.4.0

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev)

**Comment by taha-ghadirian** [comment]
Same issue for me, on ArchLinux. 

### Steps to reproduce

1. Play a music (Ex. `Hich` By `Theshey`)
2. Seems that default source isn't correct. 
3. Try to change source using `Alternative sources` option.
4. Can't find the right source on list, so I search for it on search box (Ex. `Theshey Hich`)
![image](https://github.com/KRTirtho/spotube/assets/36773254/57d91cfb-ac94-42fe-9ef5-07267ccecf99)
5. Click on the right source (Ex. `05 - Hich` by `Theshey` Duration `3:43`)
6. Nothing happens

### Operating System

Arch linux

### Spotube version

V3.4.0 / Build no. 27 / Installed via yay (AUR)

### Installation source

Arch User Repository (AUR)

### Additional information

### IMPORTANT:
Alternative sources work correctly if we don't search, but the option broke when trying to search for not listed source.
