### ISSUE TITLE
Application will not run on KDE Plasma

### ISSUE THREAD

**Issue by iceman1789** [KRTirtho/spotube#106]
Cannot run Spotube  on a minimal Arch linux system using KDE Plasma. Neither the AUR nor the AppImage packages worked. They work fine if switching to an XFCE session however (on the same system).

Steps to reproduce:
Install and try to run Spotube on a KDE session of an Arch linux system

Expected behavior: application should run

Screenshots
When the application runs in KDE the main window will not load, an icon appears on the taskbar but it won't go any further than this:
![Screenshot_20220607_021510](https://user-images.githubusercontent.com/107024765/172312848-4016d51f-7329-4f51-a3c4-0c41fb3ae4bf.png)
There are no other error messages, the icon just stays in the taskbar indefinitely.

Installation methods:
AUR and AppImage per readme instructions.

OS: Arch linux basic install with KDE and XFCE desktop environment installed (pacman -S plasma xfce4)

**Comment by KRTirtho** [comment]
I guess you're missing some gtk packages. But finding that missing piece of puzzle is gonna hard
I suggest you for the time being see if the flatpak version works on your machine or not
If the flatpak version does work yoi can be sure rhere were some lack of default gtk dependencies

**Comment by KRTirtho** [comment]
Closing due to one month of inactivity
