### ISSUE TITLE
Artist entry in library displays an error message

### ISSUE THREAD

**Issue by escortgoj** [KRTirtho/spotube#1060]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When selecting an artist in the library tab an error message is dsiplayed, i.e:
''type 'double' is not a subtype of type 'int?'in type cast''
 

### Expected Behavior

no error message and the ability to interact with the artist entry

### Steps to reproduce

1. Click an artist (favorite or freshly searched)
2. Artist menu displays normally for a couple of seconds
3. Eroor message --> ''type 'double' is not a subtype of type 'int?'in type cast

### Operating System

Android, Linux

### Spotube version

since version 3.2

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev), GitHub Releases (Binary), Play Store (Android), F-Droid (Android)

**Comment by mithras666** [comment]
You have not searched the existing issues. There are at least 4 open issues already.

**Comment by taha-ghadirian** [comment]
Duplicate to #1018
