### ISSUE TITLE
iOS background cannot play

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [KRTirtho/spotube#1061]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

iOS cannot play when app in bg

### Expected Behavior

can play any time

### Steps to reproduce

1，sing IPA and install ipa
2 play 
3 put app in BG mode

### Operating System

ios

### Spotube version

latest

### Installation source

GitHub Actions (Nightly Binary)

**Comment by AidanTheBandit** [comment]
Does the app have the background permission in XCode?

**Comment by KRTirtho** [comment]
@liuhuapiaoyuan you check if it works now by downloading and installing the nightly version

**Comment by liuhuapiaoyuan** [comment]
Perfect!
