### ISSUE TITLE
Not sync lyrics

### ISSUE THREAD

**Issue by Ercraftcitocito** [KRTirtho/spotube#1076]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The sync lyrics are not sync well. It is suposed that the bold line is the one that is being singed but it's not.

### Expected Behavior

The bold line is being singed.

### Steps to reproduce

Open the app,
search for a song with lyrics,
go to the lyrics page.

### Operating System

Windows

### Spotube version

v3.4.0

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev)

### Additional information

Probably other OS.

**Comment by KRTirtho** [comment]
Apparently, Spotify lyrics are [Region Locked](https://community.spotify.com/t5/Content-Questions/quot-Couldn-t-load-the-lyrics-for-this-song-quot-error-in-2023/td-p/5528963/page/4) so some song's lyrics, even the entire song might not be available in some regions (it sucks ik).

So we've added [LRCLIB](https://lrclib.net) as a fallback lyrics provider and it also supports synced lyrics

Support added in 5afe823
