### ISSUE TITLE
YouTube login

### ISSUE THREAD

**Issue by Carl-ki** [KRTirtho/spotube#1079]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

Artists don't get paid for their work.

### Suggested solution

I'd like to be able to login to my YouTube account with the app, so that artists get paid from my Premium subscription when I listen to their songs.

### Additional information

I would be willing to pay developers for this feature to be added, and I hope others who are interested can chip in too.

**Comment by KRTirtho** [comment]
Duplicate of #633
