### ISSUE TITLE
AppImage mentioned in README but missing in releases 

### ISSUE THREAD

**Issue by truegilb** [KRTirtho/spotube#1082]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

AppImage is mentioned in README with [link](https://github.com/KRTirtho/spotube/releases/latest/download/Spotube-linux-x86_64.AppImage), which is a 404 link.

### Expected Behavior

Either build AppImage in releases or remove it from README (I did see a number of open issues related to AppImage). 

### Steps to reproduce

1. Visit https://github.com/KRTirtho/spotube/
2. Scroll down to README and find the AppImage link https://github.com/KRTirtho/spotube/releases/latest/download/Spotube-linux-x86_64.AppImage
3. Clicking it yields 404

### Operating System

Ubuntu 22.04

### Installation source

GitHub Releases (Binary)

**Comment by KRTirtho** [comment]
AppImage support is temporarily removed due to instability of this package format

**Comment by Allen393** [comment]
[]()

**Comment by Allen393** [comment]
https://bitly.ws/39HIM

**Comment by Allen393** [comment]
https://bitly.ws/39HIM

**Comment by KRTirtho** [comment]
@Allen393 banned for phishing attempt

**Comment by Samueru-sama** [comment]
> AppImage support is temporarily removed due to instability of this package format

Hello, can you tell me what the issues are? 

I notice you already have a portable zipped build for linux, that can be wrapped into an appimage for example.

**Comment by KRTirtho** [comment]
I'm closing this. But the main thread is continued in #1292
