### ISSUE TITLE
Display a better message on missing song lyrics

### ISSUE THREAD

**Issue by meenbeese** [KRTirtho/spotube#1085]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

<p>Users don't need to see an exception when lyrics for a song are not found, it is not a friendly UX.</p>
</br>
<img src="https://github.com/KRTirtho/spotube/assets/114044633/bba64ae2-a39e-4baf-b311-945e4dd56a6d" width="65%" height="65%">

### Suggested solution

We should display a warning message (and not an exception) in a pleasant way and maybe direct them to other websites.

**Comment by ninjakappa007** [comment]
Hi ..
Can i take the issue .

**Comment by prateek-lakhanpal** [comment]
> Hi .. Can i take the issue .

go for it!

**Comment by KRTirtho** [comment]
@ninjakappa007 No worries amigo. I got it.
