### ISSUE TITLE
How to log-in

### ISSUE THREAD

**Issue by MrConqueror** [KRTirtho/spotube#109]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Installation Source/Method**
- Package Manager: <e.g flatpak/chocolatey>
- Community Repo: <e.g AUR/appimagehub>
- Binary Source: <resource_url>

**Desktop (please complete the following information):**
 - OS: [e.g. archlinux]
 - Version [e.g. v1.0.0]

**Smartphone (please complete the following information):**
 - Version [e.g. v1.0.0]

**Additional context**
Can someone teach me how to login using Spotify account

**Comment by KRTirtho** [comment]
https://github.com/KRTirtho/spotube#optional-configurations

**Comment by MrConqueror** [comment]
> https://github.com/KRTirtho/spotube#optional-configurations

![IMG_20220610_121142](https://user-images.githubusercontent.com/102837820/172988855-40d6aee8-24c3-4775-b533-72501841902b.jpg)
Yow, Look at this what's wrong???

**Comment by KRTirtho** [comment]
You're missing a step. Read the Docs carefully before submitting an issue

Step 3: After Giving the app a name & description, edit settings & add `http://localhost:4304/auth/spotify/callback` as Redirect URI for the app. Its important for authenticating
![Step 3](https://user-images.githubusercontent.com/61944859/111768971-d308a180-88d2-11eb-9108-3e7444cef049.png)

Sharing the Client ID & Client Secret of your Spotify application is really vulnerable. Delete the previously created application & start from all over

**Comment by MrConqueror** [comment]
> You missing a step. Read the Docs carefully before submitting an issue
> 
> Step 3: After Giving the app a name & description, edit settings & add `http://localhost:4304/auth/spotify/callback` as Redirect URI for the app. Its important for authenticating ![Step 3](https://user-images.githubusercontent.com/61944859/111768971-d308a180-88d2-11eb-9108-3e7444cef049.png)
> 
> Sharing the Client ID & Client Secret of your Spotify application is really vulnerable. Delete the previously created application & start from all over

Hi, Sorry i made a mistake, Anyway I got in Thanks, But there's a problem. Where can we see our downloaded song i tried it nowhere to found. and Can you make an album cover Square or make it an option to choose between them. somebody probably want circle album.

**Comment by KRTirtho** [comment]
The downloaded Songs can be found inside the `Downloads/Spotube` folder of your Platform

> Can you make an album cover Square or make it an option to choose between them. somebody probably want circle album

The album arts are already squared. What are you talking about then?

**Comment by MrConqueror** [comment]
> The downloaded Songs can be found inside the `Downloads/Spotube` folder of your Platform
> 
> > Can you make an album cover Square or make it an option to choose between them. somebody probably want circle album
> 
> The album arts are already squared. What are you talking about then?

![IMG_20220610_125608](https://user-images.githubusercontent.com/102837820/172993188-9ca8061b-8786-4921-914b-0c62983616ae.I thought 

> The downloaded Songs can be found inside the `Downloads/Spotube` folder of your Platform
> 
> > Can you make an album cover Square or make it an option to choose between them. somebody probably want circle album
> 
> The album arts are already squared. What are you talking about then?

![IMG_20220610_125608](https://user-images.githubusercontent.com/102837820/172993293-079c08f9-752e-489b-9910-0d4d4138e02c.jpg)
And I thought when we download a Song, we will see it within the app. And play it Offline.
