### ISSUE TITLE
broken link to artist detail in linux

### ISSUE THREAD

**Issue by gmorten1** [KRTirtho/spotube#1107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

click artist name in playlist or queue and get error message: `type 'double' is not a subtype of type 'int?' in type cast`

### Expected Behavior

see artist details

### Steps to reproduce

1. load playlist
2. click artist name on left of track row
3. see error message

### Operating System

linux - ubuntu 22.04.3 LTS installed from .deb

### Spotube version

Spotube v3.4.0

### Installation source

GitHub Releases (Binary)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by Tilmanfs95** [comment]
The same happens with my android phone (samsung a52s 5g - android version 14)

**Comment by gmorten1** [comment]
thanks bowarc, i missed that. i'll close this issue as duplicate of #1018 and anxiously await the update ;)
