### ISSUE TITLE
Adding (serious) support for YouTube?

### ISSUE THREAD

**Issue by CavaleriOmar** [KRTirtho/spotube#111]
The description reads "streams music using Youtube" but I 

I couldn't figure out HOW to use youtube.

I'd prefer to be able to use the playlists I have saved on my Google account rather than the Spotify ones (I listen to a lot of OST remixes that are impossible to find on Spotify but are well featured on YouTube), maybe sharing the link to it, maybe doing direct YouTube access in the app...

Would that be possible?

**Comment by KRTirtho** [comment]
Spotube is a Spotify Client & only supports Spotify authentication & Spotify data. It uses youtube for streaming/downloading the audio track provided by a Spotify playlist/album as Spotify doesn't support playback on non-premium accounts & Spotify desktop app is basically a chrome instance  wich comes with high & inefficient resource usage
Currently, Spotube has no future plans about supporting YouTube Music playlists or featured playlists. 
What you're actually looking for is a YouTube music client

**Comment by owencz1998** [comment]
Youtube music self api works faster  and smoother tho doesn't it

**Comment by KRTirtho** [comment]
Can you express your thoughts a bit more clearly, please?

**Comment by owencz1998** [comment]
Well if you use the youtube music shelf api the loading times for songs will be better almost instantly plays without waiting and when playing music it won't use the music videos but will use the actual music itself and its capability of downloading songs works grate

**Comment by owencz1998** [comment]
Sorry I meant youtube music private api

**Comment by KRTirtho** [comment]
Spotube already uses the audioOnly format of the video. So latency is pretty much same as YouTube music unless someone is living in mainland china & using proxy. Talking about download track capabilities, it depends on your location. If your country has official YouTube/Google servers, the download speed will be at it maximum (2.5-7 mb/s)

**Comment by owencz1998** [comment]
Ahh ok mate haha o see what u mean 👍
