### ISSUE TITLE
Showing wrong lyrics....

### ISSUE THREAD

**Issue by 0nahid** [KRTirtho/spotube#112]
**Describe the bug**
Showing the wrong lyrics on country wise song
If possinle use musixmatch's api

**Comment by KRTirtho** [comment]
Currently Spotube can only provide lyrics of popular tracks. It basically depends on Genius Lyrics
> If possinle use musixmatch's api

They only provide 30% of the lyrics of every track for free version of the API. It's not suitable for Spotube

**Comment by wongcheehong** [comment]
Try play music called Left and Right by Charlie Puth. It show wrong lyrics

**Comment by XenHat** [comment]
I have the same issue with "Black Corridor" by PETER LAKE.

**Comment by KRTirtho** [comment]
Spotube 2.7.0 now uses Official Spotify Lyrics API (MusixMatch) so no more wrong lyrics
