### ISSUE TITLE
ANIMATION BUG

### ISSUE THREAD

**Issue by some1zealeous** [KRTirtho/spotube#1120]
### **ANIMATION**
Swiping up and down the audio panel or switch to other sections in the bottom produce animation lagging which really bugs me to go ahead with smooth flow.

### **EXPECTED BEHAVIOUR**
Expected this issues to be fixed and made this application more convincible to use since i like the user interface - It's simple, clean and attractive to user as well.

### **Steps To Produce**
1. Opened the app.
2. Searched any audio in search bar.
3. Played any audio.
4. Now changing to other panel or section while music being played produce 
     unwanted lagging, it's seems more while the search area section is filled with listed 
     searched musics.

https://github.com/KRTirtho/spotube/assets/70045510/34c951ea-0c52-47b6-831c-4994d908665b

### **Operating System**
Android.

### **Spotube Version**
v3.4.0

**Comment by mdkaif01** [comment]
Trying to delete this issue

**Comment by KRTirtho** [comment]
The cache management was improved in 6673e5a. You can try out that using the nightly build
