### ISSUE TITLE
Automatically Permanently Remember Alternative Song Source

### ISSUE THREAD

**Issue by fleamour** [KRTirtho/spotube#1127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

Not all song results are 100% accurate from Spotify playlist.

### Suggested solution

I would like option to permanently set & forget alternative song source. 

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
It's a bug actually. During refactoring this bug happend

**Comment by KRTirtho** [comment]
Duplicate of #840
