### ISSUE TITLE
Setting for scrollbar increment

### ISSUE THREAD

**Issue by wmgaertner** [KRTirtho/spotube#114]
**Is your feature request related to a problem? Please describe.**
On windows, the mouse wheel scrolls the client rather slowly. 

**Describe the solution you'd like**
A setting added that allows the user to control the scrolling speed.

**Additional context**
[Here is a clip of me using full swipes of the wheel to scroll down followed by the smallest increment my mouse allows.](https://imgur.com/9199DXu)
Spotube v2.2.1
Windows 10

**Comment by KRTirtho** [comment]
I've checked, in Linux & even in Mac the scrolling is fine. But only in Windows the scrolling is super slow in Spotube

**Comment by KRTirtho** [comment]
It appears to be fixed. Can you verify that please @wmgaertner ?

**Comment by wmgaertner** [comment]
Yes it has been fixed 👍
