### ISSUE TITLE
Add OS Media Controls

### ISSUE THREAD

**Issue by onlyreportingissues** [KRTirtho/spotube#115]

**Comment by flexagoon** [comment]
It seems like using [just_audio_background](https://pub.dev/packages/just_audio_background) instead of [audio_service](https://pub.dev/packages/audio_service) can fix this issue.

**Comment by flexagoon** [comment]
It seems like using [just_audio_background](https://pub.dev/packages/just_audio_background) instead of [audio_service](https://pub.dev/packages/audio_service) can fix this issue.

**Comment by KRTirtho** [comment]
@flexagoon just_audio_background integrates directly with just_audio playlists so even though play/pause work, next/previous track doesn't work for android. Thus I had to implement audio_services manually since Spotube custom playback manager. Because of this Spotube is able to support next/prev+play/pause track in android
Also @onlyreportingissues is talking about desktop media controls

**Comment by KRTirtho** [comment]
Lucky for Linux users, I've recently implemented dbus MPRIS (Media Player Remote Interfacing Specification) for spotube. That means OS Media Controls (only hardware keyboard media controls) are now supported in Spotube

**Comment by flexagoon** [comment]
> is talking about desktop media controls

@KRTirtho ah, alright. Are Android media controls planned then? It's the biggest thing stopping me from using Spotube, because the lack of media controls 

1. Is just inconvinient
2. Means that Last.fm scrobbling with apps like Pano Scrobbler doesn't work

**Comment by KRTirtho** [comment]
Android Media Controls (Notification Panel & Lock Screen Media Player) are already available in the latest apk

**Comment by flexagoon** [comment]
Clarification: I'm talking about the seekbar in the notification.

**Comment by KRTirtho** [comment]
Ohh, ok now I understand. Usually in other platforms by Media Controls only Next/Prev, Play/Pause and Stop buttons are meant. Completely didn't know that Android allows Seekbar in Notification panel

**Comment by flexagoon** [comment]
@KRTirtho iOS and Linux (KDE at least) also have a seekbar in OS Media Controls though 🤔

**Comment by KRTirtho** [comment]
Well, The Android & Linux version now has SeekBar support in the latest release v2.3.0

**Close this issue if your requested feature/bug is implemented/fixed + released**

**Comment by fleixi** [comment]
You say spotube is supporting mpris, but i dont have any control in the kde systemtray-widget for mpris control. Are only keyboard buttons working or do i miss something.

System is Arch-Linux and i have installed spotube via aur "spotube-bin" (Version: 2.7.1)

**Comment by RaptaG** [comment]
Added in 3.0.0

**Comment by Schorsch980** [comment]
Hi, for me these media controls don't work on Version 3.5 (Android, via F-Droid).
I use Spotube on an Android Naviceiver, Media Control buttons are on the steering wheel. Media controls do work with Spotify app and all other media apps (e.g. Poweramp, DAB-Z), just not on Spotube...
