### ISSUE TITLE
Scrolling in long playlists not smooth and missing a side scroll bar in playlist/album screen

### ISSUE THREAD

**Issue by PhilZ-cwm6** [KRTirtho/spotube#1158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

When scrolling inside very long playlists like hundreds of files, the scrolling expierience is laggy
It seems like that it only loads a bunch of files and when we reach the end of the buffered part of teh playlist, it stops and we have to wait for the next songs in the list to load
It also misses a side scroll bar for quicker navigation to the bottom/middle of long playlists
Spotify app doesn't suffer from these issues

### Suggested solution

Load all teh playlist and not buffer part of it, or just enhance the scrolling expierience
Add a side scroll bard

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
This happens as Spotube utilizes pagination to avoid loading big playlists at once, which takes time to load and freezes the UI
