### ISSUE TITLE
[Arch Linux] Spotube dumps core on Sway Wayland

### ISSUE THREAD

**Issue by Thymelizabeth** [KRTirtho/spotube#117]
**Describe the bug**
When Spotube is run from the command line, it opens an empty window. When this window is closed, the only message in the terminal is `zsh: segmentation fault (core dumped)  spotube`

**To Reproduce**
1. Open terminal
2. Run command `spotube`
3. Close window that appears

**Expected behavior**
Spotube opens and runs reasonably well.

**Screenshots**
![19-06-2022_22-06-1655636143](https://user-images.githubusercontent.com/99952495/174477581-cdfab0ca-bf90-4fb6-9e7b-f4ab4ecfcb04.jpg)
![19-06-2022_22-06-1655636159](https://user-images.githubusercontent.com/99952495/174477590-98f9495f-fb14-4997-9bba-ea4a0b80b35e.jpg)

**Installation Source/Method**
 - Community Repo: AUR - spotube-bin

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: Rolling distro

**Additional context**
Using Sway window manager (Wayland)

**Core dump**
[spotube-coredump.txt](https://github.com/KRTirtho/spotube/files/8935209/spotube-coredump.txt)

**Comment by KRTirtho** [comment]
It's really one of the critical problem anyone can ever experience. I can't say surely but do you have gtk (gtk, gtk3 & gtk4) dependencies & `glu` installed?

**Comment by Thymelizabeth** [comment]
I have gtk2, gtk3, gtk4, and glu all installed.

**Comment by Thymelizabeth** [comment]
From gdb:
`Thread 16 "io.flutter.ui" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffc4ef1640 (LWP 34675)]
0x00007fffe0023033 in PlayerSetRate () from /usr/share/spotube-bin/lib/libwinmedia.so`
![21-06-2022_00-06-1655726602](https://user-images.githubusercontent.com/99952495/174597614-ff45e399-3b68-4a07-9bb6-0a5cb14050f3.jpg)

**Comment by KRTirtho** [comment]
Just as I thought, the discontinued audio library (which was active before) is slowly becoming incompatible with newer versions of webkit2gtk
Did you try re-installing (including webkit2gtk)?

**Comment by Thymelizabeth** [comment]
After reinstalling gtk2, gtk3, gtk4, glu, and webkit2gtk, spotube still segfaults. GDB gives a slightly different error this time:
![Thread 16 "io.flutter.ui" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffc4ef1640 (LWP 16837)]
0x00007fffe001f731 in Player::SetVolume(float) () from /usr/share/spotube-bin/lib/libwinmedia.so](https://user-images.githubusercontent.com/99952495/174721679-9f9ea6de-9797-43b5-b495-221938bbaea7.jpg)

Another thing that's changed: I have started using Linux Zen kernel. Don't know if that affects anything, just thought I'd mention it.

**Comment by KRTirtho** [comment]
I don't think that's an issue with zen kernel because I also use it & no problems
Can you install the Flatpak/Appimage variant and see if it works

**Comment by Thymelizabeth** [comment]
AppImage (after adding suid to fusermount) also segfaults.
After installing flatpak and rebooting, gives this error:
![(spotube:2): Gdk-WARNING **: 18:12:07.573: Failed to read portal settings: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop](https://user-images.githubusercontent.com/99952495/174728913-55cb15ff-cda4-459b-86c5-de73ecd151ce.jpg)

**Comment by KRTirtho** [comment]
Do you have `xdg-desktop-portal` and `xdg-desktop-portal-gtk` (or `xdg-desktop-portal-wlr` in the case of sway) installed on your system?

**Comment by Thymelizabeth** [comment]
I have `xdg-desktop-portal` and `xdg-desktop-portal-wlr` installed. I am using sway. `xdg-desktop-portal-gtk` is not installed.

**Comment by Emerald-glitch** [comment]
I installed it just now, it worked when i opened it the first time but after that it gives me this error

[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: type 'Null' is not a subtype of type 'String'
#0      Auth.loadFromLocal (package:spotube/provider/Auth.dart:75)
#1      new PersistedChangeNotifier.<anonymous closure> (package:spotube/utils/PersistedChangeNotifier.dart:30)
<asynchronous suspension>

spotube: ../libepoxy/src/dispatch_common.c:872: epoxy_get_proc_address: Assertion `0 && "Couldn't find current GLX or EGL context.\n"' failed.
Aborted

On sway that is, I also have plasma and it works just fine there.

**Comment by KRTirtho** [comment]
I still don't have any clue why this isn't working in Sway. Really sorry. It could be from the Sway's side so can you guys check if either other Flutter Applications work in Sway or not?

Such Linux desktop apps are:
- [Harmonoid](https://github.com/harmonoid/harmonoid)
- [appimagepool ](https://github.com/prateekmedia/appimagepool)
- [appflowy](https://github.com/AppFlowy-IO/AppFlowy/)

**Comment by Emerald-glitch** [comment]
@KRTirtho So, i found this it might be related 
https://github.com/anholt/libepoxy/issues/163

and if i start the app twice in successions like spotube & spotube one instance launches.
So it might be something like the first one creates glx or egl context and second launch grabs that.

**Comment by Emerald-glitch** [comment]
Tried harmonoid and appimagepool bith of them work.

**Comment by Thymelizabeth** [comment]
I just installed the latest Flatpak, and it worked. The same happened for the native package in the AUR. Thanks for your help.
