### ISSUE TITLE
“spotube.app” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by MEMEO-PRO** [KRTirtho/spotube#1172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Apple is not able to check for malicious software stuff

### Expected Behavior

Should be able to open the app without any difficulty

### Steps to reproduce

1. Download the .dmg file
2. open the app after moving it to apps folder

### Operating System

macOS

### Installation source

GitHub Releases (Binary)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by amit** [comment]
Check #1086

**Comment by KRTirtho** [comment]
Duplicate of #1086

**Comment by Obambulate** [comment]
Since the earlier report was closed, could you "notarize" the app? If not, I will not be able to use it due to not having an admin password. Thanks.
