### ISSUE TITLE
Can't play the same song twice without the loop / repeat option

### ISSUE THREAD

**Issue by equationslayer12** [KRTirtho/spotube#1174]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Without the loop option enabled, after finishing a song played through the search bar, I can't seem to be able to play it again.
The title of the current song playing stays the same after it finishes, but the duration of the song resets to 00:00
![image](https://github.com/KRTirtho/spotube/assets/80574033/6ea134b9-a632-423b-99bc-478c1b5f81e4)

Clicking on play does nothing. Trying to search for the same song and playing it again through the search bar does nothing as well.

### Expected Behavior

After finishing a song played from the search bar, it should either:
Go back to the beginning of the song and pause it.
Or, play the next search result.

Either way, it should let me play the song from the search bar once I'm done.

### Steps to reproduce

1. I opened the app
2. I searched for a song
3. I played the top result, without enabling the loop option
4. After finishing it, I tried to play it again either from the search bar or from the play button.

### Operating System

Windows

### Spotube version

v3.4.1

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev)

### Self grab

- [X] I'm ready to work on this issue!

**Comment by Takkun053** [comment]
This bug has been confirmed in my Android app.

version: 3.4.1
install from: Play Store
