### ISSUE TITLE
Does Not Work on Windows 10 LTSC

### ISSUE THREAD

**Issue by angudaz** [KRTirtho/spotube#118]
**Describe the bug**
As mentioned in [this bug report](https://github.com/KRTirtho/spotube/issues/44), I'm unable to run Spotube on Windows 10 LTSC. The version I tried running is the latest version, 2.2.1.

**To Reproduce**
1. Have Windows 10 LTSC
2. Download Spotube
3. Install Spotube
4. Attempt to run Spotube (appears in task manager for 2 seconds and disappears).

**Expected behavior**
It's supposed to run

**Screenshots**

**Installation Source/Method**
Straight from github using [Spotube-windows-x86_64-setup.exe](https://github.com/KRTirtho/spotube/releases/download/v2.2.1/Spotube-windows-x86_64-setup.exe)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise LTSC
 - Version: 1809 Build 17763.2928

**Additional context**
Running as admin doesn't do anything (Nor does compatibility mode).  I have Visual C++ Redistributables installed.  Nightly build doesn't work as well.

**Comment by KRTirtho** [comment]
There's now only one way to know what the error is & I don't have Windows 10 LTSC installation. So if you can, can you [build Spotube from source](https://github.com/KRTirtho/spotube/blob/master/CONTRIBUTION.md#your-first-code-contribution) & then provide the error generated from the terminal/cmdline

Additional resources:
- [How to install flutter in Windows](https://docs.flutter.dev/get-started/install/windows)
- [Enable flutter desktop support](https://docs.flutter.dev/development/platform-integration/desktop)

**Comment by ghj0sh** [comment]
Alright, Ill try building it myself and tell you how it goes.

**Comment by KRTirtho** [comment]
Good luck. You're gonna need it
![image](https://y.yarn.co/2e907ebb-772b-4df0-8976-1e6ae8402d1d_text.gif)

**Comment by ghj0sh** [comment]
After fiddling with create-secrets.dart and my secrets.json file, (I had to move create-secrets.dart from the bin dir to the root so it would find a path it wasn't finding.), I was able to finally try building the app.  Here's what I got:

`
libwinmedia - 0.0.3
-------------------
Building on Windows against C++/WinRT 2.0.210806.1
C++ Standard: 17
Enabled Dart VM NativePorts callbacks.
Nuget.exe not found, trying to download or use cached version.
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/scroll_to_index-2.1.1/lib/scroll_to_index.dart(358,57): warning GBC99161D: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null. [D:\Spotube-build\spotube\build\windows\flutter\flutter_assemble.vcxproj]
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/fading_edge_scrollview-2.0.1/lib/src/fading_edge_scrollview.dart(195,20): warning GBC99161D: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null. [D:\Spotube-build\spotube\build\windows\flutter\flutter_assemble.vcxproj]
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/fading_edge_scrollview-2.0.1/lib/src/fading_edge_scrollview.dart(220,20): warning GBC99161D: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null. [D:\Spotube-build\spotube\build\windows\flutter\flutter_assemble.vcxproj]
Building Windows application...
Error waiting for a debug connection: The log reader stopped unexpectedly, or never started.
Error launching application on Windows.
`

No idea if this was my fault or not though.  I feel like I went through the instructions right (although using the example json didn't let me use create-secrets.dart since there were unexpected characters) so this might be the errors you were looking for.  I honestly have no idea what any of it means lol

**Comment by KRTirtho** [comment]
The example `secrets.json` file contains fake secrets & they won't to work at all. Youll have to fill it with your own Genius Lyrics API keys and Spotify clientId & clientSecrets

Relevant Links:
- [Genius Lyrics API Access Token](https://genius.com/api-clients) (You've to be logged in in genius.com)
- [Spotify Client ID & Client Secret](https://developer.spotify.com/dashboard/) (Don't forget to add `http://localhost:4304/auth/spotify/callback` as Redirect URI)

**Comment by ghj0sh** [comment]
Thats what I did

**Comment by ghj0sh** [comment]
Added the localhost thing you just mentioned to the apps I made.  Did a quick build to see if it works.  Here's what I got:

Building on Windows against C++/WinRT 2.0.210806.1
C++ Standard: 17
Enabled Dart VM NativePorts callbacks.
Nuget.exe not found, trying to download or use cached version.
Building Windows application...
Error waiting for a debug connection: The log reader stopped unexpectedly, or never started.
Error launching application on Windows.

**Comment by KRTirtho** [comment]
Did you install `Desktop development with C++` component inside Visual Studio?

**Comment by KRTirtho** [comment]
Also show me the output of `flutter doctor -v`

**Comment by KRTirtho** [comment]
Everything looks in order. I think you only don't have `nuget.exe` available in your $PATH variable
I guess, you've to download & install nuget too

[Download Nuget Commandline Executable](https://www.nuget.org/downloads) & place the executable in the `spotube` directory
Or, if you have chocolatey installed in your system you can simply install nuget by running `choco install nuget.commandline`

**Comment by ghj0sh** [comment]
This time I got a few more errors

Building on Windows against C++/WinRT 2.0.210806.1
C++ Standard: 17
Enabled Dart VM NativePorts callbacks.
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/scroll_to_index-2.1.1/lib/scroll_to_index.dart(358,57): warning GBC99161D: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null. [D:\Spotube-build\spotube\build\windows\flutter\flutter_assemble.vcxproj]
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/fading_edge_scrollview-2.0.1/lib/src/fading_edge_scrollview.dart(195,20): warning GBC99161D: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null. [D:\Spotube-build\spotube\build\windows\flutter\flutter_assemble.vcxproj]
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/fading_edge_scrollview-2.0.1/lib/src/fading_edge_scrollview.dart(220,20): warning GBC99161D: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null. [D:\Spotube-build\spotube\build\windows\flutter\flutter_assemble.vcxproj]
D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.dir\Debug\Generated Files\winrt/impl/Windows.UI.Xaml.Media.Animation.0.h(2294,39): warning C4002: too many arguments for function-like macro invocation 'GetCurrentTime' [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(389,25): warning C4018: '<': signed/unsigned mismatch [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(539,25): warning C4018: '<': signed/unsigned mismatch [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(662,25): warning C4018: '<': signed/unsigned mismatch [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(810,10): warning C4244: 'return': conversion from '_Rep' to 'int32_t', possible loss of data [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(819,46): warning C4244: 'return': conversion from 'double' to 'float', possible loss of data [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(828,52): warning C4244: 'return': conversion from 'double' to 'float', possible loss of data [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(837,52): warning C4244: 'return': conversion from 'double' to 'float', possible loss of data [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(845,74): warning C4244: 'return': conversion from 'double' to 'float', possible loss of data [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1637,10): warning C4244: 'return': conversion from '_Rep' to 'int32_t', possible loss of data [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1654,33): warning C4018: '<': signed/unsigned mismatch [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1661,33): warning C4018: '<': signed/unsigned mismatch [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1670,33): warning C4018: '<': signed/unsigned mismatch [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1677,33): warning C4018: '<': signed/unsigned mismatch [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1689,33): warning C4018: '<': signed/unsigned mismatch [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1650,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1651,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1652,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1658,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1665,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1667,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1674,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1681,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1683,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1684,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1685,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1686,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1687,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1693,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1695,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1709,33): warning C4018: '<': signed/unsigned mismatch [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1719,33): warning C4018: '<': signed/unsigned mismatch [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1733,33): warning C4018: '<': signed/unsigned mismatch [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1745,33): warning C4018: '<': signed/unsigned mismatch [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1707,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1713,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1715,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1717,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1723,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1727,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1728,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1729,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1737,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1739,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1740,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1741,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1742,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1743,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1749,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1751,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1773,58): warning C4244: 'argument': conversion from 'uint64_t' to 'uint32_t', possible loss of data [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1775,40): warning C4244: 'argument': conversion from 'uint64_t' to 'uint32_t', possible loss of data [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1326,1): warning C4244: '=': conversion from '_Rep' to 'int32_t', possible loss of data [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
D:\Spotube-build\spotube\windows\flutter\ephemeral\.plugin_symlinks\libwinmedia\master\libwinmedia.cpp(1270,1): warning C4244: '=': conversion from '_Rep' to 'int32_t', possible loss of data [D:\Spotube-build\spotube\build\windows\plugins\libwinmedia\libwinmedia\libwinmedia.vcxproj]
Building Windows application...
Error waiting for a debug connection: The log reader stopped unexpectedly, or never started.
Error launching application on Windows.

**Comment by ghj0sh** [comment]
> The main issue here is the `Error waiting for a debug connection: The log reader stopped unexpectedly, or never started` error log . Above error is just internal warnings & should be fixed if you again run `flutter clean`

Alright, Ill try that again tomorrow.  Its 5:30AM where I live right now so Im gonna need to sleep.

**Comment by Vintic** [comment]
Same problem for me:
Edition	Windows 11 Home
Version	22H2
Installed on	‎27.‎05.‎2022
OS build	22621.290
Experience	Windows Feature Experience Pack 1000.22632.1000.0

**Comment by Bugophobe** [comment]
I just did ~40 Captcha to sign up and say this is not fixed yet!
(also reverting back to 2.6.0 works fine for me too, win 11)

**Comment by KRTirtho** [comment]
The only native dependency I had added in 2.7.0 was `window_manager` replacing `bitsdojo_window`. I doubt this has something to do with. As mentioned in #1156, any CPU that doesn't support SSE4_1 and AVX cannot run Spotube.

**Comment by KRTirtho** [comment]
Closing this issue as it's related to outdated hardware and is out of scope of this project to support the architecutre and instruction set
