### ISSUE TITLE
add arm64 v8 in release 

### ISSUE THREAD

**Issue by rajarshikhatua100** [KRTirtho/spotube#1184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

add additional architecture for Android apk

### Suggested solution

add additional architecture for Android apk

### Useful resources

add additional architecture for Android apk

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
It's already bundled with the apk. It's called universal apk for all architecture to avoid confusion for users

**Comment by rajarshikhatua100** [comment]
to avoid confusion you are increasing the bundle size, and it causes poor performance, I don't want to fat shame but it's true

**Comment by KRTirtho** [comment]
The Apk installer only selects & installs the required arch apk for the device's architecture. I don't see the point how it can cause performance issue.

It's like a zip with multiple architecture of apks. And android can choose between which ones viable for it's architecutre. I hope you get the idea
