### ISSUE TITLE
Severe performance issues

### ISSUE THREAD

**Issue by BerntA** [KRTirtho/spotube#1189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Having spotube in idle mode for a while hogs down most of the resources on my PC,
![image](https://github.com/KRTirtho/spotube/assets/10424971/7e43de04-f85a-4054-a521-16c3717ae7f2)
using almost 10GB ram, seems overkill?

### Expected Behavior

To manage memory properly, and hopefully better than the Spotify app..

### Steps to reproduce

Opened the app, listened to music, left it on idle for a while.

### Operating System

Windows 11, Version 10.0.22000, Build 22000

### Spotube version

v3.4.1

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by gollex** [comment]
same here xD.
got memory resource issues and then realized it's spotube eating all memory...

**Comment by KRTirtho** [comment]
Fixed the leak in 6673e5a. Try out the nightly build
