### ISSUE TITLE
Request Spottube’s win client to add socks5 or http proxy function

### ISSUE THREAD

**Issue by taotao1058** [KRTirtho/spotube#1198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

It cannot be used in some areas where Spotify is not available, and it cannot be used if the system proxy is turned on.

### Suggested solution

Request Spottube’s win client to add socks5 or http proxy function

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
Duplicate of #88
