### ISSUE TITLE
Auto play not available 

### ISSUE THREAD

**Issue by Sunilr001** [KRTirtho/spotube#1204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

No auto play when you play single song, app not recommend next songs.
![Screenshot_20240204_192105_Spotube](https://github.com/KRTirtho/spotube/assets/150259844/aa01548f-36e6-46af-b6cf-95ce2affa2d1)

### Suggested solution

Pleade Add auto play options.

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
Endless playback support was added in v3.5.0
