### ISSUE TITLE
Songs doesn't start to play

### ISSUE THREAD

**Issue by ptscz** [KRTirtho/spotube#121]
**Songs doesn't start to play.**
- After trying to play any song, time progress indicator keeps on time 00:00.
- Download song doesn't work too
- Same problem occurs on non-linked and linked Spotify account

**To Reproduce**
1. Choose any song from anywhere in app
2. Click Play icon
3. You can check the problem on song playing page, artwork is spinning, but there's no sound

**Expected behavior**
Songs should play.

**Screenshots**
![Spotube-screenshot_bug_playing](https://user-images.githubusercontent.com/107478198/175034243-56670b0e-c748-4e62-8e57-bfc09eb6ca97.jpg)

**Installation Source/Method**
- Package Manager: [F-droid repository](https://f-droid.org/packages/oss.krtirtho.spotube/)
- Community Repo: N/A
- Binary Source: N/A

**Desktop (please complete the following information):**
 - OS: N/A
 - Version N/A

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 9T 
 - OS: Android, deGoogled /e/OS from [e.foundation](https://e.foundation/e-os/)
 - Version 10

**Additional context**
I think, that the problem can be caused by deGoogled OS, if some Google services are used to connection to Spotify server. I either have these services disabled or they are not present in my operating system at all.

But it's only just my guess, I am not a programmer.

I can attach some developer log, if it'll be useful.

Thank you very much for any thoughts or help.

**Comment by Emerald-glitch** [comment]
How long did you wait, for me it takes a while to start playing.

**Comment by KRTirtho** [comment]
First try doing a data clear from App Info
> I can attach some developer log, if it'll be useful.

Yeah, that'll be really helpful

Also are you logged in with your Spotify account?

**Comment by adamli86** [comment]
**Met the same Issue**

I tried both my HW phone and debain 11 under ChromeOS, and it all failed to start playing, whether I login as guest or link my account and authorized the develop account access.

sources: F-droid, flatpak(flathub)
environment: Andriod 10 (Huawei Harmony2.0) ，debain 11 
network: wifi China, with proxy server bypass GFW

**Comment by KRTirtho** [comment]
@adamli86 Spotube isn't yet tested for Chrome OS (including chrome os linux containers) & HarmonOS isn't yet supported so I can't guarantee it'll run in these OSs or not

**Comment by ptscz** [comment]
@KRTirtho I've tried probably every common combination with solving - both with or without my Spotify profile linked, I've tried deleting cache, deleting app data, reinstall application, unfortunately the same problem still persists.

Here is my most recent [developer log file](https://github.com/KRTirtho/spotube/files/9011588/bugreport-davinci-QQ3A.200805.001-2022-06-29-15-13-24.txt.zip)

Thank you for your investigation!

**Comment by ptscz** [comment]
@KRTirtho The songs started playing, that it seems, that problem is solved. Thanks!
