### ISSUE TITLE
Fire TV Stick compatibility

### ISSUE THREAD

**Issue by ParkerStacbind** [KRTirtho/spotube#1215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

Hello
After trying installation on amazon fire TV stick with apps2fire, Spotube does not work on it.
Issue is possible?
Thx

### Suggested solution

Apps working on fire stick

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
I guess we can use https://iheart.com/podcast to add podcast ability to Spotube

**Comment by VirusBurst** [comment]
Spotube can be installed on FireTV (or Android TV) devices but it's impossible to use with a remote, external mice/touchpad is required!

Version testet 3.4.1 on FireTV 4k, 4kMax v1, 4kMax v2, Nintendo Switch running Android, Generic Android TV devices

**Comment by KRTirtho** [comment]
Duplicate of #441
