### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by bernardopg** [KRTirtho/spotube#1217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
> Não foi possível resolver as dependências da transação; 1 problema detectado:
>  Problema: solicitações conflitantes
>   - nothing provides libmpv.so.1()(64bit) needed by spotube-3.4.1+28-28.x86_64 from @commandline
```

### Expected Behavior

install

### Steps to reproduce

1. Download the .rpm
2. cd Downloads
3. sudo dnf install ./Spotube-linux-x86_64.rpm

### Operating System

Fedora

### Spotube version

3.4.1

### Installation source

Flathub (Flatpak)

### Self grab

- [X] I'm ready to work on this issue!

**Comment by olivier2** [comment]
Duplicate of #929 ?

**Comment by subhamBharadwaz** [comment]
Using `flatpak install com.github.KRTirtho.Spotube` solved my installation issue.
