### ISSUE TITLE
Great app but please add proxy

### ISSUE THREAD

**Issue by oneflowa** [KRTirtho/spotube#1219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

YouTube is blocked in China, and so songs can't be played.

### Suggested solution

Add http or sock5 proxy. 

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by olivier2** [comment]
Duplicate of #88 ?

**Comment by KRTirtho** [comment]
Duplicate of #88
