### ISSUE TITLE
Downloaded music is 0kb

### ISSUE THREAD

**Issue by prismacolorgold** [KRTirtho/spotube#122]
Downloaded music is 0kb on both desktop and android clients
![1](https://user-images.githubusercontent.com/19483499/175448995-72c45884-a620-430a-a437-61327eb4b219.PNG)

**To Reproduce**
1. Install either the desktop or android clients
2. go to the song view, hit download

**Expected behavior**
downloaded music should open and play

**Screenshots**

**Installation Source/Method**
Installed from F-droid and github

**Desktop (please complete the following information):**
 - OS: Win10
 - Version v2.2.1

**Smartphone (please complete the following information):**
 - Device: Samsung Note8
 - OS: Android 9
 - Version Android 9

**Comment by KRTirtho** [comment]
Its only happening when Download Lyrics option is turned on. For now, turn download lyrics option off to download the track successfully

**Comment by prismacolorgold** [comment]
Ah ok thanks!
for some reason, the files I download from the android shows 1min or so. when i look at its properties in another music player/also file explorer, i cant view a lot of stuff (bitrate). i can play the whole song in vlc media player. i have not try with pc yet.

![Screenshot_20220626-010754_GoneMAD](https://user-images.githubusercontent.com/19483499/175805794-44a50b67-28fd-4d73-9bcc-325a18213969.jpg)
![Screenshot_20220626-010050_Material Files](https://user-images.githubusercontent.com/19483499/175805822-ae0abe84-55f8-4dad-a547-6edc605eb19e.jpg)

**Comment by prad33p7** [comment]
> Downloaded music is 0kb on both desktop and android clients ![1](https://user-images.githubusercontent.com/19483499/175448995-72c45884-a620-430a-a437-61327eb4b219.PNG)
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Install either the desktop or android clients
> 2. go to the song view, hit download
> 
> **Expected behavior** downloaded music should open and play
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Installation Source/Method** Installed from F-droid and github
> 
> **Desktop (please complete the following information):**
> 
> * OS: Win10
> * Version v2.2.1
> 
> **Smartphone (please complete the following information):**
> 
> * Device: Samsung Note8
> * OS: Android 9
> * Version Android 9

Disable lyrics download for now

**Comment by KRTirtho** [comment]
@prismacolorgold The reason you don't see correct metadata on those audio files is Spotube for now only downloads the mp3 directly from youtube servers & doesn't append any metadata to it. I'm currently looking for solutions to how to write correct metadata for downloaded audio files. Don't worry, it might be available in the next release

**Comment by KRTirtho** [comment]
Your issued bug got fixed in the latest release v2.3.0

Please create separate issue for Downloaded Track metadata

**Close this issue if your requested feature/bug is implemented/fixed + released**
