### ISSUE TITLE
SOCKS5 Proxy Support

### ISSUE THREAD

**Issue by amirsadeghi1** [KRTirtho/spotube#1220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

Spotify has sanctioned Iran and also YouTube is filtered in Iran and we do not have access to it to use SpoTube.

### Suggested solution

Please add feature to use SOCKS5 (proxy) to the SpoTube

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by olivier2** [comment]
Duplicate of #88 ?
