### ISSUE TITLE
Compatibility with Wavelet (Android Headphone DSP app)

### ISSUE THREAD

**Issue by inodentry** [KRTirtho/spotube#1221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'd like to use Wavelet for Headphone DSP/EQ while listening to music. When I start playing music in other apps, Wavelet detects that there is an "audio session" and enables the settings. Spotube is not detected and does not work.

### Expected Behavior

When playing music in Spotube, Wavelet detects it and is able to apply EQ and other effects to the audio.

### Steps to reproduce

1. Install and setup Wavelet: https://play.google.com/store/apps/details?id=com.pittvandewitt.wavelet
2. Try playing something in another app (Youtube, Soundcloud, work just fine to give some examples), to make sure it is working. Wavelet should detect that audio is playing and be able to intercept the audio and apply effects like EQ.
3. Try playing something in Spotube. It does not show up in Wavelet.

### Operating System

Android

### Installation source

Play Store (Android)

### Additional information

Their website has some instructions for other music players that might not work out of the box: https://pittvandewitt.github.io/Wavelet/Configuration/ . My interpretation of what I am reading there seems to suggest that if a music player is not compatible out of the box, it might be because of the APIs it uses to play audio, and in most such players, enabling any setting for in-app audio processing (such as in-app EQ or something, whatever the player offers) forces it to use some sort of different API or mode for audio playback, which can be detected by Wavelet. Spotube does not seem to have any settings that could affect how it plays audio via the Android OS.

I am reporting this issue with Spotube rather than Wavelet, because of this. It seems to me like the problem is with how Spotube plays audio in Android, and not what Wavelet does.

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by olivier2** [comment]
Hey @inodentry , good news! I tested Wavelet with Spotube [configured with the AudioTrack audio output](https://github.com/olivier2/spotube/commit/0e73443471cf7c471a94367d475304643d057cf5) (see issue #571 ) and it works in Legacy mode. If you're able to compile from source, you're good to go.

**Comment by mustard007** [comment]
When I use Jiosaavn audio source, Wavelet works, otherwise it doesn't work with Youtube or Piped audio source.

**Comment by inodentry** [comment]
> Hey @inodentry , good news! I tested Wavelet with Spotube [configured with the AudioTrack audio output](https://github.com/olivier2/spotube/commit/0e73443471cf7c471a94367d475304643d057cf5) (see issue #571 ) and it works in Legacy mode. If you're able to compile from source, you're good to go.

I already tried that, but Legacy mode does not seem to be compatible with my phone (Fairphone 5). I used it on my old phone (Samsung Galaxy S10 5G), it worked fine there, but I can't use it on this phone. When I tried to do some research about it, the only info I found was related to the "Disable Hardware Bluetooth A2DP Handling" setting in Developer Settings. I tried messing with that option, but changing it completely broke my audio. Either Wavelet has no effect, or I have no audio at all whatsoever.

This is why I'd like all the apps I use to work in the normal (not Legacy) mode in Wavelet. Spotube is the only one that doesn't. So I filed this issue, so we can investigate why that might be.

**Comment by olivier2** [comment]
> This is why I'd like all the apps I use to work in the normal (not Legacy) mode in Wavelet. Spotube is the only one that doesn't. So I filed this issue, so we can investigate why that might be.

Do you know of any open source android player that work in the normal (not Legacy) mode in Wavelet?

> I see the commit is already in the repo / merged. Is there going to be a new release soon?

Unlikely, I only committed in a fork I own and haven't submitted a pull request. I found something that fixes the issue by luck and have absolutely no idea what that change will do on other android devices.

**Comment by inodentry** [comment]
Oh okay i didnt realize the link was to a fork. Sorry.

Okay. I will try to learn how to build the Spotube Android app from source so that I can try it out.

I can try some open-source media players to see how they behave. I'll report findings later. :)

**Comment by olivier2** [comment]
For reference, here's a [high level overview of how equalizer apps, like Wavelet, attach to other players](https://web.archive.org/web/20240210024117/https://www.esper.io/blog/android-equalizer-apps-inconsistent) on android.

Also, 2 implementations of a how to broadcast the audio session id to other apps: [moneytoo/Player](https://github.com/moneytoo/Player/commit/b412fe6515d1ab75de08d4f1f5da09664a51832b) and [NewPipe](https://gitea.it/Peertube/NewPipe-app-android/commit/ba6fdecbae6ea8dccd9fa8bfaaaf94a95ee7028b#diff-0c5c71ddd8f54de9bb156a80fb3b6de35bcb10b8)

**Comment by olivier2** [comment]
@inodentry it works! 🎉 

https://github.com/KRTirtho/spotube/assets/1408881/a1ad2f1d-cd04-445b-87d3-e14ebb239af1

**Comment by olivier2** [comment]
@inodentry, can you test the [nightly](https://github.com/KRTirtho/spotube/releases/tag/nightly) and report back if it works as expected?

**Comment by inodentry** [comment]
Yes! Just tried it, and it is detected! That's awesome.

Should I close the issue or leave it open until there is an actual release with the fix?

**Comment by olivier2** [comment]
I think issue will be closed automatically once it's merge in master
