### ISSUE TITLE
Add an "are you sure you want to delete" prompt when deleting a playlist

### ISSUE THREAD

**Issue by Ocean-OS** [KRTirtho/spotube#1222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

When I was trying to select a playlist on the Android app, the app didn't seem to be responding, so I tapped again. Unfortunately, the playlist was in the same location as the delete button, so a millisecond before I tapped the second time, it opened the playlist, and my second tap deleted the playlist.

### Suggested solution

You could add a prompt when the user presses the delete button on a playlist saying, "Are you sure you want to delete this playlist?", maybe with an input to enter the playlist's title to confirm the deletion.

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by BastienH** [comment]
Another way of looking at this is to have a trash system where you could get you playlist back from... just a thought

**Comment by KRTirtho** [comment]
Sorry that you had to lose your playlist. This is a critical UX issue that should have been addressed before, but somehow it got unnoticed. There should be confirmation for all sorts of destructive behaviours.

**Comment by Khenziii** [comment]
@Ocean-OS, I'm not sure if you know about this, but you can actually instantly recover playlists deleted in last 90 days.

Take a look at [this](https://support.spotify.com/us/article/save-recover-playlists/) article. You can basically go to [www.spotify.com/account](https://www.spotify.com/account/) & then click "Recover playlists" (<https://www.spotify.com/us/account/recover-playlists/>)

I hope, that this will help.
