### ISSUE TITLE
Use Spotify audio sources directly

### ISSUE THREAD

**Issue by p0we7** [KRTirtho/spotube#1226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

I've purchased Spotify Premium, but I don't want to use the official Electron App. spotube doesn't use electron which I like, and it would be nice to have it support using spotify's audio sources directly.

### Suggested solution

Like I said above.

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by ccrowles** [comment]
Was about to ask the same thing. I have Spotify premium but I hate the official app, it's full of bugs and consumes too much battery. It would be nice if we can have Spotify added as source.

**Comment by KRTirtho** [comment]
Spotify Web API doesn't allow using their audio sources directly for 3rd party apps, even with premium. It's only possible if we use Spotify's audio player (libspotify) which is proprietary and there's no Dart binding available for that C++ shared library.

Although, there are brilliant libraries like [librespot](https://github.com/librespot-org/librespot), but it's written in Rust and porting it to Dart or creating bindings for Flutter (flutter_rust_bridge)  will take huge team effort and requires much deeper understanding of the Rust language itself which has a big learning curve.

**Comment by ccrowles** [comment]
Understood, thanks for explaining!

**Comment by AlphaCraft9658** [comment]
> Spotify Web API doesn't allow using their audio sources directly for 3rd party apps, even with premium. It's only possible if we use Spotify's audio player (libspotify) which is proprietary and there's no Dart binding available for that C++ shared library.
> 
> Although, there are brilliant libraries like [librespot](https://github.com/librespot-org/librespot), but it's written in Rust and porting it to Dart or creating bindings for Flutter (flutter_rust_bridge) will take huge team effort and requires much deeper understanding of the Rust language itself which has a big learning curve.

Kind of a late contribution, but would it be possible to use librespot for accessing Spotify's resources (for premium accounts)?
