### ISSUE TITLE
Strange behavior while playing specific artist

### ISSUE THREAD

**Issue by Ud4ba** [KRTirtho/spotube#1229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While searching, or selecting specific tracks of a specific album then the app only plays ony 1 track from the album(while trying to choose to play different tracks) or play other track from older album.
https://open.spotify.com/album/3IBdv0FmmbtLJh7BMOehTa
If anyone try to play it from spotify will listen different track.

### Expected Behavior

Should play the selected track.

### Steps to reproduce

I opened the app, searched or either pick it from my liked list , then try to choose anything from here : https://open.spotify.com/album/3IBdv0FmmbtLJh7BMOehTa
If anyone try to play it from spotify will listen different track.

### Operating System

Android

### Installation source

F-Droid (Android)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
This has been fixed in e964f61d38cb303e3d3fd60c866414f57207181c
