### ISSUE TITLE
previous and next music button does not work in v3.4.1

### ISSUE THREAD

**Issue by vshal5** [KRTirtho/spotube#1234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

from android phone, does nothing but glows when clicked 

### Expected Behavior

from android phone, when clicked on previous/next button it should change music according

### Steps to reproduce

1. open the app
2. from home button click on song music
3. click on ⏮️or⏭️button to change songs

### Operating System

Android

### Spotube version

 v3.4.1

### Installation source

GitHub Releases (Binary)

### Additional information

used .apk file

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
This has been fixed in e964f61d38cb303e3d3fd60c866414f57207181c

**Comment by vshal5** [comment]
thanks, but app seems to be frozen at start page

**Comment by KRTirtho** [comment]
Login with your Spotify credentials

**Comment by callegar** [comment]
If this is the same as #1154, then it is not fixed. At least #1154 and #1348 are still there.

#1348 is particularly nasty, because it makes the app hang when using playlists.
