### ISSUE TITLE
Nothing works on Linux. Many errors in console (failed to access plugin: path_provider)

### ISSUE THREAD

**Issue by ProgrammingLife** [KRTirtho/spotube#124]
**Describe the bug**
In console I see many such errors:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationSupportDirectory on channel plugins.flutter.io/path_provider)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165)
<asynchronous suspension>
#1      getApplicationSupportDirectory (package:path_provider/path_provider.dart:77)
<asynchronous suspension>
#2      JsonCacheInfoRepository._getFile (package:flutter_cache_manager/src/storage/cache_info_repositories/json_cache_info_repository.dart:213)
<asynchronous suspension>
#3      JsonCacheInfoRepository.open (package:flutter_cache_manager/src/storage/cache_info_repositories/json_cache_info_repository.dart:40)
<asynchronous suspension>
```
So in my case Spotube can't show album/artist images, can't play any song, etc.

**To Reproduce**
1. Downloaded a new version of Spotube today and start it from console.

**Expected behavior**
Working app.

**Screenshots**
n/a

**Installation Source/Method**
AppImage binarp

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Version 19.3

**Smartphone (please complete the following information):**
 - Device: n/a

**Additional context**
n/a

**Comment by KRTirtho** [comment]
That's a really weird issue. It looks Spotube doesn't enough permission for the application support directory `~/.local/share/oss.krtirtho.spotube`. Or the Application Support Directory could be read only

**Comment by KRTirtho** [comment]
Duplicate of https://github.com/KRTirtho/spotube/issues/523
