### ISSUE TITLE
Title bar incorrectly spaced/positoned in miniplayer

### ISSUE THREAD

**Issue by AuburnMedia** [KRTirtho/spotube#1244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The title bar (close, minimize, maximize buttons) is incorrectly positioned covering the logo and some of the lyrics.

### Expected Behavior

Possible solution:
Hide the title bar and replace it with it own X button, and move the Exit Miniplayer button alongside it.

### Steps to reproduce

1. Open app
2. Choose your vibes and press play :)
3. Place into miniplayer
4. look at the top left corner

### Operating System

macOS Sonoma 14.0

### Spotube version

v3.4.1

### Installation source

GitHub Releases (Binary)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
It's fine here. What's your resolution, DPI, zoom factor etc?
<img width="1344" alt="image" src="https://github.com/KRTirtho/spotube/assets/61944859/29a5c338-ad3d-44f0-b4d3-586a2dcee38d">

**Comment by AuburnMedia** [comment]
<img width="410" alt="Screenshot 2024-02-27 at 6 57 21 am" src="https://github.com/KRTirtho/spotube/assets/137
234483/ec5507fb-a57d-4424-9fac-4eb809321fda">

<img width="470" alt="Screenshot 2024-02-27 at 6 59 43 am" src="https://github.com/KRTirtho/spotube/assets/137234483/f92943f3-e46f-442e-ab04-88d470f66bc3">


Resolution: 2560x1600

As you can see, the logo is covered by the title bar buttons.

**Comment by AuburnMedia** [comment]
bump

**Comment by KRTirtho** [comment]
Oh, you meant the mini player. I was thinking about the entire player.

**Comment by AuburnMedia** [comment]
> Oh, you meant the mini player.

Yes, it seems to only appear when in the miniplayer window.
