### ISSUE TITLE
 Side buttons of the mouse forward and back does not working

### ISSUE THREAD

**Issue by Naitipesnu** [KRTirtho/spotube#1248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

It is very impractical to reach for a cross or an arrow every time, you can just press a convenient button that is supported in many services!

### Suggested solution

Implement convenient functionality

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
Duplicate of #416
