### ISSUE TITLE
More features for those without an account

### ISSUE THREAD

**Issue by Daniele1012** [KRTirtho/spotube#125]
Please add the function to search and add a playlist to favorites even for those who do not have an account.

**Comment by KRTirtho** [comment]
Sorry it wouldn't be possible. Spotify servers doesn't allow search & custom playlists without authenticated user. Until Spotify API allows I can't add more features than those available

**Comment by ildar** [comment]
search: ok
but local favorites are possible for artists, albums, maybe playlists.
Please reopen, if agree.

**Comment by cipitaua** [comment]
I cannot undestand why one could not search without account as long as the app uses the youtube service. Could you please explain what prevents  anonymous search? https://github.com/KRTirtho/spotube/issues/1913
