### ISSUE TITLE
Battery settings pop up every time the app starts.

### ISSUE THREAD

**Issue by ChromiaCat** [KRTirtho/spotube#1252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It might not be a bug but more of an annoyance with the app.

If I've set the battery saver settings for the app on anything other than No Restrictions (MIUI) it keeps bringing up the settings to change it and it kinda annoys me, it should be just a fresh install kinda thing and after that it should stop pestering the user.

### Expected Behavior

It only brings up the battery saver settings for Spotube only the first time after install and never again.

### Steps to reproduce

1. Install Spotube.
2. Set the battery saver settings for it on anything but No Restrictions.
3. Start the app however many times you want.
4. Profit.

### Operating System

Android 11

### Spotube version

v3.4.1

### Installation source

Play Store (Android)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
This is because custom OEM android ROMs kills Spotube from background automatically without user's concern. [Learn More](https://dontkillmyapp.com)
So, to have a better experience and for letting users know that the OEM is the one to be blamed for this kind of artificial battery health and poor battery saving tactics.

This is unfortunately an intended behaviour to allow Spotube to play in the background without getting interrupted

**Comment by ChromiaCat** [comment]
I realize that but from my experience Spotube doesn't get stopped, at least for me. Would it be too much trouble to add a toggle to stop that?

**Comment by KRTirtho** [comment]
By default, users will be asked once after install or unless neither Allow/Deny was pressed. So I suppose there's something that went wrong. Did you try to clear data?

**Comment by ChromiaCat** [comment]
> By default, users will be asked once after install or unless neither Allow/Deny was pressed. So I suppose there's something that went wrong. Did you try to clear data?

Just did and it still asks every time I open it.

**Comment by ChromiaCat** [comment]
I don't think it's an issue with my device, if I set Spotube to no background restrictions it stops bothering me.

Is it possible to make that a notification in the app with an option to not ask again?

**Comment by ChromiaCat** [comment]
Thanks for fixing it, you rock!
