### ISSUE TITLE
Minor typographical splash screen correction (English translation)

### ISSUE THREAD

**Issue by zanovis** [KRTirtho/spotube#1256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

'Upholded by OS community'

https://github.com/KRTirtho/spotube/blob/5d0b5e69a5e43b17561656160fd963de4ff0f833/assets/branding.png 

### Expected Behavior

'*Upheld by OS community'

### Steps to reproduce

Typographical

### Operating System

Cross-platform

### Spotube version

Latest

### Installation source

F-Droid (Android)

### Additional information

Would make PR but branding.svg isn't in assets/~

### Self grab

- [X] I'm ready to work on this issue!

**Comment by brckd** [comment]
I was wondering about this for so long! Thanks for fixing it.
