### ISSUE TITLE
[Bug] Cannot play any music on Linux

### ISSUE THREAD

**Issue by arenekosreal** [KRTirtho/spotube#1257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After I login into spotify, I can see all my playlists and even search for new songs. But when click one of the songs to play, I can't see anything shows it works, there is no playback, nor the correct music length shows(it always 00:00). But I can see the album cover is updated at left down corner, and also play the song directly on YouTube.

### Expected Behavior

The song is playing.

### Steps to reproduce

1. Open the app and login into spotify
2. Search a song,(like Sakura Fubuki)
3. You can see some songs match your query
4. Choose first one (Sakura Fubuki - Street)
5. After waiting for it loads, the song cannot play, but the cover is updated.

### Operating System

Arch Linux

### Spotube version

v3.4.1

### Installation source

GitHub Releases (Binary)

### Additional information

MPRIS is updating, it even shows spotube is playing, sets correct music length and refreshes progress in real-time.

Running spotube with `--verbose` flag and trying to play Sakura Fubuki mentioned before outputs this in my terminal:
[spotube.log](https://github.com/KRTirtho/spotube/files/14381287/spotube.log)

Manually open the same googlevideo.com URL at browser returns a 403 error.

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
Use the nightly version and change the Audio Source to JioSaavn. Looks like youtube.com is unreachable for some reason in your device

**Comment by arenekosreal** [comment]
I downloaded nightly version at https://github.com/KRTirtho/spotube/releases/tag/nightly. I must say it is pretty old, it is even elder than v3.4.1. But there is no JioSaavn in Audio Sources, only YouTube and Piped.
![image](https://github.com/KRTirtho/spotube/assets/17194552/5cf0537e-d65f-4af5-96fb-0e354eb45414)

**Comment by KRTirtho** [comment]
Can you use the .deb or .rpm version?

**Comment by moosicmaan** [comment]
I had the same problem.  Somehow, changing my browser from firedragon to firefox seemed to work, so, I would imagine the issue has to do with settings in the default browser and  youtube.

**Comment by arenekosreal** [comment]
Oh, I see, the .rpm or .deb version is newer than the tar one. However, I am using archlinux and installing them directly is not allowed. So I unpacked .deb version and run binary in `usr/share/spotube/spotube` instead. But unfortunately it seems to be worse, I cannot even finish loading. Here is the log output when searching Sakura Fubuki and trying to play it:
[spotube.log](https://github.com/KRTirtho/spotube/files/14395216/spotube.log)
It seems that the token has been limited, but I have already tried logout from spotify and login again.

PS: I have noticed that you mentioned it may because I cannot connect to YouTube, here I will give a brief introduction about my network. I live in place where Spotify and YouTube are both blocked, but I started spotube with environment variables set to access Spotify and YouTube through proxy. I am not using English locale either, so the actual command I start the spotube to debug is `LANG=C HTTPS_PROXY=http://127.0.0.1:2080 HTTP_PROXY=http://127.0.0.1:2080 ALL_PROXY=http://127.0.0.1:2080 spotube --verbose`

**Comment by arenekosreal** [comment]
Today I found the solution: follow https://github.com/KRTirtho/spotube/issues/88#issuecomment-1959065479 to set environment variables completely, `http_proxy`, `https_proxy` and `all_proxy` all need to be set, and their name is lower case.
