### ISSUE TITLE
Queue randomly play earlier song.

### ISSUE THREAD

**Issue by remclean** [KRTirtho/spotube#1267]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Every now and then, the queue randomly plays a song from early in the queue and then goes back to the correct spot. I don't believe the song is the problem but I did notice 2 songs I have had this happen with more commonly. (Amity Part 1 - [[https://open.spotify.com/track/4tuTNXc8lbLR95xslWrp6Z](url)] and Please don't let me be misunderstood - [https://open.spotify.com/track/7vYA9ET5AUqJt5pBbhKmcB](url))

### Expected Behavior

The Queue should only play the songs in the order on the queue unless the user selects a song.

### Steps to reproduce

I'm not sure how likely this is to work for everyone but he is what I did:
1. Select a playlist (I always use random order but I doubt that affects the bug)
2. Just listen and wait. Pay attention to that songs have already played and wait for one to play again.
3. After long enough, with luck, it should glitch and play an earlier song. 

### Operating System

Android

### Spotube version

v3.4.1

### Installation source

Play Store (Android)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by remclean** [comment]
Anyone able to back this issue? Or is it local?

**Comment by remclean** [comment]
Update, I believe that it is just the 2 songs I have gotten to do this. Can anyone else get it to happen.

**Comment by mgautam07** [comment]
I faced a similar issue. Although in my case songs were different and I added 3 songs by using play next.

**Comment by remclean** [comment]
Is it fixed now, because it is first me and I was gonna mark it fixed. Is it good for you?

**Comment by mgautam07** [comment]
No, I faced it a few hours ago
