### ISSUE TITLE
Cache songs

### ISSUE THREAD

**Issue by Happyfeet01** [KRTirtho/spotube#127]
Is it possible to introduce a function to temporarily store or preload songs in order to listen to songs even if the Internet connection should be interrupted for a short time?

**Comment by KRTirtho** [comment]
Well, you can always download tracks you want if you know that there won't be any internet connection for some time

**Comment by Rstment25** [comment]
> 

That's true but like life is random z: Even if you know this exact moment that you have to go out you'd be troubled trying to download all of those songs manually...

Cache is a nice idea - as in cache played songs and store them for some time , maybe a day or two or even a week idk? User choice here could be nice like a drop down menu in settings for how long the cache should keep songs.

If anything it would help even in scenarios where you are connected to Internet - no point in having to download same songs over and over again tho idk if it's possible to identity songs precisely via APIs...

**Comment by KRTirtho** [comment]
I think we finally have a architecture to support it.
