### ISSUE TITLE
type 'Track' is not a subtype of type 'SourcedTrack' in type cast

### ISSUE THREAD

**Issue by GStudiosX2** [KRTirtho/spotube#1289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Some songs do not play and alternative sources provide me with this error

`type 'Track' is not a subtype of type 'SourcedTrack' in type cast`

<details>
  <summary>behaviour</summary>

![Screenshot_20240304-060804](https://github.com/KRTirtho/spotube/assets/76548041/ebf38769-ff24-47d0-bcb0-299d935fa05e)
</details>

### Expected Behavior

The song to play and let me pick other sources.

### Steps to reproduce

1. I opened the app (nightly version)
2. I tried to play a few songs and some did not play
3. And the ones that don't play don't let me select other sources and returns a error

### Operating System

Android 11

### Spotube version

v3.4.1-nightly 
Build Number: 215

### Installation source

GitHub Releases (Binary)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by GStudiosX2** [comment]
Update: For some reason using piped makes two songs that didn't work play ? But now it wouldn't play from YouTube so not sure what's going on there

**Comment by GStudiosX2** [comment]
<details>
<summary>log</summary>

```
============================== CATCHER 2 LOG ==============================
------- DEVICE INFO -------
id: RPJS31.Q4U-47-35-17
board: rav
bootloader: MBM-3.0-rav_reteu-a863e9dc072-220330
brand: motorola
device: rav
display: RPJS31.Q4U-47-35-17
fingerprint: motorola/rav_reteu/rav:11/RPJS31.Q4U-47-35-17/4bff0:user/release-keys
hardware: qcom
host: ilclbld180
isPhysicalDevice: true
manufacturer: motorola
model: moto g(8)
product: rav_reteu
tags: release-keys
type: user
versionBaseOs: motorola/rav_reteu/rav:11/RPJ31.Q4U-47-35/0edbf:user/release-keys
versionCodename: REL
versionIncremental: 4bff0
versionPreviewSdk: 0
versionRelease: 11
versionSdk: 30
versionSecurityPatch: 2022-04-01
------- APP INFO -------
environment: release
version: 3.4.1-nightly
appName: Spotube Nightly
buildNumber: 215
packageName: oss.krtirtho.spotube.nightly
---------- ERROR ----------
VideoUnavailableException: Video 'kMBRQmATvuE' is unavailable
In most cases, this error indicates that the video doesn't exist, is private, or has been taken down.
If you can however open this video in your browser in incognito mode, it most likely means that YouTube changed something, which broke this library.
Please report this issue on GitHub in that case.
------- STACK TRACE -------
#0      WatchPage.get.<anonymous closure> (package:youtube_explode_dart/src/reverse_engineering/pages/watch_page.dart:147)
<asynchronous suspension>
#1      retry (package:youtube_explode_dart/src/retry.dart:16)
<asynchronous suspension>
#2      VideoClient._getVideoFromWatchPage (package:youtube_explode_dart/src/videos/video_client.dart:37)
<asynchronous suspension>
#3      YoutubeSourcedTrack.fetchSiblings (package:spotube/services/sourced_track/sources/youtube.dart:228)
<asynchronous suspension>
#4      YoutubeSourcedTrack.fetchFromTrack (package:spotube/services/sourced_track/sources/youtube.dart:51)
<asynchronous suspension>
#5      SourcedTrack.fetchFromTrack (package:spotube/services/sourced_track/sourced_track.dart:116)
<asynchronous suspension>
#6      ProxyPlaylistNotifier.load (package:spotube/provider/proxy_playlist/proxy_playlist_provider.dart:330)
<asynchronous suspension>
#7      SearchTracksSection.build.<anonymous closure>.<anonymous closure> (package:spotube/pages/search/sections/tracks.dart:75)
<asynchronous suspension>
#8      TrackTile.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:spotube/components/shared/track_tile/track_tile.dart:93)
<asynchronous suspension>
------- CUSTOM INFO -------
```
</details>

Why is it returning a private or deleted video

**Comment by s0u7a** [comment]
same error

**Comment by remclean** [comment]
Same error on android and linux ubuntu.

**Comment by GStudiosX2** [comment]
What's weird is some of the broken songs can play on the release version

**Comment by Bowarc** [comment]
Same error on windows10, i might add that since quite a time now, some songs like [xanny bar from LOAT!](https://song.link/s/1SHay8Odqxk8nOqdhPH1kC) or [all girls are the same from RØNIN](https://song.link/s/3W2m2qa0vPHoCMqEjrpLAo) are not loading even tho they exist and are not behind private / 'trigger warning' walls.
