### ISSUE TITLE
im got error from yr source 

### ISSUE THREAD

**Issue by moohamedsalman93** [KRTirtho/spotube#129]
please help to resolve
![Screenshot 2022-06-30 114906](https://user-images.githubusercontent.com/53552621/176606479-2dfb7cbd-b503-49b2-b119-e0a55627d27e.png)

**Comment by KRTirtho** [comment]
Read the [build from source](https://github.com/KRTirtho/spotube/blob/master/CONTRIBUTION.md#your-first-code-contribution) steps in the docs more carefully before creating an issue. If further assistance needed please create a discussion
