### ISSUE TITLE
Incorrect Dutch translations

### ISSUE THREAD

**Issue by jabas1** [KRTirtho/spotube#1297]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Some words from the Dutch translations are not correct, or don't really fit.

### Expected Behavior

These translations should be updated:
"guest" should be "Gast"
"search" should be "Zoeken"
"lyrics" should be "Songteksten"
"artists" should be "Artiesten"
"filter_playlists" should be "Afspeellijsten filteren"
"liked_tracks" should be "Favoriete nummers"
"play" should be "Afspelen"
"fans_also_like" should be "Fans luisteren ook"

There are probably some others, I could update them.

### Steps to reproduce

1. Open the app
2. (if not already) change the app language to Dutch (Nederlands)
3. Look at the bad translations

### Operating System

Any

### Spotube version

v3.4.0

### Installation source

F-Droid (Android)

### Self grab

- [X] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
@SecularSteve @Stephan-P a little help here please

**Comment by Stephan-P** [comment]
Thank you, @jabas1 
I will try and find these texts.
Since the dutch translations are at 100% translated, it could be that you discover a number of missing translations

**Comment by jabas1** [comment]
Good to hear.
I could still correct you on something, @Stephan-P, as the 'faulty' translations aren't really wrong, but the targeted context of a word is wrong. Shuffle does mean 'schuifelen', but shuffle in playlist form should translate to ''Shufflen'.

Just thought I might want to add this comment to save you some time in finding missing translations, as none are missing, but some are just not right.

**Comment by Stephan-P** [comment]
> @SecularSteve @Stephan-P a little help here please since you both are the dutch translators

I've checked and can confirm that all these texts do NOT exist in Weblate. 
Most likely, these are new strings that are missing for translation.

**Comment by Stephan-P** [comment]
@jabas1, A little problem of my own: how would you translate "assets" ?

**Comment by jabas1** [comment]
I don't know what context you're implying, I'll try to guess. Does 'aandelen', 'onderdelen / gegevens', or 'activa' help?

**Comment by Stephan-P** [comment]
Okay, i need to take back everything i've said so far. I was checking the translations of another project i'm involved in.
I'll be back with a proper response layer this weekend. 
@jabas1 , @KRTirtho

**Comment by Stephan-P** [comment]
https://github.com/KRTirtho/spotube/pull/1305
