### ISSUE TITLE
Improper formatting of some characters

### ISSUE THREAD

**Issue by bean-frog** [KRTirtho/spotube#1300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the UI attempts to display certain characters like `'`, it shows what looks to be the HTML character equivalent (?, not sure what it's called), like this: `&amp;#x27`

### Expected Behavior

Characters like apostrophe (') and ampersand (&) should be displayed without this equivalent.

### Steps to reproduce

1. open the app
2. navigate to a playlist/album containing an `'`
3. observe

### Operating System

CachyOS (Arch-based), XFCE/xfwm4

### Spotube version

v.3.4.1

### Installation source

Arch User Repository (AUR)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by bean-frog** [comment]
it appears to do something similar for commas as well

**Comment by KRTirtho** [comment]
Can you share the album/playlist it's happening with?

**Comment by bean-frog** [comment]
sure.
after some investigation it looks like only descriptions are affected.
heres a screenshot of 2 playlists where this happens: (Android 14, OneUI 6.0, latest Spotube release from F-Droid)
![Screenshot_20240309_112353_Spotube](https://github.com/KRTirtho/spotube/assets/104943861/85855a37-3c57-4b27-ba3e-a6ad7e5e5311)

heres what the same playlists look like on the spotify web player (CachyOS arch-based, kernel version 6.7.9-2 stable, XFCE/xfwm4, latest spotube version from AUR)
![20240309_112545](https://github.com/KRTirtho/spotube/assets/104943861/8e69cfb2-722d-4ecb-b137-63f8ca17b88b)
![20240309_112535](https://github.com/KRTirtho/spotube/assets/104943861/588479bb-7a91-48e1-9eb8-f280a9786e2f)

**Comment by bean-frog** [comment]
oops, i meant to also upload spotube desktop (linux as described above)
![Screenshot_2024-03-09_11-28-13](https://github.com/KRTirtho/spotube/assets/104943861/6e74a315-a52f-49eb-bdf8-05d16efaf0f3)

**Comment by graue70** [comment]
`Beyoncé` is shown as `BeyoncÃ©` on the home screen. On the artist page, everything seems to be fine.
