### ISSUE TITLE
Slow music loading, slow in general

### ISSUE THREAD

**Issue by Sxmourai** [KRTirtho/spotube#1304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The app is (most of the time) super slow and sometimes crashes / I have to reopen it.
I have a Redmi 12
When I try to start a song it takes 5-10 seconds before starting to play, even though I set low song quality and I have a good connection.

### Expected Behavior

The app should be way faster because it's native

### Steps to reproduce

Things I find slow (nearly everything):
Try to listen to a song, launch the app, change between search / library / settings...

### Operating System

Android

### Spotube version

Latest on play store

### Installation source

Play Store (Android)

### Additional information

I can work on it, I just don't really know a lot of mobile development

### Self grab

- [X] I'm ready to work on this issue!

**Comment by alexou2** [comment]
Same thing on the f droid version

**Comment by Sxmourai** [comment]
Maybe more async code is needed ?
It seems like the app loads 1-3 songs before playing
