### ISSUE TITLE
flathub update issue

### ISSUE THREAD

**Issue by coolst3r** [KRTirtho/spotube#1313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

flat hub no update but warns theirs a update with pop up.
i am using discover on plasma 6.

### Expected Behavior

a update on flathub

### Steps to reproduce

open app

### Operating System

arch linux

### Spotube version

unsure

### Installation source

Flathub (Flatpak)

### Self grab

- [X] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
Flathub update is not yet published

**Comment by Peperehobbit01** [comment]
I hope soon, maybe it fix the bugs I have but I think, I will need to wait the next update for that xD.

**Comment by KRTirtho** [comment]
Ok closing it as it's solved
