### ISSUE TITLE
Option to log in to Youtube Music account

### ISSUE THREAD

**Issue by Johndjk** [KRTirtho/spotube#1316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

Another login option would be great and would increase the app's user base

### Suggested solution

Add option to log in to Youtube Music account

### Additional information

Desktop app in Linux

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
Explained here why it's not in our vision.
[#1079 ](https://github.com/KRTirtho/spotube/issues/633#issuecomment-1962800128)
