### ISSUE TITLE
Different song playing when another song is supposed to be playing.

### ISSUE THREAD

**Issue by TheJosephKhong** [KRTirtho/spotube#135]
Different song playing when another song is supposed to be playing.

I don't know what caused this.

Installation Source/Method

https://github.com/KRTirtho/spotube/releases/latest/download/Spotube-windows-x86_64-setup.exe
Desktop:

OS: Windows 10
![spotube_YiDnLzMDQg](https://user-images.githubusercontent.com/102836277/177370557-6f79ec9f-0b94-4e8e-b651-fb29bcfdabbd.png)

Version 21H2 (OS Build 19044.1766)

**Comment by KRTirtho** [comment]
Duplicate of https://github.com/KRTirtho/spotube/issues/32
