### ISSUE TITLE
Constant black screen on mac

### ISSUE THREAD

**Issue by ghost** [KRTirtho/spotube#1353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the app opens, the window is all black, with nothing but the traffic light dots in the upper-left corner.

### Expected Behavior

The window would display the app's content.

### Steps to reproduce

1. Open the app on macos (here using Sonoma 14.4 on x86, but this has been like this for months, so previous version of Sonoma were all affected).

### Operating System

MacOS

### Spotube version

3.5 (but was also like this for 3.4 and most likely others before)

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev)

### Additional information

I really want to love this app, but it's always been malfunctioning for me -- from the fact that songs would be followed by minutes of silence (with the track displaying as twice as long as in reality) to this back screen. 
I read similar reports for linux and there were mentions of a secret sharing library, but I am not sure whether this is the same issue on macos and what remedial action can be taken.

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by xoco70** [comment]
present on 3.6 also

**Comment by KRTirtho** [comment]
Launch the app from terminal and submit the logs here. On M1 (and onwards) mac it's working fine. I doubt it will be any different for x86_64 macs. It's probably some system configuration clashing with Spotube's Flutter embedder for MacOS

**Comment by KRTirtho** [comment]
Run following to start from the terminal:

```bash
ERROR=true DEBUG=true VERBOSE=true /Applications/spotube.app/Contents/MacOS/spotube
```

**Comment by xoco70** [comment]
```
➜  ~ ERROR=true DEBUG=true VERBOSE=true /Applications/spotube.app/Contents/MacOS/spotube

[WARNING:flutter/common/graphics/persistent_cache.cc(284)] Could not acquire the persistent cache directory. Caching of GPU resources on disk is disabled.
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PathNotFoundException: Cannot create file, path = '/Users/juju/Library/Containers/oss.krtirtho.spotube/Data/Library/Logs/.spotube_logs' (OS Error: No such file or directory, errno = 2)
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _File.create.<anonymous closure> (dart:io/file_impl.dart:286)
<asynchronous suspension>
#2      getLogsPath (package:spotube/models/logger.dart:30)
<asynchronous suspension>
#3      main (package:spotube/main.dart:122)
<asynchronous suspension>

2024-05-02 11:31:55.652 spotube[21408:743868] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.

```

**Comment by KRTirtho** [comment]
Ok, found the issue. I guess this will happen for every ***new*** mac users. I accidentally removed code for creating the Logs Directory before using it.

So, just creating that directory should fix the issue for now. Run following, it'll create directory and file that is missing at startup.

```bash
mkdir -p ~/Library/Containers/oss.krtirtho.spotube/Data/Library/Logs
touch ~/Library/Containers/oss.krtirtho.spotube/Data/Library/Logs/.spotube_logs
```

**Comment by KRTirtho** [comment]
> ```
> [WARNING:flutter/common/graphics/persistent_cache.cc(284)] Could not acquire the persistent cache directory. 
> Caching of GPU resources on disk is disabled.
> ```

Also, why's it running on Software rendering? Flutter should have access to a GPU. It'll not stop the app from running but it'll make experience sluggish.
