### ISSUE TITLE
Notification service is dying

### ISSUE THREAD

**Issue by Rstment25** [KRTirtho/spotube#136]
Notif keeps dying even when ignore battery optimization is applied :/

**Enable sound while playing video.**

Play/Stop button doesn't work , sometimes pictures freeze too ( it takes fast forwarding through 2/3 songs for it to start loading pictures again ). In video you will see that forwarding to another song starts the playback of that song but that's not the usual behavior... Usually notification service dies , play/stop button only retains ability to pause music and forward/backwards button switches songs but the playback never starts.

Other than that all works fine , this is just inconvenience that has me force closing app every hour or two x: ( On your device might take longer to reproduce ).

I'm also curious if there's any plan to add seek bar to notifications? 
(Control music playback by dragging slider to adjust time)

Like button would also be appreciated so you can favourite a song from the notifications , right now you can only do this by closing whatever you're doing and opening the spotube app which outright kills adding songs to favourite for me

Repeat toggle is missing too both inside the app and notification

https://user-images.githubusercontent.com/32986283/177718312-9a3c9f5f-fad7-48c4-9fbd-ffd8bdb59055.mp4

**Comment by KRTirtho** [comment]
The "running in background" notification issue is harmless & after stopping music Spotube doesn't run in the background at all. Its just a healthy notification from Android to let the user know that some app could be running in the background  (since you Allowed the App to run in the background) but it doesn't mean the App is running

The Notification Panel Controls glitch is resolved already & will be available from the next update

But the Seekbar support in Notification panel will take sometime to land

**Comment by Rstment25** [comment]
@KRTirtho what I mean is I enabled run in the background but the notification controls keep dying despite that... That's what you call notification glitch I guess zzz

Anyways can't wait to see seekbar ! If you have time please add favourite/repeat sometime ( favourite is much needed in the notification window, repeat option idk is nice to have but you can live without it )

**Comment by KRTirtho** [comment]
It's kind of funny but I managed implement SeekBar for Notification Panel in no time. But the Favorite & Repeat button can be time consuming. There's currently no API exposed to Flutter for adding custom buttons to Notification/Lockscreen MediaControls

**Comment by KRTirtho** [comment]
Requested features implemented & issued bug got fixed in the latest release

Please create a separate issue for Favorite & Repeat Button 

**Close this issue if your requested feature/bug is implemented/fixed + released**

**Comment by Rstment25** [comment]
> Requested features implemented & issued bug got fixed in the latest release
> 
> Please create a separate issue for Favorite & Repeat Button
> 
> **Close this issue if your requested feature/bug is implemented/fixed + released**

Was gonna try but do you know why this happens?
![Screenshot_20220711-085119_Package installer](https://user-images.githubusercontent.com/32986283/178205667-980af171-d8f9-423b-aacf-5ec7284b40cc.png)
![Screenshot_20220711-085356_SAI](https://user-images.githubusercontent.com/32986283/178205887-cc8c7aa0-be42-45a4-b510-727e4ba137e1.png)

**Comment by Rstment25** [comment]
My current version is 2.21 also from github

**Comment by KRTirtho** [comment]
> My current version is 2.21 also from github

That's because previous versions were not signed thus Android shows this annoying pop up. From v2.3.0 Spotube will always be signed & from the next update nobody have to uninstall before installing the update

**Comment by Rstment25** [comment]
> > My current version is 2.21 also from github
> 
> That's because previous versions were not signed thus Android shows this annoying pop up. From v2.3.0 Spotube will always be signed & from the next update nobody have to uninstall before installing the update

Let me tell you another tip for how to keep app open for longer - use android take audio focus permission. That's what Spotify uses , yt music too and they never get closed even without battery optimizations enabled.

Spotube never pauses other audio sources which itself is nice but it doesn't help it stay alive if you don't even declare permission ... You can just declare audio focus I think , or use it bogusly on when starting the app and later don't use it ( that's how games nowadays stay alive in background although it might not be necessary to even use audio focus as long as it declared. That's to be tested further I guess... )

**Comment by KRTirtho** [comment]
This issue has been fixed now and available in the latest v2.4.0
