### ISSUE TITLE
[Instance of artist] Bug

### ISSUE THREAD

**Issue by Alguienqueesunapapa** [KRTirtho/spotube#1362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When i try to see the artist outside the app (like in android auto) it's just [Instance of artist]

### Expected Behavior

To see the artist name

### Steps to reproduce

Opened spotube, put a music and go to "action bar?"

### Operating System

Android

### Spotube version

3.5.0

### Installation source

GitHub Actions (Nightly Binary)

### Additional information

I have also tried in the normal build, Same thing

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by BassHoven** [comment]
Just checked, it only happens in the nightly

**Comment by KRTirtho** [comment]
Closing as fixed
