### ISSUE TITLE
Check if music is available locally before downloading it

### ISSUE THREAD

**Issue by hcalebe** [KRTirtho/spotube#1368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

Good evening and thank you for the work you do with this application, it really is perfect. I mean I really like it, I use it every day. now everything that is done can always be improved, don't you think?
I wanted to start a playlist for which I already have all the songs downloaded to my PC, but I noticed that the app was still downloading the songs to play them. It's not really economical, don't you think?

### Suggested solution

This is why I am offering you an option that will check if the song is already downloaded before downloading it again or playing it.

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by Peperehobbit01** [comment]
That would be a good idea

**Comment by rramirezg22** [comment]
Any comments on this enhancement? The white/blank time seconds between tracks are really annoying.
Many players including the Spotify client has a fade feature.

**Comment by Peperehobbits01** [comment]
I completly forgot it was even a - thing. I haven't used Spotify Client for more than 9 months.

**Comment by Peperehobbits01** [comment]
I have created an issue including this and some other improvements regarding downloaded content whit Spotube at #2051 . We will see if the idea gets made or not but to be fair, this issue here is already a ting that should be done.
