### ISSUE TITLE
Black background color option on Android

### ISSUE THREAD

**Issue by Avaneesh-Linux** [KRTirtho/spotube#137]
It would help save battery on many Android devices with OLED and AMOLED displays.

**Comment by KRTirtho** [comment]
Implemented your request. It'll be available in the next release

**Comment by Avaneesh-Linux** [comment]
Thank you :-)

**Comment by KRTirtho** [comment]
Here's a sneak peek

![image](https://user-images.githubusercontent.com/61944859/178048390-4fb5962e-ac1b-40b9-89dd-2a47ed9cb26a.png)

**Comment by KRTirtho** [comment]
Latest version released. Check it out now

**Close this issue your requested feature is implemented + released**
