### ISSUE TITLE
Enormous CPU Draw -- Massive Memory Leak

### ISSUE THREAD

**Issue by sagewilde** [KRTirtho/spotube#1370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I would love to use this app more often. Truly, I would. But there are several problems associated with it. One of which is that it is 5-6x more memory hungry than the closed-source, official application. 

I've gotten so frustrated, I've reverted to using the Snap package on Ubuntu. And it's using 3% of my CPU memory. Spotube peaks at a staggering 76% of my CPU usage, as the *only app.* And it is *still* crashing.

You have a memory leak, and it is catastrophically severe. I cannot in good conscience safely use this application or recommend it to my friends until this memory leak is patched.

### Expected Behavior

Maximum of 10% memory utilization, and the ability to play songs.

### Steps to reproduce

1. I installed the app.
2. I used the login as described in the documentation.
3. It crashes on the first play.

### Operating System

Ubuntu 22.04 LTS

### Spotube version

v3.5.0

### Installation source

F-Droid (Android), Arch User Repository (AUR), Flathub (Flatpak)

### Additional information

I greatly respect the work that you do on this. And if I knew how to write in Dart, or where to start looking for this memory leak, or had the time to do so, I would gladly help. There's a chance you have a 'for' loop that wasn't closed somewhere. Barring that, it may be time to rewrite this from scratch, possibly in a low-level, memory-safe language like Rust, Go, or Java.
I wish you luck.

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
Can you try out the nightly build and check if it was fixed there by any chance? Because there had been major re-writes of the internal cache manager.

>  Barring that, it may be time to rewrite this from scratch, possibly in a low-level, memory-safe language like Rust, Go, or Java.

I'm pretty sure that will cut off half of the platforms supported by this project. The issue you're facing could be a rare case, because I myself use Linux Mint 21.3 (latest ig), and yet I haven't found any memory leaks.

**Comment by Meta4245** [comment]
> I'm pretty sure that will cut off half of the platforms supported by this project.
it won't cut off mac, windows, or linux for sure, but Rust and android just seems to be yew.rs or tauri (essentially webview)

**Comment by sagewilde** [comment]
I'll give it another try. Thank you.

**Comment by KRTirtho** [comment]
Can you try out the [nightly version](https://github.com/KRTirtho/spotube/releases/tag/nightly)? The cache management was changed significantly like I said before. I want to make sure we're not tracking an already fixed bug in nightly

**Comment by sagewilde** [comment]
I just tried the Nightly version. I'm listening to it now, and I'm noting significantly less memory draw, on par with the official app. It's much more responsive, and far less laggy. A vast improvement! Well done.

**Comment by KRTirtho** [comment]
> I'm actually new to programming. I just started learning at university, and we haven't started learning cache management yet. How do you find problems like this, and what are the steps you take to correct them?

Here's the secret, we don't. We simply re-write the entire project /s

But on serious note, user usually complaints and there's usually debuggers (devtools for flutter stack) that show memory usage waterfall or allocation based graphs (scatter graphs usually). From these graphs/reports/dumps we can learn about what instances of what Class and with what dependencies are allocating memory more frequently and not getting Garbage Collected for a long time (singleton classes are ignored in this case). Also, we can see the same for methods/functions for a more granular report.

But the tricky ones are the CPU spikes. They can be hard to find, especially the spikes that are happening at random and depends on ridiculous but frequent scenarios to happen. It's like finding a needle in a haystack.

Don't get confused by all these terms and analogies. Just keep on learning, after sometime, you'll know it way better than ever.
