### ISSUE TITLE
Missing dependencies in .deb files

### ISSUE THREAD

**Issue by Peperehobbit01** [KRTirtho/spotube#1373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you try to install the .deb version of the app you are getting the error saying that the libjsoncpp25 is unsatisfied. I'am gonna look into it and post followups here but if someone could help I would not mind.

### Expected Behavior

The dependecies can be installed to install the app.

### Steps to reproduce

- Donwload the .deb packages of the latest version.
- Open it
- Then you will have the error

### Operating System

Linux Mint (Cinamon Edition)

### Spotube version

v3.5.0

### Installation source

GitHub Releases (Binary)

### Additional information

If some what's to help on this i would appriciate because I am still a newbie on linux xD

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by Peperehobbit01** [comment]
![image](https://github.com/KRTirtho/spotube/assets/106733214/79a66948-c3d1-4303-a7e3-7024fbfc1946)

**Comment by KRTirtho** [comment]
Are you running Mint version that is based on Ubuntu version lower than 23.04 (e.g. 20.04/22.04/22.10 etc)? If so, it'll not work as the package was built for Ubuntu 23.04. You've to use Flatpak version of Spotube in that case

**Comment by Peperehobbit01** [comment]
Well, there is no version of linux mint based of the 23.04 of Ubuntu xD, just say that you don't supported then whit the .deb packages or just created a version that is supported because I mean, Linux Mint is the most use distro of linux.

**Comment by KRTirtho** [comment]
Wait a minute 22.04 is actually [supported](https://ubuntu.pkgs.org/22.04/ubuntu-main-amd64/libjsoncpp25_1.9.5-3_amd64.deb.html). Anything below that shouldn't work. There must be some other issue.

Btw try to post error logs/screenshots in English. It makes it easier for anyone to investigate the bug.

**Comment by Peperehobbit01** [comment]
Oh ok, well I am on 20.3 because 21.3 dosen't work for me so yeah It dosen't work xD and sure no problem :)
