### ISSUE TITLE
App lags too much on android 10

### ISSUE THREAD

**Issue by Chndnngr** [KRTirtho/spotube#1378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The apps lags too much, i think  spotube's dpi is the main problem here, so can you make an app for android 10 with lesser dpi? Its a request, bcus it's almost unusable in my phone, but media playing is really great, and that's the best thing in the app

### Expected Behavior

I thought the app will be smooth af

### Steps to reproduce

1. I open the app. 2. Started scrolling or going to my library. 3. The app lags during any animations

### Operating System

Android 10 arm64

### Spotube version

V3.5.0 (29)

### Installation source

GitHub Releases (Binary)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
Fixed in 6673e5a

**Comment by KRTirtho** [comment]
It'll be available in the next release

**Comment by Chndnngr** [comment]
Thanks man
