### ISSUE TITLE
Indicator for already Downloaded songs

### ISSUE THREAD

**Issue by owencz1998** [KRTirtho/spotube#138]
Add a tick to the song that's downloaded on the playlist section and a download song button whiles on the playlist tab.

**Comment by owencz1998** [comment]
Cheers dude

**Comment by owencz1998** [comment]
![Screenshot_20220708-200944.jpg](https://user-images.githubusercontent.com/96526481/178056481-d40edd18-189f-4d2a-a109-013675684456.jpg)

Is it possible to add a download button and the download indicator into the playlist like the  image obviously the tick can be the colors that are on the app lol I just couldn't get a normal tick lol :D

**Comment by Farincal** [comment]
Helo
