### ISSUE TITLE
Lyrics time added/subtracted should reset when song changes

### ISSUE THREAD

**Issue by Ocean-OS** [KRTirtho/spotube#1400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the Android app, if you add/subtract seconds to the lyrics so they sync better with the song, the seconds added/subtracted remain added/subtracted for all of the songs. So, if you add 5 seconds to the lyrics for one song, unless you change it back, those 5 seconds will stay added to the lyrics for every song. 

### Expected Behavior

I would expect that the seconds added/subtracted from the lyrics would reset with every song, as most of time, songs don't have the same exact syncing issue. 

### Steps to reproduce

1. Start a playlist or queue with multiple songs
2. Add/subtract a few seconds from the song's lyrics
3. Wait for the next song/skip to the next song
4. See that the number of seconds added/subtracted stays the same

### Operating System

Android

### Spotube version

3.5.0

### Installation source

Play Store (Android)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
Check out in 3.6.0. It should be fixed
