### ISSUE TITLE
Spotify login error (format exception)

### ISSUE THREAD

**Issue by rti2** [KRTirtho/spotube#1403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I enter the app, I get an error with logging into the Spotify and some html codes :
Format exception .Unexpected character at( line 2 character 1)

### Expected Behavior

Don't get that error and use the app normally 

### Steps to reproduce

I opened app and get this error 

### Operating System

Android 

### Spotube version

3.5.0

### Installation source

GitHub Releases (Binary)

### Additional information

![IMG_20240414_182118](https://github.com/KRTirtho/spotube/assets/149401693/4eb35edd-edea-49b6-a1ff-fde206fe4ec7)
This is the error .

### Self grab

- [x] I'm ready to work on this issue!

**Comment by graue70** [comment]
I think I had this issue. After that, I was automatically logged in to some kind of test account based in Bangladesh with the subscription 'hacker'. Pretty confusing.

Logout and login helped.

**Comment by KRTirtho** [comment]
Lol, I guess the cache didn't get reset after login (which is def' a bug). Those are the default name/info for Anonymous user. I left it there as an easter egg. Well, congratulations, you found it 🎉  But there are no prizes 😂

**Comment by KRTirtho** [comment]
Please create a new issue for it though because, it wasn't supposed to be there after successful login. Probably a caching issue

**Comment by Erz3** [comment]
> Lol, those are the default name/info for Anonymous user. I left it there as an easter egg. Well, congratulations, you found it 🎉  But there are no prizes 😂 

... That make me feel worry about the security state of my device 😓

**Comment by ElBori82** [comment]
I'm having the same issue on my devices, android & pc. Login in to spotify no longer works.

**Comment by Dodysui** [comment]
> Try logging out and relogin

IS note working you have to force stop app and restart

**Comment by rocholojavinar** [comment]
![](https://img.youtube.com/vi/skZcNHFExzo/maxresdefault.jpg)

**Comment by ADIOR-enigma** [comment]
> Lol, those are the default name/info for Anonymous user. I left it there as an easter egg. Well, congratulations, you found it 🎉  But there are no prizes 😂 

So that's what it is 😂 I was literally worried that my account was hacked.
And searched the whole internet for it like 2 hours. Lol, 🤣

**Comment by rti2** [comment]
> > Lol, those are the default name/info for Anonymous user. I left it there as an easter egg. Well, congratulations, you found it 🎉  But there are no prizes 😂
> 
> So that's what it is 😂 I was literally worried that my account was hacked. And searched the whole internet for it like 2 hours. Lol, 🤣

LOL
