### ISSUE TITLE
[Fail update] Missing depends on deb package

### ISSUE THREAD

**Issue by OpenCode** [KRTirtho/spotube#1412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Installation fails because there is a missing depend: mdns-scan

### Expected Behavior

Installation without warnings and fails.

### Steps to reproduce

1. Download deb package from https://spotube.krtirtho.dev/downloads
2. Try to install the package

### Operating System

Ubuntu 22.04

### Spotube version

v3.6.0

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev)

### Additional information

Can be solved as workaround with `sudo apt install mdns-scan`

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
But `mdns-scan` is already listed as a dependency. Why would fail to install? 🤔

**Comment by OpenCode** [comment]
> But `mdns-scan` is already listed as a dependency. Why would it fail to install? 🤔

I don't know. It happened to me trying to install the latest package.

**Comment by gengrill** [comment]
Same here, latest version doesn't install:
```
dpkg: dependency problems prevent configuration of spotube:
 spotube depends on avahi-discover; however:
  Package avahi-discover is not installed.
 spotube depends on avahi-utils; however:
  Package avahi-utils is not installed.
 spotube depends on mdns-scan; however:
  Package mdns-scan is not installed.

dpkg: error processing package spotube (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 spotube
```

**Comment by KRTirtho** [comment]
@gengrill using `dpkg -i` will not resolve the dependency of any given .deb bundle. You've to use `sudo apt install` to get all the dependencies of .deb installed alongside

**Comment by OpenCode** [comment]
Old issue. Solved.
