### ISSUE TITLE
No settings after updating to 2.3.0 on windows 10

### ISSUE THREAD

**Issue by JoAllg** [KRTirtho/spotube#144]
**Describe the bug**
After Updating the windows app (via chocolatey or the exe from github) to the new version 2.3.0, the settings button is missing
![grafik](https://user-images.githubusercontent.com/57436524/178351507-a6b74639-4319-494b-94d6-c2f75e7b7d1b.png)

The old spotube version is also still installed in syswow64 (featuring a settings button).

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 10

**Comment by KRTirtho** [comment]
The settings button along with user profile icon is now at the lower section of the application. Its just shy above the player in left sidebar

**Comment by JoAllg** [comment]
Not in my case. It might have something to do with the installation over the older version, so I can try a complete new installation.
![grafik](https://user-images.githubusercontent.com/57436524/178434855-685659c4-b1bf-46e0-bfa6-36a74c7826c9.png)

**Comment by x07C0** [comment]
Same here, but the setting menu is available when app is not in fullscreen. 
Normal:
![image](https://user-images.githubusercontent.com/37380849/178495290-684303aa-8754-4b63-b641-c268d9de824b.png)
Fullscreen:
![image](https://user-images.githubusercontent.com/37380849/178495343-2ab1c53b-f427-4883-894e-a1cc8447986d.png)

**Comment by Thymelizabeth** [comment]
I have the same problem.
Running Sway (Wayland) on Arch Linux.
The problem occurs with both the flatpak and the AUR apps.
It seems to occur only when the window is above a certain width on the screen (about 3/4 across it).

![19-07-2022_11-07-1658188076](https://user-images.githubusercontent.com/99952495/179635705-9408b484-3b01-4100-b993-d05e88f15e5c.jpg)
Below 1/5, the button for settings is displayed at the bottom of the screen, and can be clicked on.

![19-07-2022_11-07-1658188095](https://user-images.githubusercontent.com/99952495/179635728-fa205007-5c78-48f0-9db9-a6f5df064095.jpg)
Between 1/5 and 2/5, no settings icon is displayed, but I can still click on the profile picture to go to settings.

![19-07-2022_11-07-1658188115](https://user-images.githubusercontent.com/99952495/179635747-7558c982-5e79-4a5e-95f0-199176618d75.jpg)
Between 2/5 and 3/4, the settings button is displayed above the song bar, and can be clicked on.

![19-07-2022_11-07-1658188130](https://user-images.githubusercontent.com/99952495/179635769-f6c321b7-d57f-4fee-8a35-bebdbd335c49.jpg)
It is only when the app is more than 3/4 filling the screen horizontally that the settings button disappears. Note that in the image above, the app is not full screen. When the app is full screen, however, it still has the same layout.

**Comment by KRTirtho** [comment]
Yeah, it's fixed already but not yet released. You can find the fix in [Nightly Release](https://spotube.netlify.app/other-downloads/nightly-downloads)

**Comment by KRTirtho** [comment]
@JoAllg @Thymelizabeth it's now available in the release version 2.4.0
