### ISSUE TITLE
Windows App Crash v3.6.0

### ISSUE THREAD

**Issue by Bugophobe** [KRTirtho/spotube#1440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

As mentioned in https://github.com/KRTirtho/spotube/issues/1156 and https://github.com/KRTirtho/spotube/issues/118 and https://github.com/KRTirtho/spotube/issues/44 Spotube crashes after running

### Expected Behavior

It's supposed to run!

### Steps to reproduce

1. Installed the app.
2. Attempt to run Spotube
3. Appears in task manager for 2 seconds and disappears

### Operating System

Win 11

### Spotube version

v3.6.0

### Installation source

GitHub Releases (Binary)

### Additional information

reverting to 2.6.0 works fine 
@KRTirtho could you fix this, please?

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
Closing it as there's already issues opened

**Comment by KRTirtho** [comment]
> Is there an existing issue for this?

> - [x] I have searched the existing issues

What's the point of this if you already know there's issues exist? Please, do not open same issues just to enforce priority on it. The developers already knows about this. If you just want to remind, ask on the specific issue thread.
