### ISSUE TITLE
Music not playing 

### ISSUE THREAD

**Issue by 6ftFemboy** [KRTirtho/spotube#1444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Absolutely nothing is playing, only downloaded songs. It just loads for a fre seconds and stops then does nothing 

### Expected Behavior

For it to play songs 💀

### Steps to reproduce

Opened the app (downloaded from play store)
Go to playlists tab
Try to play a playlist

### Operating System

Android 

### Installation source

Play Store (Android)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by lucastucious** [comment]
Same... 
Win 11, version 3.6.0, tried uninstall-reinstall but same issue...

**Comment by kaibaur** [comment]
Just installed it, no music loading, no FAQ or fix for this.

**Comment by KRTirtho** [comment]
Can you provide the logs from "Settings" > "Logs"?

**Comment by lucastucious** [comment]
> Can you provide the logs from "Settings" > "Logs"?

Nothing in the log

**Comment by lucastucious** [comment]
https://github.com/KRTirtho/spotube/assets/28046122/6135aeba-c239-4f19-a3ce-23847b3d45e6

Weird behavoiur recorded

**Comment by Tonnoman** [comment]
I experienced the exact same issue as @lucastucious, not only on win 11 but also with the mobile app

**Comment by KRTirtho** [comment]
This was an YouTube API change that broke the playback. Check #1979
