### ISSUE TITLE
Can't login with Spotify in iOS app

### ISSUE THREAD

**Issue by AushevAhmad** [KRTirtho/spotube#1448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When clicking on "Login with your Spotify" causes a "Something went wrong" error, then app reloads Spotify page yet nothing works

### Expected Behavior

Logging in by Spotify

### Steps to reproduce

1. I've opened app
2. Went to settings
3. Pressed on "Login with your Spotify account"
4. I got an error message "Something went wrong"

### Operating System

iOS

### Spotube version

v3.6.0

### Installation source

GitHub Releases (Binary)

### Additional information

I used Maplesign to sign & install the app and it successfully installed without any issues but I still experience that bug

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by Obambulate** [comment]
do you have any alternate browser or some sort of app that blocks ads or is not supported by the spotify web client that might be interfering with this process?
