### ISSUE TITLE
I'm finding it impossible to link my spotify account. Is this problem peculiar to me? It was working before I updated to version 2.3.0. Update: it finally worked.

### ISSUE THREAD

**Issue by drscrado** [KRTirtho/spotube#145]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Installation Source/Method**
- Package Manager: <e.g flatpak/chocolatey>
- Community Repo: <e.g AUR/appimagehub>
- Binary Source: <resource_url>

**Desktop (please complete the following information):**
 - OS: [e.g. archlinux]
 - Version [e.g. v1.0.0]

**Smartphone (please complete the following information):**
 - Version [e.g. v1.0.0]

**Additional context**

**Comment by KRTirtho** [comment]
Please provide the required information first else How will I be able to help you?
