### ISSUE TITLE
Some text is garbled

### ISSUE THREAD

**Issue by xfrqh** [KRTirtho/spotube#1463]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The text of the artist in the interest recommendations is garbled.

### Expected Behavior

No garbled text.

### Steps to reproduce

1. Launch Spotube
2. Scroll down

<img width="540" alt="2024-05-02_14-16-27" src="https://github.com/KRTirtho/spotube/assets/73733485/f36da0a7-a982-414e-bf06-5d3704563cf0">

3. You can see that the text of the artist in the interest recommendations is garbled.

Spotify 客户端的正常表现

![Screenshot_2024-05-02-13-52-42-276_com spotify music](https://github.com/KRTirtho/spotube/assets/73733485/0c08cc18-d17d-4a9b-a397-95241afa6196)

### Operating System

Android: 13
UI: MIUI 14.0.8.0(TKPCNXM)
Linux Kernel: 4.14.186-gaa24d707761c
Device: Redmi Note 10 Pro(chopin)
Magisk: 26.4-kitsune(26400)

### Spotube version

3.6.0 (30)

### Installation source

F-Droid (Android)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by JapanYoshi** [comment]
As I pointed out in #1475, This behavior is consistent with mis-interpreting UTF-8 text as Latin-1.

Correct text: 每日推荐

UTF-8 bytes: `E6 AF 8F E6 97 A5 E6 8E A8 E8 8D 90`

Misinterpreted as Latin-1: `æ¯�æ�¥æ�¨è��` (� = byte not mapped to any character)

**Comment by KRTirtho** [comment]
I fixed the issue. But, it was actually related to the `http` package. It uses latin-1 by default for all `application/json` responses without `; chartset=utf8` in 2024. I didn't know that until facing this issue.

https://github.com/dart-lang/http/issues/175
