### ISSUE TITLE
Lyric Source Selection

### ISSUE THREAD

**Issue by Ocean-OS** [KRTirtho/spotube#1464]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

As the lyrics system has changed, and some sources have bugs, and some sources are just better than others, it'd be nice to be able to choose what source is the priority for lyrics. 

### Suggested solution

I was thinking that there could be one of two options: 
- A dropdown selection for lyric source, like the music source selection in settings
- A button in settings, that lets you sort music sources in a list, based on priority (if a song doesn't have lyrics available from the first priority source, try the second priority source, and so on)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
Spotify Lyrics are considered the best match and if it have both Synced and static lyrics, it'll be selected by default.
LRCLIB.net works as a fallback now already. Becuase LRCLIB usually has popular tracks, but regional ones (except US, CA, UK, Sweden) are much better found on Spotify and that doesn't require Premium, luckily

> - A button in settings, that lets you sort music sources in a list, based on priority (if a song doesn't have lyrics available from the first priority source, try the second priority source, and so on)

Audio Source has nothing to do with the Lyrics. Lyrics are directly matched using Spotify Track title and primary artist for LRCLIB and track id for Spotify (Musixmatch) itself

**Comment by makoto-kokoroki** [comment]
You definitely have to have Spotify Premium now for lyrics to work, so...

**Comment by KRTirtho** [comment]
Yup, so if it detects there's no lyrics, it'll switch to LRCLIB automatically.

**Comment by KRTirtho** [comment]
Ok, so it's the same issue of #1461. In that case we've check if it's more than 4 lines or not (or something similar).

**Comment by KRTirtho** [comment]
The thread will continue there. Thus closing it as duplicate (sorta)
