### ISSUE TITLE
Too many artists for a track causing overflows

### ISSUE THREAD

**Issue by powerdollkirby** [KRTirtho/spotube#1470]
### Current Behavior

this is not necessarily a bug but it's inconsistent 
![Screenshot_20240503_171215](https://github.com/KRTirtho/spotube/assets/105698999/1ae8b4e3-9983-4597-ae47-2174ffea11b7)

### Expected Behavior

have/keep same height/size

### Steps to reproduce

playing any song with a long title or multiple artists

### Operating System

Linux

### Spotube version

v3.6.0

### Installation source

Arch User Repository (AUR)

### Additional information

also some songs like Derude - sandstorm don't match the audio

### Self grab

- [X] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
Lol, at that point they should just create a temporary band or group vocalists 🤣 

No, worries. I guess we've to limit the artists to 2 Lines instead allowing all of them, breaking the UI
