### ISSUE TITLE
Duration of song doubled on MacOS

### ISSUE THREAD

**Issue by ahshum** [KRTirtho/spotube#148]
**Describe the bug**
Duration of song doubled in MacOS

**To Reproduce**
1. Open Spotube
2. Play any song
3. The duration is doubled
4. It is not display error. After the correct duration, the song will continue to play silently.

**Expected behavior**
Display correct duration and play next song correctly.

**Screenshots**
The song is 3:23 long:
<img width="952" alt="image" src="https://user-images.githubusercontent.com/4080806/179194413-547a5ab2-7b69-475f-bd68-8424109411d4.png">

While it is playing, it shows 7:07 and is still playing after 3:23
<img width="952" alt="image" src="https://user-images.githubusercontent.com/4080806/179194448-d4dfecf5-863d-41f7-ad93-e18471097bef.png">

**Installation Source/Method**
- download from Github release

**Desktop (please complete the following information):**
 - OS: Mac
 - Version: v2.3.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by KRTirtho** [comment]
Looks like a lot of people are having this issue

**Comment by cocoonkid** [comment]
Came here to report the same!  MacOS

In the playlist durations are correct but doubled when playing and remainder is just silent.

**Comment by karniv00l** [comment]
Same here

**Comment by KRTirtho** [comment]
@karniv00l Since you're already familiar with Spotube codebase and happens to have a Mac, can you try using different available YouTube codecs in MacOS and see if this happens in other codecs as well?

You can see the available codecs by adding `print(trackManifest.audioOnly.map((info) => info.codec.mimeType));` before following  Line-435 
https://github.com/KRTirtho/spotube/blob/aba1ba932592923720a36395c057f78820dafecf/lib/provider/Playback.dart#L435-L444

**Comment by karniv00l** [comment]
I'm actually not familiar with the codebase at all 😅

Changing codec from `audio/mp4` to `audio/webm` results in error.

I've also inspected some variables in this class, and it seems like YT and Spotify tracks both reports correct length and correct song (with some exceptions). So I would say it may be some bug in elsewhere, like in the core of the player?

**Comment by KRTirtho** [comment]
Yeah `audio/webm` in Apple devices is not supported 'cause it's Apple

> I've also inspected some variables in this class, and it seems like YT and Spotify tracks both reports correct length and correct song (with some exceptions). So I would say it may be some bug in elsewhere, like in the core of the player?

So it could be flutter `audioplayers` plugin?

**Comment by cocoonkid** [comment]
@KRTirtho @karniv00l . 

Thanks for looking into this.  It's really an annoying bug in the core :-)

**Comment by maxired** [comment]
Hi,
As a macos user, I also experience this bug.
after some investigation, this seems to be a rather low level bug.
Downloading the audio/mp4 file played by spotube, then trying to open it with QuickTime, the display duration is also wrong.
With VLC, the correct duration is visible.

After renaming the file, as suggested by https://apple.stackexchange.com/a/443882 , the correct duration is visible

**Comment by karniv00l** [comment]
This isn't solved @RaptaG

**Comment by KRTirtho** [comment]
So I replaced `audioplayers` for macos with `just_audio` and it seems like this double duration issue is fixed. You can download the latest [nightly](https://spotube.netlify.app/other-downloads/nightly-downloads) to check if it's working for you

**Comment by maxired** [comment]
@KRTirtho I confirm the nightly build has correct sont duration on macos Monterey
