### ISSUE TITLE
Home Assistant Integration

### ISSUE THREAD

**Issue by Chreece** [KRTirtho/spotube#1481]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

It would be nice to have an integration that could eventually control the Spotube from a Smart Home application such as [Home Assistant](https://www.home-assistant.io/).
This could release a plenty of new potentials, such as music automation depending on circumstances (wake up, sleep, party) or the people that are home... Imagination is the sky...

### Suggested solution

Integration for Home Assistant

### Useful resources

https://www.home-assistant.io/
https://developers.home-assistant.io/

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
Usually, we don't build integration with 3rd party softwares except anything that benifits the playback in Spotube itself.
We, have an API based on WebSocket and `zeroconf` that can be used to control the playback of Spotube. The "Connect" feature of Spotube uses it to implement Remote Control from any device in same WiFi/Network.

Currently, there are no docs about it. But, here's the [source code](https://github.com/KRTirtho/spotube/blob/v3.6.0/lib/provider/connect/server.dart)

**Comment by s-b-repo** [comment]
https://github.com/s-b-repo/spotube-api-docs/tree/main made some api docs feel free to correct me
