### ISSUE TITLE
Automatically find source and buffer next song.

### ISSUE THREAD

**Issue by ManIWishIHadTacos** [KRTirtho/spotube#1497]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

Often times I've eagerly waited for the next song to load, but it takes an unreasonable amount of time.

### Suggested solution

Automatically search for the source of the next song in queue while the current song is playing, and buffer the first bit (hypothetically 250kb) for seamless playback.

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by knightmar** [comment]
Please make this !

**Comment by KRTirtho** [comment]
This has been implemented ages ago. But there was a certain bug where the player got stuck on track that it can't find any match for. Fixed in v3.7.1
