### ISSUE TITLE
Graphic-bugs

### ISSUE THREAD

**Issue by bkfirmen** [KRTirtho/spotube#150]
The screen is randomly flickering when using Spotube. Ive never seen this bug before, so I assume that it is a bug of Spotube, not of LineageOS (maybe I am wrong).

**To Reproduce**

**Expected behavior**

**Screenshots**
Video: [Spotube-bug.webm](https://user-images.githubusercontent.com/85055040/179348382-c9000d69-85e0-4f1e-9203-77ca9fc5fec6.webm)

**Installation Source/Method**
- Package Manager: FDroid
- Community Repo: 
- Binary Source: 

**Smartphone:**
 - Device: Samsung Galaxy S5 Duos (SM-G900FD)
 - OS: LineageOS
 - Version 18.1 (Android 11)

**Additional context**
Screen-Resolution: 1080p
App-Version: 2.3.0
-> Ask me for more information (if needed)

**Comment by KRTirtho** [comment]
This can be a graphics driver issue or directly related to Flutter's compatibility with LineageOS

**Comment by karniv00l** [comment]
Maybe same issue as here: https://github.com/flutter/flutter/issues/105093

**Comment by bkfirmen** [comment]
Thanks, :) Then it is an issue of the lineage drivers/flutter.
