### ISSUE TITLE
Add song covers to rich presence!

### ISSUE THREAD

**Issue by DqrknessItself** [KRTirtho/spotube#1503]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

The Discord Rich Presence status uses an image for the cover that means nothing considering all songs use it.

### Suggested solution

Please consider adding the covers for tracks as they would add a lot of value to the rich presence!

### Useful resources

I'm not a developer but you already have access to the Spotify API and song covers as they are used in the app. Therefore, they should be usable for discord rich presence (I'd assume) :)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by SrIzan10** [comment]
yeah! I'm not into dart but just by adding the URL into the rich presence server settings it should work!

**Comment by SrIzan10** [comment]
alright, for anyone who has the Flutter dev tools on their machine, adding the image URL on this line should do it: https://github.com/KRTirtho/spotube/blob/cb95663412fcc9a829c5657e0160132f13fb0649/lib/provider/discord_provider.dart#L32

**Comment by DqrknessItself** [comment]
@KRTirtho
Hi there, kindly please see this simple suggestion! :)
