### ISSUE TITLE
Cannot login in Android phone

### ISSUE THREAD

**Issue by gtang8** [KRTirtho/spotube#1506]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I can login my google account in an Android pad, but cannot login in my Android phone. There is a login bar in Android pad, but no such login bar in Android phone.

### Expected Behavior

I can login in both pad and phone

### Steps to reproduce

No login bar in Android phone

### Operating System

Android

### Spotube version

13

### Installation source

GitHub Releases (Binary)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by homestocksan** [comment]
same issue for me, Can't login on android phone.
