### ISSUE TITLE
Spotube Connect not discovering devices

### ISSUE THREAD

**Issue by sudoAlphaX** [KRTirtho/spotube#1507]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Spotube connect feature is not being discovered by either my PC or my android phone. Im able to find my other android devices but it seems the PC app is not discovering any devices, nor is being discovered by any device.

### Expected Behavior

Spotube desktop app discovers other devices in the network, and can be discovered by other devices to control music playing in any device.

### Steps to reproduce

1. Launch Spotube desktop app
2. Go to settings and enable Spotube Connect under playback
3. Install and launch spotube connect in another device (android)
4. Follow step 2 for the android app
5. Click on devices button on the app on both the devices
6. No device is discovered in either device 

### Operating System

Arch Linux x86_64

### Spotube version

v3.6.0

### Installation source

Arch User Repository (AUR), Flathub (Flatpak)

### Additional information

I have concluded that the issue lies on the desktop app, since my two other android devices are successfully discovering each other. But the desktop app is not discovering either device.
I have tried installing the flatpak app, the spotube-bin from the AUR, and even compiled spotube using the spotube AUR package. Still, none of the methods work.

Also, on one android device, I've installed Spotube through F-Droid, and on the other, through Play Store.

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
<img width="1118" alt="image" src="https://github.com/KRTirtho/spotube/assets/61944859/ede8ba6c-7508-4948-a032-b47c7bcbe543">

**Comment by sudoAlphaX** [comment]
Hello @KRTirtho, thanks for replying.
As i have mentioned in the issue, under "Steps to Reproduce" point 2, I have already enabled Spotube Connect under settings, in all the 3 desktop clients i have tried.

**Comment by sudoAlphaX** [comment]
It seems that somehow, my desktop client is unable to access the local network. I have notices that if Spotube Connect is enabled in any of my android device, under the Remotes section, the device itself appears. It must be a bug, but it helped my conclude one thing. The desktop client is unable to access the local network, because in my desktop client, under the remote section, no device appears.

**Comment by sudoAlphaX** [comment]
Issue fixed

I was able to fix this by enabling and starting avahi-daemon.service and avahi-dnsconfd.service.

Commands ran:
sudo systemctl enable --now avahi-daemon.service
sudo systemctl enable --now avahi-dnsconfd.service

OS details:
Arch Linux x86_64
spotube-bin from AUR

**Comment by Sythsaz** [comment]
Does this not discover Chromecast, Sonos etc, devices on the network as well? Thanks

**Comment by sudoAlphaX** [comment]
Nope, afaik, Spotube Connect is different from Spotify Connect. It can be used only to discover (and control) other devices running a Spotube client

**Comment by clari7744** [comment]
I'm having this issue as well on Ubuntu 24.04. I tried `sudo systemctl restart avahi-daemon.service`, but I don't have the `dnsconfd` service that @sudoAlphaX has.
Restarting the avahi-daemon made the Remote section appear, but there's nothing under it.
![image](https://github.com/user-attachments/assets/037d51ed-18c3-42ae-a2fc-88d0ec10caa2)
I am experiencing the same situation where my Android phone is showing itself but not my laptop. I know they can both see each other over Tailscale so if they are supposed to be on the same network, that shouldn't be an issue.
Any suggestions? I don't have a lot of networking knowledge so I may just be missing the Ubuntu equivalent of that DNS conf service
