### ISSUE TITLE
Windows installer default path to temp folder

### ISSUE THREAD

**Issue by darkphoenixfox** [KRTirtho/spotube#1508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Downloaded the W32 installer from https://spotube.krtirtho.dev/ using Edge 124.0.2478.97 (Official build) (64-bit) on Windows 11 23H2

The installer does not allow to chose a install path. The default path is an Edge temp folder:
`C:\Users\<username>\AppData\Local\Temp\MicrosoftEdgeDownloads\ef474762-dce7-4da0-95c3-53e251a7e5a5\Spotube`

The folder is emptied on restart, effectively uninstalling Spotube

### Expected Behavior

The app is installed to an non-volatile location and persists through restarts.

### Steps to reproduce

1. Download W32 installer with Edge browser
2. Install on Windows 11 23H2
3. Check the location for the spotube.exe file
4. Restart computer
5. App has been deleted

### Operating System

Windows 11 23H2

### Spotube version

v3.6.0

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
This has been fixed in 3.7.0

**Comment by darkphoenixfox** [comment]
@KRTirtho I have downloaded the latest installer and I am still observing the same behaviour
