### ISSUE TITLE
Error 401 no get tokens

### ISSUE THREAD

**Issue by Matt0967** [KRTirtho/spotube#1518]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Current Behavior

Hi, I have a bug to this app and i my on Linux Ubuntu (Pop_os)

Error : 
![Capture d’écran du 2024-05-21 14-46-04](https://github.com/KRTirtho/spotube/assets/144120980/eed18253-799e-4366-8345-c9e80875bad3)

### Expected Behavior

I expected to work to my pc with music

### Steps to reproduce

1. I open the app 
2. What happens if
I not information

### Operating System

linux

### Installation source

GitHub Releases (Binary), GitHub Actions (Nightly Binary)

### Additional information

![Capture d’écran du 2024-05-21 14-46-04](https://github.com/KRTirtho/spotube/assets/144120980/e770ead9-111f-4ca6-8e35-1eaeca363317)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by s-b-repo** [comment]
have the same issues just restart app tokens probably expired

**Comment by s-b-repo** [comment]
what can solve this a deamon in the background that fetch scripts in the background

**Comment by s-b-repo** [comment]
https://github.com/s-b-repo/spotube-daemon-cookie-grabber/tree/main made a basic implementation you can work off of

**Comment by Matt0967** [comment]
Thanks, it's fixed now

**Comment by Msakhibullin24** [comment]
on win 11 this problem
how to fix?

> https://github.com/s-b-repo/spotube-daemon-cookie-grabber/tree/main made a basic implementation you can work off of

**Comment by RyzeNGrind** [comment]
Have same issue on android apk with spot. acct.
