### ISSUE TITLE
Spotube uses incorrect values for MPRIS position property

### ISSUE THREAD

**Issue by AlephNought0** [KRTirtho/spotube#1521]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Spotube currently uses QVariant(qlonglong) for position property which makes it unable to fetch the proper position of the current playing media on Spotube.

### Expected Behavior

Spotube should send the value of the property according to the freedesktop specifications. Mpris:Position is not a variant. See more here.
https://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html#Property:Position

### Steps to reproduce

1. Open Spotube
2. Try fetching Mpris position property from Spotube using playerctl or other means.
3. The returned value does not reflect the actual position of the media

### Operating System

Linux, NixOS

### Spotube version

v3.6.0

### Installation source

GitHub Releases (Binary)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
That's a great finding. I think we change the datatype to Time_in_Us

**Comment by KRTirtho** [comment]
Actually, we are using a library `audio_service_mpris` that implements the DBus interface for MediaPlayer2. So, it was sending the wrong types. Now, they've updated to freedesktop specifications. So it's just simple library update.

**Comment by AlephNought0** [comment]
> Actually, we are using a library `audio_service_mpris` that implements the DBus interface for MediaPlayer2. So, it was sending the wrong types. Now, they've updated to freedesktop specifications. So it's just simple library update.

That's great to hear!
