### ISSUE TITLE
Chrome Extension for Easy Cookie Extraction

### ISSUE THREAD

**Issue by PrivTEC** [KRTirtho/spotube#1527]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Pain

Hello,

I am a developer who recently created a Chrome extension specifically for Spotube. 

The idea for this extension came to me spontaneously when my girlfriend, who is not a tech-savvy person, struggled with the manual cookie extraction process described in your documentation. I realized that there must be many other users facing similar challenges, so I decided to create a solution to make this process easier for everyone and I hope this extension can contribute to its success.

### Suggested solution

The extension, called "Spotify Cookie Extractor for Spotube," automates the process of extracting the 'sp_dc' cookie from Spotify's website. This cookie is necessary for Spotube to function properly, but the manual extraction process can be quite complicated for non-developers.

I believe this tool could greatly enhance the user experience for Spotube users, especially those who are not familiar with developer tools. I would love to hear your thoughts on this and discuss any potential collaborations or improvements.

### Useful resources

You can find the extension and its repository here: 
[PrivTEC](https://github.com/PrivTEC/Spotify-Cookie-Extractor-For-Spotube)

### Additional information

![head_gitimg](https://github.com/KRTirtho/spotube/assets/96919646/517bff37-6dc0-404d-ac3b-308d4c2b7ba1)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by Peperehobbit01** [comment]
Yeah, that does make sense.

**Comment by KRTirtho** [comment]
Thanks for the amazing work. Yes, using this extension will be much more straightforward for less tech savy Desktop users.
I love that you've already published it in the Chrome webstore. I suppose, we can also publish it for Firefox users as well.

We could make the design similar to Spotube's design, and we may also host the source code for it in this repo and take issues/PRs related to it here as well. Of course, you'll be the maintainer of the extension part. I will also help from time to time. Do you think it's a good idea?

**Comment by s-b-repo** [comment]
can you make a firefox version please

**Comment by s-b-repo** [comment]
https://github.com/s-b-repo/spotube-firefox-cookie-grabber/tree/main made a basic one that can be used

**Comment by PrivTEC** [comment]
Hello KRTirtho,

Apologies for the delayed response. I have been very busy with various projects lately.

I am excited to announce that the Spotify Cookie Extractor extension is now available on the Chrome Web Store! With just a few clicks, you can install the extension directly into your Chrome browser and start using it immediately.

**Extension Details:**
- **Version:** 1.0.0.1
- **Updated on:** June 24, 2024
- **Offered by:** Strategus One
- **Size:** 155KiB
- **Languages:** English

For more information and the installation link, please visit my GitHub repository [Spotify Cookie Extractor for Spotube by PrivTEC](https://github.com/PrivTEC/Spotify-Cookie-Extractor-For-Spotube).

I will get in touch with you next week to discuss the details.

Best regards,  
ByteMeHarder

**Comment by KRTirtho** [comment]
@PrivTEC luckily we managed to get webview support for Spotube and a PR with the support has been recently merged #1688 

I guess we can now close this issue in favor of #1688
