### ISSUE TITLE
Support on IOS

### ISSUE THREAD

**Issue by Zemerik** [KRTirtho/spotube#1535]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

I am free user of Spotify who uses Spotify on Windows as well as IOS (mostly IOS). I was hoping for this client to work on IOS as well, but unfortunately it is not supported. 

### Suggested solution

You could solve this by making Spotube compatible on IOS as well. 

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by Vitalii-code** [comment]
You can download an IPA file for iphone from the [website](https://spotube.krtirtho.dev/downloads)

**Comment by Zemerik** [comment]
oh ok. Thanks @Vitalii-code
