### ISSUE TITLE
for some reason after opening the app on the second time there are no icons its all empty

### ISSUE THREAD

**Issue by BossTurtle500** [KRTirtho/spotube#1538]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/KRTirtho/spotube/assets/106552589/305ebbfc-48d5-4a54-a7dd-36698249d16d)
i downloaded the app and its very good ngl and after using it for an hour i closed it and opened it again and boom no symbols/icons whatever thats called but yea

### Expected Behavior

to have the symbols/icons like before

### Steps to reproduce

1.installed
2.logged in
3.closed it
4.opened it again
5.everything works but no symbols

### Operating System

windows 10

### Spotube version

3.6.0

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev)

### Additional information

nice app you got there ill donate soon

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by Peperehobbits01** [comment]
Is this bugs still active? If not please close this issues.

**Comment by KRTirtho** [comment]
Closing as no further response
