### ISSUE TITLE
Lyrics language unknown

### ISSUE THREAD

**Issue by singhh9596** [KRTirtho/spotube#1539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Lyrics shown for hindi songs are literally showing me random language. 
![Screenshot_20240530_233941_Spotube Nightly](https://github.com/KRTirtho/spotube/assets/31469965/29abf4bd-569c-49fb-8734-cd2736d408d0)

### Expected Behavior

Lyrics must show in english/hinglish/hindi

### Steps to reproduce

Open app
Search song (Asal mein, sajni re and many more)

### Operating System

Android

### Spotube version

3.6.0 nightly

### Installation source

GitHub Actions (Nightly Binary)

### Additional information

Can you change the lyrics provider with better one

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
Duplicate of #1463
