### ISSUE TITLE
[Windows] media pause/play function does not pause/play music (Nightly build) & 3.7.0 Release

### ISSUE THREAD

**Issue by Obambulate** [KRTirtho/spotube#1542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Windows media pause/play function does not pause/play music.

### Expected Behavior

Windows media pause/play function pauses/plays music.

### Steps to reproduce

1. opened the app 2. played some sick tunes 3. tried to pause with windows built in pause/play function, no worky

### Operating System

windows

### Spotube version

v3.6.0 nightly *edit, same with 3.7.0 release*

### Installation source

GitHub Actions (Nightly Binary)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by Dropsii** [comment]
Having the same issue with v3.7.0 release. Windows media keys do not work for Spotube. (tried pause/play and next track)
Downgraded to v3.6.0 release and it works as expected.
Windows 10 Pro

**Comment by Arthurdw** [comment]
This issue is also present on Windows 11 Pro, it also seems to have problems with launching and the custom navbar doesn't work anymore.

Best remedy right now is to downgrade to 3.6.0 :/

**Comment by elenakrittik** [comment]
Same issue for me as well. Any fix incoming?

**Comment by KRTirtho** [comment]
Fixed in 3.7.1

**Comment by jojommeke** [comment]
im having this issue on arch linux(steamos) with 3.7.1 now, also downgraded and now it works(flatpak) #1627

**Comment by Glesas** [comment]
v3.7.1 (build 32) - flatpak - Nobara linux (gnome) 39 - doesn't work media buttons.
(Also i used it on windows 11 21h2 - No media detection aswell)

**Comment by KRTirtho** [comment]
Try the fix in [#1627](https://github.com/KRTirtho/spotube/issues/1627#issuecomment-2211811187)
