### ISSUE TITLE
Build for raspberry arm64

### ISSUE THREAD

**Issue by jackygoule** [KRTirtho/spotube#1543]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

I don't find build for ARM64

### Suggested solution

Build for ARM64

### Self grab

- [X] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
There's already arm64 build available in the [nightly](https://github.com/KRTirtho/spotube/releases/nightly)

**Comment by jackygoule** [comment]
Thanks for your answer 
Sorry I don't know aarch64 = ARM64
