### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by fxzxmicah** [KRTirtho/spotube#1558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Buggy UI. View the screenshot.

### Expected Behavior

No bug.

### Steps to reproduce

1. Add some songs to play queue.
2. Clear the play queue.

1. Open some song lists on the home page.

### Operating System

Android 14

### Spotube version

3.7.0

### Installation source

Play Store (Android)

### Additional information

![Screenshot_20240603_232324](https://github.com/KRTirtho/spotube/assets/48860358/7a6e458b-5fe8-4f01-85de-169b4743d38f)
![Screenshot_20240603_233053](https://github.com/KRTirtho/spotube/assets/48860358/eac27f4d-c189-4298-9114-ea4e86395216)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
Try the latest 3.7.1.
