### ISSUE TITLE
Update URL and Release URL are not working

### ISSUE THREAD

**Issue by Speedylux** [KRTirtho/spotube#1559]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Update Pop up screen links to non-existing URLs with Release v.3.6.0 after v.3.7.0 was published
-> See Screenshot 

Referenced Links to update application are not working and leading to 404 not found page on both, Windows and Android

![grafik](https://github.com/KRTirtho/spotube/assets/55111914/01123f29-1e42-4118-babf-af4a1ed91525)

### Expected Behavior

Opening correct URL to download and read release notes.

Release notes referencing to:
a) https://github.com/KRTirtho/spotube/releases

Download Button referencing to either:
a) https://spotube.krtirtho.dev/downloads 
b) https://github.com/KRTirtho/spotube/releases

### Steps to reproduce

1. Open the app with an old release versoin
2. Pop up appears informing about new version
3. Click on "release" or "download now"
4. both URLs end up in "404 not found page"

--> Release is linked to https://spotube.krtirtho.dev/other-downloads/stable-downloads
--> download now is linked to https://spotube.krtirtho.dev/other-downloads/stable-downloads

### Operating System

Android 14 + Windows 11

### Spotube version

v3.6.0

### Installation source

GitHub Releases (Binary)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
It's been fixed. The url was wrong in 3.6. From 3.7 it's correct
