### ISSUE TITLE
api-ms-win-core-*.dll files missing 

### ISSUE THREAD

**Issue by godspeedfw** [KRTirtho/spotube#156]
**Describe the bug**
Running spotube after installation gives missing api-ms-win-core-*.dll error. I tried manually downloading the dll file but it shows an error with another dll. 

**Screenshots**

![image](https://user-images.githubusercontent.com/74945202/181885780-16f07cbc-3515-4aff-82db-2dbd1961426e.png)

**Installation Source/Method**
- Github Release: Spotube-windows-x86_64-setup.exe 

**Desktop (please complete the following information):**
 - OS: Windows 8.1 Pro
 - Version 6.3.9600 Build 9600

**Comment by KRTirtho** [comment]
Sorry to inform, but Spotube only supports Windows 10 or above currently

**Comment by godspeedfw** [comment]
Ah okay, thanks for the response.
