### ISSUE TITLE
Android media controls dont't work in v3.7.0

### ISSUE THREAD

**Issue by Speedylux** [KRTirtho/spotube#1561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Media controls in Android (located near the Quick Settings or from locked screen) no longer work after updating to v3.7.0

### Expected Behavior

Showing media controls as it is used to work with the previous verison v3.6.0 on android or similar music apps from lock screen or quick settings

Reference to https://developer.android.com/media/implement/surfaces/mobile?hl=en

### Steps to reproduce

1. open Spotube in v3.7.0 on android 14
2. start playing music
3. slide down to open quick settings or lock screen
4. media controls are missing and don't appear

### Operating System

Android 14

### Spotube version

v3.7.0

### Installation source

GitHub Releases (Binary)

### Additional information

Downgrading to previous version v3.6.0 shows media controls immediately.

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by Speedylux** [comment]
minor remark:

THe Media Controls view in v3.6.0 was missing the app-icon on the top left corner. Instead the foreseen icon space is an empty circle.

**Comment by echedey-ls** [comment]
Neither on Windows 10. I tried rebooting without luck.

**Comment by KRTirtho** [comment]
Fixed in 3.7.1
