### ISSUE TITLE
After the update (version 3.7.0.) the application cannot be started.

### ISSUE THREAD

**Issue by lusmo** [KRTirtho/spotube#1568]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After upgrade app stopoped working. Nothing happened. App does not start.
Fedora 40 Workstation.

### Expected Behavior

The app should work.

### Steps to reproduce

After installing I open the app.
Nothing happens.

### Operating System

Fedora 40 Workstation

### Spotube version

3.7.0

### Installation source

Flathub (Flatpak)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by Arthurdw** [comment]
Duplicate of #1564

**Comment by KRTirtho** [comment]
Duplicate of #1555
