### ISSUE TITLE
Blank screen when selecting the lyrics tab on Android

### ISSUE THREAD

**Issue by conantin** [KRTirtho/spotube#157]
**Describe the bug**
When I touch the lyrics tab, the screen is blank.
The app still plays the audio file but to get back to the menu, I need to close the app.

**To Reproduce**
1. Click on the lyrics tab
2. Screen is blank

**Expected behavior**
To see the lyrics and also still have access to the UI.

**Screenshots**
![image](https://user-images.githubusercontent.com/46955618/181996807-ca3bf574-e351-4adf-bec2-cc2a68bb9c62.png)

**Installation Source/Method**
- Package Manager: Fdroid 

**Smartphone (please complete the following information):**
 - Device: Faihpone 4
 - OS: Android 11
 - Version 2.3.0
 
**Additional context**
When I download a song, I still get a txt file of the lyrics, since I choose to do)wnload the lyrics along with the audio file.

**Comment by KRTirtho** [comment]
Can you try installing the .apk [downloaded ](https://github.com/KRTirtho/spotube/releases/latest/download/Spotube-android-all-arch.apk)directly from the release

**Comment by conantin** [comment]
Thanks, that works.
