### ISSUE TITLE
Flatpak update, spotube dosen't run on Linux Mint 20.3 Cinammon Edition

### ISSUE THREAD

**Issue by Peperehobbits01** [KRTirtho/spotube#1582]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you try to open the app, it crash. This is not like 3.7.0 it's a new one, as the text in console is different.
![image](https://github.com/KRTirtho/spotube/assets/106733214/f281048c-041e-415f-ab8a-d30aaa8af238)

### Expected Behavior

The app can register the dbus/gbus and run.

### Steps to reproduce

1. Install the 3.7.1 above 3.7.0 on a Linux Mint 20.3 Cinammon Edition via the terminal whit flatpak update com.github.KRTirtho.spotube
2. Confirm the update by typing "Y"
3. Then try to run the app via start menu or terminal (whit flatpak run com.github.KRTirtho.spotube
4. Then you will just have the app crashing.

### Operating System

Linux Mint (Cinamon Edition) 20.3

### Spotube version

v3.7.1

### Installation source

Flathub (Flatpak)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
Uninstall the Spotube from flatpak first then re-install. It has been fixed already

**Comment by Peperehobbits01** [comment]
OK, i'll close the issues then.
