### ISSUE TITLE
generate a playlist based on all liked songs

### ISSUE THREAD

**Issue by s-b-repo** [KRTirtho/spotube#1589]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

just for better playlists

### Suggested solution

just grab all liked song then generate a list and play them in a random order so users dont get bord but dont let it play the same song within a range of 5 songs

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
We already have an option for "Endless playback" that adds songs after the last song of the queue based on that song. These gets added automatically while playing the last track of the queue if the "Endless Playback" option is turned on
