### ISSUE TITLE
Open playlists via deep link

### ISSUE THREAD

**Issue by meinto** [KRTirtho/spotube#159]
Is it possible to open a playlist, shared via link, via deep linking?

Let's assume we have the following shared playlist:
https://open.spotify.com/playlist/xxxxxxxxxx?si=yyyyyyyyyyyy

The expected behavior would be:
I click the link and android asks me if I want to open this link with spotube.

**Comment by KRTirtho** [comment]
This is something already planned. But it's going to take sometime

**Comment by KRTirtho** [comment]
As it seems, it's not possible to implement as it requires verification from the host (`spotify.com`) using a file that includes Spotube's bundle id

**Comment by citizenserious** [comment]
How can I search for a playlist of an specific user?
If there would be a playlist called "Music" I can found thousands but not the specific one. If it can't be shared via a deep link, is there an other solution to find it?

**Comment by anaxonda** [comment]
> How can I search for a playlist of an specific user? If there would be a playlist called "Music" I can found thousands but not the specific one. If it can't be shared via a deep link, is there an other solution to find it?

Any solution to this problem?
