### ISSUE TITLE
v3.7.1 Windows version startup crash

### ISSUE THREAD

**Issue by rampageX** [KRTirtho/spotube#1590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After launching the exe, no UI show, a dmp file "C:\Users\xxx\AppData\Local\CrashDumps\spotube.exe.28376.dmp" create immediately.

### Expected Behavior

Show the right UI.

### Steps to reproduce

1. Install the app on Windows 11
2. Open the app

### Operating System

Windows 11 x64

### Spotube version

v3.7.1

### Installation source

GitHub Releases (Binary)

### Additional information

v3.7.0 start fine but i cant move the app windows if i dont enable windows system titlebar.

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by skccy159** [comment]
I also have the same problem

**Comment by duoduo7207** [comment]
+1

**Comment by princeofsky** [comment]
Same.

**Comment by karniv00l** [comment]
can you folks try to update/reinstall Visual C++ Redistributable?

https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by rampageX** [comment]
> can you folks try to update/reinstall Visual C++ Redistributable?
> 
> [learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170)

Yes, update  Visual C++ do the trick. Thanks!

BTW: still face this issue: https://github.com/KRTirtho/spotube/issues/1595

**Comment by Obambulate** [comment]
> > can you folks try to update/reinstall Visual C++ Redistributable?
> > [learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170)
> 
> Yes, update Visual C++ do the trick. Thanks!
> 
> BTW: still face this issue: #1595

this did not work for me

**Comment by princeofsky** [comment]
It didn't work for me neither.

**Comment by josephw1122** [comment]
> > > can you folks try to update/reinstall Visual C++ Redistributable?
> > > [learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170)
> > 
> > 
> > Yes, update Visual C++ do the trick. Thanks!
> > BTW: still face this issue: #1595
> 
> this did not work for me

Have you tried restarting after installing the vc-redist?

**Comment by princeofsky** [comment]
It finally worked. I had installed the x86 version instead of the x64 one. Now, it's working.

I noticed that the latest version for windows is installing the 3.7.0, not the 3.7.1. Is there any way to install it?
