### ISSUE TITLE
3.7.1's Windows installer provide 3.7.0 instead

### ISSUE THREAD

**Issue by vico93** [KRTirtho/spotube#1595]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Basically, i've downloaded `Spotube-windows-x86_64-setup.exe` from 3.7.1 release (and tried once with the one in spotube website), uninstalled 3.7.0 an installed 3.7.1 installer, and on starting spotube it asked for the update (and in the about menu it showed the app version as 3.7.0).

### Expected Behavior

The installer to properly install 3.7.1

### Steps to reproduce

- Download the 3.7.1 `Spotube-windows-x86_64-setup.exe`, either from Github releases or the homepage;
- Uninstalled Spotube 3.7.0 via `appwiz.cpl` (Add or remove programs);
- Installed Spotube from the downloaded installer
- On opening it asks me to update since it's still on 3.7.0

### Operating System

Windows 11 x64

### Spotube version

3.7.1

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev), GitHub Releases (Binary)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by Daemoen** [comment]
Reproduces in Scoop as well.  I would imagine the packer somehow grabbed the wrong binary, or that the latest binary is being wrongly tagged, since it seems to happen across all of the windows installers.

**Comment by H1ghSyst3m** [comment]
No, I think the package is correct but in the code, the version is wrong. Because all the issues that the 3.7.1 fixed are really fixed, only the version is still the same

**Comment by nicovoni** [comment]
I downloaded version 3.7.1 from assets: https://github.com/KRTirtho/spotube/releases/download/v3.7.1/Spotube-windows-x86_64-setup.exe but every time I opened spotube, the following popup appeared:
![image](https://github.com/KRTirtho/spotube/assets/49231283/ae49b394-ef9f-4cf8-8e1a-d73d89b27725)
So after opening Spotube several times, I decided to click on "Download Now" to update the software, so the following page opens: https://spotube.krtirtho.dev/downloads
Of course I downloaded the executable for Windows. Despite the reinstallation, I still keep seeing the popup to update to version 3.7.1

**Comment by Z3MMIE** [comment]
> I downloaded version 3.7.1 from assets: https://github.com/KRTirtho/spotube/releases/download/v3.7.1/Spotube-windows-x86_64-setup.exe but every time I opened spotube, the following popup appeared: ![image](https://private-user-images.githubusercontent.com/49231283/338470991-ae49b394-ef9f-4cf8-8e1a-d73d89b27725.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNzk3OTEsIm5iZiI6MTcxODI3OTQ5MSwicGF0aCI6Ii80OTIzMTI4My8zMzg0NzA5OTEtYWU0OWIzOTQtZWY5Zi00Y2Y4LThlMWEtZDczZDg5YjI3NzI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDExNTEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2ZGI2ZDAwZjk3YzM0NDExZjE3MDEyOGEyYmE1MDEyOWE3NGFjODUwNGU5NzE1N2QxYTAxM2QzMDQ3MzFkOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cQrwpmG2ntJj78NOnxYC2jvB8m_o6UlXN0MKkVOA2tc) So after opening Spotube several times, I decided to click on "Download Now" to update the software, so the following page opens: https://spotube.krtirtho.dev/downloads Of course I downloaded the executable for Windows. Despite the reinstallation, I still keep seeing the popup to update to version 3.7.1

Ive got the same exact issue

**Comment by Schoggiweggli** [comment]
Same issue Win 10 x64

**Comment by tkoeck** [comment]
Any update for that?

**Comment by KRTirtho** [comment]
That's a really weird bug that I still got no solution of. Kinda bummer. I'll continue to finding a solution for it

**Comment by KRTirtho** [comment]
I've fixed it on 3.8.0

**Comment by tkoeck** [comment]
Thanks.
