### ISSUE TITLE
M1 Mac Support

### ISSUE THREAD

**Issue by KRTirtho** [KRTirtho/spotube#16]
Is there a way you can make the app a universal app (aka add support for m1) instead of only an intel app?

_Originally posted by @highjeans in https://github.com/KRTirtho/spotube/issues/9#issuecomment-1027525326_

**Comment by KRTirtho** [comment]
@highjeans, The M1 Mac Support can take a bit of time. Currently have no way to build the app on ARM architecture due to github action only supports x86_64 runners. If you've a M1 mac, you can contribute to the project

**Comment by highjeans** [comment]
I am currently on an M1 Mac, so yes I can do that.

**Comment by highjeans** [comment]
Can you add me as a contributor? I will need that in order to do anything.

**Comment by KRTirtho** [comment]
I don't have to. You can fork the project & then do modifications/enhancements you want to. Then create a PR.
I'll then review it & merge accordingly
For further help see: [Your First Code Contribution](https://github.com/KRTirtho/spotube/blob/master/CONTRIBUTION.md#your-first-code-contribution)

**Comment by highjeans** [comment]
So I was able to get an arm version compiled, but the way to do it was to change a file that was generated when we ran flutter build macos.

**Comment by highjeans** [comment]
Seems like we have to wait until building for arm is supported natively as changing the generated file caused tons of errors.

**Comment by KRTirtho** [comment]
M1 Mac support is now only not possible due to unavailability of MacOS VM support with M1 hardware in Github Actions https://github.com/actions/virtual-environments/issues/2187

**Comment by highjeans** [comment]
It doesn't matter if M1 hardware is required, it matters if flutter can build an M1 version or a universal version or not

**Comment by KRTirtho** [comment]
M1 is supported natively in Flutter we just don't have the hardware/VMs to build the app now

**Comment by highjeans** [comment]
@KRTirtho I just learned that flutter 3 now build universal binaries, so I think building for m1 should work now

**Comment by KRTirtho** [comment]
@highjeans That's great. Can you try running Spotube with Flutter 3 since I don't have a m1 mac?

**Comment by highjeans** [comment]
@karniv00l There is a pull request regarding the issue: https://github.com/bitsdojo/bitsdojo_window/pull/155[](https://github.com/bitsdojo/bitsdojo_window/pull/155)

**Comment by highjeans** [comment]
@KRTirtho I tried building it through Github Actions and it failed  from the same issue in bitsdojo.

**Comment by KRTirtho** [comment]
That's great news. Now we've to wait

**Comment by KRTirtho** [comment]
M1 Mac support (through Rosetta) was added by https://github.com/KRTirtho/spotube/pull/87. Thanks to Flutter 3.0 MacOS Universal binary package support, the M1 Mac executable is available now
Can you see if the latest version 2.3.0 works or not?

**Comment by karniv00l** [comment]
It's been working fine via Rosetta for some time. I believe this issue can be closed, native arm64/universal binary it's a different story though (no M1 machines available yet in GH actions)

**Comment by KRTirtho** [comment]
@karniv00l Yeah, native M1 macs gonna take a while
Btw, can you check if Media Controls in MacOS works or not?

**Comment by karniv00l** [comment]
It's working great!

<img width="325" alt="Screenshot 2022-07-11 at 11 10 14" src="https://user-images.githubusercontent.com/3144291/178230636-e561f458-bc09-4a9f-88d1-6c04fc1cb75f.png">

However, there are a couple of UI quirks, some of them related to mac:

<img width="320" alt="Screenshot 2022-07-11 at 11 11 10" src="https://user-images.githubusercontent.com/3144291/178230939-538ae2f3-9c97-4aad-9d79-e75799ee09dc.png">

I might open a new issue for others, so I don't clog up this thread, but generally try to test some views while resizing.

**Comment by KRTirtho** [comment]
Glad to hear that.... Thanks 👍

**Comment by yoyo930021** [comment]
I'm not sure I've misunderstood anything, but I download v2.3.0 and use it.

The monitor app talks to me:
It was a native apple silicon app.
![截圖 2022-07-15 下午5 58 37](https://user-images.githubusercontent.com/9126398/179200941-2c1e6914-ecaf-45f7-a288-b6fff202afc0.png)

**Comment by karniv00l** [comment]
Oh yes! You don't actually need M1 to build the universal binary, so the latest release (2.3.0) that I've just tested is actually universal:

```bash
$ file spotube.app/Contents/MacOS/spotube

spotube.app/Contents/MacOS/spotube: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64
- Mach-O 64-bit executable x86_64] [arm64:Mach-O 64-bit executable arm64
- Mach-O 64-bit executable arm64]
spotube.app/Contents/MacOS/spotube (for architecture x86_64):	Mach-O 64-bit executable x86_64
spotube.app/Contents/MacOS/spotube (for architecture arm64):	Mach-O 64-bit executable arm64
```

**Comment by KRTirtho** [comment]
Wow, we unknowingly have support for M1 Mac! Maybe that's because Flutter 3.0 now builds & ships Universal Binaries by default. That's just awesome
