### ISSUE TITLE
Lack of notification permission on v3.7.0

### ISSUE THREAD

**Issue by Roxelanne** [KRTirtho/spotube#1603]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I just installed Spotube. The app is not asking notification permission. So the music controls does not appear on the lockscreen and notif. panel. I just checked on system settings of my phone and it says "Notifications blocked" and there is no notification section in the general permissions. Looks like app it self doesnt want any notification request. 

Have to make it work with music player?

Also I couldnt grand the permission via android setting> Apps> Spotube. 

### Expected Behavior

There should be a notification permission request or another way. 

### Steps to reproduce

1. Download the Spotube 3.7.0 App from fdroid.
2. Launch the app
3. Start listening music
4. Pull down notif panel or go to lockscreen

### Operating System

Android 14

### Spotube version

3.7.0

### Installation source

F-Droid (Android)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by Annie-G** [comment]
Can confirm. Before the recent update, I had the controls on my lockscreen. They vanished after the update and I cannot activate "allow notifications" to make them re-appear.

**Comment by Vitalii-code** [comment]
Fixed in v3.7.1

**Comment by Peperehobbits01** [comment]
So it seems that it's fixed on v3.7.1. If it's the case, @Roxelanne please close this issues, this helps developers looking faster into bugs that have to be fixed.

**Comment by KRTirtho** [comment]
It's been fixed in v3.7.1 so closing it
