### ISSUE TITLE
cannot see country specific track (android app via f-droid)

### ISSUE THREAD

**Issue by meanssaddles** [KRTirtho/spotube#162]
on spotube android version (download via f-droid) i cannot see a country specific content while i can on the browser (i go through vpn and set my country to japan but can't see song/album that's japan only on spotube)

is there any way to fixed this?

browser:
![Screenshot_20220803_103453](https://user-images.githubusercontent.com/86918103/182519351-d8073dcf-047e-41b7-bae3-0504d621f69c.jpg)

spotube:
![Screenshot_20220803_103434](https://user-images.githubusercontent.com/86918103/182519392-0ea44d29-a846-41d6-8d79-4dc019d62683.jpg)

**Comment by KRTirtho** [comment]
I guess you need to change country to Japan (JP) from the settings

**Comment by meanssaddles** [comment]
> I guess you need to change country to Japan (JP) from the settings

doesn't work, in the image above setting is already set to jp

**Comment by meanssaddles** [comment]
updated: it become jp after a few hours

i guess this is caching issue

**Comment by KRTirtho** [comment]
Did you restart the app after connecting to the VPN?

**Comment by meanssaddles** [comment]
> Did you restart the app after connecting to the VPN?
yes, multiple time
