### ISSUE TITLE
[Windows] [3.7.1] Spotube does not start anymore

### ISSUE THREAD

**Issue by Sommergoldhaehnchen** [KRTirtho/spotube#1620]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After updating from version 3.6.0 to 3.7.1 the app doesn't start anymore.
I already tried to uninstall the old version first and do a clean install, but same behaviour.

### Expected Behavior

App should start

### Steps to reproduce

1. Update to version 3.7.1 (from 3.6.0) on windows.
2. Try to start the app.

### Operating System

Windows 11 Pro

### Spotube version

v3.7.1

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev)

### Self grab

- [ ] I'm ready to work on this issue!

![IMG_20240613_115459](https://github.com/KRTirtho/spotube/assets/19205341/43e4cd78-6e55-47d5-9540-0a1f127cc74a)
![IMG_20240613_115449](https://github.com/KRTirtho/spotube/assets/19205341/48ed54bb-0f59-407d-8775-a2a6bda329c1)

**Comment by Sommergoldhaehnchen** [comment]
After reinstalling v3.6.0 Spotube does start as expected, v3. 7.1 doesn't.

**Comment by karniv00l** [comment]
For `v3.7.1` try reinstalling Visual C++ Redistributable: https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by Sommergoldhaehnchen** [comment]
It's working, thanks.
But now, I encounter an issue that v3.7.1 points to v3.7.0 either via github or krtitho.dev. 🧐

![IMG_20240613_150412](https://github.com/KRTirtho/spotube/assets/19205341/91888313-8269-4f88-a99f-a64569729103)

**Comment by Sommergoldhaehnchen** [comment]
> For `v3.7.1` try reinstalling Visual C++ Redistributable

Should one note (FAQ, download section) that the latest VC version should be installed?

**Comment by Peperehobbits01** [comment]
It's probably linked to this 

> It's working, thanks. But now, I encounter an issue that v3.7.1 points to v3.7.0 either via github or krtitho.dev. 🧐
> 
> ![IMG_20240613_150412](https://private-user-images.githubusercontent.com/19205341/339370295-91888313-8269-4f88-a99f-a64569729103.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MDkyMjYsIm5iZiI6MTcxODgwODkyNiwicGF0aCI6Ii8xOTIwNTM0MS8zMzkzNzAyOTUtOTE4ODgzMTMtODI2OS00Zjg4LWE5OWYtYTY0NTY5NzI5MTAzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDE0NTUyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhZmIyZGY4M2EyMjVhMjAzOWY5YjIxOGZiZWVhNDM1NzZmNmM0ZmE3M2M3NTc0MmYyOTQ4NDJjZGVmMTAxZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-z9wroDSXuuKipCk-qsS2Th1kGxywNTMf1a8in_VsUA)

It's probably linked to this https://github.com/KRTirtho/spotube/issues/1595

**Comment by Peperehobbits01** [comment]
Could you close this issues to help looking trhow issues for maintainers easier please? Thank you.

**Comment by coder0107git** [comment]
> For `v3.7.1` try reinstalling Visual C++ Redistributable: https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

When I was running Spotube from the command line I kept getting "Segmentation fault". Following this piece of advice I got it to actually run! I did discover that the version installed has to exactly match your system (on x86_64 you had to install the x64 version).
