### ISSUE TITLE
[Linux][Flatpak] OS Media Controls not working

### ISSUE THREAD

**Issue by jojommeke** [KRTirtho/spotube#1627]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

if i open spotube 3.7.1 the icon tray works now, big thanks btw but archlinux + kde (steamos) doesn't detect the media, i can't use my play/pause or skip key, just my system doesn't detect it as media, i am using flatpak version

### Expected Behavior

media shows up in tray, is detected by the system and media control keys work

### Steps to reproduce

1. opened the app
2. play music
3. no media control

### Operating System

              .,,,,.                  deck@steamdeck          .,'onNMMMMMNNnn',.            --------------       .'oNMANKMMMMMMMMMMMNNn'.         OS: SteamOS Holo x86_64     .'ANMMMMMMMXKNNWWWPFFWNNMNn.       Host: Jupiter 1    ;NNMMMMMMMMMMNWW'' ,.., 'WMMM,      Kernel: 6.1.52-valve16-1-neptune-61   ;NMMMMV+##+VNWWW' .+;'':+, 'WMW,     Uptime: 1 day, 6 hours, 16 mins  ,VNNWP+######+WW,  +:    :+, +MMM,    Packages: 1094 (pacman), 42 (flatpak)  '+#############,   +.    ,+' +NMMM    Shell: bash 5.1.16    '*#########*'     '*,,*' .+NMMMM.   Resolution: 1280x800, 1920x1080       `'*###*'          ,.,;###+WNM,   DE: Plasma 5.27.5           .,;;,      .;##########+W    WM: KWin  ,',.         ';  ,+##############'    WM Theme: Sweet-Dark   '###+. :,. .,; ,###############'     Theme: [Plasma], Space-dark [GTK2/3]    '####.. `'' .,###############'      Icons: breeze-dark [Plasma], breeze-dark [GTK2/3]      '#####+++################'        Terminal: konsole        '*##################*'          CPU: AMD Custom APU 0405 (8) @ 2.800GHz           ''*##########*''             GPU: AMD ATI AMD Custom GPU 0405                ''''''                  Memory: 10093MiB / 14814MiB 

### Spotube version

3.7.1

### Installation source

Flathub (Flatpak)

### Self grab

- [ ] I'm ready to work on this issue! (i would really like to help but im not familiar with dart )

**Comment by bayang** [comment]
same here on manjaro with spotube flatpak 3.7.1.
It seems that MPRIS is broken or not working.

So media keys do not work, neither do external devices (bluetooth, usb , headsets etc...)

**Comment by forteller** [comment]
Same issue in Nobara (based on Fedora).

Thanks for a great app!

**Comment by forteller** [comment]
Thanks for the workaround! It works! Hope this can be implemented in the app :)

**Comment by KRTirtho** [comment]
@diegopvlk when you're free can you update this permission in the [flathub/com.github.KRTirtho.Spotube](https://github.com/flathub/com.github.KRTirtho.Spotube) repo please?

**Comment by arnavpadwal** [comment]
Fixed the same issue on arch (kde), thanks @diegopvlk for workaround!
![image](https://github.com/KRTirtho/spotube/assets/85226365/69323334-a623-4b1c-94b1-225136957159)

**Comment by C-512L** [comment]
> @diegopvlk when you're free can you update this permission in the [flathub/com.github.KRTirtho.Spotube](https://github.com/flathub/com.github.KRTirtho.Spotube) repo please?

Is this a good resolution? According to the [MPRIS spec] and [D-BUS spec] names should only contain ASCII characters  '[A-Z][a-z][0-9]_-' and in case of MPRIS dots should only be used for handling multiple instances (which Spotube doesn't do). The examples shown don't use reverse dns names either because of that so I think this could be a spec violation and/or undefined behavior.

[MPRIS spec]:https://specifications.freedesktop.org/mpris-spec/latest/#Bus-Name-Policy 
[D-BUS spec]:http://dbus.freedesktop.org/doc/dbus-specification.html#message-protocol-names-bus

**Comment by KRTirtho** [comment]
@C-512L that makes sense. I realized that the underlying plugin didn't require a separate specification for Linux instead it continued using android's notification channel name. Changing that `com.krtirtho.Spotube` to just `spotube` fixed the issue.

**Comment by matyas-zavora** [comment]
Since v3.8.0 the session bus is now set to `org.mpris.MediaPlayer2.Spotube.*`, but the media controls still don't work

**Comment by forteller** [comment]
Yeah, doesn't work for me either, unfortunately

**Comment by jojommeke** [comment]
the flatpak version of 3.8.0 isn't out yet(or "discover" is telling me lies)

**Comment by bayang** [comment]
I have spotube 3.8.0 installed.
To get mpris working again, I opened flatseal and clicked on the "reset" button to revert to default settings (because I had manually changed the mpris bus to get it working with the previous workaround).
It was still not working, but if you look closely in flatseal the Session BUS permission was unticked so I  gave the permission and now it is working.

**Comment by oktayacikalin** [comment]
> in flatseal the Session BUS permission was unticked so I gave the permission and now it is working

Same here. Thank you very much 😁👍️

**Comment by oktayacikalin** [comment]
> in flatseal the Session BUS permission was unticked so I gave the permission and now it is working

Same here. Thank you very much 😁👍️

**Comment by forteller** [comment]
I can't change the ticks under Session BUS in Flatseal. It looks like this: 

![image](https://github.com/user-attachments/assets/f8f6ddda-f0b0-4c90-9300-60151fc28cdc)

I tried clicking Reset, but media keys still don't work

**Comment by oktayacikalin** [comment]
Hmm... I completely missed what @C-512L just pointed out and ticked the general right for the sessions D-Bus. But just changing "Spotube" to "spotube" in "Owns" does the trick. :+1:

**Comment by matyas-zavora** [comment]
I would like to confirm that ticking `D-Bus session bus` fixes the issue.

<details>
![image](https://github.com/user-attachments/assets/7ef021c3-4afb-40ef-861a-5d07bc6160cc)
<details>

**Comment by forteller** [comment]
Thanks, @matyas-zavora, yes that worked for me too!

Hopefully this should mean that it's fairly easy to fix.

**Comment by KRTirtho** [comment]
Fixed by https://github.com/flathub/com.github.KRTirtho.Spotube/pull/101
