### ISSUE TITLE
Start a radio function not working on a song

### ISSUE THREAD

**Issue by mustard007** [KRTirtho/spotube#1629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The "Start a radio" function not working for me when clicked on a song.

### Expected Behavior

When I click "Start a radio" on a song, I expect this song start playing and a queue is present with similar song. (A radio)

### Steps to reproduce

Open app 
Click "Star a radio" on 3 dots menu on a song (searched song, playlist song, etc..)

### Operating System

Android 14 

### Spotube version

3.7.1 stable 32

### Installation source

Play Store (Android)

### Additional information

Pixel 6 Pro, lastest Android 14.
I have the same behavior in a few last nightly versions.

Thanks!!

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by owosoup** [comment]
Same, nothing happens when pressing the radio option in spotube. 

HOWEVER, clicking the radio button in Spotify opens a dialogue (the same as choosing which app to open a file, for example) and lets me choose between Spotify or Spotube to open the playlist created.

**Comment by Oscar1584** [comment]
on windows 11, this doesn't work either for me. I click on start radio, nothing happens.

**Comment by thmegy** [comment]
Also not working for me on ubuntu 22. It doesn't seem to work at all.

**Comment by midirhee12** [comment]
Still exists on Android.

**Comment by TipsyTheCat** [comment]
I'm on 3.8.1 and still experiencing this bug

**Comment by midirhee12** [comment]
@TipsyTheCat It seems fixed in `v3.8.3`.

**Comment by Ejemy** [comment]
Still experiencing this on Android
