### ISSUE TITLE
Spotube has an update on latest bug

### ISSUE THREAD

**Issue by adamk324** [KRTirtho/spotube#1634]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

latest and popup

### Expected Behavior

on latest no popup

### Steps to reproduce

1.opened spotube 2.popup opened

### Operating System

Windows 10 22H2

### Spotube version

v3.7.1

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev), GitHub Releases (Binary)

### Additional information

![image](https://github.com/KRTirtho/spotube/assets/90887270/4bcc3317-f7e7-4d42-834c-c30a06b42e98)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by adamk324** [comment]
on android this doesnt happen!

**Comment by Sukrit-Singh** [comment]
Same Here!!

**Comment by mfaathirarsa** [comment]
Yeah this only happen in the windows distribution as far as I know, in android is fine

**Comment by DrVektor** [comment]
![Ekran Alıntısı](https://github.com/KRTirtho/spotube/assets/105983978/c3cd2f02-05ac-476a-8faa-a521eb5f1207)

**Comment by jojommeke** [comment]
#1595

**Comment by Peperehobbits01** [comment]
To make looking into bugs faster, could you close this issues as a another issues was already opened before for this bugs.
