### ISSUE TITLE
Spotube can't handle special characters

### ISSUE THREAD

**Issue by mfaathirarsa** [KRTirtho/spotube#1641]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When i try to write the description of my playlist as "I Don't Know" it results on a jumbled mess
![photo_6305532583970193850_y](https://github.com/KRTirtho/spotube/assets/104710180/92e850ed-e6c4-4f97-9d6d-6b9d7e414a00)

### Expected Behavior

The app should be able to handle special characters correctly, because when i see this playlist in spotify this issue is not present

### Steps to reproduce

1. Go to playlist tab
2. Make/edit a playlist title/desc
3. Use special characters in this case (')
4. You get a jumbled mess

### Operating System

Windows 10 22H2 (19045.4170)

### Spotube version

3.7.1

### Installation source

WinGet (Windows)

### Additional information

I think this may just be the classic string error like if you have a string lets say 'apple' and an end user insert one of those tick at the middle the program cant recognize the string properly like 'app'le' would just be read as app and an error

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by mfaathirarsa** [comment]
This issue is also present in the Android Version that I Downloaded from F-Droid

**Comment by KRTirtho** [comment]
This has been fixed in 3.8.0
