### ISSUE TITLE
A 'Now Playing' app for the Tidbyt display

### ISSUE THREAD

**Issue by Bout2GitIt** [KRTirtho/spotube#1647]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

Currently, I use a small digital display called the [Tidbyt](https://tidbyt.com/) to show me what's playing on Spotify. But, now that I'm switching to Spotube, I find that I can no longer see what's playing on my Tidbyt screen.

### Suggested solution

Create an app for Tidbyt that displays what I'm currently playing on Spotube.

### Useful resources

[Tidbyt for Developers](https://tidbyt.dev/docs/overview/getting-started)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by jojommeke** [comment]
could be related to my issue #1627 , try downgrading

**Comment by KRTirtho** [comment]
Sorry, this out of our project's scope as we don't add plugin/extension support for 3rd parties. This is something we allow the community to work on.
