### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by andercard0** [KRTirtho/spotube#1648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Just downloaded the most recently version (V3.7.1) at: release pages installed as normal via setup but app insists to update

![image](https://github.com/KRTirtho/spotube/assets/43047877/bb4c132d-ac61-47ad-b7d9-835bf2ec635e)

At about page of the app the current version is behind V.3.7.0
![image](https://github.com/KRTirtho/spotube/assets/43047877/0e8c2607-fe23-4712-b63f-796861bc5f30)

### Expected Behavior

Expect to download the correct version from here:
https://github.com/KRTirtho/spotube/releases/tag/v3.7.1 and be updated correctly.

### Steps to reproduce

1. Go into : https://github.com/KRTirtho/spotube/releases/tag/v3.7.1 download setup
2. install it as normal
3. open the app 
4. the app says it has a new update which should be downloaded from the link in step one

### Operating System

Windows 10

### Installation source

GitHub Releases (Binary)

### Additional information

None at the moment

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by Peperehobbits01** [comment]
You haven't searched the existing issues sir, as you would of found this https://github.com/KRTirtho/spotube/issues/1595 , and this https://github.com/KRTirtho/spotube/issues/1643 . Please, to make issues easier for devevlopers, can you please close this issues.

**Comment by andercard0** [comment]
> You haven't searched the existing issues sir, as you would of found this https://github.com/KRTirtho/spotube/issues/1595 , and this https://github.com/KRTirtho/spotube/issues/1643 . Please, to make issues easier for devevlopers, can you please close this issues.

Sure. Ty
