### ISSUE TITLE
The song is not playing

### ISSUE THREAD

**Issue by Lucifer25x** [KRTirtho/spotube#165]
I start the song, but the song does not play for a long time. After this time, the song starts playing. This period takes about 3-4 minutes.

**To Reproduce**
1. Search for some song
2. Click play button

**Expected behavior**
The moment I hit the play button, the song should start playing.

**Screenshots**
![S20808-04083944](https://user-images.githubusercontent.com/74368520/183316572-98a9af33-2457-4668-96da-510eeee7b3b0.jpg)

**Installation Source/Method**
I downloaded the program from F-droid

**Smartphone:**
 - Device: Meizu M5C
 - OS: Flyme
 - Android Version: 6.0

**Comment by NSTAdventure** [comment]
temporary work around is press the play button from notification
also mini player bar on this app is buggy if you click play button from playlist
mini player is displayed and disappeared in second -_-
