### ISSUE TITLE
Syncing database from ViMusic

### ISSUE THREAD

**Issue by SilverSkull23** [KRTirtho/spotube#1655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

Have recently shifted from ViMusic to Spotube, but my database of songs has not been shifted over to my disappointment. As of this time, there is no method to sync the database exported

### Suggested solution

Add a method to sync the database exported from apps like ViMusic

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
We only support Spotify playlists/Albums etc. ViMusic uses it's own format. So we can't implement that to import into Spotube.

Btw, if you manage to transfer ViMusic playlists database to Spotify, it'll infact, show up in Spotube also.

**Comment by KRTirtho** [comment]
Since, this feature request is outside the scope of the project, we're closing it
