### ISSUE TITLE
Recusive Search through local folder

### ISSUE THREAD

**Issue by lucyamonster** [KRTirtho/spotube#1659]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

I cant display my songs since they're all in nested folders

### Suggested solution

Some way to enable recursive search so the songs are displayed and working

### Additional information

It would be nice if the songs would still be sorted by location

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
It's been there from 3.7.1. Now, in 3.8.0 it works fully

**Comment by KRTirtho** [comment]
use the Add Library feature to add more local folders
