### ISSUE TITLE
Support for track repeat mode

### ISSUE THREAD

**Issue by PranavBhattarai** [KRTirtho/spotube#166]
Currently, if the user only wants to listen to one song, he/she can't. Two things happen:
- Either the song stops after playing
- Or, the next song appear

Repeating a song shouldn't be too hard to implement, but what's hard is to properly meditate. ;-D
![image](https://user-images.githubusercontent.com/32763112/183335357-dae5f272-422e-4d78-85e5-5954fcc5d693.png)

 A change in behavior where the Shuffle icon change to the Repeat icon upon double/single clicking.

**Comment by KRTirtho** [comment]
Wow, I completely forgot about this one. It's so less used :sweat_smile:

**Comment by PranavBhattarai** [comment]
Yes, this feature is used quite less. Almost never. 
But sometimes, whenever we discover new songs/tunes, they might want to listen more until they are satisfied or get used to the song.

_I didn't realize this feature was not there until I wanted to try meditation._ 😁

**Comment by KRTirtho** [comment]
It's now available in the latest release

**Comment by PranavBhattarai** [comment]
Thank you.
