### ISSUE TITLE
Bluetooth media controls not working on Linux

### ISSUE THREAD

**Issue by GideonBear** [KRTirtho/spotube#1661]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Pressing the play/pause button on my Bluetooth headset does not play/pause in Spotube. Skip forward / skip backward also does not work.

### Expected Behavior

Bluetooth media controls to work.

### Steps to reproduce

1. I connect my Bluetooth headphones
2. I open Spotube
3. I start a song
4. I press the play/pause button on my Bluetooth headphones

### Operating System

Linux Mint 21.3 Cinnamon

### Spotube version

3.7.1

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev)

### Additional information

Bluetooth media controls do work for Spotube on Android, and Bluetooth media controls do work for other apps (e.g., Spotify via Chrome, YouTube via Chrome) on Linux.

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by bayang** [comment]
probably related to #1627

**Comment by GideonBear** [comment]
By the way, the software media controls (via the tray icon) are working fine, as are keyboard media controls.

**Comment by GideonBear** [comment]
Huh, suddenly Bluetooth media controls are working again. I'll close this issue for now, as it seems to be a temporary issue on my side.
