### ISSUE TITLE
app window doesn't match with my screen resolution

### ISSUE THREAD

**Issue by rahulguggilam** [KRTirtho/spotube#1664]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when i open the the app interface is doesn't fit my window size and some part of the app has been in transparent 

### Expected Behavior

the app should fit the screen resolution and we need to view app nicely

### Steps to reproduce

1. opened the app
2. the app opened with improper interface 

### Operating System

windows

### Spotube version

3.70

### Installation source

GitHub Releases (Binary)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by GhoulBoii** [comment]
Update to 3.7.1
It fixed the distorted window size issue

**Comment by rahulguggilam** [comment]
@GhoulBoii  In my pc 3.71 is not working , i am unable to open the application

**Comment by GhoulBoii** [comment]
> @GhoulBoii In my pc 3.71 is not working , i am unable to open the application

Is it giving an error? Describe what exactly is happening

**Comment by rahulguggilam** [comment]
@GhoulBoii Whenever I click on the spotube app no action has been performed by my system.

**Comment by KRTirtho** [comment]
This has been fixed since 3.7.1
