### ISSUE TITLE
Playlist already played can't be played again

### ISSUE THREAD

**Issue by Kamion008** [KRTirtho/spotube#1681]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://github.com/KRTirtho/spotube/assets/98531311/5fb9521f-e5d4-4139-bf16-48a5a0ff46b9

### Expected Behavior

The playlist plays normally

### Steps to reproduce

I opened the app, then play a random sobg of a playlist, close the app and reopen. Now you can't play a song in that playlist anymore

### Operating System

Android

### Spotube version

v3.7.1-nightly 298

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev), GitHub Actions (Nightly Binary)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
It's been fixed try the latest nightly

**Comment by Kamion008** [comment]
Now it works, ty!
