### ISSUE TITLE
Now listening widgets on discord profile 

### ISSUE THREAD

**Issue by NeproChan** [KRTirtho/spotube#1682]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

![20240703_195011](https://github.com/KRTirtho/spotube/assets/143866449/bd2e9fec-4bfc-44c0-b9c5-68655bbe1158)

I need this discord connection widgets on spotube so i can show people what I'm listening to in discord profile
By the way that widgets is from dantotsu anime app it is open source too if you want discord widget code
Here's the link the app https://github.com/rebelonion/Dantotsu

### Suggested solution

Using widgets on discord

### Useful resources

https://github.com/rebelonion/Dantotsu

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
It's already there. Turn on Discord RPC from Settings
