### ISSUE TITLE
[Linux] Flatpak not working on Mageia Linux v9

### ISSUE THREAD

**Issue by ozky84** [KRTirtho/spotube#1683]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have bug Spotube not playing anything

package:media_kit_libs_linux registered.
flutter: media_kit: WARNING: package:media_kit_native_event_loop not found.
flutter: Configure AudioServiceLinux.

i get this terminal output.....

### Expected Behavior

No idea

### Steps to reproduce

I open try to play but nothing happens....

### Operating System

Mageia linux version 9

### Installation source

Flathub (Flatpak)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by ozky84** [comment]
Rpm works installed urpmi --allow-nodeps
So rpm version working and audio playing working fine...
Deps are different in rpm distros
i'm also Mageia Linux qa team tester testing packages until they go to

**Comment by KRTirtho** [comment]
I guess it's not Spotube's fault if the expected dependencies aren't there. The RPM was packaged keeping Fedora/Redhat distros in mind.

**Comment by ozky84** [comment]
Yes Flatpak not working, rpm deps are just different named but they are all available in repos....

**Comment by ozky84** [comment]
There came update flatpak Spotube and now it working...
Thanks...
I will close now this issue...
