### ISSUE TITLE
Player stopped without any problems Write the title here

### ISSUE THREAD

**Issue by sanups90** [KRTirtho/spotube#1694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Playing music in this player.. it will stop whitout reason. 

### Expected Behavior

Need to change this problem 

### Steps to reproduce

1

### Operating System

Android 

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev)

### Self grab

- [X] I'm ready to work on this issue!

**Comment by GhoulBoii** [comment]
Disable battery optimizations for spotube in your settings.
https://dontkillmyapp.com/

**Comment by sanups90** [comment]
Battary optimised not on.. it's off.. automatically closing 😪. App..

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by GhoulBoii** [comment]
You can try out spotube nightly and see if your issue is fixed or not. There was a new commit which fixed the android killing application bug.

**Comment by KRTirtho** [comment]
Try out v3.8.0. It's been fixed there
