### ISSUE TITLE
Windows Spotube launching Failure

### ISSUE THREAD

**Issue by adamk324** [KRTirtho/spotube#1698]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

opening Spotube resoults with nothing. 
![image](https://github.com/KRTirtho/spotube/assets/90887270/27f9bfd0-10c0-4897-aedb-6313609d8e1a)
![image](https://github.com/KRTirtho/spotube/assets/90887270/ee475c23-9a4f-49b9-9207-7c629552b28f)

### Expected Behavior

Opening

### Steps to reproduce

1. Open the app

### Operating System

Windows 10 22H2

### Spotube version

v3.7.1

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev), GitHub Releases (Binary)

### Additional information

Windows Version is in fact Windows 10 22H2.
[Spotube_Log.txt](https://github.com/user-attachments/files/16143937/Spotube_Log.txt)
Latest Log is from 2024 6 17. (Uploaded In txt form beacouse github didnt let me upload otherwise)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by nitefood** [comment]
[This](https://github.com/KRTirtho/spotube/issues/1620#issuecomment-2165488148) worked for me. HTH

**Comment by adamk324** [comment]
> [This](https://github.com/KRTirtho/spotube/issues/1620#issuecomment-2165488148) worked for me. HTH

Thank you works good :)
