### ISSUE TITLE
Can't Login in MacOS

### ISSUE THREAD

**Issue by KRTirtho** [KRTirtho/spotube#17]
Also I can't login. My browser is unable to find localhost:4304. I tried all browsers and none of them worked.

_Originally posted by @highjeans in https://github.com/KRTirtho/spotube/issues/9#issuecomment-1027529246_

**Comment by KRTirtho** [comment]
@highjeans Can you please try launching it via command line & then paste the error logs here?

**Comment by highjeans** [comment]
Yes I will try that tomorrow.
