### ISSUE TITLE
Spotube instantly uploads gigabytes of whatever after launch (caused by flutter_tools.snapshot)

### ISSUE THREAD

**Issue by meinto** [KRTirtho/spotube#170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Try to run spotube via `flutter run -d macos`.

Directly after launch the upload begins and slows the mac down. It becomes nearly unusable...

<img width="840" alt="grafik" src="https://user-images.githubusercontent.com/2804678/183892749-4eb539fe-b83b-47c7-af4b-b1fb046b6cbe.png">

### Expected Behavior

Dev mode should work on macos

### Operating System

Mac OS

### Operating System Version

MacOS Monterey 12.5

### Installation Source

Github Release (Binary)

### Additional information

Installation Source is wrong. I compiled it directly from github source code.

**Comment by KRTirtho** [comment]
@karniv00l Are you facing the same issue as this one?

**Comment by karniv00l** [comment]
Doesn't seem to be the exact case on my end

my findings (16" M1 Max)

- only happens in `debug` mode (release is fine)
- only happens on `Library` tab
- `Sent Bytes` are slowly rising - around 100 KB/s
- not seeing any additional network calls on the flutter devtools
- not seeing outgoing traffic from my machine (used `Little Snitch`)

conclusion -  probably flutter devtools server (websocket) is generating local traffic

**Comment by KRTirtho** [comment]
Thanks a lot dude @karniv00l

**Comment by meinto** [comment]
Mh yea, I think you are right @karniv00l. It is local traffic.

I found that this bug is also available in the release version. My MacBook turns extreamly slow when I make the Spotube window larger. At some point it seems to trigger an infinite rendering loop (but that's only my first guess). The performance tab of the devtools doesn't stand still at this point. When I make the window smaller again, the performance issue is gone and the MacBook becomes usable again...

**Comment by KRTirtho** [comment]
Closing this issue as it is a Flutter's Issue, and not Spotube 's
