### ISSUE TITLE
RPC upgrade

### ISSUE THREAD

**Issue by lori28167** [KRTirtho/spotube#1708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

I'd like to have The album photo and artist in the discord rpc

### Suggested solution

You could add some scripts to put it there. (IDK how to code that.) 

### Useful resources

IDK

### Additional information

No additional infos

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
It's not possible as discord has no API to upload custom cover images. They only allow a pre-uploaded selection of images.

**Comment by KRTirtho** [comment]
Also, the Spotify activity is only exclusive to Spotify playback. That's why you don't see other music players having similar activity and only see re-using the game activity

**Comment by KRTirtho** [comment]
It's possible and it's been added on 3.8.0
