### ISSUE TITLE
Add a Spotify source 

### ISSUE THREAD

**Issue by Chickenshrimps** [KRTirtho/spotube#1711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

By selecting YouTube source , it fetches songs directly from YouTube not YouTube music which hinders the playback experience on my android phone 

### Suggested solution

You could add a Spotify source directly from their API or add a YouTube music source since they changed their API 

### Useful resources

YouTube music
Spotify Music
Apple music 

### Self grab

- [X] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
We can't use the Spotify api directly as it's not available for public usage

**Comment by Chickenshrimps** [comment]
> We can't use the Spotify api directly as it's not available for public usage

What about YouTube music api

**Comment by Chickenshrimps** [comment]
> We can't use the Spotify api directly as it's not available for public usage

YouTube music source would be great for downloading and streaming music with no data loss
