### ISSUE TITLE
[Bug] long tracks with silence

### ISSUE THREAD

**Issue by mohovkm** [KRTirtho/spotube#172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Every track, that I'm trying to play is longer, that actual song.
An example, actual song is 3:00 minutes long, but in application it will be 7:00 minutes.

When song is finished (at the end of third minute) track is continuing to play with silence.

### Expected Behavior

Songs with actual length.

### Steps To Reproduce

1. Open Spotube
2. Login
3. Search for any song (let's say it Imagine Dragons)
4. Click on play
5. See, that song length is 7:13 instead of 3:10

### Spotube Version

2.3.0 (12)

### Operating System

Mac OS

### Operating System Version

MacOS Monterey 12.4 (Intel)

### Installation Source

Official Website (spotube.netlify.app)

**Comment by Ahmedk-n** [comment]
This bug is also present on linux ( manjaro )

**Comment by KRTirtho** [comment]
Can you provide details about the exact song with which you're facing this issue?

**Comment by ntvinhit** [comment]
Same! For all the songs. Always add up to 3 minutes of silence

**Comment by KRTirtho** [comment]
This kind of weird. Maybe it's a problem with the Audio plugin in MacOS platform or YouTube's audio format

**Comment by KRTirtho** [comment]
Looks like there's already an issue for it #148

**Comment by KRTirtho** [comment]
Is the issue still persists?

**Comment by leeretaschen** [comment]
Yes, the issue is still there for me with 2.5.0 on macOS 11.7.

**Comment by mohovkm** [comment]
Downloaded update, all the same. (but actually not). 
Song started from beginning, but it was 1:37 on the player, and total length was 10:00 (minutes) with silence as well

**Comment by artskeit** [comment]
I have the exact same issue which is very annoying. An example is in the image provided. The music stopped around 04:17 but track length is 08:32 and is just silence.

<img width="1247" alt="image" src="https://user-images.githubusercontent.com/6928564/206659712-55afe006-b86d-43fa-907c-23cefe2dc479.png">

**Comment by quarkl8** [comment]
I have exactly the same issue even though sponsorblock is on
<img width="1552" alt="Screen Shot 2023-03-03 at 6 51 36 AM" src="https://user-images.githubusercontent.com/100106421/222752676-e857b7be-51d8-461a-abe2-096cf25fead8.png">

**Comment by KRTirtho** [comment]
When we made the migration to media_kit this issue was fixed
