### ISSUE TITLE
Permanently set new song URL for a song

### ISSUE THREAD

**Issue by ObsoletePixel** [KRTirtho/spotube#1727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

I started using spotube yesteday, and I really like it, but I was shuffling through my library and came across a song (specifically Haru by Yorushika, see [here](https://www.youtube.com/watch?v=CkvWJNt77mU)) and the shuffled version was  a lyricless version that was not the version of the song I wanted to listen to.

### Suggested solution

I'd like a feature where I can set a song URL as the new, default URL for that song when streamed in the future. Ideally synced across my installs of spotube, but I'm not sure how feasible that is.

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
Duplicate of #1752
