### ISSUE TITLE
Menu in task bar

### ISSUE THREAD

**Issue by rjsmith899** [KRTirtho/spotube#1739]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hey, I just want to report there are bugs in spotube. I have the attach of the bug picture, the task menu is blank and has no menu. I install the deb file and flathub to see if it is a problem with only one. and it's the same issues in both

### Expected Behavior

Hey, I just want to report there are bugs in spotube. I have the attach of the bug picture, the task menu is blank and has no menu. I install the deb file and flathub to see if it is a problem with only one. and it's the same issues in both

### Steps to reproduce

I try to install in flathub and from the official website and both have issues with the menu not showing.
![2024-07-28_15-56](https://github.com/user-attachments/assets/88265ab8-9553-4e0c-b045-73eafd835c37)

### Operating System

Linux Mint

### Spotube version

v.3.7.1

### Installation source

Website (spotube.krtirtho.dev), Flathub (Flatpak)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
This has been fixed in 3.8.0
