### ISSUE TITLE
[Bug] Can't use seek bar on android

### ISSUE THREAD

**Issue by Demizo** [KRTirtho/spotube#174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Unable to seek through a song on android. Instead it always jumps back to the previously playing moment in the song. (i.e. if I am 30 seconds into a song and skip to a minute, it jumps back to around 30 seconds. This also happens when attempting to seek backwards).

After installing and reinstalling a few versions I found that it works fine in v2.2.1 the issue only appears in v2.3.0.

### Expected Behavior

Should be able to seek through songs

### Steps To Reproduce

1. Open Spotube
2. Play any song
3. Attempt to seek throughout the song

### Spotube Version

v2.3.0

### Operating System

Android

### Operating System Version

Android 9

### Installation Source

F-Droid (Android)

### Additional information

This issue is also present on the Github binary for v2.3.0

**Comment by KRTirtho** [comment]
It has been fixed in the the latest version v2.4.0
