### ISSUE TITLE
Add YouTube song remixes 

### ISSUE THREAD

**Issue by aRedondoH** [KRTirtho/spotube#1745]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

It is common in YouTube to have the best song remixes which are not found in Spotify, it could be a amazing feature to add

### Suggested solution

Just make an scraper of YouTube song remixes

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
Sorry but this is not something that we can implement. It is tied to YouTube. Remember, this is a Spotify client. So it's not on our roadmap to implement YouTube's features here
