### ISSUE TITLE
The music randomly stops 

### ISSUE THREAD

**Issue by SleepyGoober69** [KRTirtho/spotube#1747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The music randomly stops at the and of a song and doesn't continue to play. 

### Expected Behavior

To continue playing the next song

### Steps to reproduce

1.opend app
2.Started my Playlist
3.music stops at the end of the next song. 

### Operating System

Android 14

### Spotube version

v. 3.7.1 Stable. Build = 32

### Installation source

F-Droid (Android)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by wizdoux** [comment]
Having this issue too, maybe something with killing the process. With the app open works fine, but stop just by locking the screen.

**Comment by KRTirtho** [comment]
#1492
