### ISSUE TITLE
[Bug] High gpu consumption by album moving labels.

### ISSUE THREAD

**Issue by AlexSua** [KRTirtho/spotube#175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am getting up to 60% of GPU consumption on an integrated Intel UHD Graphics 630 under Fedora using sway as the window manager. I usually don't have any problem reproducing 4k or other middle-intensive GPU tasks with other programs.

I have observed that the GPU-consuming task inside Spotube is the one in charge of moving long album labels such as this one:
![image](https://user-images.githubusercontent.com/8196195/185203113-7a4ae2d3-a772-416d-9b16-afee189de617.png)
with the following GPU consumption:
![image](https://user-images.githubusercontent.com/8196195/185203291-90b8a4b6-8000-440d-a572-115a7894cbf6.png)

Whilst if I am in the search section without any moving label I get the following GPU consumption:
![image](https://user-images.githubusercontent.com/8196195/185203687-6b51f17b-6f9f-49ff-b688-673e46b63fa3.png)

 

### Expected Behavior

Optimizing the GPU consumption of these animations would be interesting so you can get a better battery performance and not interfere with the performance of other applications.

Possible solution: Stop the animation when idle and the mouse is not over the Spotube app or the album image.

### Spotube Version

2.3.0

### Operating System

Linux

### Operating System Version

Fedora 36

### Installation Source

Flathub (Flatpak)

**Comment by karniv00l** [comment]
That's definitely a problem with `Marquee` widget, and it hogs the CPU/GPU around 40-50% on my end too.

@KRTirtho weird thing is that if you enable `debugRepaintRainbowEnabled = true;`, you will see whole app repainting 🤔. I've tried using `RepaintBoundry` widget, but it doesn't seem to do much.

**Comment by KRTirtho** [comment]
@karniv00l RepaintBoundary does work. It stops repaints in the Search page contents. But for some reason everything except the the Search page is getting repainted

**Comment by KRTirtho** [comment]
I've made `SpotubeMarqueeText` to animate once on mount and stop after that. But when hovered over its parent Widget it'll again start to animate again until the mouse exits from the hover region. This works only in Desktop btw, for mobile devices the nothing changed

**Comment by karniv00l** [comment]
Weird, I'm curious if there's a proper fix for that, seems like a common thing to have a animation like that

**Comment by KRTirtho** [comment]
I don't know why but even a small animation inside a hello world flutter app utilizes the gpu heavily
Where firefox running YouTube doesn't even make the gpu to go over 10-20%

**Comment by KRTirtho** [comment]
The fix has been released. It's now available in v2.4.0
