### ISSUE TITLE
winget package stuck at 3.7.0

### ISSUE THREAD

**Issue by a-p-jo** [KRTirtho/spotube#1757]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I open spotube, I am greeted with a pop-up that askes me if I wish to upgrade to 3.7.1, but running `winget upgrade` shows there are no updates for the KRTirtho.Spotube package. It seems that the binary shipped through winget is at 3.7.0 and hasn't been updated. 

### Expected Behavior

`winget upgrade` should list the upgrade available for spotube, from 3.7.0 to 3.7.1

Manual download and install defeats the point of using a package manager.

### Steps to reproduce

1. Use winget to install spotube
2. Open spotube

### Operating System

Windows

### Spotube version

3.7.0

### Installation source

WinGet (Windows)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by a-p-jo** [comment]
`winget show` says the package is at 3.7.1
`winget list` informs me that the installed package is 3.7.1+32

BUT, I get the update pop-up and Settings > About > About Spotube says it's at 3.7.0

**Comment by a-p-jo** [comment]
`winget remove spotube && winget install spotube` also gives the same result - the package isn't corrupted, this is how it is when freshly installed.

**Comment by jishnurajendran** [comment]
Same issue with scoop installation.

**Comment by KRTirtho** [comment]
This has been fixed in 3.8.0
