### ISSUE TITLE
Spotube black screen

### ISSUE THREAD

**Issue by damagr** [KRTirtho/spotube#1760]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

First time I install the app and it only shows black screen.

### Expected Behavior

APP should start.

### Steps to reproduce

1. I installed the app.
2. I openned it, and nothing happened.

### Operating System

Linux Mint 21.3 Cinnamon v6.0.4

### Spotube version

v3.7.1

### Installation source

Flathub (Flatpak)

### Additional information

I've tried to install it from .deb from last releases but it didn't worked too.

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
Does the same happens with 3.8.0?

**Comment by damagr** [comment]
On Flathub appears like 3.7.1 version, but I've updated it and it seems been working. 

Maybe it's showing a previous version but the code is the same from 3.8.0? It happened to me on Windows, I've installed the 3.8.0 and then it shows a popup where says that I'm on a previous version, I check the "about" section and there's the v3.7.1.

**Comment by KRTirtho** [comment]
On flathub the changelog was probably not updated. But, the app is indeed in 3.8.0.

Windows is also showing 3.8.0 not sure why it's happening to your installation

**Comment by KRTirtho** [comment]
Since it's fixed I'll close the issue
