### ISSUE TITLE
Touchscreen does not work on Linux

### ISSUE THREAD

**Issue by rcky844** [KRTirtho/spotube#1763]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When attempting to scroll in the application with a touchscreen on Linux (Arch Linux in my case), nothing happens, and instead the list entries are selected if I happen to be pressing on it.

### Expected Behavior

The pages should scroll as usual, like on mobile variants.

### Steps to reproduce

The above description is enough for describing this bug.

### Operating System

Arch Linux

### Spotube version

3.7.1

### Installation source

Arch User Repository (AUR)

### Additional information

I am not a Flutter developer, but I found an open issue in one of their repos regarding similar issues:
`https://github.com/flutter/flutter/issues/90366`

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
I don't have any Linux device with touchscreen support so I can't test it. But it looks like `ScrollBehaviour` issue

**Comment by rcky844** [comment]
> I don't have any Linux device with touchscreen support so I can't test it. But it looks like `ScrollBehaviour` issue

If possible, please open a branch and push a change so that Actions can compile a build. I have the device to test it on, if it is the issue it wouldn't be too difficult (?)

**Comment by KRTirtho** [comment]
It's not difficult but time consuming as there's a lots of ScrollView also I've to think of ways to detect that display has touch support. Because otherwise in non-touch devices, users will be able to scroll using mouse drag which is not a standard behavior for desktop apps

**Comment by rcky844** [comment]
> It's not difficult but time consuming as there's a lots of ScrollView also I've to think of ways to detect that display has touch support. Because otherwise in non-touch devices, users will be able to scroll using mouse drag which is not a standard behavior for desktop apps

Alright, ping me when you are ready.

**Comment by erebion** [comment]
Using this on my Linux phone, works absolutely brilliantly, except for scrolling.

Maybe look at FluffyChat, they got it working. That one is also a Flutter application. :D

https://github.com/krille-chan/fluffychat

**Comment by KRTirtho** [comment]
@rcky844 Can you try out the nightly version now? I forgot to ping u 😅

**Comment by rcky844** [comment]
I finally got time to test it, confirmed working 👍
