### ISSUE TITLE
Discord RPC doesnt work

### ISSUE THREAD

**Issue by prex-xo** [KRTirtho/spotube#1764]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I dont see any discord RPC. I tried using snap, flatpak, deb version of discord. I also tried using vesktop. But still it doesnt work. I am using Ubuntu 24.04
I have ensured that i have turned on Allow discord presence from the Spotube app.

ngl, this is best music app ever. But the discord RPC should work

### Expected Behavior

RPC should be visible

### Steps to reproduce

I opened the app and turned on the discord RPC thing. restarted my PC
also reinstalled the app.

### Operating System

Linux

### Spotube version

3.7.1

### Installation source

Flathub (Flatpak)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
It's been fixed in 3.8.0

**Comment by PringleKitten** [comment]
What about mobile integration? Kizzy has found ways for it but Is there gonna be a built in for this or no?
