### ISSUE TITLE
*Cannot resume the song*

### ISSUE THREAD

**Issue by Ugwattu** [KRTirtho/spotube#1773]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I cannot resume the song that i was playing after i have restarted the app

### Expected Behavior

This didn't happen until this update

### Steps to reproduce

I don't know

### Operating System

Android

### Spotube version

V3.8.0

### Installation source

Play Store (Android)

### Additional information

No

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by Chreece** [comment]
I have the same problem after updating to v3.8.0
If I quit the app when I a have loaded a playlist and reopen it, the playlist doesn't reappear in the Spotube app but the last song played is available in the dropdown menu from android. If I press play or next on this "mini player" nothing happends.
So it isn't possible to continue playing the playlist after restarting the app.
Android v14

**Comment by KRTirtho** [comment]
@Chreece try the nightly build where it has been fixed

**Comment by KRTirtho** [comment]
Fixed in 95ff13324ee82de409ecc3fdd4d93f8fbe8d2523
