### ISSUE TITLE
The IOS version !

### ISSUE THREAD

**Issue by RAZ321** [KRTirtho/spotube#178]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Category of the Feature

Unable to categorize

### Credits

me (RAZ)

### Pain

Because IOS (iphone) users cannot download this beautiful app. Moreover, it remains that this platform so that spotube is available to all ! 🎉

### Suggested Solution

I think you juste need to adapt the android version in ios, there is the swift language for ios apps or objective-c for this, after that you juste need to generate a .ipa downloadable on the [website page](https://spotube.netlify.app/) (it will directly install the app on the home screen) 😀
Here is the documentation : 
[swift](https://developer.apple.com/swift/)
[objective-c](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/Introduction/Introduction.html)

### Useful resources/references

[Swift 🕊](https://developer.apple.com/swift/)
[Objective-©](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/Introduction/Introduction.html)
[Create an ios app 📱](https://devmountain.com/blog/how-to-create-an-ios-app/)
[Many others languages 😎](https://developer.apple.com/develop/)

**Comment by KRTirtho** [comment]
Dude, I'm not making fun of you but this is hilarious! :rofl: Thanks, I haven't laughed this much for a long time. I wish I could show you how I rolled off my desk. Only if I had recorded it :laughing: 

**The reason of my laughter:**
You suggested me to create a full iOS version of Spotube in native Swift and Obj-C in the most calming, casual and transparent way

Don't mind it. It's all joke and I just wanted to know

**Comment by KRTirtho** [comment]
But seriously, iOS support is something already planned and there's already a discussion for it https://github.com/KRTirtho/spotube/discussions/173

**Comment by KRTirtho** [comment]
Hey @RAZ321, if you have [Scarlet](https://usescarlet.com/) or anything similar installed, you should be able to use Spotube in iOS. The IPA can be found in the Release section or simply from the [website](https://spotube.krtirtho.dev/downloads)

**Comment by KRTirtho** [comment]
Unfortunately, I'm unable to create an Apple developer ID as I live in Bangladesh. And, for some reason, Apple hasn't yet _invented_ my country lol 🤣 
So, I can't yet publish the app in App Store. Also, there's no guarantee if judges (App testers/reviewers)  from apple will even allow this app on their holy (irony) platform 🙃  even if I ever be able to create an Apple Dev ID

**Comment by Peperehobbits01** [comment]
Wait... why this issues is still opened if the iOS support is done?

**Comment by KRTirtho** [comment]
True!
