### ISSUE TITLE
Newpipe api

### ISSUE THREAD

**Issue by owencz1998** [KRTirtho/spotube#179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of the Feature

More Efficiency, Performance Improvements

### Credits

Me

### Pain

With the current api it takes a very long time for songs to start and the risk of getting banned by youtube when downloading.

### Suggested Solution

Newpipe would be a better api for your app quicker streaming able to abuse downloads without the risk of ip block by youtube and much more.

### Useful resources/references

Search newpipe on github and it gives u all the help to implement this.

**Comment by KRTirtho** [comment]
Can you give more details? At a glance, it looks like a lot of unneeded + unreasonable work

**Comment by KRTirtho** [comment]
BTW, the risk of IP block is far less as Spotube automatically delays each download by 5 seconds

**Comment by owencz1998** [comment]
I was only thinking off newpipe as it would be cool if streaming was more instant as when loading a song it normally takes like 5 mins to start playing unless I hit a different song and go back to the other one :)

**Comment by KRTirtho** [comment]
> it normally takes like 5 mins to start playing unless I hit a different song and go back to the other one :)

This is a issue previous versions of Spotube used to have. It's been fixed already as far as I remember. Are you using the latest v2.3.0?

**Comment by owencz1998** [comment]
Ahh I think it's more performance issues I'm having that could be causing some of the delays but yes I'm using that version u said I'd send a screen record but github won't allow me to send as vidoe is like 1 min long.

**Comment by owencz1998** [comment]
Maybe this is some off the issues I'm having I'm on a samsung z fold 3 also can it be changed so u don't have to click on the little play button that u can just click the full tile and it will play the song instead of taking u to the artist :) 

https://user-images.githubusercontent.com/96526481/186484661-2b1084e7-8cd7-4284-bdaa-475cd62e22d9.mp4

**Comment by owencz1998** [comment]
Not sure but even downloaded song don't play instantly

**Comment by KRTirtho** [comment]
> Could I possible make a discord server for spotube and build a community easier to share issues bugs features and ect I'll pay for the server and keep it up and going at all times :)

Wow that's a bold statement. Thanks a lot
Yeah, a discord server would be super helpful. I wanted make one too but I don't have much time (college years are tiring :sweat_smile:) so I won;t be able to moderate it. If someone wants to moderate and manage Discord community on behalf of me for Spotube, then I'm always positive about this. In summary, that's a yes from me! :smile:

**Comment by owencz1998** [comment]
Your a legend mate I'll create one today for u obviously u can also be administrator to and I'll keep it running all times  😁😁

**Comment by KRTirtho** [comment]
Definitely! Wow dude you rock! Thanks for your contribution to Spotube community. You don't know how much you have helped the project
Don't forget to add me to the server :smiley:

**Comment by owencz1998** [comment]
Add this to your github page as a button then people can join this invite is a permanent one 😁😁and always mate I'm happy to help anytime 😊 


https://discord.gg/PsWgsxqV3W

**Comment by NSTAdventure** [comment]
> If someone wants to moderate and manage Discord community on behalf of me for Spotube, then I'm always positive about this. In summary, that's a yes from me! 😄

Hi i can help you to moderate the discord community if you want :-)
