### ISSUE TITLE
[Feature] Easier way to add songs to "Liked Tracks" and other playlists

### ISSUE THREAD

**Issue by PlotCitizen** [KRTirtho/spotube#180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of the Feature

UI Improvements

### Credits

None

### Pain

Currently, when searching for a song, there is a dropdown menu at the right of the interface with the options:

- Add to Playlist
- Favorite
- Share

This is particularly inefficient when the user is in the process of adding a lot of songs to a playlist, or adding a lot of songs to their favorites.

### Suggested Solution

A more efficient way of dealing with this issue would be to remove the menu, and redistribute the buttons so that they are immediately visible without having to move your mouse to the right side of the screen and perform an extra click. I have designed a mock-up which you can see here:

![spotube-1](https://user-images.githubusercontent.com/2030636/186434654-2c32f704-5933-4e4a-bb36-b4364e82878a.png)

In my suggested solution, the "Favorite" and "Add to Playlist" buttons are moved to the left of the "Play" button, and the old menu dropdown button is replaced with the "Share" button. I think it would be a good idea to put the "Share" button at the right since people are presumably less likely to share a track than to favorite it or add it to a playlist.

_Note that this UI improvement is not intended for much smaller screen resolutions, such as those of mobile phones in portrait mode, on which it may make more sense to keep the dropdown menu as it is due to a lack of space._

**Comment by KRTirtho** [comment]
It's already been done and will be available in the next release. This is how it looks now (loggen in)
![image](https://user-images.githubusercontent.com/61944859/186585082-c2459043-5a65-4547-96c2-b40fc897afdf.png)

**Comment by PlotCitizen** [comment]
It looks great! Closing the issue.
