### ISSUE TITLE
Login gives Gray Page

### ISSUE THREAD

**Issue by Ugwattu** [KRTirtho/spotube#1800]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Fresh install of spotube v3.8.0  open for the first time new login page will just show me gray page

### Expected Behavior

It is supposed to let me connect to spotify

### Steps to reproduce

1. freshly install spotube
2. Try login it just show me gray page

### Operating System

Windows 10 22H2

### Spotube version

v.3.8.0

### Installation source

Website (spotube.krtirtho.dev)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by Goaty1208** [comment]
Same happening on Arch

**Comment by Just1diaxx** [comment]
Same but only at the first launch, I just closed and reopen the app and it got fixed.

**Comment by fccfc5d245c** [comment]
> Same but only at the first launch, I just closed and reopen the app and it got fixed.

I had the exact same problem, could connect to Spotify on my second launch, so it's not really a problem anymore. Running:
- Flatpak 3.7.1
- Debian 12

The F-Droid version works fine.

**Comment by 0x7C2f** [comment]
Same issue here. Reloading button does nothing. Right click > reload does nothing. Installed via yay package manager
OS: Arch Linux x86_64
WM: i3

![ksnip_20240820-133629](https://github.com/user-attachments/assets/9915b9a6-e664-4570-acc2-cff5085401d7)

**Comment by sudo-splinter-cell** [comment]
Even after entering the credentials and pressing login, the whole Spotube freezes and cpu usage spikes to 100% which causes the whole system to crumble. I had to force close Spotube to get back to normal. This happens in the first login. After that i could log in on the second time (if you count the grey screen, it was actually the third time).

**Comment by SSUPII** [comment]
Happens on Windows 10 20H2 too. Skipping the login then going into the app's setting to attempt to login, the Connect With Spotify button does nothing.

**Comment by SpamixOfficial** [comment]
I am experiencing this issue atm. Was a fix every found? I just installed the spotube-bin package from AUR with yay.

**Comment by Ugwattu** [comment]
> I am experiencing this issue atm. Was a fix every found? I just installed the spotube-bin package from AUR with yay.

The latest update fixed the issue.

**Comment by SpamixOfficial** [comment]
> > I am experiencing this issue atm. Was a fix every found? I just installed the spotube-bin package from AUR with yay.
> 
> The latest update fixed the issue.

I am on 3.8.1-2, which is the latest. I can with confidence say that no, the issue isn't fully resolved. At least not for me. What makes this even worse is that this is a "It works on my machine" issue lol

**Comment by Ugwattu** [comment]
Try uninstalling completely and reinstalling
That would help I guess, cause I did try(reinstall) for myself, It was fixed

**Comment by 0x7C2f** [comment]
Newest update breaks for me

```sh
Building Linux application...
CMake Error at /usr/share/cmake/Modules/CMakeTestCXXCompiler.cmake:73 (message):
  The C++ compiler

    "/usr/lib/ccache/bin/clang++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: '/tmp/makepkg/spotube/src/spotube-3.8.1/build/linux/x64/release/CMakeFiles/CMakeScratch/TryCompile-p8iNuU'

    Run Build Command(s): /usr/bin/ninja -v cmTC_e9f22
    [1/2] /usr/lib/ccache/bin/clang++   -march=native -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection         -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -Wp,-D_GLIBCXX_ASSERTIONS -MD -MT CMakeFiles/cmTC_e9f22.dir/testCXXCompiler.cxx.o -MF CMakeFiles/cmTC_e9f22.dir/testCXXCompiler.cxx.o.d -o CMakeFiles/cmTC_e9f22.dir/testCXXCompiler.cxx.o -c /tmp/makepkg/spotube/src/spotube-3.8.1/build/linux/x64/release/CMakeFiles/CMakeScratch/TryCompile-p8iNuU/testCXXCompiler.cxx
    [2/2] : && /usr/lib/ccache/bin/clang++ -march=native -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection         -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -Wp,-D_GLIBCXX_ASSERTIONS -Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now          -Wl,-z,pack-relative-relocs -fuse-ld=mold CMakeFiles/cmTC_e9f22.dir/testCXXCompiler.cxx.o -o cmTC_e9f22   && :
    FAILED: cmTC_e9f22
    : && /usr/lib/ccache/bin/clang++ -march=native -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection         -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -Wp,-D_GLIBCXX_ASSERTIONS -Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now          -Wl,-z,pack-relative-relocs -fuse-ld=mold CMakeFiles/cmTC_e9f22.dir/testCXXCompiler.cxx.o -o cmTC_e9f22   && :
    clang++: error: invalid linker name in argument '-fuse-ld=mold'
    ninja: build stopped: subcommand failed.





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)


Unable to generate build files
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: spotube-exit status 4
checking dependencies...

Package (2)  Old Version  Net Change

patchelf     0.18.0-3      -0.24 MiB
rustup       1.27.1-1      -7.62 MiB

Total Removed Size:  7.86 MiB

:: Do you want to remove these packages? [Y/n]
:: Processing package changes...
(1/2) removing rustup                                [---------------------------] 100%
(2/2) removing patchelf                              [---------------------------] 100%
:: Running post-transaction hooks...
(1/2) Arming ConditionNeedsUpdate...
(2/2) Cleaning up old package cache...
==> no candidate packages found for pruning
 -> Failed to install the following packages. Manual intervention is required:
spotube - exit status 4
```
