### ISSUE TITLE
libwebkit2gtk-4.1.so.0 missing

### ISSUE THREAD

**Issue by Erwin-Iosef** [KRTirtho/spotube#1801]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I use Arch Linux and when running spotube(spotube-bin AUR) from the CLI, I get the following error: <code>
spotube: error while loading shared libraries: libwebkit2gtk-4.1.so.0: cannot open shared object file: No such file or directory 
</code>

### Expected Behavior

Run Spotube normally I guess.

### Steps to reproduce

1. I ran `spotube` on the command line.
2. It returned:<code>
spotube: error while loading shared libraries: libwebkit2gtk-4.1.so.0: cannot open shared object file: No such file or directory 
</code>

### Operating System

Arch Linux

### Spotube version

v3.8.0-1

### Installation source

Arch User Repository (AUR)

### Additional information

There's already a workaround for this and that is to install webkit2gtk-4.1 from the repos.

The question is, will the aur package mark it as a dependency or will it move to use the standard webkitgtk package?

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by tomodachi94** [comment]
The `spotube-bin` package in AUR has a known missing dependency on libwebkit2gtk: https://aur.archlinux.org/packages/spotube-bin#comment-986938

**Comment by KRTirtho** [comment]
I forgot about AUR! Sorry!! I'll fix it right way

**Comment by KRTirtho** [comment]
I've updated the AUR package. You can try upgrading or reinstalling Spotube to fix the issue

**Comment by Erwin-Iosef** [comment]
> I forgot about AUR! Sorry!! I'll fix it right way

No problem. Will test fix right away.

Nope, still same issue, I think I forgot to tell you I already have webkit2gtk installed. The issue is it requires the 4.1 version of the package. Which is present in arch repos and installing it fixes the problem. So.... The issue is in the library although I think it's good that you added the webkit as a dependency anyway.

**Comment by KRTirtho** [comment]
Ok so I guess using [webkit2gtk-4.1](https://archlinux.org/packages/extra/x86_64/webkit2gtk-4.1/) should fix the issue?

**Comment by Erwin-Iosef** [comment]
It does and spotube does work as it should but then. Why not make it use the regular webkit libraries instead of the 4.1, if possible?

OR
Like, maybe add the webkit 4.1 as a dependency for now but maybe in the next release or hotfix, make it add the regular webkit package?

**Comment by KRTirtho** [comment]
> It does and spotube does work as it should but then. Why not make it use the regular webkit libraries instead of the 4.1, if possible?

Well, the library under the hood looks for `webkit2gtk-4.1.so` to make sure we've access to the feature level. And AUR's `webkit2gtk` provides the shared object as `webkit2gtk-4.0.so` so it can't use it. But Spotube can be built with `webkit2gtk-4.0`

Ok I'll upgrade the depdencies once again

**Comment by KRTirtho** [comment]
Try re-installing/upgrading spotube. Now, it should work

**Comment by Erwin-Iosef** [comment]
> But Spotube can be built with `webkit2gtk-4.0`

So, what's the plan for now? Stick with 4.1 for the time being?

> Ok I'll upgrade the depdencies once again

Already did and it works, thanks!

**Comment by Erwin-Iosef** [comment]
@KRTirtho Should I close the issue now, since it's kinda solved?

**Comment by KRTirtho** [comment]
It's solved so please close it👍

**Comment by Erwin-Iosef** [comment]
Thank you for your help. Have a nice day.
