### ISSUE TITLE
[Feature] Add search function in Liked Tracks and alphabetical sorting capabilities

### ISSUE THREAD

**Issue by PlotCitizen** [KRTirtho/spotube#181]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of the Feature

UI Improvements

### Credits

None

### Pain

At the moment, it is difficult to navigate through my "Liked Tracks" because the names of the songs are not in alphabetical order, and there is no search function within the "Liked Tracks" area of the program. 

This means that if I want to play a specific song from my "Liked Tracks", I need to either:

1. Look up the song and find it again in the "Search" part of the program (which means that once the song finishes playing, it will not automatically start playing another song in my "Liked Tracks")
2. Find it manually within my "Liked Tracks", which could take a while if there are many songs added

### Suggested Solution

Adding a search function to "Liked Tracks" would be a big help because it would make it easier to find songs that I have previously liked, without having to leave the "Liked Tracks" area to perform a search.

Plus, the ability to alphabetically sort titles (and albums) of songs in "Liked Tracks" would also make this task easier. 

Also, since "Liked Tracks" is effectively just another playlist, my suggestions also apply to any playlist which can be created / accessed through Spotube.

**Comment by PlotCitizen** [comment]
Closing the issue since @KRTirtho has already added the feature for the next release. (Either way, alphabetical sorting isn't that important if there's a search function)

**Comment by KRTirtho** [comment]
Hey, searching for a song in a playlist/album could be a good feature. So I'm re-opening it!

**Comment by KRTirtho** [comment]
Sorting by different logic is added in v2.5.0

**Comment by KRTirtho** [comment]
Searching feature is now available from Spotube v2.7.0
