### ISSUE TITLE
[Feature] Add option to select Genius as default for lyrics

### ISSUE THREAD

**Issue by PlotCitizen** [KRTirtho/spotube#182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of the Feature

UI Improvements, Logical Improvements, More Efficiency

### Credits

None

### Pain

If you are listening to a playlist while on the "Lyrics" tab and you change the song, a pop-up comes up saying: 

> The found lyrics might not be properly synced. Do you want to default to static (genius.com) lyrics? Hint: Wait for a moment to see if the lyrics actually sync. Sometimes it may sync.

You need to either press "No" or "Yes" so you can clearly see the lyrics behind the pop-up and this can get annoying, especially if you are fine with no lyric syncing capabilities.

### Suggested Solution

During my time using Spotube, it seems like the matching process for finding song lyrics via Genius tends to be more accurate than the other option (RentAnAdviser, I believe), but obviously the downside of the Genius method is that there is no syncing. 

Ideally, users who don't care too much about syncing could just select to always use Genius somewhere in the settings. This way, there would be no need to keep deciding which source for lyrics you want to use for every song that you listen to. Of course, there is also the issue of missing lyrics for less popular songs - perhaps if the lyrics are not found on Genius, then it can fall back to the other option (assuming that they are found on the other option).

**Comment by KRTirtho** [comment]
Luckily, this feature isn't needed anymore as Spotube now uses Official Spotify (Musixmatch) lyrics. So we dropped genius.com and rentanadviser.com support in favor of it
