### ISSUE TITLE
Flathub has outdated version 3.7.1

### ISSUE THREAD

**Issue by CoolSpot** [KRTirtho/spotube#1827]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Flathub has outdated version 3.7.1 which causes issue #1760 for me.

Flathub screenshot:
![image](https://github.com/user-attachments/assets/c47e5ecc-68b0-40f9-89c0-468c534ead3d)

Flatpak CLI output:
```
> flatpak list | grep -i spot
Kingkor Roy Tirtho	com.github.KRTirtho.Spotube	3.7.1	stable	flathub	system

> flatpak update com.github.KRTirtho.Spotube
Looking for updates…
Nothing to do.
```

### Expected Behavior

Expectation: version 3.8.0 is available on FlatHub

### Steps to reproduce

```
> flatpak list | grep -i spot
Kingkor Roy Tirtho	com.github.KRTirtho.Spotube	3.7.1	stable	flathub	system

> flatpak update com.github.KRTirtho.Spotube
Looking for updates…
Nothing to do.
```

### Operating System

Rocky Linux 9.4

### Spotube version

3.7.1

### Installation source

Flathub (Flatpak)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by tisfyx** [comment]
By the way, this is probably an issue of flathub having a wrong version number and not actually the wrong version.
Here's why i'm saying that:
```
> flatpak list | grep -i spotube
Spotube com.github.KRTirtho.Spotube     3.7.1   stable  system

> flatpak run com.github.KRTirtho.Spotube --version
flutter: Spotube v3.8.0
```

**Comment by CoolSpot** [comment]
You're right that the actual app version shows v3.8.0 . Closing this.

**Comment by jojommeke** [comment]
issue still persists, the app may be the new version but version number on flathub is still 3.7.1 see: https://flathub.org/apps/com.github.KRTirtho.Spotube
