### ISSUE TITLE
[Bug] Shuffle button sometimes gets stuck and stops working

### ISSUE THREAD

**Issue by PlotCitizen** [KRTirtho/spotube#183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

_NOTE: I noticed the following in the "Liked Tracks" part of the program_

After enabling the shuffle button, the program sometimes presents the following two bugs at the same time:

1. Unless I restart the program, the shuffle button remains active (green) even after I click it to disable it 
2. The music does not actually get shuffled - it just plays the next track in the playlist

### Expected Behavior

Enabling shuffle should not cause it to get stuck and not shuffle

### Steps To Reproduce

I am not sure how to reproduce the issue and I cannot think of any specific trigger that caused it

### Spotube Version

v2.3.0

### Operating System

Linux

### Linux Distribution (if applicable)

Fedora

### Operating System Version

36

### Installation Source

Flathub (Flatpak)

**Comment by KRTirtho** [comment]
I've checked and I can confirm this happens when you're already listening to a shuffled playlist and then play another playlist. Good catch! I'd have never found it :+1:

**Comment by KRTirtho** [comment]
Fixed it
