### ISSUE TITLE
History Look Up 

### ISSUE THREAD

**Issue by iloukine** [KRTirtho/spotube#1834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

I use Spotube a lot without the ability to touch my phone for a while so it would be a help if I could see a history of music played so I can find songs I heard. 

### Suggested solution

A tab for listening history. 

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
Implemented in #1522
