### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by Ugwattu** [KRTirtho/spotube#1844]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

I had free time so I made this logo. You can use it if you want I tried to make more plain and simple so it doesn't look out of place. Old one looks out of place everytime

### Suggested solution

![Untitled](https://github.com/user-attachments/assets/2ef55022-2821-4ad8-848d-67c205894204)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by oblassov** [comment]
![image](https://github.com/user-attachments/assets/bfc8787c-6ddd-4249-99bb-1271e1a0905b)
I agree on the logo, and decided to go with a different approach, so may I suggest something like this?

**Comment by KRTirtho** [comment]
Sorry but we're currently not accepting new logo requests
