### ISSUE TITLE
[Feature] Use system's window bar

### ISSUE THREAD

**Issue by RaptaG** [KRTirtho/spotube#185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of the Feature

UX Improvements

### Credits

None

### Pain

Some people (including me) change the locations of the window decorations for the window bar. Spotube has the window button inside the app and in a locked position. I believe it would be cool to use the system's window bar!

### Suggested Solution

Use system's window bar

### Useful resources/references

None

**Comment by KRTirtho** [comment]
Added in v3.1.1
