### ISSUE TITLE
[Feature] Switch between synced and static lyrics on demand

### ISSUE THREAD

**Issue by SteveeWasTaken** [KRTirtho/spotube#186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of the Feature

UI Improvements, More Efficiency

### Credits

Me

### Pain

When selecting lyrics for some songs, it seems like they're extremely delayed and I would like to use the static lyrics, but I clicked off the pop-up that lets me switch it.

### Suggested Solution

Add a small button that allows you to change the lyrics from static to synced and vice-versa too. It could be next to the "Lyrics Delay" button.

**Comment by KRTirtho** [comment]
duplicate of #182
