### ISSUE TITLE
All songs of my playlist are not being listed 

### ISSUE THREAD

**Issue by TheGodOfCoding2004** [KRTirtho/spotube#1874]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I login through spotify on either the mobile app or the desktop app , I try to play one of my playlists. But I find that a few of the songs are missing , especially the last few. I have about 700 songs in that playlist. Is there a limit to how many number of songs we can add to a playlist ? 

### Expected Behavior

I wish to have all of my playlist songs so that I can fully migrate to this app from Spotify. 

### Steps to reproduce

1. I logged in through Spotify on phone and for desktop I followed the steps correctly. 
2. I look for my playlist and open it. 
3. I find that out of 700 songs , only 350 were migrated. 

### Operating System

Android , Windows , Linux

### Installation source

Website (spotube.krtirtho.dev), Play Store (Android), F-Droid (Android), chocolatey (Windows), WinGet (Windows)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
This has been fixed in 3afe3cea80eb8a662190035519cbff804a81e54e
