### ISSUE TITLE
Remove the volume fader on the low screen on Android 

### ISSUE THREAD

**Issue by Porrumentzio** [KRTirtho/spotube#1875]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

Sometimes, without noticing it, accidentally, I lower the volume of the reproduction on the volume fader that appears at the bottom of the screen at the detailed playback page (where you can see the list and lyrics).

This happens accidentally because that part of the screen is very susceptible to unwanted touching, and I don't notice why the volume went down.

### Suggested solution

Remove this bar. Android, for example, does already have volume control.

### Self grab

- [X] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
Sorry, this is for controlling the in app volume. It sits quite low in the page and has a bigger gap from the other controls.
I don't see the reason to remove a feature for simple mistouches once in a while.

**Comment by Porrumentzio** [comment]
OK. It's very annoying to me and to more people when that happens, and I don't ever use the in-app volume.

Anyway, what about an option in settings to hide it?
