### ISSUE TITLE
Why it shows "hacker" subscription

### ISSUE THREAD

**Issue by Unchanged4352** [KRTirtho/spotube#1878]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![Ekran görüntüsü 2024-09-09 194225](https://github.com/user-attachments/assets/bebc518b-82fe-47cf-a1e2-005d09d0e0d2)
![Ekran görüntüsü 2024-09-13 191114](https://github.com/user-attachments/assets/49f9bc7b-abae-47e7-b050-4733d30d5da9)
So as you can see when the "Error Authentication Failure" occurs and I just close all tabs of it, it shows me the "hacker" subscription I don't know how and why this bug occurs but as you can see.

### Expected Behavior

It not to be happen.

### Steps to reproduce

1. Open the Spotube
2. Listen to music for a while
3. And then this bug occurs

### Operating System

Windows 11 and android

### Spotube version

v3.8.0

### Installation source

GitHub Releases (Binary), F-Droid (Android)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
That page is a placeholder page when there's no user logged in. It's just an easter egg

**Comment by Unchanged4352** [comment]
> That page is a placeholder page when there's no user logged in. It's just an easter egg

Oh okay i understand it thanks

**Comment by Ajay-056** [comment]
Its a terrible easter egg or I wonder if its really an easter egg 🙂
