### ISSUE TITLE
Playbacks Statistics under Listened Minutes and the other was around

### ISSUE THREAD

**Issue by Jens-prog** [KRTirtho/spotube#1880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I click on the listened Minutes Statistics I get a List with Playback Times. If I click on Listened Songs I get a List with Playback Minutes.

### Expected Behavior

If I click Listened Minutes I get the Songs sorted by Minutes, and If I click Listened Songs I get a List sorted by Listened Songs.

### Steps to reproduce

I opened the App.
Clicked in the Statistics Tab.
Described behavior happens.

### Operating System

Android 14

### Spotube version

v3.8.0

### Installation source

F-Droid (Android)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
Thanks for the report
