### ISSUE TITLE
Shuffle is not sufficiently random on Android

### ISSUE THREAD

**Issue by GrampaWildWilly** [KRTirtho/spotube#1888]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have Spotube 3.8.1 on both my Windows 11 Pro 64-bit desktop PC & my Android 13 cell phone.  On the desktop, shuffle works OK.  The tracks do shuffle up in what looks like pretty random order.  But on the cell phone, it's nowhere near as good.

What it seems to be doing on the phone is picking the artist whose albums are at the start of my playlist & randomly playing tracks by that artist.  I would guess that once all of that artist's tracks have been played, Spotube would go to the next artist in my playlist & randomly play all of that artist's tracks.

### Expected Behavior

I expect shuffle play to select a different artist almost all the time.  The concept of random does allow for the occasional consecutive tracks being by the same artist.  But that ought to be unusual.  The shuffled playlist should be picking & choosing from essentially random positions in my playlist.  The Android version should work mostly like the desktop version.

A few releases back, I can't say now how many, the shuffle play on Android worked fine.  But at some point, a new Spotube for Android lost its good shuffle ability.

### Steps to reproduce

1. Open Spotube on Android.
2. Open my playlist.
3. Click the shuffle button.
4. Start playback.

### Operating System

Android 13

### Spotube version

3.8.1

### Installation source

GitHub Releases (Binary - for Windows), Play Store (Android - auto updates when new releases appear)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
It's just random behaviour which I can't control. Also, if we randomize something following a pattern, that's not randomness. That's just another algorithm 😅

**Comment by GrampaWildWilly** [comment]
But it's not random.  It's playing all the tracks by a given artist.  Granted, it's not playing those tracks in order.  But it's not really random.  Whatever you're doing on the Windows desktop is much better.  There has to be a way to do the same thing on Android.  Plus it used to be better on Android & at some point, it got like the way it is now.

**Comment by GrampaWildWilly** [comment]
Can't control?  It's your app.  Of course you control it.  You're doing it right on the desktop.  Just do it like that on the cell phone.

**Comment by KRTirtho** [comment]
Sorry, this is not a thing anyone can control. Randomness is not controllable. We can shuffle it more but it'll still be random. Also shuffle is handled by [MPV](https://mpv.io) so it's truly not on my hand how it's handled there.

**Comment by KRTirtho** [comment]
Closing this since it's a request that we can't fulfill
