### ISSUE TITLE
Add ability to insert a next track to a queue

### ISSUE THREAD

**Issue by GrampaWildWilly** [KRTirtho/spotube#1889]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

This is kind of a duplicate of #626 but that one is closed & it's old.  There is functionality that is available on Spotify that is not available in Spotube.  You can pick any track, not just a track in your playlist but any track on Spotify, & insert it on the queue.  When the current track finishes playing, your inserted track will play next.

### Suggested solution

In #626 you suggest dragging & dropping to reorder entries in your queue.  I have 2 objections to that.  First, I don't necessarily want to permanently change the position in my queue of the track I want to play next.  I should be able to leave it in its place in the queue AND also play it next.  Besides, maybe what I want to play next is not even in my queue or my playlist.

Second, my queue, which is my complete playlist shuffled, contains 7659 tracks.  Dragging & dropping anything in such a queue is just not feasible.

As an alternative to doing things in the GUI, if there were a file somewhere that contains my queue, I could manipulate that directly in, let's say, Notepad++ or perhaps an Open Office component.  Of course, I would do that while Spotube is not running.  Then next time I open Spotube, presto, my chosen tracks could be next in queue.

If I could manipulate some file directly, I would make certain adjustments to the random queue.  There are certain albums that have sequences of tracks that really are a single multi-part track.  Examples: Dark Side of the Moon, several tracks on Abbey Road, suites on Chicago II & Chicago III, Singing Winds, Crying Beasts + Black Magic Woman + Oye Como Va on Abraxas, Eruption + You Really Got Me on Van Halen I, Little Guitars (intro) + Little Guitars on Diver Down.  I could go on.  I would like to edit my queue to make those tracks consecutive in my otherwise more or less random queue.  Dragging & dropping is simply not possible in the GUI with my queue of over 7600 tracks.

Once I have manipulated this queue on my desktop, I'd like to be able to got it over to my Android 13 cell phone.

### Useful resources

If you want to use my playlist for testing, I believe I have shared it in read-only mode.  My user ID on Spotify is the same as my user ID here on GitHub.

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
Oh come on. Give us a break. Why do you have to write an essay? 😩 (jk) You could at least list out the requests instead of writing all in the same paragraph 😭 (jk++)

Also the "Insert a next track" feature already exists (known as "Play Next" in Spotube) 😉 
<img width="1314" alt="image" src="https://github.com/user-attachments/assets/fd2260f0-e97a-456c-bcce-26e91ff783c9">

**Comment by KRTirtho** [comment]
This works for Local Tracks as well
<img width="1314" alt="image" src="https://github.com/user-attachments/assets/b138a757-6064-4436-bdb5-1324e455cc05">

**Comment by KRTirtho** [comment]
Closing since there's no response and the feature is already available
