### ISSUE TITLE
failure to connect spotify account, TLS support is not available

### ISSUE THREAD

**Issue by jonvemo** [KRTirtho/spotube#1892]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![2024-09-17_14-35-38_ScreenShot](https://github.com/user-attachments/assets/d81313e3-f6de-4e2d-a14d-8438f9fac7a4)

### Expected Behavior

Connect to Spotify

### Steps to reproduce

Clicking on the connect to Spotify button opens a window with a dialog box: TLS support is not available

### Operating System

Linux, NixOS 24.11.20240913

### Spotube version

v3.8.0

### Installation source

Website (spotube.krtirtho.dev)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by workwarrior** [comment]
Same problem, cannot login spotify TLS no support
