### ISSUE TITLE
smtc_windows.dll marked as trojan by windows defender

### ISSUE THREAD

**Issue by Alex25820** [KRTirtho/spotube#1894]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I installed the latest version (v3.8.1) of Spotube using the windows installer provided in the GitHub releases page a few days ago and used it without any problem. Today when I launched the program windows defender detected a trojan in `smtc_windows.dll` and put it in quarantine before deleting the file. Reinstalling the program and the launching it triggers the same response from windows defender. Since the file `smtc_windows.dll` is deleted Spotube will no longer launch.

Here is a picture of what windows defender says:
![Windows defender history](https://github.com/user-attachments/assets/93f30e61-4fbc-4267-989f-6bd1bf99bc3a)
Details translates to: This program is dangerous and runs commands from an attacker.
Learn more link leads [here](https://go.microsoft.com/fwlink/?linkid=142185&name=Trojan:Win32/Wacatac.B!ml&threatid=2147735505).

### Expected Behavior

Spotube launches without windows defender detecting a trojan.

### Steps to reproduce

1. Install the latest version (v3.8.1) of Spotube on windows using `Spotube-windows-x86_64-setup.exe` from GitHub releases.
2. Launch Spotube after the installation is done.
3. Windows defender will detect a trojan in `smtc_windows.dll`.

### Operating System

Windows 11

### Spotube version

v3.8.1

### Installation source

GitHub Releases (Binary)

### Additional information

None

**Comment by MrGumpIT** [comment]
I had the same problem

**Comment by NoirPi** [comment]
![image](https://github.com/user-attachments/assets/8c64491a-8cf2-4e29-b865-1ca9f828334a)
Same here...

**Comment by Donnervogel** [comment]
Same issue

**Comment by ashwinjadhav818** [comment]
Same here

**Comment by KRTirtho** [comment]
It's literally built in Microsoft's own Github actions. And it sees as trojan 🤦

I guess it detects that this DLL uses Windows's `SystemMediaTransportControls` API to provide media playback control. So thinks it as a trojan disguising itself as a legitimate software

**Comment by RKDeviancy** [comment]
This happened to me last night. Decided to try it again today, and it didnt flag it this time. Probably just windows defender being sensitive for a moment?? I'm not one who would understand the inconsistency

**Comment by KRTirtho** [comment]
Hmm, it definitely was a false alarm but I guess someone reported this and they patched it.

**Comment by TechedWind707** [comment]
Got this from Microsoft Defender right now
Threat blocked Severe 2026-06-18  Detected: Trojan:Win32/MalUri.A!cl Status: Removed A threat or app was removed from this device. Date: 2026-06-18 Details: This program is dangerous and executes commands from an attacker. Affected items: file: C:\Users\......\Downloads\Spotube-windows-x86_64-setup.exe webfile: C:\Users\....\Downloads\Spotube-windows-x86_64-setup.exe|https://spotube.cc/l
