### ISSUE TITLE
UI on mac has Windows minus square and x

### ISSUE THREAD

**Issue by highjeans** [KRTirtho/spotube#19]
**Describe the bug**
On MacOS the title bar contains both the radio buttons that are on mac and the Windows buttons. Also in settings, the back button is under the macOS radio buttons.

**To Reproduce**
1. Login
2. Look at the top right and left
3. Click on the gear
4. Look at the top left.

**Screenshots**
<img width="1624" alt="Screen Shot 2022-02-02 at 4 15 36 PM" src="https://user-images.githubusercontent.com/77588045/152259567-b8f17828-a799-46ae-a344-500740abd33b.png">
<img width="1624" alt="Screen Shot 2022-02-02 at 4 17 24 PM" src="https://user-images.githubusercontent.com/77588045/152259659-387984eb-83f6-400c-80e1-e8200c570705.png">

**Desktop (please complete the following information):**
 - OS: MacOS

**Comment by KRTirtho** [comment]
@highjeans I fixed the issue. Can you check again & submit new screentshots with it?

**Comment by highjeans** [comment]
Ok so now the back arrow in settings is oddly placed, but the windows style title bar is gone now.
<img width="1624" alt="Screen Shot 2022-02-03 at 7 10 29 PM" src="https://user-images.githubusercontent.com/77588045/152465897-fe351a72-30b0-4595-b1d0-364f0377678c.png">

**Comment by KRTirtho** [comment]
Currently the titlebar buttons are provided by macos itself & those buttons aren't available in the widget tree. Thus there is no spacing information available for those titlebar buttons. So I'm kind of guessing the size information & placing the widgets according to it
bitsdojo_window package is working on this issue https://github.com/bitsdojo/bitsdojo_window/issues/62 & https://github.com/bitsdojo/bitsdojo_window/issues/111

**Comment by KRTirtho** [comment]
I re-positioned the leading section of the titlebar. Can you check if it's better than before in your time?

**Comment by highjeans** [comment]
The back button can be positioned a bit more to the left, but is better than before.
<img width="1624" alt="Screen Shot 2022-02-03 at 9 14 35 PM" src="https://user-images.githubusercontent.com/77588045/152475921-856da12b-3b8e-4886-a72c-e465842f4458.png">

**Comment by KRTirtho** [comment]
Can you edit the value of this file to find the best possible padding & create a PR?
https://github.com/KRTirtho/spotube/blob/b378375b19620138f37be7e45d98380a253add34/lib/components/Shared/PageWindowTitleBar.dart#L64

**Comment by highjeans** [comment]
Ok I will do that when I can.
