### ISSUE TITLE
Spotube crashes on start after updating from 3.7.0->3.8.1: Unknown GPU error

### ISSUE THREAD

**Issue by abrushworkriot** [KRTirtho/spotube#1904]
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

When I launch Spotube in console I get:
`ac: Unknown GPU, using 0 for raster_config
Cannot find target for triple amdgcn-- Unable to find target for this triple (no targets are registered)
fish: Job 1, 'spotube' terminated by signal SIGSEGV (Address boundary error)`

### Expected Behavior

App should launch successfully

### Logs

<details>
<summary>Logs</summary>

```
<Replace this line by pasting your logs here>
```
</details>

### Operating System

Linux Desktop (Wayland)

### Spotube version

3.8.1

### Installation source

GitHub Releases (Binary)

### Additional information

Downloaded from nixpkgs unstable branch.

```
          ▗▄▄▄       ▗▄▄▄▄    ▄▄▄▖            username@nixos
          ▜███▙       ▜███▙  ▟███▛            -----------
           ▜███▙       ▜███▙▟███▛             OS: NixOS 24.05.4997.086b448a5d54 (Uakari) x86_64
            ▜███▙       ▜██████▛              Host: LENOVO LNVNB161216
     ▟█████████████████▙ ▜████▛     ▟▙        Kernel: 6.6.51
    ▟███████████████████▙ ▜███▙    ▟██▙       Uptime: 1 day, 21 hours, 51 mins
           ▄▄▄▄▖           ▜███▙  ▟███▛       Packages: 2766 (nix-system), 664 (nix-user), 159 (nix-default)
          ▟███▛             ▜██▛ ▟███▛        Shell: bash 5.2.32
         ▟███▛               ▜▛ ▟███▛         Resolution: 1920x1080
▟███████████▛                  ▟██████████▙   DE: Hyprland (Wayland)
▜██████████▛                  ▟███████████▛   Terminal: alacritty
      ▟███▛ ▟▙               ▟███▛            CPU: AMD Ryzen 7 5800H with Radeon Graphics (16) @ 4.463GHz
     ▟███▛ ▟██▙             ▟███▛             GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series
    ▟███▛  ▜███▙           ▝▀▀▀▀              GPU: AMD ATI Radeon RX 6600/6600 XT/6600M
    ▜██▛    ▜███▙ ▜██████████████████▛        Memory: 4869MiB / 27921MiB
     ▜▛     ▟████▙ ▜████████████████▛
           ▟██████▙       ▜███▙
          ▟███▛▜███▙       ▜███▙
         ▟███▛  ▜███▙       ▜███▙
         ▝▀▀▀    ▀▀▀▀▘       ▀▀▀▘
```

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
Please create this issue in https://github.com/NixOS/nixpkgs as I don't maintain the package officially.

**Comment by jakubkaczor** [comment]
I have experienced the same issue on both, [Arch Linux package](https://aur.archlinux.org/packages/spotube-bin) and Nix package, so I am not sure if it's package related. I didn't use Spotube before continuously, so I cannot tell when the issue raised, but somewhere in the past, Spotube worked on my setup. I tried return to it after the official Spotify client stopped working for unknown reasons. If I am correct, both applications use different technologies for GUI, so I wouldn't expect the issues to be related, but it is still weird they both don't work at the same time.

**Comment by abrushworkriot** [comment]
@jakubkaczor It worked for me for something like june and everything was more or less fine.
I started to get this error after updating from 3.7.0, so it's one of the three releases. I didn't get deep into changelogs, so I don't know what caused this, but the error suggest it being related to GPU support. I don't think packaging is to blame here.

**Comment by jakubkaczor** [comment]
I have found the cause of the problem. The Spotube versions I tested were either from nixpkgs-unstable or AUR, but I used it with an incompatible version of the Mesa driver, that is, from nixpkgs 24.05. For more details, you can read [my comment](https://github.com/hyprwm/aquamarine/issues/88#issuecomment-2408521160) in the analogous Hyprland issue.

@abrushworkriot, I am not sure if nixGL is meant to be used also on NixOS, but if you want to run Spotube from nixpkgs-unstable, try by invoking
```sh
nix run --override-input nixpkgs nixpkgs/nixpkgs-unstable --impure github:nix-community/nixGL -- spotube
```

**Comment by abrushworkriot** [comment]
Thank you. I'll see once nixpkgs unstable gets up to date with newest release.
Do you think anything can be done about it so it works properly? Did you report the issue to pkg maintainers?

**Comment by jakubkaczor** [comment]
I am afraid there is nothing to do within the realm of the package.

**Comment by abrushworkriot** [comment]
The command you gave me does indeed work. Thank you!
I bet there is a way to write a derivation that makes it work but I'm a noob with Nix, so probably not gonna have luck attempting it.

**Comment by le0nAg** [comment]
I'm experiencing a similar with chromium based browsers... Is it a common issue with nix/NixOS? 
[linkt to thread](https://discourse.nixos.org/t/cannot-run-chrome-nor-chromium/54373l)
