### ISSUE TITLE
Search without an account

### ISSUE THREAD

**Issue by 12people** [KRTirtho/spotube#1913]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

I don't have a Spotify account and don't intend to create one.

It'd be great to be able to use search without it.

### Suggested solution

I'd suggest not requiring a Spotify account to search. (Since the back-end is Youtube-based, this should be possible.)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by loxoron218** [comment]
I'd also love to see this feature implemented! [_Nuclear_](https://github.com/nukeop/nuclear) also allows searching for music and listening to songs without creating any spotify account even though it partly parses informations from it.

**Comment by cipitaua** [comment]
I second this issue, related to https://github.com/KRTirtho/spotube/issues/125

**Comment by KRTirtho** [comment]
Dupliacte of #125

**Comment by KRTirtho** [comment]
The app uses Spotify API and Spotify Account and all it's entities. YouTube api is only used for the audio source/music nothing else.
It's strictly a Spotify Client "not a YouTube/YT Music client" thus we can't provide search without Authenticated user as Spotify API requires it
