### ISSUE TITLE
Songs simply do not play

### ISSUE THREAD

**Issue by Hfhdhdhf** [KRTirtho/spotube#1916]
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

The app just refuses to play any song, i hit play on a playlist and it just waits until it stops, and i cannot hit play again

https://github.com/user-attachments/assets/81552b15-cd1f-4ef0-89a1-56f064759717

and yes, i did try reinstalling, i used both flatpak and aur version

(arch linux)

logs:
[dhza@archlinux ~]$ spotube
package:media_kit_libs_linux registered.
flutter: media_kit: WARNING: package:media_kit_native_event_loop not found.

### Expected Behavior

play the song

### Steps to reproduce

1: opened the app
2: login bug so i gotta re-login for the billionth time
3: play a song
4: song dont play

### Logs

<details>
<summary>Logs</summary>

```
[dhza@archlinux ~]$ spotube
package:media_kit_libs_linux registered.
flutter: media_kit: WARNING: package:media_kit_native_event_loop not found.
```
</details>

### Operating System

Arch Linux latest kernel

### Spotube version

latest

### Installation source

Arch User Repository (AUR), Flathub (Flatpak)

### Self grab

- [x] I'm ready to work on this issue!

**Comment by Obambulate** [comment]
same on windows and ios

**Comment by lzccr** [comment]
Same thing happened to me. I tried reinstalling and it did not work. It was fine this morning and both my desktop (arch linux, installed via flatpak) and my android device (installed via fdroid and also tried the one in Play Store) suddenly stopped working today around 3pm. 

I checked my log and it is just a bunch of 403 and "TrackNotFoumd"

Did YouTube do anything that stopped from spotube frpm running? 

* note: I have YouTube as my source and I am able to access YouTube.com without any problem

**Comment by Hfhdhdhf** [comment]
piped seems to not work too, now the other, that asia one i forgot the name i havent tested yetr

**Comment by Hfhdhdhf** [comment]
i did some testing and saw that other providers are not working too...

**Comment by dhay3** [comment]
It must be something has been done by Youtube, though I do not found any announcement. The `youtube_explode_dart` dependency does not working which Piped and Youtube audio source rely on( related issue: Hexer10/youtube_explode_dart#286 ).

Detail logs of Spotube

```
YoutubeExplodeException: Video SYKU7DfEJT4 returned 403 (stream: 18
#0      StreamClient.getManifest.<anonymous closure> (package:youtube_explode_dart/src/videos/streams/stream_client.dart:46)
<asynchronous suspension>
#1      retry (package:youtube_explode_dart/src/retry.dart:16)
<asynchronous suspension>
#2      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:949)
<asynchronous suspension>
#3      YoutubeSourcedTrack.toSiblingType (package:spotube/services/sourced_track/sources/youtube.dart:145)
<asynchronous suspension>
#4      YoutubeSourcedTrack.fetchSiblings (package:spotube/services/sourced_track/sources/youtube.dart:239)
<asynchronous suspension>
#5      YoutubeSourcedTrack.fetchFromTrack (package:spotube/services/sourced_track/sources/youtube.dart:63)
<asynchronous suspension>
#6      SourcedTrack.fetchFromTrack (package:spotube/services/sourced_track/sourced_track.dart:117)
<asynchronous suspension>
#7      sourcedTrackProvider.<anonymous closure> (package:spotube/provider/server/sourced_track.dart:25)
<asynchronous suspension>
#8      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>
```

**Comment by lzccr** [comment]
so basically all it takes is to figure out a new way to interact with YouTube api?

**Comment by saxomorris** [comment]
Exactly my problem as well, nothing plays.

**Comment by hervoan** [comment]
same problem here, on windows 3.8.1

**Comment by dhay3** [comment]
It should be fixed asap for temporarily used. For the detail check this PR Hexer10/youtube_explode_dart#287

**Comment by JaivishChauhan** [comment]
switch the source to piped close app then open and play would work

**Comment by lzccr** [comment]
> switch the source to piped close app then open and play would work
> 

it do play something but it is not the song sometimes

**Comment by saxomorris** [comment]
yes, works!
laying in hospital bed with pain, the app helps me so much, thanks
I didnt have to login to comment and get you reply of fix very quickly.
morris

Sep 26, 2024 05:20:32 Edward L ***@***.***>:

**Comment by saxomorris** [comment]
however it's showing a jazz song in player panel but playing rap hip hop music, this after I tried to shuffle my classical playlist

Sep 26, 2024 05:20:32 Edward L ***@***.***>:

**Comment by saxomorris** [comment]
I don't understand the Queue system.
It seems without me understanding by clicking abulms etc, a queue is being built without my intention. need a distinct button for this and maybe a way to turn off, atleast til I can understand its use. I never use this feature in past. Reason I mention is songs play sometimes from Queue much later even when they wont play directly ... maybe a backlog of Queue causes problems, I clear when I see the opportunity  but cant find.Queue easily.

Sep 26, 2024 05:20:32 Edward L ***@***.***>:

**Comment by typoworx-de** [comment]
Same here on my ubuntu 23 system. fresh install of spotube trying to find a better alternative for native spotify (bad audio quality). But after login with spotube to spotify songs do not start to play.

**Comment by RayBEAMM** [comment]
I

> switch the source to piped close app then open and play would work

This worked at first but then when I went to change sources it stopped working

**Comment by Hoosck** [comment]
Same on android since september 24th.

**Comment by LtKie** [comment]
> ### Is there an existing issue for this? (Please read the description)
> * [x]  I have searched the existing issues
> 
> ### Current Behavior
> The app just refuses to play any song, i hit play on a playlist and it just waits until it stops, and i cannot hit play again
> 
>  2024-09-24.20-55-49.mp4 
> and yes, i did try reinstalling, i used both flatpak and aur version
> 
> (arch linux)
> 
> logs: [dhza@archlinux ~]$ spotube package:media_kit_libs_linux registered. flutter: media_kit: WARNING: package:media_kit_native_event_loop not found.
> 
> ### Expected Behavior
> play the song
> 
> ### Steps to reproduce
> 1: opened the app 2: login bug so i gotta re-login for the billionth time 3: play a song 4: song dont play
> 
> ### Logs
> Logs
> ### Operating System
> Arch Linux latest kernel
> 
> ### Spotube version
> latest
> 
> ### Installation source
> Arch User Repository (AUR), Flathub (Flatpak)
> 
> ### Additional information
> _No response_
> 
> ### Self grab
> * [x]  I'm ready to work on this issue!

Yes experience this current issue on android.. done reinstalling but same issue

**Comment by LtKie** [comment]
Yes experience this current issue on android.. done reinstalling but same issue

**Comment by BloodRaven0** [comment]
Soo, the app is not functioning for anyone, and there is a working patch available since 5 days ago. Why are we not releasing a new version?

**Comment by aws1313** [comment]
The new version is there... it might take some time to get in the app stores but it's on GitHub and for me also on Google Play...

**Comment by saxomorris** [comment]
Aurora Store has.
Thank you, back to enjoying  the app!

Sep 30, 2024 22:30:09 aws1313 ***@***.***>:

**Comment by Porrumentzio** [comment]
Just for knowing if any other one is facing this again. The same or something similar is happening to me now with v3.8.2

Maybe it's momentaneous, let's see tomorrow (I'll remove the comment if it works again)

**Comment by Obambulate** [comment]
It is in fact not working again(on phone) will check on computer later

**Comment by marcos-aparicio** [comment]
same here with v3.8.2 neither my computer nor my android phone are working

**Comment by eric2788** [comment]
same here, does login to youtube can solve the 403 problem ?

**Comment by BloodRaven0** [comment]
I also experienced something similar two days ago, but it wasn't limited to Spotube, anything youtube related refused to work, for example Freetube. They've been doing nice stuff with the API again.

**Comment by saxomorris** [comment]
Android
Nothing plays except local downloads.
Try to play a single song from playlist, spins, stops.
Tried all there audio sources with forced restarts.

.

Oct 9, 2024 00:44:21 Porrumentzio ***@***.***>:

**Comment by mythril64** [comment]
ive had this same problem since this morning (android version). it worked last night, pretty well too. fell asleep with the sleep timer eventually i think. then i tried opening it this morning and playing music, it was constantly starting to play and then doesnt do anything.
the funniest thing is that at one point 2 songs or something played- while i wasnt logged in. but not in their correct version, they were romanian songs and started playing like indian pop as the source material? which im sorry, am i insane or does that make no sense?
so yea anyway right now i tried starting it using the apk on android, no difference. and on windows the app wont even open.

**Comment by Porrumentzio** [comment]
Now the app wont even launch. Any possible fix?

Maybe you could help, @sunryze-git?

**Comment by saxomorris** [comment]
Here works fine now except needs a force quit now and then if I see playlists are not loading, usually after a lost connection popup.

Oct 12, 2024 11:29:10 Porrumentzio ***@***.***>:

**Comment by Porrumentzio** [comment]
Apparently fixed with the new version 8

**Comment by wimpywarlord** [comment]
Changed the source to pipe and quit the application and restared. Started working.

Used kevin.rockstart source for pipe server.

MacOS

**Comment by wimpywarlord** [comment]
Its was my VPN causing issues. Disable VPN - I was using Proton VPN

**Comment by Porrumentzio** [comment]
This is happening again. Three new issues were created about this problem.

**Comment by Porrumentzio** [comment]
@KRTirtho, @sunryze-git, could you have a look at this, in case it has again to do with the YouTube dependency?

**Comment by Mr-BlackHat-lab** [comment]
Same thing happened to me agian i am using windows 11 and latest version of spotube pls fix as soon as possible

**Comment by timpim-dev** [comment]
Same on android with Spotify

**Comment by Seyed-A** [comment]
YO
so I'm still getting issue on 5.1.2, so I decided to crack down on it. I feel like this is a mozzilla or code bug as the logs read as the following on Android 16 (note that it is the same error no matter api, audio source or metadata source. Tried yt, spotify, 3rd party flak one, jiivosan and listenbrains all independently together):

DioException [bad response]: This exception was thrown because the response has a status code of 500 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 500 has the following meaning: "Server error - the server failed to fulfil an apparently valid request"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.
