### ISSUE TITLE
Authentication Failure DioException

### ISSUE THREAD

**Issue by ghost** [KRTirtho/spotube#1917]
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

错误 Authentication Failure
DioException [connection error]: The connection errored: 信号灯超时时间已到This indicates an error which most likely cannot be solved by the library.Error: SocketException: 信号灯超时时间已到(OS Error: 信号灯超时时间已到
errno=121),address =open.spotify.com, port = 40659

### Expected Behavior

i dont't know

### Logs

<details>
<summary>Logs</summary>

```
<Replace this line by pasting your logs here>
```
</details>

### Operating System

Win11

### Installation source

GitHub Releases (Binary)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by Hfhdhdhf** [comment]
check internet connection. or if spotify is down ig

**Comment by suchangv** [comment]
spotube 默认不走系统代理，要开下 tun 模式
