### ISSUE TITLE
Macos spotify login error

### ISSUE THREAD

**Issue by selimanajjar9** [KRTirtho/spotube#1918]
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

Macos latest system download and login spotify, webpage login successful, not jump page to app, close webpage, prompt authorization error.
![image](https://github.com/user-attachments/assets/f61d082c-bedb-4c75-80d1-709d01ac1d42)

### Expected Behavior

It should be a direct jump to the app after logging in, and then already logged into the spotify account

### Logs

<details>
<summary>Logs</summary>

```
<Replace this line by pasting your logs here>
```
</details>

### Operating System

macOS

### Spotube version

Version 3.8.1 (34)

### Installation source

GitHub Releases (Binary)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by lzccr** [comment]
Something happened to spotube today and it is currently down. See issue #1916.
