### ISSUE TITLE
Spotify Login Not Aligned on Android

### ISSUE THREAD

**Issue by dyennn** [KRTirtho/spotube#1943]
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

The login screen for spotify is slightly off.

### Expected Behavior

It should cover my screen.

![1727675431981](https://github.com/user-attachments/assets/9c2d592d-94fe-489d-81f2-e03502bec9ed)

### Steps to reproduce

1. Click on the Spotube app.
2. Click on the Settings icon (top-right).
3. Click "Login with your Spotify account".

### Logs

<details>
<summary>Logs</summary>

```
<Replace this line by pasting your logs here>
```
</details>

### Operating System

Android - Xiaomi HyperOS 1.0.5.0 THGMIXM

### Spotube version

v3.8.1

### Installation source

Play Store (Android)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by ayato91** [comment]
May I fix this issue?

**Comment by KRTirtho** [comment]
@ayato91 all yours

**Comment by KRTirtho** [comment]
Read the [CONTRIBUTION.md#your-first-code-contribution](https://github.com/KRTirtho/spotube/blob/master/CONTRIBUTION.md#your-first-code-contribution)
Then create a PR with the fix and add me as a reviewer.

Good Luck

**Comment by ayato91** [comment]
Working on It

**Comment by KRTirtho** [comment]
It is aligned now in v3.8.3

**Comment by KRTirtho** [comment]
Closing as completed
