### ISSUE TITLE
feat: Jetpack Compose based Android app

### ISSUE THREAD

**Issue by tvnmguy** [KRTirtho/spotube#1955]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

Technically this app too brilliant and I love this app. But lot of UI bugs put me back a step from this app.

### Suggested solution

Jetpack Compose based Android app reduce lot of UI related bugs of this app and simplify UI development and maintainability.

### Useful resources

Jetpack Compose is a modern UI toolkit for building native Android applications introduced by Google. It simplifies and accelerates the UI development process, allowing developers to write less code and reducing the potential for bugs.

Key features of Jetpack Compose:

1. Declarative programming: Compose uses a declarative programming model, where you describe what you want to see on the screen (the UI) without worrying about the implementation details.
2. Composable functions: Compose is built around composable functions, which are small, reusable pieces of code that define a UI component. These functions can be combined to create more complex UI layouts.
3. Less code: Jetpack Compose reduces the amount of code needed to build a UI, making it easier to maintain and update your app.
4. Material Design 3: Compose provides an implementation of Material Design 3, Google's design language for Android, out of the box. This means you can easily create apps with a consistent and modern look.
5. Kotlin APIs: Compose uses Kotlin APIs, making it a great choice for Kotlin developers.
6. Integration with Android: Jetpack Compose is designed to work seamlessly with the Android ecosystem, allowing you to leverage Android's features and APIs.

Benefits of using Jetpack Compose:

1. Faster development: Compose's declarative programming model and reduced code requirements enable faster development and prototyping.
2. Improved maintainability: With less code and a more modular architecture, Compose makes it easier to maintain and update your app over time.
3. Enhanced UI consistency: Compose's built-in support for Material Design 3 ensures a consistent and modern look across your app.
4. Better performance: Compose's optimized rendering and layout management lead to better performance and smoother user experiences.

Overall, Jetpack Compose is a powerful tool for building modern, native Android applications with a focus on simplicity, flexibility, and performance.

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
Nada
