### ISSUE TITLE
Spotify Login Not Opening Properly

### ISSUE THREAD

**Issue by Lory-exe** [KRTirtho/spotube#1963]
### Is there an existing issue for this? (Please read the description)

- [x] I have searched the existing issues

### Current Behavior

When I click on "Connect with Spotify" it opens a not formatted login window and it is impossible to login:

![image](https://github.com/user-attachments/assets/9529ccdf-5215-410c-95cc-7dfb835250a2)

### Expected Behavior

Can insert my Spotify Email and password to login and connect with spotube

### Logs

<details>
<summary>Logs</summary>

```
<Replace this line by pasting your logs here>
```
</details>

### Operating System

Arch LInux

### Installation source

Flathub (Flatpak)

### Self grab

- [X] I'm ready to work on this issue!

**Comment by hakangoksu** [comment]
I have the same problem

**Comment by hakangoksu** [comment]
I assume problem with flatpak continues. I used aur package, works flawlessly.

**Comment by hartontw** [comment]
I've used the AUR package. Login button shows blank screen.

Fix worked for me:
```bash
WEBKIT_DISABLE_COMPOSITING_MODE=1 spotube
```
