### ISSUE TITLE
Large logfile

### ISSUE THREAD

**Issue by valankar** [KRTirtho/spotube#1968]
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

There seems to be a giant logfile created in my Documents folder on Windows:

![image](https://github.com/user-attachments/assets/12439685-3f34-4961-a7c9-8c6bc8dc7001)

### Expected Behavior

I would like to disable this logging completely.

### Logs

<details>
<summary>Logs</summary>

```
<Replace this line by pasting your logs here>
```
</details>

### Operating System

Windows 11

### Spotube version

v3.8.2

### Installation source

GitHub Releases (Binary)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
You can delete it. Logs file are supposed to store all logs. If you don't have any issues it can be deleted. It'll start from zero once again
