### ISSUE TITLE
Unable to play audio - VideoUnavailableException

### ISSUE THREAD

**Issue by moisestohias** [KRTirtho/spotube#1971]
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

I'm unable to play any audio with the recent version of Spotube Desktop App on linux, I've facing the same behavior on Android as well. The app throws a VideoUnavailableException with the following details:

- Error message: Video '4RKwlqulnIQ' is unavailable
- Possible causes: ??
- Version: latest at the time of reporting this (2024-10-06).  

The error suggests that if the video is accessible in an incognito browser window, it might indicate a change on YouTube's end that has broken the library used by Spotube.

### Expected Behavior

Audio to play.

### Steps to reproduce

Install latest version of Ubuntu. Set Youtube as source.

### Logs

<details>
<summary>Logs</summary>

```
[2024-10-06 21:49:56.029678]---------------------
VideoUnavailableException: Video '4RKwlqulnIQ' is unavailable
In most cases, this error indicates that the video doesn't exist, is private, or has been taken down.
If you can however open this video in your browser in incognito mode, it most likely means that YouTube changed something, which broke this library.
Please report this issue on GitHub in that case.
#0      WatchPage.get.<anonymous closure> (package:youtube_explode_dart/src/reverse_engineering/pages/watch_page.dart:145)
<asynchronous suspension>
#1      retry (package:youtube_explode_dart/src/retry.dart:16)
<asynchronous suspension>
#2      VideoClient._getVideoFromWatchPage (package:youtube_explode_dart/src/videos/video_client.dart:38)
<asynchronous suspension>
#3      YoutubeSourcedTrack.fetchSiblings (package:spotube/services/sourced_track/sources/youtube.dart:242)
<asynchronous suspension>
#4      YoutubeSourcedTrack.fetchFromTrack (package:spotube/services/sourced_track/sources/youtube.dart:63)
<asynchronous suspension>
#5      SourcedTrack.fetchFromTrack (package:spotube/services/sourced_track/sourced_track.dart:117)
<asynchronous suspension>
#6      sourcedTrackProvider.<anonymous closure> (package:spotube/provider/server/sourced_track.dart:25)
<asynchronous suspension>
#7      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

```
</details>

### Operating System

Linux Ubuntu 24.04 LTS

### Spotube version

v3.8.2

### Installation source

GitHub Releases (Binary)

### Self grab

- [X] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
Fixed in v3.8.3 #1979
