### ISSUE TITLE
can't play any song

### ISSUE THREAD

**Issue by EndyIndo7** [KRTirtho/spotube#1972]
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

i can't play any song and it just guide me to enable runo call CRM and its plugin. but i don't feels enable any battery optimization, is people get the same condition? or just me? I'm android 12 user

### Expected Behavior

it suposed to work just without those runo stuff cause I don't enable any battery optimization

### Logs

I dunno 

### Operating System

Android 12

### Spotube version

3.8.2

### Installation source

Play Store (Android)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by romfila** [comment]
Hi.
Same here: for the past few days, when I open the app, it automatically tries to play songs in the playlist, can't play anything and jumps to the next title endlessly. I search and add new titles to the playlist, or replace the queue, but they won't play either.
Thanks in advance for having a look and finding a fix or workaround.

**Comment by KRTirtho** [comment]
Fixed in 3.8.3
