### ISSUE TITLE
Use spotube to play my own MP3s

### ISSUE THREAD

**Issue by lemonJumps** [KRTirtho/spotube#1974]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

spotube now only works with downloaded and online songs, it's a really cool app for listening to music all together.
However, sadly, with the decline of internet songs are being lost and theres some that cannot be found on either youtube or spotify.

### Suggested solution

Add a feature to play and search local songs from selected folders. 

### Useful resources

Uuuh vlc has an android port, and a separate library which should have all vlc functionality hidden inside of it.
https://github.com/videolan/vlc-android

maybe it'll be as easy as wrapping it as another source for metadata/ player :D

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by skruglov2023** [comment]
You should be able to add a folder? Go to the 3rd tab, and then select "Local"
Then, "Add to LIbrary" and choose which folder you want.

**Comment by lemonJumps** [comment]
OOOH it does work! even with vobris ogg. :3 I didn't knew that was a thing!
altho it doesn't load cover from the folder, but that's fine!!
