### ISSUE TITLE
The app asks for an upgrade but the version available on winget remains the previous one.

### ISSUE THREAD

**Issue by Someone-Who-Writes-Code** [KRTirtho/spotube#1983]
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

The app is prompting me to update to version 3.8.3, but when I try to install/upgrade it using winget I do not get the newer version.

Current installation:
![imagen](https://github.com/user-attachments/assets/e52bedf6-9e4b-4e3a-86cd-cbee2f716db7)

using **_install_**:
![imagen](https://github.com/user-attachments/assets/0816dd3c-095e-4431-affa-6aeb5969f8a9)

using **_upgrade_**:
![imagen](https://github.com/user-attachments/assets/3108c8c4-6be6-46d4-b117-947499849c75)

### Expected Behavior

When the app asks for an upgrade the newer version should be available on winget to download and install.

### Steps to reproduce

1. Open Spotube
2. Get the prompt showing a newer version is available
3. Try to upgrade Spotube via CLI `winget install --id KRTirtho.Spotube --version 3.8.3`
4. Fail to get the most recent version

### Logs

<details>
<summary>Logs</summary>

```
<Replace this line by pasting your logs here>
```
</details>

### Operating System

Windows 10 19045.3930

### Spotube version

v3.8.2

### Installation source

WinGet (Windows)

### Self grab

- [X] I'm ready to work on this issue!

**Comment by Renegade-Master** [comment]
It  takes time for things to be published to WinGet. They can be published on GitHub immediately, but it won't be as quick to reach WinGet. WinGet have their own processes and Actions that need to complete before updates are published.

**Comment by Someone-Who-Writes-Code** [comment]
That was my first thought too, but I just wanted to be sure. Thank you for your answer.

BTW, version 3.8.3 is still not published on winget at this time.

**Comment by singhh9596** [comment]
I'm getting update on playstore but due to different signature maybe can't update it and it's annoying.

**Comment by Balou866** [comment]
Most of the time it takes 24h-48h to the latest Spotube release to be available on winget.
Might even be more sometimes

**Comment by KRTirtho** [comment]
The upstream PR just got merged so it should be available now.
WinGet usually takes few hours to days to merge the PRs. So, Spotube (or any software) might not be available there right away after it's officially released.
Same goes for PlayStore, Flathub, F-Droid, iOS AppStore etc

**Comment by Someone-Who-Writes-Code** [comment]
> The upstream PR just got merged so it should be available now. 

Thanks for the update! It seems I'm still unable to upgrade to Spotube 3.8.3 as well, so I'll wait for now. 

![imagen](https://github.com/user-attachments/assets/7cb4080b-463a-49fe-b9e6-49ddb92c6c9e)

Appreciate your help!
