### ISSUE TITLE
[website] older versions links on website dont work

### ISSUE THREAD

**Issue by si458** [KRTirtho/spotube#1985]
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

when you visit the `older versions` on the website,
and select a version and your OS, 
it just diverts you to the github API and returns JSON ?

### Expected Behavior

when you click the OS you wanted under the version you wanted, for it download the app relating to it, not show JSON

### Steps to reproduce

1. visit the `older versions` from the website,
2. select a version and your OS, 
3. it just diverts you to the github API and returns JSON ?

### Logs

N/A

### Operating System

ANY

### Installation source

Website (spotube.krtirtho.dev)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by si458** [comment]
@s-b-repo no it isn't
If you visit https://spotube.krtirtho.dev/downloads/older

Then select any device and version, it just opens up the github api and returned json

Instead of taking u directly to the file as intended

**Comment by s-b-repo** [comment]
> @s-b-repo no it isn't If you visit https://spotube.krtirtho.dev/downloads/older
> 
> Then select any device and version, it just opens up the github api and returned json
> 
> Instead of taking u directly to the file as intended

might be a api change or a incorrect request

**Comment by si458** [comment]
> might be a api change or a incorrect request

@s-b-repo hence me opening the issue so the website devs can look into it :)
