### ISSUE TITLE
having the ability to download playlists and them to sorted in their own folders 

### ISSUE THREAD

**Issue by Sylentsyl** [KRTirtho/spotube#1992]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

when ever i download the music it downloads them to the same folder 

### Suggested solution

this could be remediated by using the things spotiflyer used to do 

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
Duplicate of #1779
