### ISSUE TITLE
Breaks after adding  clientID, clientSecret

### ISSUE THREAD

**Issue by skjo0c** [KRTirtho/spotube#2]
After adding  clientID, clientSecret. Application redirects us to this page. 

OS: Ubuntu Budgie 21.10

![image](https://user-images.githubusercontent.com/20612562/149462272-4353e5f3-d8ba-4130-8946-49f872657346.png)

**Comment by KRTirtho** [comment]
Can you try launching it via terminal & submit all the logs here?

**Comment by skjo0c** [comment]
@KRTirtho 

** (spotube:292552): CRITICAL **: 13:22:15.507: size_t fl_value_get_length(FlValue *): assertion 'self->type == FL_VALUE_TYPE_UINT8_LIST || self->type == FL_VALUE_TYPE_INT32_LIST || self->type == FL_VALUE_TYPE_INT64_LIST || self->type == FL_VALUE_TYPE_FLOAT32_LIST || self->type == FL_VALUE_TYPE_FLOAT_LIST || self->type == FL_VALUE_TYPE_LIST || self->type == FL_VALUE_TYPE_MAP' failed

** (spotube:292552): CRITICAL **: 13:22:15.508: size_t fl_value_get_length(FlValue *): assertion 'self->type == FL_VALUE_TYPE_UINT8_LIST || self->type == FL_VALUE_TYPE_INT32_LIST || self->type == FL_VALUE_TYPE_INT64_LIST || self->type == FL_VALUE_TYPE_FLOAT32_LIST || self->type == FL_VALUE_TYPE_FLOAT_LIST || self->type == FL_VALUE_TYPE_LIST || self->type == FL_VALUE_TYPE_MAP' failed

** (spotube:292552): CRITICAL **: 13:22:15.508: size_t fl_value_get_length(FlValue *): assertion 'self->type == FL_VALUE_TYPE_UINT8_LIST || self->type == FL_VALUE_TYPE_INT32_LIST || self->type == FL_VALUE_TYPE_INT64_LIST || self->type == FL_VALUE_TYPE_FLOAT32_LIST || self->type == FL_VALUE_TYPE_FLOAT_LIST || self->type == FL_VALUE_TYPE_LIST || self->type == FL_VALUE_TYPE_MAP' failed

** (spotube:292552): CRITICAL **: 13:22:15.508: size_t fl_value_get_length(FlValue *): assertion 'self->type == FL_VALUE_TYPE_UINT8_LIST || self->type == FL_VALUE_TYPE_INT32_LIST || self->type == FL_VALUE_TYPE_INT64_LIST || self->type == FL_VALUE_TYPE_FLOAT32_LIST || self->type == FL_VALUE_TYPE_FLOAT_LIST || self->type == FL_VALUE_TYPE_LIST || self->type == FL_VALUE_TYPE_MAP' failed
flutter: Bad state: No element
flutter: #0      _GrowableList.last (dart:core-patch/growable_array.dart:344)
flutter: #1      _HomeState.build.<anonymous closure>.<anonymous closure> (package:spotube/components/Home.dart:188)
flutter: #2      _FutureBuilderState.build (package:flutter/src/widgets/async.dart:615)
flutter: #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4705)
flutter: #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4588)
flutter: #5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763)
flutter: #6      Element.rebuild (package:flutter/src/widgets/framework.dart:4311)
flutter: #7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2578)
flutter: #8      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882)
flutter: #9      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363)
flutter: #10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145)
flutter: #11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082)
flutter: #12     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996)
flutter: #16     _invoke (dart:ui/hooks.dart:150)
flutter: #17     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270)
flutter: #18     _drawFrame (dart:ui/hooks.dart:114)
flutter: (elided 3 frames from dart:async)

**Comment by KRTirtho** [comment]
Found the issue. It's my mistake actually to not give proper attention to user section of the app😅

It's happening because you don't have a **profile-pic**/**avatar** in your Spotify account. So it's setting `null` to url of the `Image.url`. I'll fix this ASAP

For a workaround you can add a profile picture in your Spotify account

**Comment by KRTirtho** [comment]
@skjo0c Now it's fixed in v1.0.1
