### ISSUE TITLE
App Window Name is APP_NAME

### ISSUE THREAD

**Issue by highjeans** [KRTirtho/spotube#20]
the window is called APP_NAME and when going to the Window menu in the macOS menu bar it has APP_NAME this is really weird.
<img width="475" alt="Screen Shot 2022-02-03 at 7 13 56 PM" src="https://user-images.githubusercontent.com/77588045/152466227-50adb919-32e8-4281-963c-b48a46a498da.png">

**Comment by KRTirtho** [comment]
Nothing's weird about it. It happened because the `MainMenu.xib` file was using a placeholder name for the application. There is no mention about this thing in the entire universe so didn't get a clue about it. But it'll be fixed in the next commit

**Comment by highjeans** [comment]
Ok cool!

**Comment by KRTirtho** [comment]
It's fixed. Can you check it in your time?

**Comment by highjeans** [comment]
Ok cool this is fixed now.
