### ISSUE TITLE
Android widgets

### ISSUE THREAD

**Issue by AarushiswinnerYo** [KRTirtho/spotube#2002]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

How about a home screen widget to control the music directly from the home screen without opening the app?

### Suggested solution

Add widgets?😂 I mean what am I supposed to say here..?😂

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
Duplicate of #275
