### ISSUE TITLE
[Bug] Error when a playlist is ...empty?

### ISSUE THREAD

**Issue by lexxyungcarter** [KRTirtho/spotube#201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="458" alt="image" src="https://user-images.githubusercontent.com/19994360/189372799-da2f3b5a-ab7b-4506-9f90-81e74a4bfed7.png">

### Expected Behavior

Show empty list/placeholder

### Spotube Version

2.4.0 (13)

### Operating System

Mac OS

### Operating System Version

Macos 12

### Installation Source

Official Website (spotube.netlify.app)

**Comment by KRTirtho** [comment]
Fixed and available from latest v2.5.0
