### ISSUE TITLE
[Bug] Android interface is bad resized

### ISSUE THREAD

**Issue by Darkempire78** [KRTirtho/spotube#202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The Android interface is unusable

### Expected Behavior

Well sized interface

### Steps To Reproduce

Install and run...

### Spotube Version

2.4.0

### Operating System

Android

### Linux Distribution (if applicable)

Google Pixel 6

### Operating System Version

Android 13

### Installation Source

Github

### Additional information

![Screenshot_20220909-172814](https://user-images.githubusercontent.com/50015928/189387091-b8a4f37e-25f6-458a-9e6d-85f94b9c9ec6.png)

**Comment by KRTirtho** [comment]
Try uninstalling and reinstalling. Pixel 6 my own device have similar screen resolution and in device its completely fine

**Comment by MrWalker05** [comment]
Hello, I have the same problem.
I have a Oneplus5 with Lineageos.
I also deleted and uninstalled everything again.
At first the GUI looks normal. I scroll in the library to the artits. That crashes and afterwards the GUI looks all broken like in the picture. The program crashes often, which the 2.3 had not done now.

**Comment by Darkempire78** [comment]
Works well after reinstalling

**Comment by KRTirtho** [comment]
@MrWalker05 try using the latest nightly version https://spotube.netlify.app/other-downloads/nightly-downloads
If it doesn't auto resize, change the layout mode from `adaptive` to `compact` to force smaller display UI

**Comment by MrWalker05** [comment]
Thanks.
When I scroll / swipe from artist to album the program crashes.
I am now again back to version 2.3

![Screenshot_20220912-160526_Trebuchet](https://user-images.githubusercontent.com/68013465/189741781-df7e8139-5bf7-47ff-ba15-28fe1e809496.png)

**Comment by KRTirtho** [comment]
All of your issues got fixed and now available in v2.4.1

**Comment by Patronos** [comment]
I had this issue as well. But 2.4.0 fixed it for me. Now with 2.4.1 everything is messed up again.

E.g:

Search. The search box is way too far on the top and half out of the top area now.
Library: All the buttons like Playlist, Downloads, Local etc. are far at the top and out of seight. Basigly hidden under the notch area.

Sometimes when you reboot Anfroid, Spotube comes up correctly and sometimes it's stuck with the issues above.

I think there is a bit more work to do.

**Comment by KRTirtho** [comment]
@Patronos you can go to Spotube settings and then select the layout mode of choice
- adaptive (automatically sized ui)
- extended (force desktop ui)
- compact (forces small ui)

**Comment by MrWalker05** [comment]
Thank you
