### ISSUE TITLE
Playing the wrong song in spotube.

### ISSUE THREAD

**Issue by AlphonseHK** [KRTirtho/spotube#2021]
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

Playing the wrong song in spotube

### Expected Behavior

I play [aiko - blue] in spotube, it will become [Jhene Aiko - Blue Dream].

### Logs

<details>
<summary>Logs</summary>

```
<Replace this line by pasting your logs here>
```
</details>

### Operating System

Android 13 ,Windows 11

### Spotube version

3.8.3

### Installation source

GitHub Releases (Binary)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
> ### Is there an existing issue for this? (Please read the description)
> 
> - [X] I have searched the existing issues

![N](https://c.tenor.com/Pd0Kna5m45cAAAAC/tenor.gif)
