### ISSUE TITLE
High data usage  and seems like songs are not cached.

### ISSUE THREAD

**Issue by Kam0797** [KRTirtho/spotube#2045]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

Every song draws about 10+mb every time I play. And songs don't play with slow network connection (keeps loading for too long)

### Suggested solution

The songs could be cached in local storage - it can reduce data usage and provide faster playback of already played songs.
(I'd seen this in apps like innertune and Rimusic)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by skruglov2023** [comment]
Consider downloading playlists on wifi, and then playing them back.  I do agree that it would be nice if it was automatic though.

**Comment by Kam0797** [comment]
That's more like an offline player, and that's not what this app is supposed to be...

**Comment by KRTirtho** [comment]
Duplicate of #127
