### ISSUE TITLE
mp3

### ISSUE THREAD

**Issue by senolfndk** [KRTirtho/spotube#205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Downloading songs in m4a format

### Expected Behavior

change mp3 download format

### Steps To Reproduce

change mp3 download format

### Spotube Version

v2.4.0

### Operating System

Windows

### Operating System Version

android 12

### Installation Source

chocolatey (Windows)

### Additional information

![Ekran görüntüsü 2022-09-12 001609](https://user-images.githubusercontent.com/52818836/189549272-10b07449-0b84-4dab-a65b-98ec45f2184d.png)

**Comment by KRTirtho** [comment]
What's wrong with m4a?

**Comment by senolfndk** [comment]
> m4a'nın nesi var?

If nothing else, why don't you prefer mp3 format?
![Ekran görüntüsü 2022-09-12 155403](https://user-images.githubusercontent.com/52818836/189659287-1e56c9ef-b685-4b1d-b6d3-0b73c15b9c88.png)

**Comment by senolfndk** [comment]
> m4a'nın nesi var?

nothing you don't prefer mp3 format

**Comment by senolfndk** [comment]
nothing you don't prefer mp3 format
![Uploading Ekran görüntüsü 2022-09-12 155403.png…]()

**Comment by senolfndk** [comment]
> m4a'nın nesi var?

why m4a format not mp3

**Comment by KRTirtho** [comment]
Because all along it was mpeg-4 but I didn't realize it and was naming the downloaded files with .mp3 extension

**Comment by senolfndk** [comment]
ok can you convert it to mp3 format

**Comment by KRTirtho** [comment]
I don't think that's possible yet and is kind of unnecessary as most of the media players and even Spotube supports this format

**Comment by senolfndk** [comment]
ok

**Comment by senolfndk** [comment]
player button stands below needs to center
![Ekran görüntüsü 2022-09-12 192805](https://user-images.githubusercontent.com/52818836/189707040-e4c2f031-c1ac-443a-a757-3e284adef029.png)

**Comment by KRTirtho** [comment]
> player button stands below needs to center ![Ekran görüntüsü 2022-09-12 192805](https://user-images.githubusercontent.com/52818836/189707040-e4c2f031-c1ac-443a-a757-3e284adef029.png)

available from 2.4.1

**Comment by senolfndk** [comment]
nothing changes, still the same
![Ekran görüntüsü 2022-09-13 115556](https://user-images.githubusercontent.com/52818836/189858355-c3cd21aa-71bf-4639-8072-ec054e1f3dbb.png)

**Comment by senolfndk** [comment]
it could be a player button like this
![Ekran görüntüsü 2022-09-13 115901](https://user-images.githubusercontent.com/52818836/189859130-7bf6c157-4950-4f91-8d1b-fefba07b2385.png)

**Comment by KRTirtho** [comment]
Moved to discussion #265
