### ISSUE TITLE
Spotify login requires Edge WebView2 installed on windows. 

### ISSUE THREAD

**Issue by FrostedVolcano** [KRTirtho/spotube#2068]
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

It's probably not a bug, but to connect with Spotify, Edge WebView2 needs to be installed on windows. This might be annoying for some people including me who doesn't need Edge WebView2 for any other app.
![image](https://github.com/user-attachments/assets/347e8e6a-38b7-4ddf-9af4-938e58e6cba3)

### Expected Behavior

It would be better to not have Edge WebView2 as a dependency.

### Steps to reproduce

1. Open the app.
2. Go to settings
3. Click "CONNECT WITH SPOTIFY" at the top right corner.

### Logs

----------------------------------------
[2024-11-18 21:47:19.542068]---------------------
Error Code: 401
Valid user authentication required
#0      SpotifyApiBase.handleResponseWithBody (package:spotify/src/spotify_base.dart:282)
#1      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:256)
<asynchronous suspension>
#2      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:210)
<asynchronous suspension>
#3      CursorPages.getPage (package:spotify/src/endpoints/endpoint_paging.dart:292)
<asynchronous suspension>
#4      SinglePages.stream.handlePageAndGetNext (package:spotify/src/endpoints/endpoint_paging.dart:187)
<asynchronous suspension>

----------------------------------------

### Operating System

Windows 11.

### Spotube version

v3.8.3

### Installation source

chocolatey (Windows)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by Peperehobbits01** [comment]
It's should be on your system by default because you use Windows so that's why Spotube is using this. So it's not gonna change, you are going to have to install it back in your system.

**Comment by FrostedVolcano** [comment]
@Peperehobbits01 I actually removed WebView2 from my system for debloating, as there's no other app in my system that need it. I ended up not using Spotube as it couldn't play livestreams from youtube.
Thanks.

**Comment by Peperehobbits01** [comment]
The goal is not to play livestreams made on YouTube. It's just not the goal of the app

**Comment by Peperehobbits01** [comment]
Anyway, could you close this issues so it helps the developers of this project to go through the issues faster. Thank you.
