### ISSUE TITLE
Login with spotify by facebook

### ISSUE THREAD

**Issue by guilhass713** [KRTirtho/spotube#2077]
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

Just on my computer, I can't access my Spotify account to use Spotube. I press the option to log into spotify via Facebook (as I always do) and, when I enter my account details, it gives an error. But on my phone I can use the app associated with Spotify. How i fix this?
Thanks

### Expected Behavior

I want to login in spotify by my facebook account

### Logs

<details>
<summary>Logs</summary>

```
<Replace this line by pasting your logs here>
```
</details>

### Operating System

Windows

### Spotube version

v3.8.3

### Installation source

Website (spotube.krtirtho.dev)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
Duplicate og #1799
