### ISSUE TITLE
[Feature] <title>

### ISSUE THREAD

**Issue by Noob-linux-user** [KRTirtho/spotube#209]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of the Feature

UI Improvements

### Credits

Me?

### Pain

The media control doesn't show while browsing a playlist.
Also, can u add a button to download the tract from the playlist. Without us having to open it.

### Suggested Solution

Just adding the media control while browsing through the playlist. 
And if you add the button, then it will be much better.

**Comment by KRTirtho** [comment]
These were added/fixed in 2.7.0
