### ISSUE TITLE
Music still plays if some other audio is playing simultaneously (Pauses only for first time)

### ISSUE THREAD

**Issue by radagon12** [KRTirtho/spotube#2092]
### Is there an existing issue for this? (Please read the description)

- [x] I have searched the existing issues

### Current Behavior

Suppose I am playing a video on youtube while a music is playing in background on spotube, the both audios from youtube and spotube are playing simultaneously 

### Expected Behavior

Spotube should stop playing if some other music app is playing music

### Steps to reproduce

1. I opened the spotube
2. Plays never gonna give you up
3. Goes to youtube and plays iris by goo goo dolls
4. I can hear both of the songs simultaneously 

### Logs

<details>
<summary>Logs</summary>

```
<Replace this line by pasting your logs here>
```
</details>

### Operating System

Android

### Spotube version

3.8.3

### Installation source

Play Store (Android)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by vrndv** [comment]
Yeah, I also got the same issue while playing music on innertune while spotube was already playing.

**Comment by KRTirtho** [comment]
I can reproduce this issue. But only the first (without any audio interruptions) when user plays a YouTube video, the music pauses. It doesn't work after that.
