### ISSUE TITLE
[Feature] progress bar while in playlist view

### ISSUE THREAD

**Issue by moisestohias** [KRTirtho/spotube#210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of the Feature

UI Improvements

### Credits

no one yet

### Pain

why hide the progress bar while in playlist view

### Suggested Solution

display the progress bar while in playlist view winodw

**Comment by KRTirtho** [comment]
After v3 we made the bottom bar and player permanent. So your issue is fixed
