### ISSUE TITLE
INPUT VOLUME INSIDE APP

### ISSUE THREAD

**Issue by AdityaUniyal5678** [KRTirtho/spotube#2101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

If you use extended layout and change inner voice settings of spotube in android and then go to compact it remains the same .

### Suggested solution

Either the voice settings should reset again in compact mode or there should be option to change it in compact mode too .

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
No, this is intentional.
You can adjust the app volume by expanding the `bottom player` in `compact mode`. The volume slider is available in the very bottom of the Player view
