### ISSUE TITLE
Playlist Folders and Sub-folders.

### ISSUE THREAD

**Issue by Pseudo-Sage** [KRTirtho/spotube#2102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

This issue has been raised before but there was no response, it was from some other user, that was **issue#862**. It is sometimes a _"pain"_ to find the right song from huge list of liked list so I generally organize them in playlists, but some playlist have similar features and I have lot of playlists (at least for me it's a lot). It becomes **tiresome to and find the right playlist(s)**.

### Suggested solution

 **So it will be of really help and could also **_"enhance"_** this applications "ease of access" to implement a feature to make folders and sub-folders for playlist.** Like if I liked some Japanese songs, I would make a folder for "Japanese Songs", after sometime I would find some songs to be different from others and I would organize them as "Japanese Pop", "Japanese Rock". I generally keep track of Anime OSTs for different series, so I would like to keep separate playlist for separate series or group of series. **It would also be better if you could sync with our Spotify folders, and keep a feature to search a song inside a folder of playlists.**

### Useful resources

I would highly suggest to see how the **Spotify folder system works**. It is the only thing that keeps me using it more than I should when I got this good of an app.

### Additional information

I hope there would be no problem as **this issue was raised by an user,** and for that reason this form will be marked **_duplicate._** But it would actually help, and as the issue for enhancement was raised way back in Nov 5, 2023 and there were no responses. So I decided to write this. **Thank You.**

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
Comment on the already existing issues. There's no need to open new issues.
From next time, I'll start banning people that intentionally creates duplicate issues to gain attention.
You can simply mention me in the originally. Opening a duplicate issue helps no body
