### ISSUE TITLE
Mac app doesn't open

### ISSUE THREAD

**Issue by skharola** [KRTirtho/spotube#2103]
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

Mac App does not open after download , “spotube” can’t be opened because Apple cannot check it for malicious software.

### Expected Behavior

App showed open Home Page when opened on Mac

### Logs

<details>
<summary>Logs</summary>

```
<Replace this line by pasting your logs here>
```
</details>

### Operating System

macOS , M1 Chip

### Installation source

Website (spotube.krtirtho.dev), GitHub Releases (Binary)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by skharola** [comment]
<img width="256" alt="Screenshot 2024-12-02 at 1 06 32 PM" src="https://github.com/user-attachments/assets/c319429b-3f40-4db5-a366-31d719e295fc">

**Comment by pkpowell** [comment]
xattr -rc /Applications/spotube.app

**Comment by locochen** [comment]
same issue
<img width="262" alt="image" src="https://github.com/user-attachments/assets/66b49c3f-f8fe-427c-ac85-4e2404e11692">

**Comment by locochen** [comment]
<img width="231" alt="image" src="https://github.com/user-attachments/assets/cce88c79-00f5-40fa-a5a7-c14e536ecc70">

**Comment by locochen** [comment]
<img width="231" alt="image" src="https://github.com/user-attachments/assets/c6072419-933f-4d4c-b9c4-077886bc88d4">

**Comment by KRTirtho** [comment]
This is a macos related issue. After opening Spotube for the first time, go to "System Settings" > "Privacy & Security" > "Security"
From there click on "Open anyway" button with ⚠️.

This is a one time action. From next time, Spotube will open without this
