### ISSUE TITLE
Renforcement idée

### ISSUE THREAD

**Issue by Kafos1** [KRTirtho/spotube#2127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

Bonjour je me demandais si il était possible de pouvoir mettre c'est fichier locaux sur l'application spotube comme le propose déjà l'application Spotify pour pouvoir profiter d'une meilleure expérience car parfois l'application n'a pas toute les musiques...

### Suggested solution

Du coup rajouter cette option bien sûr que si le code peut permettre un tel changement 

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by NilsMT** [comment]
Bonjour,

Sur l'application modile c'est possible en allant dans bibliothèque puis dans Local

Pour ce qui est de la version PC je ne sais pas (elle ne marche pas pour moi 😅)

![image](https://github.com/user-attachments/assets/6c87088c-91e7-4628-b00e-7a56d301209f)
