### ISSUE TITLE
Spotify Login

### ISSUE THREAD

**Issue by an-urbanmonk** [KRTirtho/spotube#2146]
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

Spotify Login was not working. When I logged out and Opened for Login it shows "No Healthy Upstream"
And couldn't go further. Please Help 
![Screenshot_2024-12-16-14-18-24-220_oss krtirtho spotube](https://github.com/user-attachments/assets/82bb45ca-8cb2-44f8-8245-5f311e832da5)

### Expected Behavior

Should login into Spotify to bring my playlist date back to Spotube

### Steps to reproduce

Logged Off.
Uninstalled and Installed Latest Version
Uninstalled Spotify 

### Logs

<details>
<summary>Logs</summary>

```
<Replace this line by pasting your logs here>
```
</details>

### Operating System

Android

### Installation source

Website (spotube.krtirtho.dev)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by Prem189** [comment]
![Screenshot_20241216_142615_Spotube](https://github.com/user-attachments/assets/010773c9-d33e-45fc-85fa-a25486fd2b55)
I opened my spotube to listen some songs but a message pop up on screen says error authentication 504
Then i unstalled the app and reinstall it and trying to connect spotube with tha spotify but this black screen appears and i can't do anything 
I CAN'T USE SPOTUBE..
PLEASE GIVE ME A SOLITION OR SOLVE THIS PROBLEM

**Comment by niontrix** [comment]
Seems the URL is down: https://accounts.spotify.com/api/token

**Comment by an-urbanmonk** [comment]
I'm new to this. So how to change that URL to actual login URL for Spotube using Spotify 

> Seems the URL is down: https://accounts.spotify.com/api/token

**Comment by an-urbanmonk** [comment]
![image](https://github.com/user-attachments/assets/48ee854f-9659-4533-b40b-f1d610670d83)
This was the login information for me before logging out of Spotube. Error Authentication was triggered so I logged out. Before logging out this was the user information. I'm guessing it was not thisbefore.

**Comment by dzackyluc** [comment]
i think its bug from spotify API because the https://open.spotify.com/ was not working too, its working now but you need to always retry when the problem occurs

**Comment by an-urbanmonk** [comment]
So, Do you mean this was because the Spotify server was down or something. Yes I too found it working now. Man. Got Used to Spotube irrespective of its delay. Now I dont like Spotify  due to mingle of podcasts and music. Thank God It got sorted now. Thank y'all.
