### ISSUE TITLE
Transition!

### ISSUE THREAD

**Issue by Bleach2021** [KRTirtho/spotube#2170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

Nothing

### Suggested solution

Please could you add transition, it was one of Spotify's best features, it would be really cool!  (I translated it on Google Translate, my English isn't that good)

### Useful resources

Nothing 

### Additional information

Nothing 

### Self grab

- [X] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
Duplicate of #783
