### ISSUE TITLE
New Alexa Skill??

### ISSUE THREAD

**Issue by gorben-zanu** [KRTirtho/spotube#2176]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Pain

I didn't know where to put this so I put here, but I was wondering if you could turn this into an Alexa skill so that we don't have to listen to ads (and on my Alexa when I tell her, Alexa, play highway to hell by AC/DC. She says Play highway to hell radio on Spotify. So I was wondering if this could fix that)

### Suggested solution

Please do

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
Sorry we don't create 3rd party plugins or extensions for apps here
