### ISSUE TITLE
Bug na tela do aplicativo 

### ISSUE THREAD

**Issue by Mellesxep** [KRTirtho/spotube#2177]
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

Eu abro o aplicativo normalmente, coloco a música e até aí tudo bem. Porém... quando eu saio por um estante do aplicativo e volto, ele fica com a tela preta e não volta, com isso, sou obrigado a fechar e abrir novamente. É algo besta mas que pode estar atrapalhando algumas pessoas 

### Expected Behavior

Espero resolverem. Provavelmente é algum problema sobre a execução em segundo plano do aplicativo, talvez esteja meio que fechando o aplicativo mas ainda continua a tocar e buga na hora de voltar

### Steps to reproduce

1 - o aplicativo 
2 - dei play na música 
3 - saí para fazer outra coisa (fora do celular)
4 - voltei para mudar a música 
5 - tela preta 

### Logs

<details>
<summary>Logs</summary>

```
<Replace this line by pasting your logs here>
```
</details>

### Operating System

Android

### Spotube version

3.9.0

### Installation source

Website (spotube.krtirtho.dev)

### Additional information

Smartphone: moto G20 com Android 11 GSI modificada

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
Please resubmit this issue in English
