### ISSUE TITLE
[Bug] Font on linux is tiny and  has no way to increase size.

### ISSUE THREAD

**Issue by famewolf** [KRTirtho/spotube#221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I was uncertain whether this fell under bug, feature request or ask a question so apoligize in advance if I picked wrong.   On Manjaro the desktop is sized to be readable for all other apps however my primary desktop is KDE so I'm guessing perhaps it's getting it's font requirements from the gnome/gtk side of things because the font is to small for my eyes.  I don't have the best vision so it might be fine for others but I typically have to kick sizes up a notch.   I'd like a way to increase font in the app for text so I'm not having to try to change it for ALL gtk apps.

Either way, the app is fantastic and I'm amazed at how you went about this.  I wish there was a comparable app for pandora.  (I'm not requesting this...just emphasizing how much I like spotube).

### Expected Behavior

Ability to adjust font size in the app up or down by x percent ie 125% of normal.

### Operating System

Linux

### Operating System Version

Manjaro

### Installation Source

Arch User Repository (AUR)

**Comment by KRTirtho** [comment]
Hey sorry for the problem. It's better in the latest release. Please upgrade
