### ISSUE TITLE
[Feature] Blacklist for Artist, Song, Genre, Profanity

### ISSUE THREAD

**Issue by famewolf** [KRTirtho/spotube#222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of the Feature

Unable to categorize

### Credits

Myself

### Pain

There are certain artists (Nicki Minaj for example) I would prefer NEVER to hear even if they exist in a playlist I select such as top 40 usa.  There are certain genre's such as RAP I'd prefer to skip altogether ESPECIALLY since they seem to show up in genre's such as Pop.   Within those there are certain songs by Artists I may not like due to annoying sounds in the song or lyrics containing profanity.   I currently don't see a method to bypass explicit lyrics.

### Suggested Solution

Allow blacklists within Genre, Artist, Song Name and Explicit Content.

### Useful resources/references

https://www.frontgatemedia.com/a-list-of-723-bad-words-to-blacklist-and-how-to-use-facebooks-moderation-tool/
https://www.freewebheaders.com/full-list-of-bad-words-banned-by-google/
https://github.com/israelhudson/keyboard_blacklist_flutter

**Comment by KRTirtho** [comment]
This feature is now available from Spotube v2.7.0

**Comment by BoostCookie** [comment]
Does this feature still work? I'm on version 3.6.0 and all my searches in the blacklist come up empty.

**Comment by KRTirtho** [comment]
You've first blacklist songs/artists. Then it'll show up in the Blacklists page.

**Comment by BoostCookie** [comment]
Ah, I need to blacklist the artists at their respective pages. Thanks!
