### ISSUE TITLE
Can't play any song on MacOS

### ISSUE THREAD

**Issue by nank1ro** [KRTirtho/spotube#23]
**Describe the bug**
Cannot play any song on MacOS

**To Reproduce**
1. Open app
2. Click on any song
3. It never starts

**Expected behavior**
The song begins

**Installation Source/Method**
- Compiled from source with `flutter run -d macos`

**Desktop (please complete the following information):**
 - OS: MacOS Monterey  (Intel)
 - Version: 12.1

**Additional context**
Error logs:
```sh
flutter: [Player._playTrack()] (-1002) unsupported URL
flutter: #0      AudioPlayer._load (package:just_audio/just_audio.dart:778:9)
<asynchronous suspension>
#1      AudioPlayer._setPlatformActive.setPlatform (package:just_audio/just_audio.dart:1346:28)
<asynchronous suspension>

flutter: [Player._playTrack()] (-1002) unsupported URL
flutter: #0      AudioPlayer._load (package:just_audio/just_audio.dart:778:9)
<asynchronous suspension>
#1      AudioPlayer._setPlatformActive.setPlatform (package:just_audio/just_audio.dart:1346:28)
<asynchronous suspension>
#2      AudioPlayer.play (package:just_audio/just_audio.dart:852:28)
<asynchronous suspension>
#3      _PlayerState.build.<anonymous closure>.<anonymous closure> (package:spotube/components/Player/Player.dart:266:25)
<asynchronous suspension>
#4      _PlayerControlsState._playOrPause (package:spotube/components/Player/PlayerControls.dart:54:51)
<asynchronous suspension>

flutter: [PlayerControls.onPlay()] MissingPluginException(No implementation found for method play on channel com.ryanheise.just_audio.methods.0da27819-4fea-44be-9760-3ab4d0a51324)
flutter: #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
<asynchronous suspension>
#1      MethodChannelAudioPlayer.play (package:just_audio_platform_interface/method_channel_just_audio.dart:56:34)
<asynchronous suspension>
#2      AudioPlayer._sendPlayRequest (package:just_audio/just_audio.dart:890:7)
<asynchronous suspension>
```

**Comment by KRTirtho** [comment]
It says the `just_audio_macos` native plugin is missing
I guess the flutter pub dependencies weren't resolved correctly. Try running:
```bash
$ flutter clean
$ flutter pub get
$ flutter run -d macos
```

**Comment by nank1ro** [comment]
Tried, same error:
```sh
flutter: [Player._playTrack()] (-1002) unsupported URL
flutter: #0      AudioPlayer._load (package:just_audio/just_audio.dart:778:9)
<asynchronous suspension>
#1      AudioPlayer._setPlatformActive.setPlatform (package:just_audio/just_audio.dart:1346:28)
<asynchronous suspension>
```

**Comment by KRTirtho** [comment]
Thanks. And that's seems to be ok since the currentTrack isn't yet converted into a YoutubeTrack. Can you debug this line & see if the `ytTrack.uri` contains a valid URL string?

https://github.com/KRTirtho/spotube/blob/cb1237633a51b17000d373e39301df15c2dc5e01/lib/components/Player/Player.dart#L159

**Comment by nank1ro** [comment]
The app crashes on this method:
```
await player
              .setAudioSource(
            AudioSource.uri(Uri.parse(currentTrack.uri!)),
            preload: true,
          )
```

I've added a `catchError` and the error is `PlayerException ((-1002) unsupported URL)`

**Comment by KRTirtho** [comment]
I've made some changes there try pulling the new modifications & see if works now

**Comment by nank1ro** [comment]
Now I'm getting a crash here
https://github.com/KRTirtho/spotube/blob/master/lib/components/Player/Player.dart#L160

with error:
```sh
[Player._playTrack()] (-11828) Cannot Open
```

**Comment by KRTirtho** [comment]
How does the `ytTrack.uri` look. Is it a valid URL string? I guess it's the `AVFoundation` framework of Mac OS that isn't recognizing the URL as a valid URL because there's no mimetype in the headers

**Comment by nank1ro** [comment]
I've tried to add `.mp3` but th error is the same.
I also tried to open the URL in the browser but I get this error: `Access to rr2---sn-hpa7zned.googlevideo.com was denied`

**Comment by KRTirtho** [comment]
Can you provide me the URL you're getting in `ytTrack.uri`

**Comment by nank1ro** [comment]
If I go with the browser without the .mp3 added I can listen to the song.

**Comment by KRTirtho** [comment]
I found out the actual issue is Mac OS & iOS CoreAudio not supporting WebMedia codec aka `webm`,  `weba` & `webp` in previous versions. Spotube was pulling the `audio/webm` audio file to get best possible bitrate but it doesn't work on all Macs currently

I've updated the code to pull only `audio/mp4` audio in Macs which comes with a downside of having 140 kbps bitrate instead 251 kbps of the `audio/webm`

Please, pull from git & see if audio works now or not

**Comment by nank1ro** [comment]
Now it works! Amazing work  💪🥳
Feel free to close this issue cause has been fixed

**Comment by KRTirtho** [comment]
Glad it worked

**Comment by PranavBhattarai** [comment]
https://github.com/Taiko2k/TauonMusicBox/issues/717#issuecomment-1219184138
@KRTirtho 
Am I curious:
1. Are we downloading the songs in " DASH MP4's" codec and renaming the file to .mp3 because of this issue?
2. If so, then why are doing it the wrong way to 'get the things' done?!
