### ISSUE TITLE
Garbled language on Mac OS 10.12.6

### ISSUE THREAD

**Issue by mattdrepo** [KRTirtho/spotube#241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The default language seems to be overridden and Cyrillic or some form of incomprehensible language

### Expected Behavior

English

### Spotube Version

Latest

### Operating System

Mac OS

### Operating System Version

10.12.6

### Installation Source

Github Release (Binary)

### Additional information

NA

**Comment by mattdrepo** [comment]
Also the same on the latest nightly

**Comment by mattdrepo** [comment]
![garbled](https://user-images.githubusercontent.com/69482750/192513365-51486fe9-f791-4c21-bc5f-54aa547c0c46.png)

**Comment by karniv00l** [comment]
This is a known issue for macOS older than 10.13

**Comment by mattdrepo** [comment]
can it be resolved?

**Comment by mattdrepo** [comment]
https://github.com/authpass/authpass/blob/6a835981e32b1e7bb17a59dea1c7cd59cb05ada8/authpass/lib/theme.dart#L86-L102

or set minimal version so I avoid the app on Mac OS 10.12

**Comment by mattdrepo** [comment]
This has been resolved before on other flutter apps (authpass) which target Mac OS with versions lower than 10.13.  Including a few fonts in the build and dynamically linking to them.

https://github.com/authpass/authpass/blob/6a835981e32b1e7bb17a59dea1c7cd59cb05ada8/authpass/lib/theme.dart#L86-L102

**Comment by karniv00l** [comment]
As of Flutter 3.7, macOS 10.14 is a new minimum version: https://medium.com/flutter/whats-new-in-flutter-3-7-38cbea71133c

**Comment by KRTirtho** [comment]
Closing this as this as become obsolete. Please upgrade to macOS 10.14 to use Spotube as of new Flutter requirement
