### ISSUE TITLE
No way to fix a song playing an incorrect audio / Song listing is different to what is played (Android)

### ISSUE THREAD

**Issue by Fairweather-Furry** [KRTirtho/spotube#244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When testing this app, I tried out a playlist of the LittleBigPlanet's OST, and one of the songs [Left Bank Two (Vision on Gallery Theme) By Wayne Hill] ( https://www.youtube.com/watch?v=8wgPl04pgq8 ) brings up some random video's audio (Which I figured out is here: https://www.youtube.com/watch?v=JqPYEwfz0Fk ), with no way to point the song on Spotube to the correct YouTube video individually. For some reason, this song also pulls a wrong song when using the other algorithms, so changing from the default algorithm doesn't work here. This song is on Spotify correctly.

### Expected Behavior

If a song is found to be pulling from the wrong YouTube video, there should be some way to direct Spotube to the correct song link, assuming none of the algorithms built in can find the correct song.

### Steps To Reproduce

1. Find a song
2. Play song
3. Figure out that song is actually playing a low quality top 10 clickbait video
4. Attempt changing algorithm to fix it
5. Find out some other song pops up
6. Suffer

### Spotube Version

2.4.1

### Operating System

Android

### Operating System Version

Android 11

### Installation Source

F-Droid (Android)

### Additional information

I'm aware of the ability to change the algorithm in the settings and did change it to every option and tried every option, none of them bring up the correct song.

**Comment by 256shadesofgrey** [comment]
I can confirm this is the case. Trying to play the original version of P.O.D. - Alive plays some other song. The accoustic version seems to be played correctly. And that is regardless of which entry in the search results I pick.

This is also reflected by the length of the currently played song not matching the length displayed for it when looking at the playlist. So some of the bug reports in regard to song length might have the same cause.

**Comment by IntoTheVoid-900** [comment]
@KRTirtho I am also experiencing this behaviour on Windows 11 for [White & Nerdy](https://www.youtube.com/watch?v=N9qYF9DZPdw). It is playing [Ridin'](https://www.youtube.com/watch?v=CtwJvgPJ9xw) (the song this is a parody of).

**Comment by waffleboi9000** [comment]
Same thing here for [Azari - Who?](https://youtu.be/8JXiXt0D6tw) with any of the 3 search algos available on V2.6.0

**Comment by KRTirtho** [comment]
There's now a way to change the YouTube source track in Spotube v2.6.0. Check this discussion to find answers: https://github.com/KRTirtho/spotube/discussions/352
