### ISSUE TITLE
[Feature] Add backwards integration with spotify/youtube in the same time

### ISSUE THREAD

**Issue by MrCheatEugene** [KRTirtho/spotube#245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of the Feature

Unable to categorize

### Credits

My pain

### Pain

Hi there. I love listening to music. Mostly I do this using Youtube, but and the choice is not bad. 
But, sometimes I use spotify. And it also has a large choice of songs, Big issue here that spotify does not have some songs, or bans them for whatever reason.
For example, "Your love is my drug, 8 bit slowed remix." It's not available in Spotify currently, although I have it saved in Liked songs. And maybe after a year, spotify will unban this song. But, MAYBE.
On youtube it is available all time: https://www.youtube.com/watch?v=9lY7WQzydp4

And, some songs on Spotify don't exist on youtube yet. Example - "I don't want it by Crawlers".
It exists on spotify as an **exclusive**, and in fact, it is promoted that it exists ONLY on spotify!
And that sucks, I can't listen to that song using youtube! It doesn't exist. And these songs wouldn't play in spotube as well.

Also, some songs exist on YouTube, but not in spotify.
For example: Inabakumori - Secret Elementary School Student. It exists on Youtube, but not in Spotify(or, maybe I searched bad. At least, It didn't come up when I searched it on English, when YouTube perfrectly understood me.)

### Suggested Solution

Solution here is to not only search in spotify, but in YouTube. If we already search&play music from Youtube, then why we can't show results not only from Spotify, but also from YouTube? And also play music from Spotify's servers, if it's not available in YouTube. 

### Useful resources/references

To search YouTube without the data API, you can search in Google, and then grab link elements, and HREF attribute from it.
I used that technique a while ago, here's my PHP script, maybe it will help. I didn't test it from the past year, and Google has changed a lot, so it might not work without a few changes in the HTML parser. 

https://yaso.su/icfqiuMd

**Comment by KRTirtho** [comment]
Sorry this is strictly a Spotify client. So we only use Spotify API to provide the track details and users can use Spotify account. We don't have any plan add YouTube API support.
YouTube is only used as a audio source for Spotube as Spotify doesn't provide the music itself

**Comment by MrCheatEugene** [comment]
and you only answered it 2 years later, thank you for answering, but it's a bit late :)

**Comment by KRTirtho** [comment]
Lol forgive me. This issue was burried down thousands of other issues so I kind of missed it.
Hope you're enjoying spotube 😉
