### ISSUE TITLE
[Feature] Sorting options in the local section for Android

### ISSUE THREAD

**Issue by RafeeDaBoy** [KRTirtho/spotube#246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of the Feature

UI Improvements

### Credits

Idea inspired from https://github.com/Sangwan5688/BlackHole/issues

### Pain

In the "Local" section songs are listed by no specific order making it hard to navigate between certain artists, albums, etc.

### Suggested Solution

In the "Local" section where downloads are shown sorting by Artists/Albums/Genre, etc would be really useful and helpful.

### Useful resources/references

How the downloaded songs are handled in https://github.com/Sangwan5688/BlackHole/issues
![Screenshot_2022-09-30-16-31-21-30_a2df05e64545de9e48d383611b669e6e](https://user-images.githubusercontent.com/69535896/193251945-82d9479c-2229-4583-9816-0fc359deb760.jpg)

**Comment by KRTirtho** [comment]
Available from latest v2.5.0
