### ISSUE TITLE
[Bug] Volume slider not working

### ISSUE THREAD

**Issue by koelopog16** [KRTirtho/spotube#250]
### Is there an existing issue for this?

- [X] #252

### Current Behavior

So i was trying lower down the volume of the song i was listening to but when i tried to lower down it, it dosent work for some reason, im in Windows 10 and this happens to me.

### Expected Behavior

It dosent lower down the volume of the music that im listening to.

### Spotube Version

2.4.1

### Operating System

Windows

### Operating System Version

Windows 10

### Installation Source

Official Website (spotube.netlify.app)

**Comment by KRTirtho** [comment]
Can you try installing the latest nightly version and see if this issue persists?

**Comment by KRTirtho** [comment]
Closing for stale
