### ISSUE TITLE
[Feature] Have in the settings the possibility to choose automatically Yes or No for the "Do you want to replace the already downloaded track?"

### ISSUE THREAD

**Issue by Greggggggggggg** [KRTirtho/spotube#253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of the Feature

UI Improvements, Logical Improvements

### Credits

Myself

### Pain

I downloaded the songs from the playlist Liked Tracks, but I quit before the download was complete. I don't know which one didn't download, so I have to re-download everything, and click "No" several times to the question "Do you want to replace the already downloaded track?".

### Suggested Solution

Add the option in the settings to automatically choose "Yes" or "No" all the time for the "Do you want to replace the already downloaded track?"

**Comment by KRTirtho** [comment]
Available in the latest v2.5.0
