### ISSUE TITLE
[Bug] Cannot add Spotify credentials on Flatpak  

### ISSUE THREAD

**Issue by jarkkosuominen** [KRTirtho/spotube#254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Cannot add Spotify credentials on Flaptak version. The submit button doesn't do anything and it doesn't create output on console.

### Expected Behavior

Login with Spotify credentials.

### Steps To Reproduce

1. `flatpak install com.github.KRTirtho.Spotube` 
2. `flatpak run com.github.KRTirtho.Spotube -v`

### Spotube Version

2.4.1

### Operating System

Linux

### Linux Distribution (if applicable)

Gentoo

### Operating System Version

-

### Installation Source

Flathub (Flatpak)

**Comment by KRTirtho** [comment]
you're probably missing [`xdg-desktop-portal`](https://github.com/flatpak/xdg-desktop-portal)

**Comment by jarkkosuominen** [comment]
I have `xdg-desktop-portal` version 1.14.6 installed

**Comment by KRTirtho** [comment]
What DE you're using?

**Comment by jarkkosuominen** [comment]
I am using [Awesome window manager](https://github.com/awesomeWM/awesome)

**Comment by KRTirtho** [comment]
You don't have anything specific to your WM like xdg-desktop-portal-gtk/xdg-desktop-portal-kde/xdg-desktop-portal-gnome?

**Comment by jarkkosuominen** [comment]
No. I tested it with wayland as well but the problem persists. 
The available `xdg-desktop-portal`s are the following:

```
*  gui-libs/xdg-desktop-portal-lxqt
      Latest version available: 0.2.0
      Latest version installed: [ Not Installed ]
      Size of files: 16 KiB
      Homepage:      https://lxqt-project.org/
      Description:   Backend implementation for xdg-desktop-portal using Qt/KF5/libfm-qt
      License:       LGPL-2.1

*  gui-libs/xdg-desktop-portal-wlr
      Latest version available: 0.5.0
      Latest version installed: 0.5.0
      Size of files: 31 KiB
      Homepage:      https://github.com/emersion/xdg-desktop-portal-wlr
      Description:   xdg-desktop-portal backend for wlroots
      License:       MIT

*  kde-plasma/xdg-desktop-portal-kde
      Latest version available: 5.25.5
      Latest version installed: [ Not Installed ]
      Size of files: 103 KiB
      Homepage:      https://kde.org/plasma-desktop
      Description:   Backend implementation for xdg-desktop-portal that is using Qt/KDE Frameworks
      License:       LGPL-2+

*  sys-apps/xdg-desktop-portal
      Latest version available: 1.14.6
      Latest version installed: 1.14.6
      Size of files: 504 KiB
      Homepage:      https://flatpak.org/ https://github.com/flatpak/xdg-desktop-portal
      Description:   Desktop integration portal
      License:       LGPL-2.1

*  sys-apps/xdg-desktop-portal-gnome
      Latest version available: 42.3
      Latest version installed: [ Not Installed ]
      Size of files: 117 KiB
      Homepage:      https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome
      Description:   Backend implementation for xdg-desktop-portal using GNOME
      License:       LGPL-2.1

*  sys-apps/xdg-desktop-portal-gtk
      Latest version available: 1.14.0
      Latest version installed: 1.14.0
      Size of files: 373 KiB
      Homepage:      https://flatpak.org/ https://github.com/flatpak/xdg-desktop-portal-gtk
      Description:   Backend implementation for xdg-desktop-portal using GTK+
      License:       LGPL-2.1
```
I'm little bit busy at the moment so can't debug much more at the moment. I will research more after few days.

**Comment by KRTirtho** [comment]
You'll need at least two of the desktop portal. The base `xdg-desktop-portal` and a `xdg-desktop-protal-*` and I don't know what is needed for Awesome WM

**Comment by KRTirtho** [comment]
The authentication flow has changed and this problem should never occur in Spotube

**Comment by KRTirtho** [comment]
So download latest v2.5.0

**Comment by jarkkosuominen** [comment]
Thanks, works wonders now!
