### ISSUE TITLE
[Feature] Disable Cover Rotation

### ISSUE THREAD

**Issue by reaseno** [KRTirtho/spotube#255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of the Feature

UX Improvements

### Credits

Me

### Pain

The cover rotation annoys me and can't find a setting to disable it.

### Suggested Solution

A setting to just show a normal non animated cover picture.

**Comment by KRTirtho** [comment]
It'll be available in the nightly release and soon in the stable
