### ISSUE TITLE
Random stopping and restarting.[Bug] <title>

### ISSUE THREAD

**Issue by poquito-1** [KRTirtho/spotube#258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Just downloaded and set up yesterday and assembled a small playlist (7 songs) . During play the music starts and stops randomly, this also happens if I trying playing individual songs from the general catalog. This is an Android device running A13. Battery was originally set to optimized but I changed it to unrestricted with no difference in performance and also tried clearing cache which also made no difference.

### Expected Behavior

I expected continuous play without stoppages.

### Spotube Version

version 2.4.1

### Operating System

Android

### Linux Distribution (if applicable)

N/A

### Operating System Version

A13

### Installation Source

F-Droid (Android)

**Comment by Erictheplague** [comment]
Update Spotube
