### ISSUE TITLE
Cannot login on spotify using facebook within spotube version 2.5

### ISSUE THREAD

**Issue by sibylmarziopulcini** [KRTirtho/spotube#267]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Since I have updated to version Spotube 2.5 I cannot login on spotify with facebook account (previously it worked fine) because when I open the link I get the following error:
"Logging in to Facebook from an embedded browser is disabled".
Previously it was working.

### Expected Behavior

Be able to use Softube with my spotify account, authenticated via facebook

### Steps To Reproduce

1. Android 12 - Spotube 2.5

### Spotube Version

v.2.5

### Operating System

Android

### Operating System Version

Android 12

### Installation Source

Official Website (spotube.netlify.app)

**Comment by KRTirtho** [comment]
Uh darn! I forgot to add the User-Agent headers =p

**Comment by Ramys** [comment]
could you compile and upload this update for download?
@KRTirtho

**Comment by sibylmarziopulcini** [comment]
I have tried to install latest nightly package but I cannot complete the procedure: the unzipped .apk seems invalid. Can you please check?

**Comment by Ramys** [comment]
I installed it normally, but when logging into the Spotify account, I am redirected to the Spotify browser and not to the Spotube application.
I can't search for a band or song.
My region is Brazil..

@KRTirtho

**Comment by KRTirtho** [comment]
> I have tried to install latest nightly package but I cannot complete the procedure: the unzipped .apk seems invalid. Can you please check?

@sibylmarziopulcini Try downloading again. You probably have poor network connection, that's why the downloaded file got corrupted maybe

**Comment by sibylmarziopulcini** [comment]
@KRTirtho, thank you. In the meanwhile I have tried the installation again: this time I have uninstalled 2.5.0 before installing the nigthly version and it worked. I could login with my facebook credentials. Only some minor issue remain: when I open it the app now keeps notifyng to update it to version 2.5.0. I simply ignore the message and everything works.

**Comment by KRTirtho** [comment]
It only happens to nightly versions
You can turn off "Checking Update" from the settings

**Comment by workelabdml** [comment]
hi, just to confirm the issue is the same, its not possible to login choosing facebook login

**Comment by sibylmarziopulcini** [comment]
@workelabdml try to uninstall stabile versione first. Download and install the nightly build and try again to login using  Facebook account. I confirm it worked for me.

**Comment by Gonza1706** [comment]
On windows version, when I try to login with facebook, I introduce my credentials but there's a message which says "you must login to continue", and I can't login for that reason
