### ISSUE TITLE
Connectivity Events are not responding.

### ISSUE THREAD

**Issue by deep1931** [KRTirtho/spotube#268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On switch of internet, player stopped after finishing the buffering content. But when again internet turned on, then it should resume playing, but nothing happened. 

### Expected Behavior

Player should respond to connectivity event, like internet is gone, player should pause, and on internet resume player should play from same position. 

### Steps To Reproduce

1. Install app from git
2. Play any playlist
3. Switch off internet
4. Player will pause
5. Switch on internet
6. Nothing will happen

### Spotube Version

v2.5.0

### Operating System

Android

### Operating System Version

Android 12, Android 10

### Installation Source

Github Release (Binary)

**Comment by zh54tg234f** [comment]
> On switch of internet

even with bad connectivity the app on android stuck for a long time and seems sadly very unresponsive. 
I'm using a VPN, please be so kind an improve buffering / loading ahead and quicker ui event switches

**Comment by KRTirtho** [comment]
It's been fixed in v3. Please check
