### ISSUE TITLE
I can't login to the apk.

### ISSUE THREAD

**Issue by Ramys** [KRTirtho/spotube#271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I downloaded all versions to see which one could get into the app.
1. I installed it first > https://github.com/KRTirtho/spotube/releases/tag/v2.5.0 (I can connect but it only has web player and account overview options)
2. Then I installed > https://nightly.link/KRTirtho/spotube/workflows/spotube-nightly/build/Spotube-Android-Bundle ( Same thing)
I can only connect perfectly in windows..
I followed several helps like (https://github.com/KRTirtho/spotube/issues/152) (https://github.com/KRTirtho/spotube/issues/56)

### Expected Behavior

I need help to log into the account.

### Steps To Reproduce

1. Go to 'Login to Spotify'
2. Insert credentials
3. When I click on the web player it does not redirect to the browser

### Spotube Version

v2.5.0 

### Operating System

Android

### Operating System Version

Android 8.1

### Installation Source

Official Website (spotube.netlify.app), Github Actions (Nightly Binary)

### Additional information

I would like a new step by step to solve this problem.

Brazil region.

**Comment by Vitalya-code** [comment]
I have this error too :(

**Comment by KRTirtho** [comment]
Clear Spotube app and try logging again

**Comment by Ramys** [comment]
@KRTirtho 
Same thing
https://ibb.co/GCxc2SP

**Comment by Vitalya-code** [comment]
> Clear Spotube app data and try logging again

i tried but it doesn't work

**Comment by KRTirtho** [comment]
Can you guys do the following:
- go to [accounts.spotify.com](https://accounts.spotify.com) in browser
- login there
- After login, copy the URL and comment it here

**Comment by Ramys** [comment]
@KRTirtho 
https://accounts.spotify.com/pt-BR/status

**Comment by KRTirtho** [comment]
That's why. The regex for validating the URL only validates 2-3 letter Country Code. This one is joint ISO. So it fails to validate and redirect user
Don't worry I'll fix this asap

**Comment by Ramys** [comment]
Thank you in advance for your attention...your project is perfect and the best I've ever found.  Thank you very much!

**Comment by johnexu** [comment]
the best projet so far!

none compare!

we needed it!

Thank you!

**Comment by mart-ini** [comment]
I can't log in either.  I think I have the same problem.  In fedora flatpak it works perfectly and I love this app.  I look forward to the fix on android 👍🏻

**Comment by Olivermusico** [comment]
Same issue here, but... I removed data and cache and tried to log-in (the app goes to spotify login,  I logged successfully, but doesn't return to spotube... and appears like not logged) 
After restart the app appears logged... but  I can't search anything... 
And I can't connect the app with the credentials of developers page of spotify...
🤔

**Comment by Ramys** [comment]
This works perfectly now.
https://nightly.link/KRTirtho/spotube/workflows/spotube-nightly/build

https://github.com/KRTirtho/spotube/commit/0b79a1181c37cf06fbfa3bfb3854cfd47097016e#diff-7e1540655ab269a7566e46f25a64c9dd6d3a5f1123ec31e3685ecb20d4d1dd98

**Comment by Vitalya-code** [comment]
It's finally working!!!
Thanks you very much)
![Screenshot_20221023-194041_Quickstep.png](https://user-images.githubusercontent.com/58048618/197404536-0ccaf262-9e02-4c86-b11d-528f769c71d4.png)

**Comment by Ramys** [comment]
all bugs have been fixed..
@KRTirtho , thanks ..
Congratulations on the beautiful project.

**Comment by Ramys** [comment]
@KRTirtho , I found a small bug, the songs are not playing automatically, that is;  if you want to listen to an entire disc you will have to play the songs manually when it ends.

**Comment by KRTirtho** [comment]
@Ramys create a separate issue for this, filling required details. It'll help us investigate
