### ISSUE TITLE
Material You color theming, Android 13 monochrome icon and tablet support

### ISSUE THREAD

**Issue by jeffdumcum** [KRTirtho/spotube#272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Credits

Google, created Material You

### Pain

No good tablet support, no material you makes it look ugly :(

### Suggested Solution

Add material you and optimize for tablets

**Comment by RafeeDaBoy** [comment]
Have you tried out the extended layout?

**Comment by jeffdumcum** [comment]
Yes

**Comment by RaptaG** [comment]
Added in 3.0.0

**Comment by RokeJulianLockhart** [comment]
I've gotta say that I wouldn't consider this to be implemented. The icons in the toolbar are miniscule, as is the padding, and they're of a completely different icon set to the standard Material icons. If you compare Spotube to any Material 3 application, they shan't even look vaguely similar.
