### ISSUE TITLE
Remove Lyrics from bottom bar, add to now playing page

### ISSUE THREAD

**Issue by jeffdumcum** [KRTirtho/spotube#273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of the Feature

UI Improvements

### Credits

Me

### Pain

I dont like how it looks with the lyrics on the bottom bar, add to page saying what song is playing

### Suggested Solution

Switch lyrics button to now playing page

**Comment by KRTirtho** [comment]
Lyrics can be accessed via the PlayerView now (redirect to lyrics page), but the bottom bar lyrics tab will stay
