### ISSUE TITLE
Adaptive mode breaks on tablets

### ISSUE THREAD

**Issue by jeffdumcum** [KRTirtho/spotube#274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Just look at the photo.
![Screenshot_20221021-112925](https://user-images.githubusercontent.com/105110025/197244699-29c818dc-2d79-4d59-9865-f0c746eae1ca.jpg)
Logo looks broken

### Expected Behavior

Not broken on tablets

### Steps To Reproduce

1 get tablet
2 download app
3 open settings
4 set mode to adaptive

### Spotube Version

latest

### Operating System

Android

### Operating System Version

android 12

### Installation Source

F-Droid (Android)

**Comment by KRTirtho** [comment]
It has been fixed (I don't remember the version but anything after v3)
