### ISSUE TITLE
[Feature] [Android] widget

### ISSUE THREAD

**Issue by ildar** [KRTirtho/spotube#275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of the Feature

UI Improvements

### Pain

Having controls on the phone's Home screen

### Suggested Solution

Android widget

**Comment by KRTirtho** [comment]
[home_widget](https://pub.dev/packages/home_widget) plugin provides this ability for both iOS and Android. But it may take some time to implement it properly

**Comment by KingBarker** [comment]
I suggest downloading the "audio widget pack" app, it will automatically detect the app. 

You'll find the widget under "widget" after you get the pack.
Get it from gamedva for more skins.

**Comment by KRTirtho** [comment]
@ildar early Merry Christmas. Home widget is finally here

**Comment by ildar** [comment]
awesome!
Mary Xmas to you too! May God bless your kindness!
thanks a lot!
