### ISSUE TITLE
[Bug] Black screen that requires an app restart

### ISSUE THREAD

**Issue by Dwismas** [KRTirtho/spotube#279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Occasionally when I expand the music player, the screen goes black and prevents any input in the app. Pressing back returns to the home screen. Music playback is uninterrupted and plays through a playlist normally. I can still control playback with media controls. Returning to the app without killing it maintains the black screen.

### Expected Behavior

There should be no black screen and the expanded music player should show.

### Steps To Reproduce

1. Play a song
2. (Unknown in-between process)
3. Expand the music player
4. Black screen can appear instead.

### Spotube Version

2.5.0

### Operating System

Android

### Operating System Version

Android 12

### Installation Source

F-Droid (Android)

### Additional information

I am using the Galazy Z Fold 3 running One UI 4.1.1

**Comment by Dwismas** [comment]
I have used the application for a little bit longer, and it seems like I found the cause. The black screen issue seems to only occur when my Fold 3 is unfolded (in tablet mode) and in landscape orientation. The issue persists even when I change orientation and/or fold the phone.

**Comment by KRTirtho** [comment]
@Dwismas please verify if the issue still persists in v2.7.0 and let us know if it's fixed
Btw, 2.7.0 isn't available on f-droid, so please download it from the [website](https://spotube.netlify.app) or the [release](https://github.com/KRTirtho/spotube/release/latest) section

**Comment by RaptaG** [comment]
Fixed in 3.0.0
