### ISSUE TITLE
Pressing the spacebar while searching pauses/plays music

### ISSUE THREAD

**Issue by brandonnhem** [KRTirtho/spotube#28]
**Describe the bug**
When you search for a artist / song that contains a space, playback while resume or be paused.

**To Reproduce**
1. Play any song
2. Click on "Search"
3. Click on the search bar (the search bar is highlighted)
4. While the song is playing, type any artist / song that contains a space

**Expected behavior**
Pressing the spacebar while the search bar is focused should not interrupt the playback.

**Installation Source/Method**
https://github.com/KRTirtho/spotube/releases/download/v1.2.0/Spotube-windows-x86_64-setup.exe

**Desktop:**
 Windows 10

**Comment by KRTirtho** [comment]
Sorry for late response.
It is a known bug and I'm working on it to fix the bug

**Comment by KRTirtho** [comment]
This issue has been fixed in the latest release 2.3.0

**Close this issue if your requested feature/bug is implemented/fixed + released**
