### ISSUE TITLE
[Feature] Plugin for mopidy

### ISSUE THREAD

**Issue by Ilia1** [KRTirtho/spotube#289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of the Feature

Unable to categorize

### Credits

myself

### Pain

Mopidy already have plugin for spotify. Good think make plugin for spotube.

### Suggested Solution

Realize new plugin for mopidy

### Useful resources/references

https://docs.mopidy.com/en/latest/

**Comment by KRTirtho** [comment]
Sorry to say but it's unrelated to Spotube and you should ask for this in Mopidy's support center

**Comment by Ilia1** [comment]
OK, I found this https://github.com/natumbri/mopidy-spotitube

**Comment by KRTirtho** [comment]
Spotube is a spotify client (replacement for Electron based* Spotify desktop and mobile apps) and it has no connection with mopidy or mopidy-spotitube at all
As far as I know, mopidy is a music server. Where Spotube is a music streaming app that combines Spotify and YouTube APIs to stream music. So it has nothing to do with mopidy and so there's no reason on our behalf to create a mopidy plugin for Spotify
