### ISSUE TITLE
The spotube-bin on the aur doesn't work

### ISSUE THREAD

**Issue by Poseidon444** [KRTirtho/spotube#29]
**Describe the bug**
The spotube-bin on the aur does not work

**To Reproduce**
Steps to reproduce the behaviour:
On installing spotube and trying to launch it, you get /usr/bin/spotube not found.

**Expected behaviour**
The app to open

**Screenshots**
![image](https://user-images.githubusercontent.com/87462580/154856787-1d838b36-0e0f-4767-bba4-160d5a837475.png)

**Installation Source/Method**
- Package Manager: yay
- Community Repo: aur
- Binary Source: https://aur.archlinux.org/packages/spotube-bin

**Desktop (please complete the following information):**
 - OS:Arch
 - Version:probably the latest one

**Comment by KRTirtho** [comment]
The bug has been fixed. Reinstall the package to check if it works now

**Comment by Poseidon444** [comment]
Great. Thanks a lot, since the bug has been closed, I will be closing this issue.
