### ISSUE TITLE
[Bug] Token isn't automatically renewed

### ISSUE THREAD

**Issue by Cwpute** [KRTirtho/spotube#290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Music stops after around 30mn of using the app, you can't search or play any more music. The messahe belows shows vhen trying to search:
![Screenshot_20221031-181754_1](https://user-images.githubusercontent.com/80604512/199071338-65d6bff9-d60d-439e-be68-a5c80bde6a38.png)
Killing the app seems to resolve the issue for another 30mn until the problem comes up again.

### Expected Behavior

Should probably still play music ?

### Spotube Version

2.5.0

### Operating System

Android

### Operating System Version

Android 11

### Installation Source

F-Droid (Android)

**Comment by KRTirtho** [comment]
This was an issue that has been already fixed and available in the nightly channel

**Comment by Cwpute** [comment]
I'll be waiting for the official update to confirm the issue was fixed then :)
