### ISSUE TITLE
Youtube Music Api instead of Youtube Api 

### ISSUE THREAD

**Issue by Alliba** [KRTirtho/spotube#292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

First of all, a great app and thank you for your work but with me about Spotube often wrong songs are played or dur excerpts from a song.

### Expected Behavior

Would it be possible instead of using the Youtube Api to switch to Youtube Music Api to avoid such errors as Innertune and ViMusic do.

### Operating System

Android, Linux

### Operating System Version

Android 10

### Installation Source

Official Website (spotube.netlify.app), Github Release (Binary), F-Droid (Android)

**Comment by RaptaG** [comment]
@KRTirtho what's your opinion? Imo, this would help with my issue as well, since YT music has no non-music elements.

**Comment by yant0** [comment]
Would also help with loading songs too 👍

**Comment by Alliba** [comment]
With the function to select alternative title the error is almost solved, thanks for that but Spotube would have to remember the alternative title so that the next time you play the correct title is played and you do not have to select it again each time.

**Comment by KRTirtho** [comment]
> but Spotube would have to remember the alternative title so that the next time you play the correct title is played and you do not have to select it again each time.

It already does. You can try it out :wink:
