### ISSUE TITLE
Package your app with flutter_distributor.

### ISSUE THREAD

**Issue by lijy91** [KRTirtho/spotube#3]
[flutter_distributor](https://github.com/leanflutter/flutter_distributor) It is a packaging and publishing tool specially developed for flutter. Can it be used for packaging in this project?

**Comment by KRTirtho** [comment]
OMG, you're @lijy91. Huge fan sir!
Just the package I was looking for this long. Thank you so much for letting me know. I will integrate it with Spotube
But is there anyway to support AppImages, flatpak, .rpm, chocolatey & winget package formats too? It will make flutter_distributor more universal. It's feature request

**Comment by lijy91** [comment]
These will support in the future

**Comment by KRTirtho** [comment]
Waiting for it😃
