### ISSUE TITLE
[Bug] Entry point not found

### ISSUE THREAD

**Issue by regorxxx** [KRTirtho/spotube#302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Crash on startup

![image](https://user-images.githubusercontent.com/83307074/201205781-d701a8bc-98ee-4116-8e10-bbe441293587.png)

### Expected Behavior

.

### Steps To Reproduce

Win 7 x64
Install
Start

### Spotube Version

v2.5.0

### Operating System

Windows

### Operating System Version

Windows 7

### Installation Source

Official Website (spotube.netlify.app)

**Comment by KRTirtho** [comment]
Sorry, Windows 7 isn't supported
