### ISSUE TITLE
[Bug] Error type 'Null' is not a subtype of type 'Map<String, dynamic>'

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [KRTirtho/spotube#303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Whenever I open https://open.spotify.com/playlist/37i9dQZF1DX4JAvHpjipBk in spotube I get this error message. 
![Uploading image.png…]()

### Expected Behavior

Songs get displayed normally

### Steps To Reproduce

1. Go to Library
2. Select New Music Friday

### Spotube Version

2.5.0

### Operating System

Linux

### Linux Distribution (if applicable)

Gentoo

### Operating System Version

idk, it's gentoo

### Installation Source

Flathub (Flatpak)

### Additional information

Tried to re-login but did not work. Tested on android (11, infinix) and it does not work with same error message. 

PS: Release Radar does not play songs at all but it shows in the playlist.

**Comment by EsmailELBoBDev2** [comment]
It works now, out of nowhere so going to close this.

**Comment by vrotaru** [comment]
![image](https://github.com/KRTirtho/spotube/assets/246236/e390ba67-17f3-41d2-8e0b-21f7b74c459f)

It seem to have re-appeared, I've seen it 2 or 3 times before repoting.

Fedora 39 - Version 3.2.0

**Comment by EsmailELBoBDev2** [comment]
hmm, weird it works fine with me...do you want me to reopen the issue?

**Comment by vrotaru** [comment]
Most of the time is works fine for me too. As for re-opening it is up you.

Maybe, if some more reports of the same are coming in.
