### ISSUE TITLE
Lyrics Terrible

### ISSUE THREAD

**Issue by jeffdumcum** [KRTirtho/spotube#304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The lyrics are most times wrong, and on the 0.00001% percent of the times where it is kind of correct, the lyrics are unsynced

### Expected Behavior

The lyrics to be correct and synced

### Spotube Version

idk

### Operating System

Android

### Operating System Version

Android 12

### Installation Source

F-Droid (Android)

**Comment by XenHat** [comment]
Probably duplicate of #112 for the first part of the bug.

**Comment by KRTirtho** [comment]
Props to the awesome title :joy:
