### ISSUE TITLE
[Feature] Open in spotube instead of spotify

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [KRTirtho/spotube#307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of the Feature

UX Improvements

### Credits

Me

### Pain

I have spotube on phone (android) and when someone sends me spotify link, it opens in spotify app and it would be nice if spotube can catch the url and play it directly? and maybe the ability to search by spotify/yt URL too.

### Suggested Solution

Spotube opens when I click on spotify/yt music link

### Useful resources/references

I really have no idea :joy:

**Comment by KRTirtho** [comment]
That's not possible due to the protocol `spotify://` is a registered protocol and the `spotify.com` is a registered domain, only apps with allowed appIds can open those links

**Comment by EsmailELBoBDev2** [comment]
oh, i thought it's matter of if else statement. Will, thanks for the info :)

**Comment by KNIX3** [comment]
> 

Is this really true? I cannot speak for spotify links specifically but many open source apps are able to open urls from other official apps such as LibreTube, Musify, InnerTune for `youtube.com` and its link variants as well as every open source Twitter client I've used for `twitter.com` and its variants. Is there a difference between `spotify.com` and `twitter.com`?

**Comment by karniv00l** [comment]
@KRTirtho you should be able to register `spotify://` protocol for Spotube (see: https://pub.dev/packages/app_links).
However, there should be **only one app** that uses a given protocol (i.e. Spotify not installed).

I use Spotify, but I was able to switch apps in Firefox just for testing purposes:

<img width="407" alt="Screenshot 2023-07-24 at 09 25 37" src="https://github.com/KRTirtho/spotube/assets/3144291/636c72fe-cedd-470d-acaa-07d6b77dc3d1">

when you go to the `open.spotify.com/...` page, it opens the `spotube://...` url:

<img width="606" alt="Screenshot 2023-07-24 at 09 19 55" src="https://github.com/KRTirtho/spotube/assets/3144291/5f59f8a2-1025-4942-a569-41cc50500fc8">

**Comment by KRTirtho** [comment]
Never knew it even existed https://pub.dev/packages/app_links :sweat_smile:

**Comment by KRTirtho** [comment]
Linux is not supported by any of them :")

**Comment by KNIX3** [comment]
> Linux is not supported by any of them :")

 have heard you can basically get the same functionality on Linux by modifying the `.desktop` file, but on the note of Android specifically, it seems there is still an open issue ([#508](https://github.com/KRTirtho/spotube/issues/508)). Is this something you hope to implement in the future? I think many Android users would appreciate it. Not being able to just tap links my friends send me of their spotify playlists is a just bit frustrating for an otherwise amazing UX.

**Comment by selurvedu** [comment]
I would appreciate this feature on desktop.

**Comment by Rootkit-** [comment]
This would be very nice. If its made I'll make a redirect extension and give you guys the code.

**Comment by anarcat** [comment]
this would be a killer feature for anonymous users. as it is now, the app is not that useful for us as you can basically just browse suggested things... you can't search, you can't open existing pages / groups you know exist, etc...

**Comment by karniv00l** [comment]
> Linux is not supported by any of them :")

It's now supported in the newest version: https://github.com/llfbandit/app_links/issues/20

**Comment by KRTirtho** [comment]
Yes finally it can be implemented

**Comment by KRTirtho** [comment]
Anyone using Linux here, please test if it works for the platform. I am unable to test it for the platform.
Binary available in nightly or https://github.com/KRTirtho/spotube/actions/runs/7231912830

**Comment by crimsonduelist** [comment]
should this be working for setting alarms to open spotify?
