### ISSUE TITLE
Minimize to System Tray support

### ISSUE THREAD

**Issue by Mennaruuk** [KRTirtho/spotube#31]
**Is your feature request related to a problem? Please describe.**
Background playback will land spotube on Billboard Top 100!

**Describe the solution you'd like**
Take the example of [Dopamine](https://github.com/digimezzo/Dopamine). This is how they do it:

![image](https://user-images.githubusercontent.com/52135169/158748319-9df1414f-4510-4183-a2f0-58d949a8a050.png)

**Describe alternatives you've considered**
Resort to downloading music and playing them in Dopamine, or reverting back to good ol' Spotify.

**Additional context**
spotube is a really creative idea, props to you 🎉

**Comment by dag7dev** [comment]
Up!

**Comment by KRTirtho** [comment]
This is something that is now possible to implement

**Comment by RaptaG** [comment]
Added in 3.0.0

**Comment by Mennaruuk** [comment]
> Added in 3.0.0

THANK YOU! I REALLY APPRECIATE IT 😊
