### ISSUE TITLE
[Feature] When SponsorBlock is enabled and the parts are being skipped, cut the non-music things in the duration time & progress bar and recalculate the time from the part the music starts

### ISSUE THREAD

**Issue by RaptaG** [KRTirtho/spotube#312]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of the Feature

Logical Improvements, UX Improvements

### Credits

Me

### Pain

When I try to put a song from the beginning, the bar teleports to the actual musci, whihc is annoying

### Suggested Solution

cut the non-music things in the duration time & progress bar and recalculate the time from the part where the music starts

**Comment by KRTirtho** [comment]
It's doable, but would be unnecessarily complicated. Maybe an indicator that shows certain part is non-music part would do the job, just like the SponsorBlock browser extension

**Comment by RaptaG** [comment]
Would look better tho

**Comment by RaptaG** [comment]
Suspended by https://github.com/KRTirtho/spotube/commit/fb780da327a213d7a82cbc3b567ece858dc2f0e8
