### ISSUE TITLE
[Bug] Spotube acts and loads things way slower than Spotify

### ISSUE THREAD

**Issue by RaptaG** [KRTirtho/spotube#313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Spotube is slow comparing to Spotify

### Expected Behavior

Spotube being equally fast (or even faster) than Spotify

### Steps To Reproduce

1) Use Spotify
2) Then use Spotube

### Spotube Version

v2.5.0

### Operating System

Linux

### Linux Distribution (if applicable)

EndeavourOS (Arch Linux)

### Operating System Version

Kernel 6.0.8

### Installation Source

Arch User Repository (AUR)

**Comment by XenHat** [comment]
Also having this issue. First day of trying this application and that's a pretty big show-stopper for adoption when **every song** takes a good 30 seconds to load.

**Comment by Phil-hacker** [comment]
I have the same issue on android.

**Comment by demirdegerli** [comment]
Same issue on Android. But not on Flatpak on Fedora.

**Comment by RaptaG** [comment]
Less, faster and smoother animations would help

**Comment by senolfndk** [comment]
The application is very cumbersome, it is not stable, there are freezes and stutters, song transitions are very slow, sometimes it gets stuck, the play button is below, it needs to be average

**Comment by RaptaG** [comment]
Fixed in 3.0.0, lesgo!

**Comment by taw00** [comment]
v3.0.1, flathub, Fedora 37
Unusably slow. The Logs give me no clue.

**Comment by RaptaG** [comment]
> v3.0.1, flathub, Fedora 37
> Unusably slow. The Logs give me no clue.

Try fedora 38 first, then report back please

**Comment by demirdegerli** [comment]
> > v3.0.1, flathub, Fedora 37
> > Unusably slow. The Logs give me no clue.
> 
> Try fedora 38 first, then report back please

There is no visible performance boost between these two releases. Your request is unnecessary. The result will be same.

**Comment by Routhinator** [comment]
FWIW - Flathub version on Ubuntu 23.10 was also unusable and slow. I tried for a long while to figure out why. Then I downloaded the deb and everything was super fast. I have a feeling this has to do with the containment and access to the disk, but can't get enough logging out of the application to understand where it's slow.

But workaround of using the deb is fine for me. It's lightning fast now.

**Comment by taw00** [comment]
v3.4.1 ... Flatpak. Seems to be fine now.

**Comment by Biggamingmoment** [comment]
Completely unusable for me with both flatpak and the deb version. Takes insanely long to load any song and the UI itself runs at like 10fps.

**Comment by senolfndk** [comment]
> 4.0.0 çok yavaş ve gecikmeli. Daha hızlı ve akıcı olursa harika olur.

same problem

**Comment by je4npw** [comment]
4.0.0 Android too slow to load anything

**Comment by Mythses** [comment]
Same issue fedora 42
