### ISSUE TITLE
Google error 403 login

### ISSUE THREAD

**Issue by Shopimisrel** [KRTirtho/spotube#317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Google dont allow your app login to the spotipy account 
----------
You can’t sign in from this screen because this app doesn’t comply with Google’s secure browsers policy. If this app has a website, you can open a web browser and try signing in from there.

You can let the app developer know that this app doesn’t comply with Google’s secure browsers policy.
-----

### Expected Behavior

access_type: offline
response_type: code
state: AQAlPbFSejXZF6pmr2SXK1WKDv6g+fuF1phR/GyB274vH8n8NzZn6vm/QLL9EU3FM1H+YnWJJp5T2B1AxM5Zm/+Gw6VBGbIhVHS8+Up829asABOhOlcTQiv86S2tJ1a40GMvwQA0865bxkY0l5U=
redirect_uri: https://accounts.spotify.com/login/google/redirect
client_id: 1046568431490-ij1gi5shcp2gtorls09frkc56d4mjbe2.apps.googleusercontent.com
scope: https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email 

### Steps To Reproduce

1 run app
2 login with google account
3 error disallowed_useragent 403

### Spotube Version

2.5.0

### Operating System

Android

### Operating System Version

Android 10

### Installation Source

Official Website (spotube.netlify.app), F-Droid (Android)

**Comment by Ramys** [comment]
This...
https://nightly.link/KRTirtho/spotube/workflows/spotube-nightly/build

**Comment by Shopimisrel** [comment]
Works but asks for an update

**Comment by KRTirtho** [comment]
> Works but asks for an update

Just disable "Check for Updates" from the settings

**Comment by Shopimisrel** [comment]
> > Works but asks for an update
> 
> Just disable "Check for Updates" from the settings

ok thanks for your help

**Comment by RafeeDaBoy** [comment]
@Shopimisrel Please close the issue if it has been resolved
