### ISSUE TITLE
[Bug] <spotube linux based client and the missing stereo>

### ISSUE THREAD

**Issue by sleeplessaa** [KRTirtho/spotube#319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

spotube linux based client and the missing stereo for all streamed files.

ii  spotube                                2.5.0+15                                   amd64

From the downloaded track information: 
ffmpeg -i -> 
Duration: 00:05:20.41, start: 0.000000, bitrate: 130 kb/s
Stream #0:0(fra): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, **stereo**, fltp, 3 kb/s (default)

But definitely there is no stereo i.e. the both channels are the same.

The 'stereo issue' with the official spotify client for linux is not found.

Anyone detecting the same problem ? 

### Expected Behavior

stereo effect as original source

### Spotube Version

spotube                                2.5.0+15                                   amd64

### Operating System

Linux

### Linux Distribution (if applicable)

Debian

### Operating System Version

Debian GNU/Linux 11 \n \l

### Installation Source

Github Release (Binary)

**Comment by KRTirtho** [comment]
The audio is handled by gstreamer in Linux which outputs and supports multiple channeled audio. It seems to work fine
You can test with Charlie Puth's Left and Right track

**Comment by sleeplessaa** [comment]
So, can you hear the stereo output or spotube need some fix ?

**Comment by RaptaG** [comment]
Spotube doesn't support stereo audio right now.
