### ISSUE TITLE
Song Choice

### ISSUE THREAD

**Issue by Mennaruuk** [KRTirtho/spotube#32]
**Describe the bug**
Some songs are different from the ones in Spotify. It looks like spotube is fetching the top YouTube Music result, which sometimes can be different.

**To Reproduce**
1. Add a song like _Chasing Cars_ by Snow Patrol to your playlist
2. Play it

Around 2:09, Gary sings:

Let's waste time
Chasing cars
Around our heads.

Then the beat drops.

In reality, there is [another stanza](https://www.azlyrics.com/lyrics/snowpatrol/chasingcars.html) following that before the beat drops:

I need your grace
To remind me
To find my own

**Expected behavior**
I want spotube to get the original song. This means that most of the time, official music videos are not good for this because there is a whole bunch of other stuff added (it's a video). But even with audio, I feel like there should be preference given to channels that make lyrics videos such as 7clouds or DopeLyrics, they usually do a good job at cutting out all the fluff while maintaining integrity.

**Installation Source/Method**
- Package Manager: Binary
- Community Repo: Binary
- Binary Source: https://github.com/KRTirtho/spotube/releases/download/v1.2.0/Spotube-windows-x86_64-setup.exe

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: v1.2.0

**Additional context**
Thanks for your assistance.

**Comment by masasin** [comment]
Can confirm that this still happens. An example is most things by ARASHI. e.g. Hitomi no Naka no Galaxy gives you a fan doing her own cover.

**Comment by masasin** [comment]
It looks like the video fulfills all of the conditions. The official band's
title was in Japanese, and her video was the second result.

Is it possible to search for the original language? If I change my phone to
Japanese, Spotify shows me the song names in Japanese, but Spotube still
shows it in English (with that fan's rendition).

**Comment by meanssaddles** [comment]
is it possible to custom search parameter?

i want to strictly search by channel title, title, artist, duration (to match the spotify length) in that order

**Comment by koboingangkang** [comment]
> Spotube ranks tracks by track name, artist(s) name(s), author & views Ranking system is followed by:
> 
> * Checks if a youtube result contains the complete title (without artists) of the Spotify Track
> * Checks if the primary artist of Spotify is the author of the channel (not that important)
> * Checks if all the Spotify artist's name(s) are included in the Youtube result's title
> * Checks if the YouTube result is not a Live Video or a crop/cut from a Live Video
> 
> See if all the checks apply for the track you're reporting

if we are to play tracks from spotify (our playlist or not), why spotube has to research again? why doesn't it play from song(s) based on songs id directly? moreover, can we opt out youtube?

**Comment by KRTirtho** [comment]
After v2.6.0 users can override search result and can select from the range of results found initially. And it is known as _Alternative Track Sources_
The selected track source will be cached to disk, so next time listening to it will load the user overridden result as source
This should resolve the issue for now

**Comment by vehosah** [comment]
For me it still plays the audio from the video 🙁
