### ISSUE TITLE
[Feature] <Fast forward song to the specific verse when tapping it>

### ISSUE THREAD

**Issue by Rafee-M** [KRTirtho/spotube#329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of the Feature

UI Improvements

### Credits

N/A

### Pain

When tapping on a verse in the lyrics section, nothing happens.

### Suggested Solution

It'd be nice if the songs fast forwards to the verse when tapped on in the lyrics section.

**Comment by KRTirtho** [comment]
This is available now. Try the latest version

**Comment by Rafee-M** [comment]
Thanks!
