### ISSUE TITLE
Open in spotube From Spotify Web

### ISSUE THREAD

**Issue by Mennaruuk** [KRTirtho/spotube#33]
**Is your feature request related to a problem? Please describe.**
When I find a Spotify song or playlist on my browser, I can't redirect it to spotube.

**Describe the solution you'd like**
It would be so cool to have Chrome or Firefox tell me to open in spotube when it detects it's a Spotify song/playlist link.

**Describe alternatives you've considered**
Go back and play playlist in Spotify.

**Additional context**
Appreciate your help.

**Comment by Mennaruuk** [comment]
Yeah, I'm currently trying to do that. I found a [Tampermonkey script](https://pastebin.com/raw/Mz1qTFf9) that opens Spotify links in Spotify desktop client. However, what is needed is a URI protocol registered to the program. Spotify has done that already to their client, so when a browser calls spotify:the_link_to_playlist, it opens there. But spotube doesn't have a URI protocol yet.

I followed the instructions on [this page](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa767914(v=vs.85)?redirectedfrom=MSDN#registering-the-application-handling-the-custom-uri-scheme) about how to register a URI handler. I also changed the URI protocol in the Tampermonkey script from spotify: to spotube:. Unfortunately, the Spotify playlist site kept crashing every time I opened it. So something is gone somewhere. If anyone who knows about this stuff can help, please jump in!

This is how my Registry looks like:
```
Windows Registry Editor Version 5.00


[HKEY_CLASSES_ROOT\spotube]
@="URL:spotube Protocol"
"URL Protocol"=""

[HKEY_CLASSES_ROOT\spotube\DefaultIcon]
@="C:\\Users\\Menna\\AppData\\Local\\Programs\\Spotube\\spotube.exe,1"

[HKEY_CLASSES_ROOT\spotube\shell]

[HKEY_CLASSES_ROOT\spotube\shell\open]

[HKEY_CLASSES_ROOT\spotube\shell\open\command]
@="C:\\Users\\Menna\\AppData\\Local\\Programs\\Spotube\\spotube.exe \"%1\""
```

And this is an example of what Microsoft suggests to do, the protocol being **alert**:
```
HKEY_CLASSES_ROOT
   alert
      (Default) = "URL:Alert Protocol"
      URL Protocol = ""
      DefaultIcon
         (Default) = "alert.exe,1"
      shell
         open
            command
               (Default) = "C:\Program Files\Alert\alert.exe" "%1"
```

**Comment by papjul** [comment]
Is it possible to implement it in Android?

In Android, you can specify that some domain names can be open with your app. Is the ID in the URL enough to read the track?

**Comment by Megver83** [comment]
@KRTirtho this is specially helpful in Android, sometimes my friends share their playlists to me but I cannot open them directly in Spotube.

And regarding the GNU/Linux client, you can register the corresponding URI protocol in the desktop file.

**Comment by beatnickgr** [comment]
Tapping a Spotify link from Telegram opens the browser instead.

**Comment by KRTirtho** [comment]
Support added in #950
