### ISSUE TITLE
[Feature] Volumio Plugin

### ISSUE THREAD

**Issue by Arndorferd** [KRTirtho/spotube#331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of the Feature

Unable to categorize

### Credits

Myself

### Pain

Streaming to Volumio an open source streaming platform which can stream to individual speakers from a Pi is a Spotify premium feature to connect too from the app. Connecting to other devices in your app doesn't exist it seems at all. 

### Suggested Solution

A Volumio Plugin that syncs the spotube on your phone with volumio. A setting would have to be added in the spotube app that would allow pairing to the volumio plugin through wifi. There would be plugin users would download in volumio. The volumio plugin would scrape the music and play it on the volumio server. This would allow users to experience a fully open source phone to streamer "sonos speaker" like solution using spotify without paying premium or having invasive trackers.

### Useful resources/references

https://volumio.github.io/docs/Plugin_System/Writing_A_Plugin.html

**Comment by KRTirtho** [comment]
This would be something really great if the community does it. So I'm marking it as invalid
