### ISSUE TITLE
[Bug] UI flickers and elements are displayed destroyed

### ISSUE THREAD

**Issue by reaseno** [KRTirtho/spotube#332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The UI flickers completely and elements are sometimes displayed totally destroyed, which means that app use is sometimes only possible in blind flight.

### Expected Behavior

working UI

### Steps To Reproduce

1. open the app

### Spotube Version

2.5.0

### Operating System

Android

### Operating System Version

LineageOS 17.1

### Installation Source

F-Droid (Android)

### Additional information

Device: Nexus 7 2013

**Comment by KRTirtho** [comment]
Could be a Lineage OS related issue. Maybe it's missing some GFX libraries important for Flutter to work
Can you check with other apps that are built using flutter and relatively new?

**Comment by reaseno** [comment]
Can you tell me some apps?

**Comment by KRTirtho** [comment]
https://appluxit.com/blackhole/

**Comment by senolfndk** [comment]
![Ekran görüntüsü 2022-12-11 134405](https://user-images.githubusercontent.com/52818836/206899210-d6226c41-8fba-49d2-87d1-7bc9ccb2f4c5.png)
🤔

**Comment by reaseno** [comment]
> https://appluxit.com/blackhole/

Yes, I have the same issues there too.
Can I install something to fix it?

**Comment by KRTirtho** [comment]
https://github.com/flutter/flutter/issues/105093
It's the parent issue. Keep an eye on that. It might help

**Comment by reaseno** [comment]
Yes, that's how it looks on my device. Hope they can fix it soon.
Thank you very much for your help.

**Comment by KRTirtho** [comment]
This has been fixed on upstream and so is for Spotube
