### ISSUE TITLE
[Bug] Can not click Submit button on Windows client

### ISSUE THREAD

**Issue by Icarus-Xu** [KRTirtho/spotube#334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I pasted sp_dc and sp_key field, then clicked submit button but no response
my account has premium access.

![image](https://user-images.githubusercontent.com/11155311/204716058-c439798a-b2d6-4569-b099-4fa784be3669.png)

### Expected Behavior

login correctly

### Operating System

Windows

### Operating System Version

Windows 11

### Installation Source

Github Release (Binary)

**Comment by KRTirtho** [comment]
Duplicate of #333

**Comment by Icarus-Xu** [comment]
problem persist on v2.6.0
