### ISSUE TITLE
[Feature] Rewrite

### ISSUE THREAD

**Issue by RaptaG** [KRTirtho/spotube#336]
### Is there an existing issue for this?

✅ I have searched the existing issues

### Category of the Feature

UI Improvements, Logical Improvements, More Efficiency, Performance Improvements, UX Improvements, Code Refactor

### Credits

Myself, @Alliba and everyone who made related issues here

### Pain

Although Spotube is a nice idea but it has some really annoying issues both on the UX/UI and on playing songs.

### Suggested Solution

There are some very essential changes that have to be made on Spotube order to be a better player and easier to use for the "average" users. I'd like to point out:

## 1. Using the YouTube **Music**'s API instead of YouTube's

Using the YouTube Music's API would be a critical change for Spotube because:

- **It has more song accuracy.**

I'm listening to songs from the 70s up until today and using the existing YT searching algorithm lead to playing wrong songs, wrong song versions etc. I've noticed that it usually messes up when a song says it's "Remastered" or "Live". There are many times that it'll just play another song.

- **It has wide lyric support.**

I've noticed that YT Music has lyrics support. The current lyric implementation of Spotube, well, sucks. Using YT Music's lyrics would be huge for Spotube. 

- **Makes the SponsorBlock implementation useless.**

YT Music is a music dedicated platform. There no non-music segments, meaning you'll the song exactly how it's meant to be heard. 

## 2. More user friendly account login

If I remember well the Android version of Spotube has an automated login. Entering a website and copying cookie client IDs is not ideal for everyone and the most discouraging feature of Spotube. Logging in via Email, Google, Facebook directly would be really good. For example, Spotube could have a built-in screen allowing you to login using these services and then using the Spotify access this cookie data and paste them automatically.

[Heroic Games Launcher](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher) used to have the user do a such thing, but it automated it in its latest versions.
Inspiration could be taken from there.

## 3. A time delay between song downloading to avoid IP blocking<br/>or an in-app VPN creation

When downloading many songs at once, there's a warning that says the user's IP might get blocked from YT for the next couple of months. I came up with an idea that could really help avoiding that. What if the was an adjustable time delay (with a minimum limit) that would request each after eg. 5 seconds so that YT wouldn't receive all the requests at the same time and avoid IP blocking? It's a very effective way I think. Another way could also be and in-app VPN, but this may be more complicated. 

## 4. Annoying UI bugs

There's _a lot_ of UI bugs within Spotube:

- [X] **The song widgets title is `Widget` instead of `Like`, `Add to Playlist` & `Share`:** 

![widget1](https://user-images.githubusercontent.com/77157639/205499179-c2c6c276-aeb7-4904-b9e8-f7c2f1764a89.png) ![widget2](https://user-images.githubusercontent.com/77157639/205499183-4c9c7278-afac-4e6f-b411-cdb8d011911c.png) ![widget3](https://user-images.githubusercontent.com/77157639/205499186-b5776e59-4089-484e-be8e-0acf2275e4aa.png)

- [X] **Above these widgets, the Sort and Download buttons have the `Show Menu` title indead of `Sort` and `Download`:**

![showmenu1](https://user-images.githubusercontent.com/77157639/205499357-26f93392-a6c4-4c2b-a3b8-b8816fa4bce4.png) ![showmenu2](https://user-images.githubusercontent.com/77157639/205499362-edef4c11-71c6-4a4b-aa96-b0c30047d009.png)

Referring to this, the 3 dots should be replaced with a download icon.

(Both of the above title's background is white which makes them ugly.)

- [ ] **HTML breaks sometimes:**

![htmlbroken](https://user-images.githubusercontent.com/77157639/205499538-e5075be6-ba76-4888-be19-e3415da8f0f6.png)

It also might pop and `expection`-something error.

- [ ] **On Featured, the last list hardly ever loads:**

![featuredlastnotloading](https://user-images.githubusercontent.com/77157639/205499588-c9294f8d-65c7-421e-9044-8e228a7e1047.png)

- [ ] **On the Quene, all song times are 0:00 besides the already played songs:**

![incorrecttime](https://user-images.githubusercontent.com/77157639/205499621-17714046-9472-49ab-9700-2feee1c97839.png)

- [X] **When minimizing the left GUI, the profile picture minimizes as well, which is pointless because it can fit without shrinking the image:**

![minifyguiminifiespfp](https://user-images.githubusercontent.com/77157639/205499648-aa90fcd3-da1b-4975-b758-209aed25992c.png)

- [X] **The share button _does_ copy the link in the clipboard, but doesn't notify the user about it, making them think nothing happened.**

![sharebuttonnocopytoast](https://user-images.githubusercontent.com/77157639/205499760-e5b43109-7bb1-4093-adfe-151531bfd355.png)

- [ ] **On Home, when hovering above a list the title is shown beneath, which is useless because it's already shown:**

![titles](https://user-images.githubusercontent.com/77157639/205499813-948bd794-1dd3-4a73-aa86-6053c7f31566.png)

- [ ] **The window bar is inside the application, when the system's window bar should be used, for parity
(here's a comparison with Spotube's and Spotify's window bar, on Linux with a custom theme):**

![windowbarspotube](https://user-images.githubusercontent.com/77157639/205499883-c8c30aa3-3cf5-4d42-959a-789a5517f369.png)

![windowbarspotify](https://user-images.githubusercontent.com/77157639/205499967-c4071912-3e65-4f70-9bb9-b839d2bfa368.png)

---

Generally, the Spotify UI is less eye-hurting than Spotube's, cleaner, faster, with less animations. I'm not against the animations, but they could be better.

![spotifygui](https://user-images.githubusercontent.com/77157639/205500109-bb885f7b-ca02-4645-9667-086a2ee92de7.png)

The new UI helped a bit but it has 2 issues:

- [ ] It doesn't save the UI mimic option
- [ ] It can be inconsistent with Linux theming 

Also, please create a new icon, this one's not really good.

## 5. Spotube performs way slower that Spotify

As I stated in a previous issue, Spotube acts, lods and performs way slower that Spotify, which is really frustrating.

This still happens, sometimes the playlist won't show up unless restarting (but I've started thinking that it might be an issue with my WiFi adapter, but it doesn't happen with Spotify so...)

### Useful resources/references

#313, #292, #112, maybe more

###  Other

I **did not make** this issue to offend **anyone**, I just believe that these issues have to be fixed so that Spotube can benefit.

**Comment by RaptaG** [comment]
Glad to see that some of my suggestions made it to 2.6.0

**Comment by RaptaG** [comment]
@KRTirtho There's a new free API for Spotify lyrics
https://github.com/akashrchandran/spotify-lyrics-api

**Comment by KRTirtho** [comment]
Dude, that will be revolutionizing for spotube :smile:

**Comment by RaptaG** [comment]
I know right

**Comment by RaptaG** [comment]
Please read my comment here too:
https://github.com/KRTirtho/spotube/discussions/412#discussioncomment-5201996

**Comment by RaptaG** [comment]
This could also be useful (?) @KRTirtho 
https://github.com/librespot-org/librespot

**Comment by KRTirtho** [comment]
> 

Actually, it's a native open source spotify SDK and currently no dart implementation of it. We've to wait until (or create ourselves) a dart port comes out

**Comment by RaptaG** [comment]
Alright
