### ISSUE TITLE
[Bug] Home screen stuck (nightly)

### ISSUE THREAD

**Issue by Ramys** [KRTirtho/spotube#339]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After the updates, it is not possible to log in or at least click on anything, because the update screen does not allow it.
https://nightly.link/KRTirtho/spotube/workflows/spotube-nightly/build.

### Expected Behavior

The download message does not let the apk work..
It gets stuck like this and there is no way to use it
<a href="https://ibb.co/0YqHfVV"><img src="https://i.ibb.co/6DYj4JJ/Screenshot-20221207-115432.png" alt="Screenshot-20221207-115432" border="0"></a>

### Steps To Reproduce

1. Download the apk (https://nightly.link/KRTirtho/spotube/workflows/spotube-nightly/build)
2. Install normally
3. open and try to click on something
4. it is possible to see that the download screen does not let

### Spotube Version

https://nightly.link/KRTirtho/spotube/workflows/spotube-nightly/build/Spotube-Android-Bundle.zip

### Operating System

Android

### Operating System Version

Android 8.1

### Installation Source

Github Actions (Nightly Binary)

### Additional information

I would like a new step by step to solve this problem.

**Comment by KRTirtho** [comment]
This should be fixed by now
