### ISSUE TITLE
Recently Followed Spotify playlists do not appear in spotube

### ISSUE THREAD

**Issue by Mennaruuk** [KRTirtho/spotube#34]
**Describe the bug**
When I heart a playlist in Spotify Web, it doesn't appear on spotube. 

**To Reproduce**
1. Heart this [playlist](https://open.spotify.com/playlist/37i9dQZF1DX48TTZL62Yht) in your browser
2. Check back in spotube if playlist has been added

**Expected behavior**
There should be some kind of refresh button that allows users to check for changes. But I did try logging out and back in, and the recently hearted playlist was not there.

**Installation Source/Method**
- Package Manager: Binary
- Community Repo: Binary
- Binary Source: https://github.com/KRTirtho/spotube/releases/download/v1.2.0/Spotube-windows-x86_64-setup.exe

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: v1.2.0

**Additional context**
Something else I noticed is that when I search for playlists on spotube, I only get YouTube playlists, not Spotify. I believe Spotify playlists should appear in the results, and it would be awesome to have something that can distinguish between the two (maybe green vs red, or Spotify vs YouTube icons for people with color vision deficiency).

**Comment by KRTirtho** [comment]
This is because the library Spotube using under the hood to communicate with Spotify APIs, doesn't support Following Playlists yet. But I'm constantly working on it to bring support for this kind of operations

**Comment by KRTirtho** [comment]
> Something else I noticed is that when I search for playlists on spotube, I only get YouTube playlists, not Spotify. I believe Spotify playlists should appear in the results, and it would be awesome to have something that can distinguish between the two (maybe green vs red, or Spotify vs YouTube icons for people with color vision deficiency).

There's no YouTube playlists as the app only talks with Spotify Servers. The result or anything you're seeing is completely from Spotify API. Only the music you're listening to is using YouTube API to download that

**Comment by Mennaruuk** [comment]
Huh, interesting. Indeed, I checked my Spotify account and I saw that the same playlist is there. I guess somebody ported the Spotify playlist over to YouTube so when I googled it, I found it there. Thanks for your prompt response!

**Comment by KRTirtho** [comment]
Well, lucky for you the newest version of Spotube now has support for follow/unfollow artist/playlist/album & also creating/deleting your own Playlists
