### ISSUE TITLE
[Bug] High GPU usage on MacOS

### ISSUE THREAD

**Issue by Kuurse** [KRTirtho/spotube#341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The "Browse" and "Library" (Playlist & Album tabs) pages make my GPU usage jumps to 100% instantly. It seems something with the way the image "cards" work is super resource-hungry on MacOS.

### Expected Behavior

Lower GPU usage (<5% seems like a normal value).

### Steps To Reproduce

Open Spotube on the Browse page or the Playlist or Album tabs or the Library page.

### Spotube Version

2.5.0

### Operating System

Mac OS

### Operating System Version

Ventura 13.0.1

### Installation Source

Official Website (spotube.netlify.app)

**Comment by KRTirtho** [comment]
The shimmer/skeleton animation (loading indicators) are super janky and was causing high GPU usage in Home and Library

**Comment by KRTirtho** [comment]
Wow this is ancient

It was fixed long ago

**Comment by RainM** [comment]
Full-sized (expanded) Spotube consumes significant percent of GPU. If I minimize window consumption backs to normal.
 If I start play music via Spotube GPU consumption jumps to 15W. If I pause GPU power consumption shrinks back to 9W. The same behaviour If I minimize window (and still play music). 
OSX activity monitor displays the same behaviour. I have multi-monitor setup (2 external displays, 1080p and 4k).
