### ISSUE TITLE
[Bug] Cannot see the correct number of song since 100

### ISSUE THREAD

**Issue by sf0nt** [KRTirtho/spotube#347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I don't see the correct number of song since 100. I only see the first two numbers of the songs.

I tried to reproduce in Android and I had the same result.

i.e.: 
85 => 85
99 => 99
100 => 10
102 => 10
109 => 10
115 => 11

Linux:
![image](https://user-images.githubusercontent.com/209067/207358592-84f3ec24-48d6-4f77-a0c1-87a49c011ec7.png)

Android:
![image](https://user-images.githubusercontent.com/209067/207359489-034a5bba-c34b-42f9-afba-b7c966d316b4.png)

### Expected Behavior

See 3 characters instead of 2 to see the correct number of the songs

### Steps To Reproduce

1. Browse
2. Select a list that has more than 99 songs
3. Scroll at the end

### Spotube Version

v2.6.0

### Operating System

Android, Linux

### Linux Distribution (if applicable)

Linux Mint 21 Cinnamon

### Operating System Version

Linux Mint 21 Cinnamon and Android 12

### Installation Source

Flathub (Flatpak)

**Comment by KRTirtho** [comment]
Ok, it's a UI bug

**Comment by KRTirtho** [comment]
>  I cannot debug because I have an error in master branch. It doesn't found the file spotube/models/generated_secrets.dart

Only if people read the CONTRIBUTION.md before trying to build
There's instruction about how to run the project
https://github.com/KRTirtho/spotube/blob/master/CONTRIBUTION.md#your-first-code-contribution

**Comment by sf0nt** [comment]
> > I cannot debug because I have an error in master branch. It doesn't found the file spotube/models/generated_secrets.dart
> 
> Only if people read the CONTRIBUTION.md before trying to build There's instruction about how to run the project https://github.com/KRTirtho/spotube/blob/master/CONTRIBUTION.md#your-first-code-contribution

:+1:

**Comment by KRTirtho** [comment]
Fixed in v2.7.0
