### ISSUE TITLE
Improve alternative title function

### ISSUE THREAD

**Issue by Alliba** [KRTirtho/spotube#348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The function to select an alternative title I find mega, because Spotube sometimes plays a wrong title.

### Expected Behavior

But Spotube would have to remember the alternative title, so that the next time the title is played immediately the correct.

At the moment you have to select the alternative title every time to have the right title. This is not always feasible, for example, when driving.

### Operating System

Android, Linux

### Operating System Version

Android 9

### Installation Source

F-Droid (Android)

**Comment by KRTirtho** [comment]
I've tested with multiple tracks, it remembers the selected YouTube result for a particular Spotify Track
Can you provide the track you're facing this problem with?

**Comment by Alliba** [comment]
> I've tested with multiple tracks, it remembers the selected YouTube result for a particular Spotify Track correctly Can you provide the track you're facing this problem with?

Oh sorry, I take it back. It works after all.
