### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by highjeans** [KRTirtho/spotube#35]
**Describe the bug**
Unable to build in Github Actions

**To Reproduce**
1. Start workflow for building

**Expected behavior**
Finish building

**Comment by KRTirtho** [comment]
You need 2 action/repository secrets defined as LYRICS_SECRET & SPOTIFY_SECRET in your repository. Both of them should be base64 encoded JSON string
Structure of SPOTIFY_SECRET json string:
```jsonc
[
  {"clientId": "secrrtid", "clientSecret": "secret"},
  // and so on ....
]
```

Structure of LYRICS_SECRET json string:
```jsonc
[
  "<secret genius access tokens>",
  // and so on...
]
```

You can base64 encode the string [here](https://www.base64encode.org/)

This is for enabling the Anonymous/Guest support for upcoming V2 release

**Comment by KRTirtho** [comment]
@highjeans did the issue get fixed?

**Comment by highjeans** [comment]
I haven't tried yet, I will check when I get time to.

**Comment by KRTirtho** [comment]
@highjeans did you manage to build it yet?

**Comment by RaptaG** [comment]
I think it now builds, let me know if I'm wrong
