### ISSUE TITLE
Play local song instead of always streaming

### ISSUE THREAD

**Issue by siggi1984** [KRTirtho/spotube#351]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Credits

I

### Pain

I personally don't have that much data volume and I think there are others who feel the same way.  That's why it would be cool if the app after downloading a playlist plays it offline and not always streaming.

### Suggested Solution

I know the APP plays the downloaded songs but crisscross. It would be nice if the APP downloaded the playlist or album and also in the title order and not jumbled.

**Comment by KRTirtho** [comment]
If you have the _Pre Download and Play_ option turned on in settings, it'll now cache the tracks. Update available in the latest nightly

Fixed by https://github.com/KRTirtho/spotube/pull/399

**Comment by siggi1984** [comment]
How does that work now exactly.

Do you have to have listened to the song once and it is then cached and then always played back offline from the cache?

**Comment by KRTirtho** [comment]
@siggi1984 yeah, that's exactly how it works now in *Nightly*

**Comment by siggi1984** [comment]
How exactly does the song cache work. Is the cache written infinitely or does it have a limit etc...?  Or is the cache cleared after a certain period of time?

**Comment by KRTirtho** [comment]
> Or is the cache cleared after a certain period of time?

**Comment by siggi1984** [comment]
Has the song cache function been removed in version 3?
