### ISSUE TITLE
[Bug] Previous Track button does not skip to start of song when pressed in the middle of a song

### ISSUE THREAD

**Issue by waffleboi9000** [KRTirtho/spotube#354]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently, when playing a song, if you select the previous song button, the previous song plays regardless of the progress of the current song.

### Expected Behavior

The expected behavior on other apps is to first skip to the beginning of the current song, and go to the previous song if the current song is only at the very start (ex. <5 s of playback)

### Steps To Reproduce

Select the previous song button when playing the second or greater song in a playlist.

### Spotube Version

2.6.0

### Operating System

Android, Linux

### Linux Distribution (if applicable)

Nobara Linux

### Operating System Version

Nobara Linux 36, Android 12

### Installation Source

F-Droid (Android), Flathub (Flatpak)

**Comment by KRTirtho** [comment]
This has been fixed by https://github.com/KRTirtho/spotube/pull/399

**Comment by KRTirtho** [comment]
You can check the nightly
