### ISSUE TITLE
[Bug] Seekbar progress incorrect

### ISSUE THREAD

**Issue by waffleboi9000** [KRTirtho/spotube#358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In app:
![image](https://user-images.githubusercontent.com/89646595/209376504-110ea11e-a7f0-4701-b41c-a7a474357202.png)
KDE Plasma media player controls:
![image](https://user-images.githubusercontent.com/89646595/209376529-e3ac82df-764a-4609-909f-6685090ac4ac.png)

### Expected Behavior

Progress should match between both the app and KDE Plasma media controls.

### Spotube Version

2.6.0

### Operating System

Linux

### Linux Distribution (if applicable)

Nobara Linux

### Operating System Version

36

### Installation Source

Flathub (Flatpak)

**Comment by ibonlog** [comment]
I have the same problem, and the same thing happens in linux and mac app. On Android it works perfect!

**Comment by forteller** [comment]
For me the seek bar stopped working at all with the latest version, 2.7.0. Pretty sure it worked fine until then. I'm also on Nobara Linux, Flathub.

**Comment by KRTirtho** [comment]
It's fixed now. Check nightly

**Comment by RaptaG** [comment]
Fixed in 3.0.0
