### ISSUE TITLE
[Bug] Spotify: "Your client does not have permission to get URL"

### ISSUE THREAD

**Issue by Korb** [KRTirtho/spotube#364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. Click "Login with your Spotify account"
2. "Error: Forbidden. Your client does not have permission to get URL /int/why-not-available/ from this server".

### Expected Behavior

Successfully logging in to your account on spotify.com provides the corresponding functionality in the Spotube app.

### Steps To Reproduce

Click "Login with your Spotify account"

### Spotube Version

2.6.0 (16)

### Operating System

Android

### Operating System Version

13 (Funtouch OS 13 Global)

### Installation Source

F-Droid (Android)

### Additional information

> Chrome Beta 109.0.5414.44

> Модель: V2153
> Версия аппаратного обеспечения: МР_0.1
> Номер сборки: PD2201 OF_EX_A_13.1.13.1 .W20.V000L1
> Прошивка модуля связи: MPSS.HA.1.1.С2-00012-KD_ALL_PACK-1.6347.66
> Версия ядра: 4.19.157-perf+, 1 Thu Dec 1 12:15:36 CST 2022
> Время компиляции: 1 дек. 2022 г. 07:03:09
> Обновление системы безопасности Android: 1 декабря 2022 г.
> Обновление системы через Google Play: 1 ноября 2022 г.

**Comment by KRTirtho** [comment]
That's a weird error. What is your default browser?

**Comment by Korb** [comment]
> What is your default browser?

> ### Additional information
> > Chrome Beta 109.0.5414.44

**Comment by ArtyIF** [comment]
Judging by the additional info being in Russian, I assume you're in Russia. Spotify is currently unavailable there. Try using a VPN, it worked for me. I think what type of connection you have also matters, since on Tinkoff Mobile it gave me a 403 Forbidden with a VPN on, while on my home MGTS Wi-Fi it worked fine.

**Comment by Korb** [comment]
@ArtyIF, yes, I'm in the country you specified and don't currently have a valid Spotify subscription to test your hypothesis. Please check it yourself, and if you can reproduce the above error, I will close this bug report as resolved.
