### ISSUE TITLE
[Bug] Nothing loads

### ISSUE THREAD

**Issue by RaptaG** [KRTirtho/spotube#365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Nothing is shown in Spotube, besides sometimes the search and the saved playlists (excluding liked songs)

### Expected Behavior

The songs and playlists to show up

### Steps To Reproduce

Open Spotube

### Spotube Version

2.6.0

### Operating System

Linux

### Linux Distribution (if applicable)

Arch based Linux

### Operating System Version

EndeavourOS latest

### Installation Source

Arch User Repository (AUR)

### Additional information

Some log things I could find:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: OAuth authorization error (invalid_token): The access token expired.
#0      Client.send (package:oauth2/src/client.dart:134)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93)
<asynchronous suspension>
#2      SpotifyApiBase._getImpl.<anonymous closure> (package:spotify/src/spotify_base.dart:164)
<asynchronous suspension>
#3      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:197)
<asynchronous suspension>
#4      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:163)
<asynchronous suspension>
#5      Pages.getPage (package:spotify/src/endpoints/endpoint_paging.dart:235)
<asynchronous suspension>
```

**Comment by KRTirtho** [comment]
Try logging out and logging in. May be access token expired and for some reason it's not getting refreshed

**Comment by thecocce** [comment]
Hi, I have the same problem when using it for a long time

**Comment by RaptaG** [comment]
> Try logging out and logging in. May be access token expired and for some reason it's not getting refreshed

Still the same

**Comment by KRTirtho** [comment]
@RaptaG and @thecocce does is it fixed in v2.7.0? Let me know

**Comment by RaptaG** [comment]
Will test at home

**Comment by KRTirtho** [comment]
@RaptaG if it's fix close it

**Comment by RaptaG** [comment]
ok, lemme test

**Comment by RaptaG** [comment]
It seems fixed, I'll reopen if it happens again
