### ISSUE TITLE
[Bug] Cannot connect to Spotify account

### ISSUE THREAD

**Issue by ptscz** [KRTirtho/spotube#366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On my android phone (deGoogled Android [/e/OS](https://e.foundation/e-os)) I cannot login to my Spotify account.

It's probably because that Spotube/Spotify is trying to connect to www.google.com server during the login process.
On my deGoogled android OS are connections to all Google servers are blocked.

- Is this connection to Google server needed for login, when I use login to Spotify through name/password?
- Or is it any other way how to log in, avoiding to connect to any Google servers?

### Expected Behavior

Correct login to Spotify account.

### Steps To Reproduce

1. In Settings hit _Login with your Spotify account_ / CONNECT WITH SPOTIFY
2. You will be correctly redirected to Spotify login screen
3. Fill your username and password and hit the LOG IN button
4. You will receive error message, that something went wrong and you cannot connect to Spotify account
5. You can check outgoing data connections, that in that time Spotube/Spotify is trying to connect to www.google.com (beside the other spotify servers, probably needed to login)

### Spotube Version

v2.6.0

### Operating System

Android

### Operating System Version

/e/OS 1.6 (Android 10)

### Installation Source

F-Droid (Android)

**Comment by KRTirtho** [comment]
Well, I don't know about Spotify's website, but they could be using some google services related to authentication (or ads). The Spotify website is loaded only for that login part, after that Spotube directly talks with the Spotify API

Why don't you try enabling google domains and login, then disable again once you're logged in?

**Comment by ptscz** [comment]
It works! Thanks for the quick advice (and sorry for my little stupid question, with so easy solution :man_facepalming:).

**Comment by KRTirtho** [comment]
Glad it worked. Keep chilling with Spotube :smile:
