### ISSUE TITLE
[Bug] Cannot loop a track without shuffling whole playlist first.

### ISSUE THREAD

**Issue by waffleboi9000** [KRTirtho/spotube#367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

At the moment, because the playback mode switches between looping the playlist (the default), shuffle play (which shuffles all the tracks in the playlist), and looping the current song.
[1]. 
![image](https://user-images.githubusercontent.com/89646595/210824093-2b14ecd2-36b1-4e1a-91f1-0d40a4c373e2.png)

[2]. 
![image](https://user-images.githubusercontent.com/89646595/210824265-8a8af58b-d87f-47b6-a097-456e848f3d8f.png)

[3]. 
![image](https://user-images.githubusercontent.com/89646595/210824441-380d076e-e4ff-4301-8325-de8eed279b1c.png)

### Expected Behavior

It is expected that it is possible to loop just the currently playing track without changing the order of following songs in a playlist.

### Steps To Reproduce

1. Play a song in a playlist.
2. Switch to looping a single track.
3. Whole playlist is shuffled.

### Spotube Version

v2.6.0

### Operating System

Linux

### Linux Distribution (if applicable)

Nobara Linux

### Operating System Version

37

### Installation Source

Flathub (Flatpak)

### Additional information

Possible solutions include adding a separate toggle for shuffle play, so that the original playlist order is still available, or just changing the order of the current setup to cycle between 1) looping playlist, 2) looping track, and 3) shuffle playback.

**Comment by KRTirtho** [comment]
The new rewritten Playback manager fixes the following issue https://github.com/KRTirtho/spotube/pull/399

**Comment by KRTirtho** [comment]
This now deployed to 2.7.0
