### ISSUE TITLE
[Feature] Touch and Drag Scroller

### ISSUE THREAD

**Issue by testes-tester** [KRTirtho/spotube#374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of the Feature

UI Improvements

### Credits

Original Spotify

### Pain

I have to scroll down a lot and my finger seems to get fatigued when I do it too fast, or too much. The fatigue leads to weakness and when moving it, it sometimes becomes painful.

### Suggested Solution

Just like the original spotify app, there's a scroller you can touch and drag to go to a specific area in a playlist.<br><br>
![Screenshot_20230111-114011_Spotify](https://user-images.githubusercontent.com/103084749/211714525-faf45991-a92b-4d4f-b42c-67a599fc9ab8.jpg)
<br><br>
![Screenshot_20230111-114050_Spotify](https://user-images.githubusercontent.com/103084749/211714535-42db6385-565f-47a1-baf9-1eadf929f7ba.jpg)

### Useful resources/references

I am using an android, Android 11. Spotube downloaded through F-Droid. Spotube version 2.6.0<br><br>
![Screenshot_20230111-114011_Spotify](https://user-images.githubusercontent.com/103084749/211714483-eabc884d-ca83-42ae-aaf3-15f38d4b860e.jpg)
<br><br>
![Screenshot_20230111-114050_Spotify](https://user-images.githubusercontent.com/103084749/211714493-76d32b6d-1572-45fc-abc0-aa3fbc76a01e.jpg)

**Comment by KRTirtho** [comment]
This might be useful: https://pub.dev/packages/draggable_scrollbar

**Comment by KRTirtho** [comment]
Not exactly as Spotify but scrollbars from now on will be interactive
