### ISSUE TITLE
[Bug] YouTube search term format picker is misaligned

### ISSUE THREAD

**Issue by bluelhf** [KRTirtho/spotube#375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Both the text and the save button are misaligned in the YouTube search term format picker in the settings.

![image](https://user-images.githubusercontent.com/52505120/212135883-f1d70791-b7ef-4e4a-a627-640eb98aad29.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/52505120/212136490-4f3ae213-df30-4097-9b88-9d04fce0f31c.png)

### Steps To Reproduce

1. Open the settings
2. Look at the format picker

### Spotube Version

v2.6.0

### Operating System

Linux

### Linux Distribution (if applicable)

Devuan

### Operating System Version

5.18.0

### Installation Source

Official Website (spotube.netlify.app)

**Comment by KRTirtho** [comment]
Actually, removed this feature in favor of _Alternative Track Source Selection_
It'll be available in the next release

So closing this issue
