### ISSUE TITLE
[Bug] Sponsor Button contrast is too low in Dark Mode

### ISSUE THREAD

**Issue by bluelhf** [KRTirtho/spotube#376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The sponsor button does not change background color when switching between light and dark modes, while its text does. This causes an issue where the text on the button has too little contrast to be readable in dark mode:
![image](https://user-images.githubusercontent.com/52505120/212137536-9b9031c9-6aed-4363-92cf-2a8ec1dfc3ba.png)

### Expected Behavior

A darker colour would be more suitable.
![image](https://user-images.githubusercontent.com/52505120/212139274-b9d9a768-4d05-4df8-a20c-4230c9f88469.png)

### Steps To Reproduce

1. Open Settings
2. Select 'Dark Mode'
3. Look at the button

### Spotube Version

v2.6.0

### Operating System

Linux

### Linux Distribution (if applicable)

Devuan

### Operating System Version

5.18.0

### Installation Source

Official Website (spotube.netlify.app)

### Additional information

Text and icon alignment is off on this button as well.

**Comment by RaptaG** [comment]
Fixed in 3.0.0
