### ISSUE TITLE
[Feature] Show track loading icon on minimized player

### ISSUE THREAD

**Issue by Cwpute** [KRTirtho/spotube#377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of the Feature

UI Improvements

### Credits

me?

### Pain

When a track is loading, the play button is replaced with a loading icon in the fullscreen player: 
![Screenshot_20230116-184522](https://user-images.githubusercontent.com/80604512/212739612-211dbfc4-cb29-4def-aef5-2199f958c71b.png)
But the minimized player doesn't act the same: 
![Screenshot_20230116-184509](https://user-images.githubusercontent.com/80604512/212739778-c19c4af9-663b-47e3-8b00-3ce0784d3eba.png)
Here, the play button in the bottom bar stays as is, as if nothing was happening.

This can confuse users as to what is happening in the app, if it is working as intended, or even working at all.

### Suggested Solution

When a track is loading, replace the play button with the animated circle that already shows in follscreen player for the same situation.
I'd also suggest that Spotube's players integrated in Android's UI (the ones shown in screenshots below) appear right when the user touches the play button, as to show their action was registered, and also displays the animated circle to instead of the play button for when a track is loading.
![Screenshot_20230116-185330](https://user-images.githubusercontent.com/80604512/212740699-8f5da80c-0c94-472c-84a0-72dc9040b6c9.png)
![Screenshot_20230116-185344](https://user-images.githubusercontent.com/80604512/212740720-5bae7748-6cb3-4791-a2e3-a8f77088a8aa.png)

**Comment by KRTirtho** [comment]
This has been fixed and available from 2.7.0 (latest)
