### ISSUE TITLE
[Bug] Build Error on iOS

### ISSUE THREAD

**Issue by litt1e-p** [KRTirtho/spotube#380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Errors occured when run xcode build:
```
 ld: warning: ignoring file /Users/mac/dev/flutter/.pub-cache/hosted/pub.flutter-io.cn/metadata_god-0.3.2/ios/Libs/librust.a, building for iOS Simulator-x86_64 but attempting to link with file built for
    iOS-arm64
    ld: warning: Could not find or use auto-linked framework 'rust_crate'
    Undefined symbols for architecture x86_64:
      "_free_WireSyncReturnStruct", referenced from:
          _dummy_method_to_enforce_bundling in MetadataGodPlugin.o
      "_new_box_autoadd_f64_0", referenced from:
          _dummy_method_to_enforce_bundling in MetadataGodPlugin.o
      "_new_box_autoadd_i32_0", referenced from:
          _dummy_method_to_enforce_bundling in MetadataGodPlugin.o
      "_new_box_autoadd_image_0", referenced from:
          _dummy_method_to_enforce_bundling in MetadataGodPlugin.o
      "_new_box_autoadd_metadata_0", referenced from:
          _dummy_method_to_enforce_bundling in MetadataGodPlugin.o
      "_new_box_autoadd_u16_0", referenced from:
          _dummy_method_to_enforce_bundling in MetadataGodPlugin.o
      "_new_box_autoadd_u64_0", referenced from:
          _dummy_method_to_enforce_bundling in MetadataGodPlugin.o
      "_new_uint_8_list_0", referenced from:
          _dummy_method_to_enforce_bundling in MetadataGodPlugin.o
      "_store_dart_post_cobject", referenced from:
          _dummy_method_to_enforce_bundling in MetadataGodPlugin.o
      "_wire_ping", referenced from:
          _dummy_method_to_enforce_bundling in MetadataGodPlugin.o
      "_wire_read_metadata", referenced from:
          _dummy_method_to_enforce_bundling in MetadataGodPlugin.o
      "_wire_write_metadata", referenced from:
          _dummy_method_to_enforce_bundling in MetadataGodPlugin.o
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Expected Behavior

build without any error 

### Steps To Reproduce

1. env: macOS 13.0, Xcode 14, iOS 14.0
2. config: Flutter (Channel stable, 3.3.10, on macOS 13.0 22A380 darwin-arm, locale zh-Hans-CN), Dart SDK version: 2.18.6 (stable) (Tue Dec 13 21:15:14 2022 +0000) on "macos_arm64"
3. flutter pub get && flutter run
4. error occured as above

### Spotube Version

2.6.0

### Operating System

Mac OS

### Operating System Version

iOS 14.0

### Installation Source

Github Release (Binary)

**Comment by HiddenLeveI** [comment]
You can get Spotube on iOS?

**Comment by litt1e-p** [comment]
@HiddenLeveI there is a ios branch

**Comment by KRTirtho** [comment]
try by removing metadata_god fluttter plugin from pubspec

**Comment by HiddenLeveI** [comment]
@litt1e-p So I can get Spotube on the App Store? Or you have to actually build it?

**Comment by KRTirtho** [comment]
> @litt1e-p So I can get Spotube on the App Store? Or you have to actually build it?

No, Spotube is not available through app store. It isn't even compiled for iOS, although it's completely doable.  This is only held back by Apple's platform locking (only allowing developers to build iOS apps on macOS)
So I was unable to build and release an iOS pkg

**Comment by HiddenLeveI** [comment]
@KRTirtho do you think running a VM with MacOS or trying to duel boot it on your system could work?

If not, then maybe buying a cheap older macbook for a few hundred may work.

**Comment by KRTirtho** [comment]
Firstly, I'm not from US/EU and macs are hard to find unless brand new. And a mac VM is too heavy for my system and macOS VM doesn't support graphics drivers that create an issue too

**Comment by litt1e-p** [comment]
> @litt1e-p So I can get Spotube on the App Store? Or you have to actually build it?

no

**Comment by KRTirtho** [comment]
Closing it as now spotube builds fine for iOS sim
