### ISSUE TITLE
Adding a link to a song

### ISSUE THREAD

**Issue by siggi1984** [KRTirtho/spotube#383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Credits

I

### Pain

Sometimes songs are not found or wrong ones are found although they are available on YouTube.

### Suggested Solution

IIt would be good if in such a case, you could manually add the correct link to the song.

**Comment by KRTirtho** [comment]
We can already do that. It's called "Alternative Track Source" and can be found beside the Heart Button in the player

**Comment by siggi1984** [comment]
> 

Yes, I know that, but sometimes the right titles are missing.

![Screenshot_20230122-124426](https://user-images.githubusercontent.com/103368536/213914047-6112f633-f4fe-4bb0-b1cb-2220db9eb3bb.jpg)

An incorrect title is reproduced here.

**Comment by siggi1984** [comment]
![Screenshot_20230122-124433](https://user-images.githubusercontent.com/103368536/213914107-eae0e216-8b53-4a5f-811f-1e42cdec11d0.jpg)


But the right one is not offered here. But it is available on YouTube.

**Comment by siggi1984** [comment]
In this case, a manual link addition would be very useful and helpful to hear the right title

**Comment by KRTirtho** [comment]
Well, now since wehave the ability to search for the correct song I'm closing this issue
