### ISSUE TITLE
[Bug] Songs don't play when clicked play button (desktop)

### ISSUE THREAD

**Issue by sdfliutgoijfidsjtoijpoidjosighoiasdp9ue** [KRTirtho/spotube#386]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

([Same problem on mobile but it's fixed](https://github.com/KRTirtho/spotube/issues/121))
Normally, when i play a song on my laptop, it run really well.
But when i install and play a song in Spotube on my pc, the progress bar stuck at 0:00
I tried uninstall many times but it's still doesn't work.

### Expected Behavior

i don't know why it doesn't work, i also tried with stable spotube version, but it's doesn't work too.

### Steps To Reproduce

1. open spotube
2. pick a random song and play
3. the progress bar stuck and the song doesn't play

### Spotube Version

2.6.0 (latest nightly build)

### Operating System

Windows

### Operating System Version

Windows 10 LTSB 2016

### Installation Source

Github Actions (Nightly Binary)

**Comment by owencz1998** [comment]
I think it's add block that's causing the issue crossing fingers he uses a new api will fix the issue

**Comment by sdfliutgoijfidsjtoijpoidjosighoiasdp9ue** [comment]
@KRTirtho same bug on latest nightly build

**Comment by KRTirtho** [comment]
It's fixed by 3.0.0
