### ISSUE TITLE
[Feature] Album year

### ISSUE THREAD

**Issue by ildar** [KRTirtho/spotube#387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of the Feature

UI Improvements

### Credits

dunno

### Pain

Looking through the artist's page I see his/her albums without the release Year.

### Suggested Solution

Show release Year under the albums

### Useful resources/references

Sp0t1fy site shows that

**Comment by ildar** [comment]
awesome! I see the fix in the nightly build. Thanks a lot!!!

**Comment by RaptaG** [comment]
Added in 3.0.0
