### ISSUE TITLE
[Feature] Larger text for lyrics from Genius / Option to change font size

### ISSUE THREAD

**Issue by forteller** [KRTirtho/spotube#388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of the Feature

UI Improvements

### Credits

me

### Pain

Hey. Thanks for an amazing application! My problem is that the regular lyrics are not always correct, and when I change to Genius the font is so much smaller that it's hard to read.

### Suggested Solution

Just increasing the font size, to something similar as the regular Synced tab, would be a totally fine solution. But if you want to an option to set the font size in the Settings would also be nice.

Thanks again!

### Useful resources/references

On Linux desktop

**Comment by forteller** [comment]
I noticed now that this is mostly a problem in the Linux (libadwaita) theme. In the other themes the Genius font size is also much smaller than the Synced font size, but it is very readable. In the Linux theme on the other hand, it's tiny.

**Comment by KRTirtho** [comment]
Lyrics Text resizing capabilities is now available from v2.7.0
