### ISSUE TITLE
[Bug] Genius lyrics does not scroll up when switching songs

### ISSUE THREAD

**Issue by forteller** [KRTirtho/spotube#394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On the Genius lyrics tab: When you scroll down to read the lyrics all the way, then switch song (by the song ending and automatically go to the next or by manually changing it), the lyrics page keeps being scrolled down for the next song, and you have to manually scroll up

### Expected Behavior

The lyrics page should always start at the top

### Spotube Version

2.6.0

### Operating System

Linux

### Linux Distribution (if applicable)

Nobara

### Operating System Version

37

### Installation Source

Flathub (Flatpak)

### Additional information

Thanks again, my fav music streaming app by far!

**Comment by KRTirtho** [comment]
@forteller Check v2.7.0 (latest)

**Comment by forteller** [comment]
Looks great, thanks!
