### ISSUE TITLE
How To Guest Login?

### ISSUE THREAD

**Issue by seniorm0ment** [KRTirtho/spotube#396]
I see no option for guest/anon login within the app.
Cannot search anything without logging in, the only area thats usable is "home"

**Comment by KRTirtho** [comment]
The non-logged in session is the Anonymous/Guest Session. Only Search (mysterious reasons only Spotify knows) and User Playlists/Albums/Artists are not allowed in this mode

**Comment by Markus40** [comment]
@KRTirtho Would it be possible to use youtube music search instead of spotify when not logged in? The application already uses the api, maybe the search integration is simple enough.

**Comment by KRTirtho** [comment]
Haha not that simple. Basically I've change the entire base of the app :slightly_smiling_face: 
![image](https://github.com/KRTirtho/spotube/assets/61944859/4aff0758-de84-477f-ba51-1efab4150845)

**Comment by axelkar** [comment]
Search and track info works perfectly when using spotdl API keys:
https://github.com/spotDL/spotify-downloader/blob/f90cfb3f5ab1b15e73d0393d531908d4ac789e7d/spotdl/utils/config.py#L276-L277
Why don't you allow search to work with anonymous API keys or on YouTube/Youtube Music/Piped?
