### ISSUE TITLE
Mopidy/mpd Casting

### ISSUE THREAD

**Issue by seniorm0ment** [KRTirtho/spotube#397]
Is there any way to introduce casting to mopidy/mpd somehow?

So if I have a mopidy/mpd client running on my local network, connected to my stereo setup on a raspberry pi. If there was a plugin for mopidy the user can grab an api token from the Spotube app to link it to mopidy/mpd and then type in the ip addresses or something similar.

Then the user can cast to the raspberry pi so music can play on their speakers without needing bluetooth for higher quality audio, and more solid experience.
It's similar to chromecast. They can control it with their phone.

This can be extended further by allowing Spotube clients to connect to one another. For example if I have the client on my computer, and my phone, I can control one another by just linking them with the api token and typing each other's IP addresses

**Comment by KRTirtho** [comment]
It's Spotify Client not a Mopidy Client. Also, Spotube is just a "client" and utilizes Spotify's API so no in that place too. Sorry
