### ISSUE TITLE
[Bug] <title> Download folders issues

### ISSUE THREAD

**Issue by AraneTezza** [KRTirtho/spotube#398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I use Spotify and I change download folder from default to another it doesn't download. When I use my PC (Fedora Linux) and I try to change the default download folder it just doesn't do anything.

### Expected Behavior

I wish in android I can change download folder and it works. And for PC I wish the changing download folder to just do something.

### Steps To Reproduce

1. I download Spotube
2. I Log In with Spotify
3. I change download folder to a personal one
4. When I tap the download icon it shows the "loading" circle and then stops and the song hasn't downloaded.

### Spotube Version

2.6.0

### Operating System

Android, Linux

### Linux Distribution (if applicable)

Fedora

### Operating System Version

Android 13 & Fedora 37

### Installation Source

Official Website (spotube.netlify.app)

**Comment by KRTirtho** [comment]
It's been fixed already. Btw if you're using Flatpak this will not work unless entire file-system permission is provided manually
