### ISSUE TITLE
Please change the logo it does not look that good like the app which is gorgeous 

### ISSUE THREAD

**Issue by Tetrax-10** [KRTirtho/spotube#40]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by KRTirtho** [comment]
I am proud and ashamed at the same time🙂😂
I guess its happening for Android 9 & above's adaptive icons. I'll fix the padding of the logo

**Comment by Tetrax-10** [comment]
@KRTirtho I had no problem with the padding of the logo. I asked for a remastered different logo. Like vanced youtube changed their logo completely.
