### ISSUE TITLE
[Feature] New Albums Release

### ISSUE THREAD

**Issue by evilsh3ll** [KRTirtho/spotube#401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of the Feature

UI Improvements

### Credits

me?

### Pain

I can't see what are the latest albums/songs released by artists I follow, I need to manually opening each artist page

### Suggested Solution

A single page with all new albums/ep/songs by artists I follow

**Comment by KRTirtho** [comment]
There's a new personalized tab in Home page of v2.7.0
You can find the latest album releases from there. But, currently there's no way to filter releases of artist user follows

**Comment by RaptaG** [comment]
Added in 3.0.0
