### ISSUE TITLE
[Bug] Next song doesn't play if screen is locked

### ISSUE THREAD

**Issue by evilsh3ll** [KRTirtho/spotube#402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I play a song of an artist from the top songs at the beginning of the artist page (or from an album) and I lock the screen, when the song ends any other song is played.

### Expected Behavior

The next song in the top song of the artist should play after the last ends

### Steps To Reproduce

1. open an artist page
2. play a song of the top song in the top page
3. lock the screen and wait the song ends
4. then no songs are played
5. if you unlock the screen, the next song starts (it seems like the lock of the screen prevents the loading of the next song)

### Spotube Version

2.6.0

### Operating System

Android

### Operating System Version

Android 10

### Installation Source

F-Droid (Android)

### Additional information

the green loading icon doesn't start if the screen is locked, it starts 1sec after the screen is unlocked

**Comment by srjmas** [comment]
Same here, Android 12

**Comment by KRTirtho** [comment]
This is probably happening due to your device vendor's battery optimization. Spotube always has high priority Audio Focus while playing. So the only thing that stops Spotube from executing is vendor specific modification in that Audio Focus area. I don't know how they're doing it exactly but I'll work on finding a solution

**Comment by evilsh3ll** [comment]
I found that using the latest nightly version of the app, it doesn't happen anymore

**Comment by srjmas** [comment]
Mine is lg g8, i tried to disable battery optimization for the app

Feb 10, 2023 05:34:11 Kingkor Roy Tirtho ***@***.***>:

**Comment by KRTirtho** [comment]
> I found that using the latest nightly version of the app, it doesn't happen anymore

Great! I will mark it as `done`
