### ISSUE TITLE
Use SponcerBlock api to skip silence and skip non music portions 

### ISSUE THREAD

**Issue by Tetrax-10** [KRTirtho/spotube#41]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by KRTirtho** [comment]
Its a browser extension & I'm using HTTP calls for Youtube & not scraping the content using a headless browser
So it's kind of impossible to implement. I guess we've to find alternative ways to fix this issue

**Comment by paricleu** [comment]
You can use the SponsorBlock Api. The documentation can be found [here](https://wiki.sponsor.ajay.app/w/API_Docs).
Lots of custom YT clients use it.
Keep up the good work!

**Comment by Tetrax-10** [comment]
@paricleu @KRTirtho Yeah you can add sponsor block to pretty much any application you want with the help of their API.
Eg: youtube vanced uses that API in their app.
You can even add return youtube dislike to your app with their [API](https://www.returnyoutubedislike.com/docs/fetching).

**Comment by onlyreportingissues** [comment]
+

**Comment by KRTirtho** [comment]
It took a bit of time, but Finally it's done. Sponsor Block API is officially implemented in Spotube🎉
It'll be available in the Next Release, but you can try it out in the [Nightly Release](spotube.netlify.app/other-downloads/nightly-downloads) which will be available in some moment

**Comment by KRTirtho** [comment]
It's finally available in the v2.4.0

**Comment by Tetrax-10** [comment]
> It's finally available in the v2.4.0

It was actually good just tried it now. Thx for impl it

**Comment by KRTirtho** [comment]
If your issue got fixed please close the issue😄
