### ISSUE TITLE
[Bug] unable to see the correct song numbers after 99

### ISSUE THREAD

**Issue by Avichal1234** [KRTirtho/spotube#410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm not able to see the correct song numbers after 99 on the mobile app.

### Expected Behavior

Song numbers should be displayed correctly
![Screenshot_2023-02-11-11-00-34-96_1c96baa6fc3a4338d23fd334c3c04599](https://user-images.githubusercontent.com/86581604/218242093-6e052e9b-29b5-4e79-a9f6-b35ac5f526b4.jpg)

### Steps To Reproduce

1. Open a playlist with over 100 songs
2. Scroll down to the 99th one
3. All songs after that are numbered weirdly.

### Spotube Version

v2.6.0

### Operating System

Android

### Operating System Version

Android 12.1

### Installation Source

F-Droid (Android)

**Comment by toast-t-bread** [comment]
Pretty sure it's just getting cut off.

**Comment by notbrood** [comment]
Can I work on this?

**Comment by toast-t-bread** [comment]
Not sure, maybe a font resize for numbers larger would work

**Comment by KRTirtho** [comment]
It's fixed in v2.7.0

**Comment by toast-t-bread** [comment]
Works on android
