### ISSUE TITLE
[Bug] The synced lyrics page won't update the lyrics

### ISSUE THREAD

**Issue by samsleepingatparty** [KRTirtho/spotube#414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The synced lyrics page just shows a skeleton load of whatever song I played

### Expected Behavior

Synced lyrics should be updated and shows the lyrics from the music I played

### Steps To Reproduce

Using Genius Lyrics page, but with manual scroll

### Spotube Version

v2.6.0

### Operating System

Linux

### Operating System Version

Ubuntu 20.04.1 LTS 64-bit | GNOME 42.5 | X11

### Installation Source

Official Website (spotube.netlify.app)

**Comment by KRTirtho** [comment]
@samsleepingatparty Try the latest (2.7.0) spotube. And let me know if it still happens or not?

**Comment by samsleepingatparty** [comment]
I've downloaded v2.7.0 and so far no issue with the lyrics section (In a note, I used on Pop_OS). Thanks!

**Comment by KRTirtho** [comment]
@RaptaG on you buddy :smile:

**Comment by RaptaG** [comment]
Can't test rn, I'm on mobile

**Comment by RaptaG** [comment]
Can't reproduce in v2.7.0
