### ISSUE TITLE
[Feature] Accept crypto donations

### ISSUE THREAD

**Issue by rizajur** [KRTirtho/spotube#417]
Accept crypto donations

### Suggested Solution
Money rain

###  Describe alternatives you've considered
Golden bathtub

### Additional context
XMR rulez

haha i love the tutorial from the desktop app for the login - :cookie: :zany_face:

**Comment by KRTirtho** [comment]
Thanks a lot for the suggestion but unfortunately Crypo transactions are banned (illegal) in my country so unfortunately I can't use this method to accept donations

But you can always help me or spotube via:
- [OpenCollection](https://opencollective.com/spotube)
- [Buy Me Coffe](https://buymeacoffee.com/krtirtho)
- [Patreon](https://www.patreon.com/krtirtho)

**Comment by rizajur** [comment]
oss.krtirtho.spotube.cache.infinite_queries.lock

and many more files are in the ~/Documents directory after the last update.
Bro please use .local or some hidden paths and a sub directory for spotube.
