### ISSUE TITLE
[Bug] Fetching playlists data broken

### ISSUE THREAD

**Issue by rizajur** [KRTirtho/spotube#418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

some times happens sometimes it does not

![Screenshot from 2023-02-19 00-38-48](https://user-images.githubusercontent.com/123980461/219904354-7cd1d72b-4be8-4424-9988-08bbf1524ee4.png)

### Expected Behavior

load the content of the playlists
i mean i can play the list and cycle through tracks so the content has been loaded, but just this liked songs list is not being displayed properly persistent over restarts.

### Operating System

Linux

### Linux Distribution (if applicable)

Debian

### Operating System Version

12

### Installation Source

Flathub (Flatpak)

**Comment by RaptaG** [comment]
Can reroduce

**Comment by KRTirtho** [comment]
This has been fixed already. Check the nightly

**Comment by rizajur** [comment]
@KRTirtho who ever manages the flatpak should soon update. Thanks for fixing.

**Comment by KRTirtho** [comment]
It's a nightly build, and we don't publish nightly builds to flatpak. Once the new version will be released, it'll be available on the flatpak
