### ISSUE TITLE
spotify login

### ISSUE THREAD

**Issue by CrazyDORF** [KRTirtho/spotube#42]
when trying to use spotify login after getting client id and client secret and pressing submit, the link it opens only shows "INVALID_CLIENT: Invalid redirect URI". to be fair i could be doing something wrong but some help would be appreciated (:

**Comment by KRTirtho** [comment]
Did you set the Redirect URI correctly in the Spotify Developer App dashboard? It should be `http://localhost:4304/auth/spotify/callback`
![image](https://user-images.githubusercontent.com/61944859/160128574-f9b81cbd-8544-4fb0-8720-bab1003f3d69.png)

**Comment by CrazyDORF** [comment]
thank you very much, it worked. i didnt know about changing the redirect url although i had tried to do something with that before

**Comment by KRTirtho** [comment]
Glad the issue got fixed

**Comment by Shmalle** [comment]
Experiencing same issue on Android 11, redirect URI gave me authorization between App and account but then led into void (like no app is listening on that port)

**Comment by Happyfeet01** [comment]
Have the same problem. The redirection URI is correct, the API Keys are correct, but got invalid Client.
