### ISSUE TITLE
[Feature] Support Google Lyrics as default lyrics provider

### ISSUE THREAD

**Issue by jakecharlie** [KRTirtho/spotube#421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of the Feature

UI Improvements, More Efficiency

### Credits

-

### Pain

Currently Spotube lyrics system on Android is not good.

There are two options: "Synced" and "Genius"

99% of the times "Synced" doesn't load any lyrics, while "Genius" loads lyrics mostly in English, but local songs from other languages from other countries are often not in Genius' database, and it takes time to load .

### Suggested Solution

I've been studying the eSound Music app that's on the PlayStore: https://play.google.com/store/apps/details?id=com.esound

I noticed that it uses a very simple, but at the same time effective system to load song lyrics: Google Search

Through eSound Webplayer analysis (https://esound.app), I noticed that while brazilian Cazuza's "Exagerado" music was playing, the desktop browser makes a request to the Google.com website: Access to XMLHttpRequest at 'https://www.google.com/search?q=Cazuza%20exagerado%20lyrics&oq=Cazuza%20exagerado%20lyrics&sourceid=chrome&ie=UTF-8&lr=lang_en'

Basically, the user desktop browser searches for "Cazuza exagerado lyrics" or, for example, "Avicii the nights lyrics" on [google.com](http://google.com/)

So if Spotube makes a command for the user's device to load the term: **Singer name + song name + word "lyrics" in Google.com website** the chance of finding the lyrics of the songs is much greater, at the same time that the loading is extremely fast, precisely because of Google's infrastructure around the world. 

Even putting a singer from another country, like the name of his song that is in another language (brazilian portuguese, for example) and then the term "lyrics", Google.com is still able to find the lyrics of the song in the original language that is sung.

This could be implemented on all platforms currently supported by Spotube such as Android, Linux,
Windows and Mac.

**Comment by KRTirtho** [comment]
@jakecharlie no more worries. Spotube now uses Official Spotify Lyrics (Musixmatch) so all your issues should be resolved
Try the 2.7.0 and let me know

**Comment by RaptaG** [comment]
Closing because of the new, accurate official lyric support

**Comment by jakecharlie** [comment]
@KRTirtho @RaptaG 

Thank you, I will test it. I use F-droid. A curiosity: Why is the new apk in F-droid not updated as quickly as it is here on github (there it continues with version 2.6.0)? And is there any prediction of when version 2.7.0 will appear there?

**Comment by KRTirtho** [comment]
There's some difficulty going on with f-droid. Don't worry we'll update it as soon as possible

**Comment by jakecharlie** [comment]
@KRTirtho Is there any spotube external repository that I can manually add in the fdroid app so that the user can get updates faster? May e izzyondroid or maybe a spotube specific link.

Thank you

**Comment by KRTirtho** [comment]
F-droid isn't delaying the build. There were some build configs I didn't update before hand :p
