### ISSUE TITLE
[Bug] Release 2.7.0 Android not updateable - RedMi Note 8 Pro

### ISSUE THREAD

**Issue by Patronos** [KRTirtho/spotube#425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello!

First of all thank you for this great application that I really enjoy using.
Today I opened up Spotube v2.6.0 on my Android Phone and I was prompted with an update to v2.7.0. After downloading it using Google on my Phone I was asked to update the version. During installation I get an requester telling me that v2.7.0 is *not* updateable.
Now I am stuck with v2.6.0. Is there an regression somewhere ?

Thanks

### Expected Behavior

Installation of v2.7.0

### Steps To Reproduce

1. Open Spotube v2.6.0 on Android
2. You get a dialog telling you there is an update to v2.7.0
3. You click on the download link which opens google chrome
4. You download the file and click on open after it has been downloaded
5. You install the downloaded package but it aborts with *not installed*
6. Always reproducable. Reboot, Reset, De-Install and New-Install all fails.

### Spotube Version

v2.7.0

### Operating System

Android

### Operating System Version

Could be Android 10 (MIUI 12.7.0)

### Installation Source

Official Website (spotube.netlify.app)

**Comment by KRTirtho** [comment]
There was an error on the release pipeline so  the binaries weren't uploaded then
Try now it's been fixed

**Comment by Patronos** [comment]
Hi, thanks for the feedback.

Tried it a couple of moments ago.

Same issue.

**Comment by KRTirtho** [comment]
Oh, that's simple. Just uninstall the previous version of the app and then install the new downloaded one

**Comment by KRTirtho** [comment]
You've to re-download the app btw
