### ISSUE TITLE
[Bug] flatpak update resulted in log out

### ISSUE THREAD

**Issue by rizajur** [KRTirtho/spotube#431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

 flatpak update resulted in log out of spotify, normal?

### Expected Behavior

keep the user login data across updates (if possible)

### Steps To Reproduce

1. flatpak install older version
2.  login with spotify
3. update
4. see ur no longer logged in

### Spotube Version

2.6.0 

### Operating System

Linux

### Linux Distribution (if applicable)

Debian

### Operating System Version

12

### Installation Source

Flathub (Flatpak)

**Comment by KRTirtho** [comment]
Flathub builder hasn't yet built 2.7.0 of spotube which usually takes 2 days. Wait till it updates

**Comment by KRTirtho** [comment]
Flatpak uninstaller removes all data of the uninstalled app too. So can't do anything about it

**Comment by KRTirtho** [comment]
flatpak 2.70 isn't even out yet. How are u updating spotube?

**Comment by rizajur** [comment]
>2.6.0 

i edited very shortly after checking the version.
latest in terms of flatpak ... :laughing: 
anyway i had the same with lbry but not with moonlight 

maybe something flatpak related? (new way of organizing the program files or what ever)
using Flatpak 1.14.2
