### ISSUE TITLE
Add support for Android 13 monochrome icon

### ISSUE THREAD

**Issue by meenbeese** [KRTirtho/spotube#433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of the Feature

UX Improvements

### Credits

The Android team under Google

### Pain

Hello.

The new app icon is much more beautiful and cleaner. Despite this, the app is still missing a monochrome icon that works on Android 13. This would provide a lot of consistency throughout my app drawer, as most of my other icons are already themed. Please consider adding this, for it would be a nice improvement.

### Suggested Solution

Android has descriptive instructions on what resources to add in the AndroidManifest.xml file of the project. There is a link for that below.

### Useful resources/references

https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

**Comment by singhh9596** [comment]
Much needed.
