### ISSUE TITLE
[Bug] Documents folder get filled with spotube temp files (flatpak)

### ISSUE THREAD

**Issue by rizajur** [KRTirtho/spotube#438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

/home/user/Documents/oss.krtirtho.spotube.cache.infinite_queries.hive
/home/user/Documents/oss.krtirtho.spotube.cache.infinite_queries.lock
 /home/user/Documents/oss.krtirtho.spotube.cache.queries.hive 
/home/user/Documents/oss.krtirtho.spotube.cache.queries.lock 
/home/user/Documents/spotube_cache.hive 
/home/user/Documents/spotube_cache.lock
/home/user/Documents/track-cache.hive
/home/user/Documents/track-cache.lock

### Expected Behavior

use a hidden user dir directory and a sub directory for spotube files

### Steps To Reproduce

1. install via flatpak
2. enjoy Documents folder getting messy ( i guess you have to login etc)

### Spotube Version

2.6.0

### Operating System

Linux

### Linux Distribution (if applicable)

Debian

### Operating System Version

12

### Installation Source

Flathub (Flatpak)

**Comment by rizajur** [comment]
@KRTirtho this issue should be quite easy solvable i hope you address it since its quite annoying

**Comment by Derisis13** [comment]
I'd suggest another fix: use the `$XDG_CACHE_DIR` environment variable. As the problem seems linux-specific, the solution should be one too. If the env var isn't set, then fallback could be `$HOME/.cache`. Please don't put anything in Documents.

**Comment by KRTirtho** [comment]
It has been fixed & released
