### ISSUE TITLE
Lag before loading playlists and songs?

### ISSUE THREAD

**Issue by cameronmgj** [KRTirtho/spotube#439]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I select a song it takes at least 15s to load, I have also tried the previous release version of spotube and the same lag was present. Turning off pre download, and turning off sponsor block made no difference.

### Expected Behavior

Quick response time

### Steps to reproduce

I opened and clicked on any song

### Operating System

Android

### Spotube version

V2.7.0

### Installation source

F-Droid (Android)

**Comment by RaptaG** [comment]
I think F-Droid doesn't support v2.7.0 yet, so how did you install it from there.
Also about your issue, it's a known bug and a duplicate of #313

**Comment by cameronmgj** [comment]
Sorry, I should have explained. I installed .6 with fdroid and it said
there was an update so I uninstalled it and installed .7

**Comment by RaptaG** [comment]
Nope, not that I know of.
