### ISSUE TITLE
Can't login into Spotube

### ISSUE THREAD

**Issue by acidicneko** [KRTirtho/spotube#440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to login into Spotube using Spotify app clientID and clientSecret but when I hit "submit" nothing happens.
No warning or errors, it just remains still.
![image](https://user-images.githubusercontent.com/57079688/224624858-5b8c510b-6d30-4dee-a064-0ef1c8a66413.png)

### Expected Behavior

Should've logged into my account.

### Steps to reproduce

1. Opened the app
2. entered client ID and clientSecret in "sp_dc Cookie" and "sp_key Cookie" fields respectively
3. Hit enter

### Operating System

Windows 11 Ver 21H2

### Spotube version

v2.7.0

### Installation source

chocolatey (Windows)

**Comment by mjzjz** [comment]
same question，I still don’t know how to login.

**Comment by KRTirtho** [comment]
@mjzjz there's a step a step guide how to login in Spotube. Please follow that and you should be able to login
![image](https://user-images.githubusercontent.com/61944859/230143399-51c720e8-ca90-4a81-95f1-8de1a3bb5afe.png)

**Comment by mjzjz** [comment]
> @mjzjz there's a step by step guide on how to login in Spotube. Please follow that and you should be able to login
> ![image](https://user-images.githubusercontent.com/61944859/230143399-51c720e8-ca90-4a81-95f1-8de1a3bb5afe.png)
> 

I just followed it.I hit the button "submit",and there is nothing happened.No error or anything else.And I don't know what should I do.

**Comment by mjzjz** [comment]
Yes,I just followed the guide.I'm out now,but I could show you the screenshot later,if the problem still exists.

**Comment by dsh2595977663** [comment]
The same question. I found my sp_dc and sp_key and hit “submit”. Nothing happen. Just remain the page "Step 5".
The lastest version. Win10 Ver 22H2.
Can you give me some advice? Thank you

> Did you correctly copy and paste the `sp_dc` and `sp_key` in their respective fields?

**Comment by Torpedro1978** [comment]
I have the same issue 
Windows 10 V2.7.1

At least any kind of reaction from the program shoulp come... "invalid Input", or anything else.

It worked on Kubuntu 23.04. though.

**Comment by Byrnesdigital** [comment]
Same issue for me on Windows 10 22H2 19045.3086 . The login prompt and subsequent guide also always launches with a transparent background. While not a huge issue it's a little hard to see.

**Comment by Kamek437** [comment]
Same here only it logs me in, but never shows the content it just continuously displays a loading spinner in left corner but never shows content or allows me to play anything. I'm thinking this might be because my adfiltering dns or something I'll try it without it.

**Comment by Coder-Harshit** [comment]
> Same here only it logs me in, but never shows the content it just continuously displays a loading spinner in left corner but never shows content or allows me to play anything. I'm thinking this might be because my adfiltering dns or something I'll try it without it.

does it work ?

**Comment by Coder-Harshit** [comment]
i also had the same issue but it resolved As Soon as switched the internet from College Wifi to Personal Wifi but i am not so sure it would be greatly helpful if some kind of popup could appear after some time (TIMEOUT ALERT!)

**Comment by KRTirtho** [comment]
Looks like all these are related to #706

**Comment by KRTirtho** [comment]
Recently because of adding WebView support on desktop #1688 this has become an obsolete issue

Closing
