### ISSUE TITLE
Scrobbling support

### ISSUE THREAD

**Issue by isle9** [KRTirtho/spotube#445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

I would like to be able to send my scrobbles to last.fm and ideally listenbrainz too.

### Suggested solution

Develop a stand alone scrobble integration.

### Additional information

The current workaround on mobile is to use an app, but it's a bit more difficult on desktop.

**Comment by xCakes** [comment]
i support!

**Comment by KRTirtho** [comment]
This is similar to https://github.com/KRTirtho/spotube/issues/466 as both will offer to create a personal musical profile
But both takes different approach. I bet having both as an option will be the best

**Comment by KRTirtho** [comment]
But this will require extra logging into last.fm or soundbrainz

**Comment by binaryben** [comment]
Please try to make it platform agnostic as much as possible. Also keen for support for [Maloja](https://github.com/krateng/maloja)

**Comment by RaylaLe100** [comment]
I'm really looking for the lastfm integration, it's the one thing that keeps me from using spotube on a wider scale.

**Comment by KRTirtho** [comment]
Unfortunately, I'm unable to make time in my tight schedule 😓  . I'd love if any kind person can pick this up & create a PR 😇

**Resources**
- https://pub.dev/packages/scrobblenaut (https://github.com/Nebulino/Scrobblenaut)
- https://www.last.fm/api

> unfortunately, the `scrobblenaut` package is outdated but can be easily updated to support Dart 3
Btw this PR branch can be used https://github.com/Nebulino/Scrobblenaut/pull/41 as it is null safe

[lib/provider/proxy_playlist/proxy_playlist_provider.dart](https://github.com/KRTirtho/spotube/blob/master/lib/provider/proxy_playlist/proxy_playlist_provider.dart) is the file where playback related stuffs are handled.
`LastFM` can be easily integrated here. And please follow the [YouTube](https://github.com/KRTirtho/spotube/blob/master/lib/provider/youtube_provider.dart) or [Spotify](https://github.com/KRTirtho/spotube/blob/master/lib/provider/spotify_provider.dart) client initialization (using riverpod `Provider`)

Also, an entry will be needed to be entered in `accounts` section of  [/settings](https://github.com/KRTirtho/spotube/blob/0ab1dcaa6b9195e411ca2cb62e6512d0e0dbd051/lib/pages/settings/settings.dart#L72C23-L72C23) page in the to allow the user to login with LastFM

To store the LastFM credentials the [AuthenticationProvider](https://github.com/KRTirtho/spotube/blob/master/lib/provider/authentication_provider.dart) can be utilized. Also, to let the user enter credentials we will need a new Login Page for LastFM. You can follow the [components/desktop_login/login_form.dart](https://github.com/KRTirtho/spotube/blob/master/lib/components/desktop_login/login_form.dart) for inspiration.

> PS: Make sure to keep the new widgets as theme compatible as possible (3rd party widgets shouldn't be needed) 
That means use the `Theme.of(context).colorScheme` for coherence.

**Comment by Robin-Sch** [comment]
Is there any plan for enabling listenbrainz scrobbling support? Or a self hosted version of maloja like mentioned before?

**Comment by KRTirtho** [comment]
I tried to create an API client for listenbrainz but their docs is so confusing I didn't even manage get the base url for the API 😅
