### ISSUE TITLE
Store yt urls via locally [speed fix]

### ISSUE THREAD

**Issue by cameronmgj** [KRTirtho/spotube#450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

Slowwwww

### Suggested solution

Locally store a file with a dictionary of song ids and 1-5 youtube urls for the song. Written to whenever a new song not present in the file is played. Only do this for liked songs and songs in playlists. Check this list when a song about to be played is stored in a playlist or liked. Potentially reduces load time for songs (which is currently ridiculous).

Also, allow selecting default sources for tracks so that no. of sources stored in dictionary can be reduced. Only search YouTube for sources if track not in likes and not in playlist, or alternative sources button clicked.

Could be an optional setting if people don't want to use more storage (although shouldn't use much)

### Additional information

Only need to query spotify on setup of program, when opened and when new song played. Only need to query yt when new song played.

**Comment by cameronmgj** [comment]
I would attempt this myself, and will have a look anyways but have no experience using the spotify api or flutter. :(

**Comment by KRTirtho** [comment]
This is already implemented and was available from v2.6.0. Spotube by default, caches all the songs played for certain period of time. Btw, this only works when __Settings > Pre-download and Play__ is enabled

**Comment by KRTirtho** [comment]
Closing this as complete
