### ISSUE TITLE
New login mechanishm doesn't save the state of logged in.

### ISSUE THREAD

**Issue by PranavBhattarai** [KRTirtho/spotube#452]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- opened spotify.com from firefox
- pasted the **sp_dc** value
- pasted **sp_key** value
- Successfully logged in 
- Exit the app
- Launched the app
- Didn't save the logged-in state. Users need to re-login at each launch. 

### Expected Behavior

- Saved Login session

### Operating System

Fedora 37

### Spotube version

2.6.0

### Installation source

Flathub (Flatpak)

### Additional information

Why flatpak's version of Spotube is not updated to 2.7.0?

**Comment by KRTirtho** [comment]
Try with 2.7.0? There's also an RPM now

**Comment by PranavBhattarai** [comment]
@KRTirtho 

Thank you for updating Spotube in Flatpak. 
I've tried the latest version (2.7.1) of Spotube from Flatpak, but it didn't save the logged-in session after when I closed the app.

And I also tried to install Spotube, but it threw a dependency error:

```
sudo rpm -i Spotube-linux-x86_64.rpm
error: Failed dependencies:
 	gstreamer1-devel is needed by spotube-2.7.1+18-18.x86_64
 	gstreamer1-plugins-base-devel is needed by spotube-2.7.1+18-18.x86_64
 	gstreamer1-plugins-base-tools is needed by spotube-2.7.1+18-18.x86_64
```
I can install those devel dependencies, and try the RPM version of Spotube if you ask...
But I like to relay more on Flatpak if possible.

What do you want me to do? Install dependencies and try it?

**Comment by KRTirtho** [comment]
> What do you want me to do? Install dependencies and try it?

Of course those are dependencies and you've install it in order to run that's a no-brainer dude 😄
