### ISSUE TITLE
Deb packages should not have dev dependencies

### ISSUE THREAD

**Issue by kupiqu** [KRTirtho/spotube#459]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Spotube requires installing dev packages

### Expected Behavior

dev packages should not be dependencies as they are only needed to compile the source code

### Steps to reproduce

1. Install the deb package from releases
2. it asks to install dev packages

### Operating System

Debian and derivatives

### Spotube version

v2.7.0

### Installation source

GitHub Releases (Binary)

**Comment by KRTirtho** [comment]
I don't use a Debian/Ubuntu system anymore nor willing to use now, so I don't know if the `*-dev` dependency is required anymore. Will be really wholesome if anyone with such device + OS could verify that and create a PR

**Comment by KRTirtho** [comment]
This has been fixed + released
