### ISSUE TITLE
No automatic reproduction of next songs in the Flatpak version

### ISSUE THREAD

**Issue by JorgeHernandezH** [KRTirtho/spotube#46]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Installation Source/Method**
- Package Manager: <e.g flatpak/chocolatey>
- Community Repo: <e.g AUR/appimagehub>
- Binary Source: <resource_url>

**Desktop (please complete the following information):**
 - OS: [e.g. archlinux]
 - Version [e.g. v1.0.0]

**Smartphone (please complete the following information):**
 - Version [e.g. v1.0.0]

**Additional context**

**Comment by JorgeHernandezH** [comment]
When I play a playlist from my library, only the first song plays, the next song doesn't play automatically.

**Comment by KRTirtho** [comment]
Can you run the app from the terminal & then submit the output logs?

**Comment by JorgeHernandezH** [comment]
> Can you run the app from the terminal & then submit the output logs?

![Captura de pantalla de 2022-03-30 22-04-40](https://user-images.githubusercontent.com/69211300/160974340-dd189132-8b6c-403e-94ea-01adf7c58e80.png)

**Comment by JorgeHernandezH** [comment]
do you mean this?

**Comment by KRTirtho** [comment]
So I checked & it seems like it's only happening with the Flatpak version of Spotube. It might take a little bit of time to get fixed. Meanwhile, you can use the the [Spotube AppImage](https://github.com/KRTirtho/spotube/releases/download/v2.0.0/Spotube-linux-x86_64.AppImage)

**Comment by JorgeHernandezH** [comment]
Thanks, The AppImage does not have that problem, but, instead almost on Fedora 35, for spotube to appear in the menu you need to create a .desktop manually.

**Comment by KRTirtho** [comment]
Use [appimage-launcher](https://github.com/TheAssassin/AppImageLauncher). It'll do this stuff automatically

**Comment by prasanth-G24** [comment]
@KRTirtho also the shortcut for next/ previous aren't working in the flatpak version. also it would be really helpful to have a repeat button. thank you for this wonderful app!

**Comment by KRTirtho** [comment]
Bad news, I just found out the audio engine used for Spotube in Linux (libwinmedia) is archived & deprecated. It hasn't been updated for at least 4 months & now it lost its compatibilty with the latest version of webkit2gtk

Audio Playback is fine mostly except there's an issue with audio file processing stream. The stream should notify when the currently playing track is completed (finished playing) but for some unknown reason it's not firing the event thus playlist position change method `movePlaylistByPosition` never gets called
https://github.com/KRTirtho/spotube/blob/3b7f7785b66e63dfe56b07c49d009441ad56219b/lib/provider/Playback.dart#L113-L130

**Comment by KRTirtho** [comment]
Well, I did a workaround to fix the issue. Now the playback works fine (Gnome 42). But I won't use the same package for long & will do a permanent replacement to get rid of the issue completely

The fixed version will be available in the nightly build within couple of hours hopefully

**Comment by KRTirtho** [comment]
fixed in the latest release. there will be a little delay for flatpak version as it syncs the repositories once a day

**Comment by PranavBhattarai** [comment]
Thank you. Waiting for Flatpak release.
