### ISSUE TITLE
Spotube jerks/stops

### ISSUE THREAD

**Issue by siggi1984** [KRTirtho/spotube#462]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After starting the app, it runs normally for the time being. After a few songs, the app starts to jerk and no longer runs smoothly.

### Expected Behavior

Ein gleichmäßiges und ruckelfreies funktionieren der App.

### Steps to reproduce

I have tried different versions
v 2.5, 2.6, 2.7.
Unfortunately the same problem with all of them.

I have a Samsung Galaxy A8 (2018). 
I can't imagine that it's because of the Hady or are there other solutions.

### Operating System

Android 9

### Spotube version

v2.7

### Installation source

GitHub Releases (Binary)

**Comment by RaptaG** [comment]
Thankfully for you I know some German so I understood what you wrote there
