### ISSUE TITLE
Add support for Bandcamp

### ISSUE THREAD

**Issue by forteller** [KRTirtho/spotube#464]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

I have some music with Bandcamp, but I always forget about it. Being able to log in to Bandcamp in Spotube and playing my Bandcamp music from there would be fantastic!

### Suggested solution

Adding the Bandcamp music to the Library tab after logging in

### Useful resources

I'm no coder, so I don't know if this is possible, but if it is I think you'll find what you need here: https://bandcamp.com/developer

### Additional information

Thanks again! :)

**Comment by KRTirtho** [comment]
Sorry, such feature is never planned to be implemented & Spotube is only meant to be used with Spotify. If you want import your playlists from some other music provider use services like:

- https://soundiiz.com/
- https://www.tunemymusic.com
