### ISSUE TITLE
[Feature] Better animations, transitions and loading animations

### ISSUE THREAD

**Issue by KRTirtho** [KRTirtho/spotube#467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

Currently, 
- The transitions are terrible as Spotube currently uses Material You (Material 3.0) page transitions which are jittery and laggy.
- There's literally no animation in the app, everything is super boring
- The loading animations straight sucks

### Transitions:
- We could ditch regular transitions offered by material_ui or start to utilize material Hero animations
- Use slide up animations for bottom sheets (confusing as to why material ui doesn't do this by default)
   - Mobile Player pull up/down animation that is fluid with touch
   - Queue up/down animation that is fluid with touch
   - Mobile Lyrics modal fluid up/down animation
   - Alternative track source fluid up/down animations

### Loading Animations:
- Loading animations straight up sucks, replace them with some good [rive.app](https://rive.app) animations
- Playlist/album character/mascot based loading animation

### UI Animations:
- Introduce friendly animation for the empty lists/page
- Subtle UI animations for heart/favorite, download button
- Play/pause button icon animation
- Donate button animations

### Useful resources

- [rive.app](https://rive.app)

### Additional information

This is a big task, will be executed best if helped by some passionate animator/artist

**Comment by RaptaG** [comment]
Fixed in 3.0.0
