### ISSUE TITLE
Windows 7 ESU Support

### ISSUE THREAD

**Issue by darkalexis1990** [KRTirtho/spotube#469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![Capture1](https://user-images.githubusercontent.com/107497874/230773684-8300df39-45e3-4540-98d4-070fc3b34673.JPG)

can you add support for WIN7 esu please?

### Expected Behavior

crashing

### Steps to reproduce

error message

### Operating System

Windows

### Installation source

Website (spotube.netlify.app)

**Comment by karniv00l** [comment]
64 or 32 bit?

**Comment by KRTirtho** [comment]
I think `audioplayers` doesn't support Windows 7 or it could be other plugin

**Comment by woeisme** [comment]
I'd love a working win7 version too!

**Comment by KRTirtho** [comment]
As much as I love Windows 7, it is hard to admit supporting such an old OS will be a nightmare. Flutter barely supports Windows 7 and a lot of its plugins are written to run on Windows 10/11. And manually re-creating those plugins isn't a viable option as Spotube has to support 5 other platforms too. And for an incomplete application like Spotube, features and stability is much more important than supporting a legacy OS

**Comment by darkalexis1990** [comment]
ok ..... :(
