### ISSUE TITLE
Memory leak after following a new artist

### ISSUE THREAD

**Issue by Saacman** [KRTirtho/spotube#471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After pressing the follow button on an artist page Spotube starts chugging RAM until it allocates all system memory.
![Screenshot from 2023-04-09 22-38-05](https://user-images.githubusercontent.com/16470786/230795488-6b91406b-22bb-4b20-a371-0964fb7e37de.png)

### Expected Behavior

Continue the playback with a normal amount of memory allocation (I noticed around 150mb during normal playback)

### Steps to reproduce

1. Go to search
2. Search for an artist
3. open the artist page
4. press follow

### Operating System

Linux

### Spotube version

2.6.0

### Installation source

Flathub (Flatpak)

### Additional information

Music was playing when this happened, and I haven't tried the unfollow button. Pretty nice player otherwise.

**Comment by KRTirtho** [comment]
That's an old bug and fixed please use 2.7.0
