### ISSUE TITLE
Ubuntu 22.04.1 cannot install deb

### ISSUE THREAD

**Issue by woeisme** [KRTirtho/spotube#476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Unable to install the program using existing debian / ubuntu instructions. 
Apt complains about dependencies such as "libgstreamer1.0-0" and "gir1.2-gstreamer-1.0" since using `apt install` method will not resolve dependencies. 

### Expected Behavior

program installed.

### Steps to reproduce

1. grab debian package 
2. sudo apt install ./Spotube-linux-x86_64.deb (or alternatively use Gdebi)
3. failure to install due to dependency issues

### Operating System

Ubuntu 22.04.1

### Spotube version

2.7.1+18

### Installation source

Website (spotube.netlify.app)

### Additional information

I'd recommend setting up a ubuntu PPA 

https://askubuntu.com/questions/71510/how-do-i-create-a-ppa

this will allow rolling packages and allow automatic dependency resolution.

**Comment by runechronicler** [comment]
Same goes with `Ubuntu 22.04.02` here, for me it's complaining about :
`libjsoncpp.so.25: cannot open shared object file: No such file or directory`

**Comment by KRTirtho** [comment]
Try `apt install libjsoncpp25`

**Comment by KRTirtho** [comment]
This has been fixed on 3.0.0
