### ISSUE TITLE
Mimic platform configuration is not saved

### ISSUE THREAD

**Issue by Somaxa8** [KRTirtho/spotube#478]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I change the "Mimic platform" option, that configuration is changed but not stored

### Expected Behavior

The mimic platform configuration must be stored when changing it like the rest of the options

### Steps to reproduce

1. I opened the app
2. I go to the settings section
3. I change the option of the mimic platform select
4. I close the app and reopen it

### Operating System

Linux

### Spotube version

v2.7.1

### Installation source

Flathub (Flatpak)

**Comment by KRTirtho** [comment]
Unfortunately this feature is removed. So this issue isn't valid anymore
