### ISSUE TITLE
Download lyrics along with track doesn't work

### ISSUE THREAD

**Issue by Turhvjbufv** [KRTirtho/spotube#479]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Should download the track and .lrc file with synced lyrics 

### Expected Behavior

Only downloads the track

### Steps to reproduce

Open the app choose a random song and download it

### Operating System

Android 

### Spotube version

2.7.1

### Installation source

GitHub Releases (Binary)

**Comment by KRTirtho** [comment]
This feature is incomplete as downloading lyrics as txt file is completely useless since you can't even use it. We're are now planning on embedding lyrics in the mp4 metadata which is supported by many players and media servers

**Comment by ThreeDeeJay** [comment]
There are tons of players (including Android) that support .[LRC](https://en.wikipedia.org/wiki/LRC_(file_format)#File_format) (scrolling lyrics) format, though.
Would be nice to download even lyrics alone for existing files that other lyrics sources don't yet have an LRC file for.

**Comment by ThreeDeeJay** [comment]
@KRTirtho Do Spotify/Spotube already use LRC for scrolling lyrics? Cuz I just noticed this line https://github.com/KRTirtho/spotube/blob/ca2b81d5720c79fcaaa545c990f8770243f0bf6a/lib/utils/service_utils.dart#L218
If so, I think all we'd need is for the LRC to be copied next to the track file with the same file name for other apps to load it

**Comment by ThreeDeeJay** [comment]
In case anyone cares, just found out about this https://github.com/Lambada10/SongSync
