### ISSUE TITLE
Android client on F-Droid

### ISSUE THREAD

**Issue by shom13** [KRTirtho/spotube#48]
First of all great work. I am really enjoying the app so far. Any chance of seeing the android app uploaded to F-Droid

**Comment by KRTirtho** [comment]
I've been actually working in this recently but I think the process to upload a simple application to F-Droid is kind of overly complicated & the steps documented in the documentation is kind of confusing too. It's possible that I'm new to F-Droid (actually haven't heard of it before this Issue) & that is why its hard for me
But if you/anyone is experienced in F-Droid, if possible please simplify the process & give a clear & concise idea about how can I make my app available in the F-Droid repository

It'll massively help this project's Android part

**Comment by shom13** [comment]
@KRTirtho Thanks for taking note. Yes fdroid is a great platform for open source apps. Unfortunately i am not much of a developer, but will definitely see what i can do and get back to you. Meanwhile if you find a way, do keep us posted

**Comment by IzzySoft** [comment]
@KRTirtho thanks for your efforts! As pointed out, I'll gladly help you get it going (disclosure: I'm one of the F-Droid maintainers). Mentioned [Fastlane structures](https://gitlab.com/-/snippets/1895688) would be the first step (for starters, just the `short_description.txt` and `full_description.txt` for `en-US` would do, though I highly recommend to include some screenshots, too). With that in place, I could run a pre-check by adding your app to m repo (which often serves as stepping stone on the way to F-Droid.org – literally hundreds of apps went this way already).

For simplicity, let's do it step by step – this first stage passed I'd lead you on, choosing the easy approach. As the saying goes: many roads lead to Rome. The one you mentioned is "the king's road", there are [easier ones](https://android.izzysoft.de/articles/named/fdroid-intro-2#rfp) available :wink:

**Comment by IzzySoft** [comment]
To give you a "quick taste" I've just [added your app](https://apt.izzysoft.de/fdroid/index/apk/oss.krtirtho.spotube) to my repo (will show up at the link in about 5h from now with the next sync). Some (Android-App) screenshots would be much appreated (you see it looks quite "naked" now), I could then provide you with a "fastlane starter package".

One more thing I've noticed: you're not taking care for the `versionCode`, which is still set to `1` despite of multiple versions have been released already. Android uses `versionCode`to tell versions apart, so it's important to inrease that with eah release. This being a Flutter app, the proper place would be [here in `pubspec.yaml`](https://github.com/KRTirtho/spotube/blob/master/pubspec.yaml#L18), which should read something like

```yaml
version: 2.1.0-pre+9
```

(i.e. `<versionName>+<versionCode>`).

**Comment by KRTirtho** [comment]
I added descriptions & screenshots. Now as far as I know I've to fork fdroid/data repo in gitlab, create a branch with my appId & a `oss.krtirtho.spotube.yaml` file with build+update instructions in the `metadata` directory
I did that part but the build fails in parts

[Here's the metadata file](https://gitlab.com/krtirtho/fdroiddata/-/blob/oss.krtirtho.spotube/metadata/oss.krtirtho.spotube.yml)
[build error logs](https://gitlab.com/krtirtho/fdroiddata/-/jobs/2291610467)

**Comment by KRTirtho** [comment]
I fixed most of the part & now the build works mostly fine but before building I also have to generate some secrets that are used in the application ([see here](https://github.com/KRTirtho/spotube/blob/3b7f7785b66e63dfe56b07c49d009441ad56219b/.github/workflows/flutter-build.yml#L21)) but I don't see anyway to do that in F-Droid's metadata/build-schema file
@IzzySoft Is there anyway I can use _secrets_ at build in F-Droid?

**Comment by IzzySoft** [comment]
I've just checked your metadata, and first a few notes on that:

* `short_description.txt` is limited to 80 chars (hence "short"), yours is much longer and thus will be truncated
* if in `full_description.txt` you'd insert another line break directly before the bullet point list, that'd be properly formatted as Markdown (and I could then use it with my repo)
* screenshots are fine, just updated the listing with my repo (taking effect with the next sync around 6 pm UTC today)

Now let's have a look at your logs.

* YAML:
  * Please remove summary & description there, else they're not taken from fastlane
  * If you're using `FUNDING.yml` (which you do), the `OpenCollective:` entry can be removed as well (it's taken from `FUNDING.yml` then which, like Fastlane, gives you the flexibility to update it anytime without requiring another MR to get it into effect)
  * all else looks fine (though I'm not sure if the `output:` line is needed. Doesn't hurt IMHO, though)
* build log: the message is quite clear, it says "fdroidserver.exception.VCSException: Git checkout of 'v2.10.2' failed". Reason is quite obvious as well: there is no such tag :rofl: Cause is… uh? Strange. Why is it going for v2.10.2? I see that nowhere in the YAML. Ah, wait, that's Flutter. And that has a `2.10.2` – but I have no idea what adds the `v` in front. I've checked with other YAMLs in our metadata, and see several with `flutter@2.10.1` and `flutter@2.10.3`, so the syntax should work. Could it be the fix 6h ago was removing the `v` there?
* secrets: no idea, I'm not an Android dev. You could ask that at the Matrix/IRC channel, or search the issues/the forum.

**Comment by linsui** [comment]
@momobobe You can follow the progress [here](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11101)

**Comment by KRTirtho** [comment]
@momobobe I've already submitted the app in fdroiddata after I was able to make a successful build in my fork. Now its only hold for review https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11101

**Comment by KRTirtho** [comment]
Great news everyone. My PR to add Spotube to fdroid has been merged recently. So Spotube should be available on F-Droid's official repository from tomorrow

**Comment by KRTirtho** [comment]
Awesome news everyone __Spotube__ is finally available in the official F-Droid repositories🎉
Now you can directly download Spotube from F-Droid client application

![image](https://user-images.githubusercontent.com/61944859/174589268-39a5d243-c9ce-4fac-bd0e-ac34a9b4f06f.png)


Special thanks to💖:
- @IzzySoft 
- @linsui 
- @momobobe

**Comment by IzzySoft** [comment]
Gladly! And happy to read :smiley: So I'll remove it from my repo then after a ~10 day overlap (unless you insist I keep it) to avoid confusion with signatures and stuff?

**Comment by KRTirtho** [comment]
> So I'll remove it from my repo then after a ~10 day overlap (unless you insist I keep it) to avoid confusion with signatures and stuff

As you say, you can remove it from your repo if you want

**Comment by IzzySoft** [comment]
Okay, thanks! Should you need it back later for some reason, just let me know. Easy enough to re-establishas I'll just archive the metadata then.

**Comment by KRTirtho** [comment]
Thanks a lot for your help & support

**Comment by flexagoon** [comment]
@shom13 @KRTirtho please close this issue if it's already resolved.
