### ISSUE TITLE
Volume resets on program launch

### ISSUE THREAD

**Issue by bengalbroy** [KRTirtho/spotube#481]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The volume I set manually doesn't save when I close and re-open the program. It defaults back to the default volume of the program & if I use EarTrumpet to try and get the volume to stick it resets that too. 

### Expected Behavior

The volume to stay at what I set it as. 

### Steps to reproduce

1. Open the app, set the volume level you want manually (lower than default) 
2. Close the app & re-open it

### Operating System

Windows 10 22H2 (19045.2788)

### Spotube version

v2.7.1

### Installation source

Website (spotube.netlify.app)

**Comment by KRTirtho** [comment]
Nope. It works fine. Check if something else is causing this. Perhaps, check if Spotube access the user "Documents" directory as this is where all of it cache files are stored (for now)

**Comment by RaptaG** [comment]
Fixed in 3.0.0
