### ISSUE TITLE
Low follower count should be represented as integer

### ISSUE THREAD

**Issue by ruzko** [KRTirtho/spotube#482]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

All follower counts are represented as floating point(?), even very low numbers.
It looks somewhat weird for an artist to have "428.0 Followers".
E.g. see the image
![Screenshot_20230417-150820](https://user-images.githubusercontent.com/75946143/232495589-1accce69-ab32-49c2-ba8a-787a02cfdf53.png)

### Expected Behavior

Low follower counts are represented as integers, and at some point, for example 1000 followers, representation changes to "1.0k followers"

### Steps to reproduce

1. I opened the app (downloaded from F-droid)
2. Find an underlistened artist with sub 1000 followers
3. Voila

### Operating System

Android 10

### Spotube version

v.2.7.1

### Installation source

F-Droid (Android)

### Additional information

I discovered this app last week and it's already shot waay up my list of most used apps.
Thank you so much for developing it, great work!

**Comment by KRTirtho** [comment]
Yeah make sense. We devs often ignore this kind of small bugs 😅

**Comment by ruzko** [comment]
If I get time this week, I can try to implement something and open a pull request. Should be doable for me, I think :)

**Comment by RaptaG** [comment]
Fixed in 3.0.0
