### ISSUE TITLE
Add a way to delete downloaded songs from tracks

### ISSUE THREAD

**Issue by Nate-12** [KRTirtho/spotube#484]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

I have not been able to delete any songs on my phone from the app or from files. I would like to see a way to delete songs in app. Another feature would be to be able to organize download songs in folder's or just in order.

### Suggested solution

You could add a way to delete songs in app

### Useful resources

Android 12 
Pixel 3a

**Comment by Nate-12** [comment]
I would recommend a way to tap and hold to select the downloaded track and then add a option to delete and select all.

**Comment by RaptaG** [comment]
Added in 3.0.0
