### ISSUE TITLE
Scoop version of Spotube crash on Launch

### ISSUE THREAD

**Issue by vallx-ny** [KRTirtho/spotube#485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Spotube crashes on Launch

### Expected Behavior

Spotube to not crash on launch

### Steps to reproduce

Open Spotube and the program will crash

### Operating System

Windows

### Spotube version

2.7.2

### Installation source

Scoop (Windows)

### Additional information

I already tried re-installing from different sources and the problem persists. I believe is some kind of corrupted installation as I use spotube in other devices without any problems, so I don't think it's related to Scoop.
I tried deleting some of the cache files in mydocuments and the issue persists, am I missing any other config files? - I believe deleting all of them and doing a clean install could solve it.

**Comment by KRTirtho** [comment]
What version of Windows you're using?
Can you please provide the logs available in the `.spotube_logs ` from `Documents` folder?

**Comment by sofiaritz** [comment]
This is also happening to me. I use Windows 10 22H2, I've downloaded the installer from the Spotube page. The `.spotube_logs` file is empty.
