### ISSUE TITLE
Can't repeat/loop single song

### ISSUE THREAD

**Issue by CKMz17** [KRTirtho/spotube#487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I don't understand how to repeat a song endlessly.

### Expected Behavior

Well, idk, maybe pressing loop/repeat icon in right bottom on player UI it should repeat playlist or the queue

### Steps to reproduce

I tried both these ways:
-Added the song in a new empty playlist and pressed the loop/repeat icon in right bottom on player UI but nothing, not working
-Searched song from artist page and played from there, pressed the loop/repeat icon in right bottom on player UI but nothing, not working

### Operating System

Android 10

### Spotube version

2.7.1

### Installation source

F-Droid (Android)

### Additional information

I haven't battery optimization for this app and I tried both in the background/screen locked and with the app screen active/screen unlocked

**Comment by RaptaG** [comment]
Added in 3.0.0
