### ISSUE TITLE
Windows version crashes on launch with no error messages 

### ISSUE THREAD

**Issue by Ahmedk-n** [KRTirtho/spotube#488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When opening the app it crashes after seconds.

### Expected Behavior

It should open normally

### Steps to reproduce

1. Install the app on windows 10 
2. Open it

### Operating System

Windows 10 

### Spotube version
2.7.1

### Installation source

Website (spotube.netlify.app)

**Comment by Ahmedk-n** [comment]
I checked the log file but it didn't record anything today here is it: 
`
============================== CATCHER LOG ==============================
Crash occurred on 2023-04-22 02:20:10.951086

------- DEVICE INFO -------
computerName: DESKTOP-2562TVS
numberOfCores: 4
systemMemoryInMegabytes: 8192

------- APP INFO -------
environment: release
version: 2.7.1
appName: spotube
buildNumber: 
packageName: spotube

---------- ERROR ----------
ClientException: {url: null, isAbort: false, statusCode: 404, response: {code: 404, message: The requested resource wasn't found., data: {}}, originalError: null}

------- STACK TRACE -------
#0      BaseCrudService.getFirstListItem.<anonymous closure> (package:pocketbase/src/services/base_crud_service.dart:125)
<asynchronous suspension>
#1      SpotubeTrack.fetchFromTrack (package:spotube/models/spotube_track.dart:84)
<asynchronous suspension>
#2      PlaylistQueueNotifier.play (package:spotube/provider/playlist_queue_provider.dart:374)
<asynchronous suspension>
#3      PlaylistView.playPlaylist (package:spotube/pages/playlist/playlist.dart:40)
<asynchronous suspension>

------- CUSTOM INFO -------
======================================================================
`

**Comment by KRTirtho** [comment]
Do you have [vcredist (2019-2022)](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022) installed for both x86 and x64?

**Comment by LittleYe233** [comment]
On my machine the lastest stable version 2.7.1 failed to work too, but the nightly build seemed to work well. I did not find a way to check out the crash log so I am not sure I met the same issue. Also I have installed the latest VC++ before these attempts.

**Comment by mendelsphotography** [comment]
happened by me to

**Comment by mendelsphotography** [comment]
i got an error. 
![2023-04-29_23-31-41](https://user-images.githubusercontent.com/61063382/235590009-ddc75777-66ed-4e10-9af6-c0d05d0e58ca.jpg)

**Comment by parkerjarnigan** [comment]
I get the same error as mendelsphotography ONCE ... installed via winget.  After the error, double checked that [vcredist (2019-2022)](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022) was installed for both x86 and x64

Reinstalled, still instantly crashes.  Most the time I get no error message, just a crash

**Comment by ustas-eth** [comment]
Same error with the latest version. I tried to install it with choco and an executable.

**Comment by KRTirtho** [comment]
Does Spotube v3 resolves this issue?

**Comment by ustas-eth** [comment]
> Does Spotube v3 resolves this issue?

Yes, it does, thanks!
