### ISSUE TITLE
Crash On Launch

### ISSUE THREAD

**Issue by IamDeepx** [KRTirtho/spotube#498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When app is launched it closes immediately.

### Expected Behavior

Launch and use Spotube with no issues.

### Steps to reproduce

1. Install app
2. Open app

### Operating System

Chromebook Android 9

### Spotube version

2.7.1

### Installation source

Website (spotube.netlify.app), GitHub Releases (Binary)

### Additional information

There is a issue like this but for windows.

**Comment by KRTirtho** [comment]
Sorry Chromebook isn't a supported platform
