### ISSUE TITLE
[Flatpak] Follow system theme

### ISSUE THREAD

**Issue by aha999** [KRTirtho/spotube#50]
**Is your feature request related to a problem? Please describe.**
Currently when you enter the app for the first time, it has a white theme, which is inconsistent with the system if you're using a dark theme system-wide and the apps adopt this.

**Describe the solution you'd like**
The app should follow the system theme by default. If the OS or desktop environment theme is dark, the app should have a dark theme, and vice versa. Manual theming options should of course still be accessible, but the default option should be "Follow system theme."

**My specs**
OS: EndeavourOS
App version Spotube v2.0.0
DE: KDE Plasma 5.24.4
App package installed: Flatpak

**Comment by KRTirtho** [comment]
The Flatpak version doesn't follow the system themes as the Flatpak sandbox doesn't provide the system color scheme yet. Although freedesktop has announced system theme access to snadbox for consistency recently but it might take little of time to get onboard

**Comment by KRTirtho** [comment]
Starting from v3 Spotube can now detect dark mode inside Flatpak as well
