### ISSUE TITLE
CJK characters missing in Flatpak version

### ISSUE THREAD

**Issue by FranGamer1892** [KRTirtho/spotube#500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Some song titles and author names are not being displayed correctly because they are CJK (Chinese, Japanese or Korean) characters. Probably because it is not included on the Flatpak version. 

### Expected Behavior

All song titles and author names should be displayed correctly.

### Steps to reproduce

1. Open the flatpak app
2. Look for Chinese/Japanese/Korean authors and songs

### Operating System

Debian 11

### Spotube version

v2.7.1 build 18

### Installation source

Flathub (Flatpak)

### Additional information

Images showing the problem in question:

![](https://user-images.githubusercontent.com/13150712/235335603-ed2b4f23-e46d-4e19-b0f7-8b18a82d941a.png)

**Comment by KRTirtho** [comment]
You're probably missing some fonts or your fonts doesn't support these languages

**Comment by FranGamer1892** [comment]
Sorry, but outside this app CJK characters on my system are working fine.
Maybe I am missing something?

**Comment by RaptaG** [comment]
Cannot reproduce

![image](https://user-images.githubusercontent.com/77157639/236619865-5c38bf2d-eda0-4494-9b11-62e17e332234.png)
