### ISSUE TITLE
Invisible login button in dark mode

### ISSUE THREAD

**Issue by gab12** [KRTirtho/spotube#502]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The "login with your spotify account" button is invisible in darkmode, because the text is the same color as the background.
![setting](https://user-images.githubusercontent.com/6320898/235778019-28c07ab8-75c2-47bc-807e-4d70b105f4b5.png)

If we press we can see that the text was present.
![Screenshot_20230502-222116](https://user-images.githubusercontent.com/6320898/235778022-f36e7bd4-199b-42de-bfd1-db97bb54ddb3.jpg)

### Expected Behavior

Put the text in white like the other texts.

### Steps to reproduce

1. Use darkmode on your phone.
2. Go to spotube settings

### Operating System

Android 11, Samsung A50

### Spotube version

v2.7.1

### Installation source

F-Droid (Android)

**Comment by KRTirtho** [comment]
This has been fixed already but waiting for v3 release 😄

**Comment by Be1zebub** [comment]
same issue on miui, if its related to OS

**Comment by sathwikd** [comment]
I was about to post the same thing.
Glad to know that issue has been already fixed and will be released in v3.😄

**Comment by RaptaG** [comment]
Fixed in 3.0.0
