### ISSUE TITLE
No internet after hibernate with spotube active

### ISSUE THREAD

**Issue by reaseno** [KRTirtho/spotube#504]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When Spotube is open and I hibernate the computer, the Internet does not work after I turn it back on. Only when I close spotube. Does Spotube use any proxy or VPN?

### Expected Behavior

Internet should not be influenced by spotube.

### Steps to reproduce

1. open spotube
2. go to hibernate
3. turn computer on again
4. try any app to reach the internet (spotube also can't)
5. close spotube
6. try any app to reach the internet > works again

### Operating System

Windows 10

### Spotube version

2.7.1

### Installation source

WinGet (Windows)

**Comment by KRTirtho** [comment]
What?

**Comment by reaseno** [comment]
Good question. It may also be due to a Windows update that seems to have happened around the same time. I will continue to monitor it.

**Comment by KRTirtho** [comment]
I was kidding. Spotube doesn't use any VPN or Proxy so it's unlikely that it can cause this issue

> Good question. It may also be due to a Windows update that seems to have happened around the same time. I will continue to monitor it.

This is a good reason. Windows update can mess up internet configuration

And I'm closing this issue as it's unrelated to spotube
