### ISSUE TITLE
macOS build is actually universal

### ISSUE THREAD

**Issue by karniv00l** [KRTirtho/spotube#505]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

current name of the release: `Spotube-macos-x86_64.dmg`

### Expected Behavior

makes more sense to rename it to: `Spotube-macos-universal.dmg`

### Steps to reproduce

n/a

### Operating System

n/a

### Installation source

GitHub Releases (Binary)

**Comment by KRTirtho** [comment]
Yep, I've to rename the dmg 😄

**Comment by RaptaG** [comment]
Fixed in 3.0.0
