### ISSUE TITLE
Handle android app links

### ISSUE THREAD

**Issue by agerhbour** [KRTirtho/spotube#508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

When I press a link to a Spotify playlist, I would like the option to open it in spotube
![Screenshot_20230512_212833](https://github.com/KRTirtho/spotube/assets/35976580/90f91833-8418-4229-8826-b2b62b88afdb)

### Suggested solution

Handle the android app link

### Useful resources

https://developer.android.com/training/app-links

**Comment by commander-keen** [comment]
When I saw issues #307 and #950, I thought, this one would be solved by them. But while a Spotify link shared by someone else on Android is being fetched successfully and Spotube app offered for handling the link:

![IMG_20240104_222135](https://github.com/KRTirtho/spotube/assets/179097/f1af0285-79b9-42ad-974a-6a0daac6fb6e)
![IMG_20240104_222115](https://github.com/KRTirtho/spotube/assets/179097/bd2e5590-beb5-45ac-8065-078945b01605)

It will just open the Home-Tab instead searching/playing the song:
![Screenshot_20240104-221408_Spotube](https://github.com/KRTirtho/spotube/assets/179097/4c02abcb-706d-47f4-8f8d-a936862c3a14)

Is there still something missing?

**Comment by KRTirtho** [comment]
Track link is still not implement. Unlike Spotify, Spotube doesn't have a separate screen for each track.

**Comment by KRTirtho** [comment]
@agerhbour Feature has been added. So closing now.

**Comment by KRTirtho** [comment]
@commander-keen Please create a separate issue for that
