### ISSUE TITLE
final line of lyrics obscured by buttons

### ISSUE THREAD

**Issue by ruzko** [KRTirtho/spotube#509]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The bottom line of lyrics is covered by the buttons controlling the lyrics.
Lyrics are partially visible because buttons are semi-transparent (nice, btw).
![Screenshot_20230514-014933](https://github.com/KRTirtho/spotube/assets/75946143/748d34a4-298c-4a9b-abb6-5a6c5eb58016)

### Expected Behavior

Like now, just that the final line should scroll to be above buttons. This way it looks cleaner and more readable.

### Steps to reproduce

1. Open app
2. Play song
3. Go to synced lyrics view
4. Listen to last line of lyrics, not able to read it easily

### Operating System

Android

### Spotube version

v2.7.1, build number 18

### Installation source

F-Droid (Android)

### Additional information

Still love the app, it's stunning

**Comment by KRTirtho** [comment]
Fixed by v3
![image](https://github.com/KRTirtho/spotube/assets/61944859/03a6b0fd-f5f2-4ecb-8e4b-0fd02c1c90d4)
