### ISSUE TITLE
Options too far apart

### ISSUE THREAD

**Issue by aha999** [KRTirtho/spotube#51]
**Is your feature request related to a problem? Please describe.**
When the app is fullscreen or in a bigger sized window, the settings and their toggles are too far apart so not obvious that they're together. See screenshot below.

**Describe the solution you'd like**
Put the settings from left/right closer.

**Additional context**
Screenshot:
![image](https://user-images.githubusercontent.com/50620416/161621705-42c733e4-9e04-4ba0-b43c-018ccab54711.png)

**Comment by KRTirtho** [comment]
You're monitor has a wider aspect ratio

**Comment by RomanJos** [comment]
Having a maxWidth like most website around 1200px should solve the issue.

https://discourse.webflow.com/t/whats-a-good-container-div-block-max-width-to-accommodate-for-most-screens/108788/3

**Comment by KRTirtho** [comment]
I don't think its causing any issues & functionality seems fine. Also it'd look weird to see those tiles aligned only into left

**Comment by RomanJos** [comment]
Yeah of course but having a maxWidth while centered.

<details><summary>Here are some example on a 4k screen</summary>

![Asana](https://i.imgur.com/lc5aiLE.png)
![Volley](https://i.imgur.com/wJGxLvh.png)
![Avionic design](https://i.imgur.com/keFLbTB.png)


</details>

**Comment by KRTirtho** [comment]
Dude, that's a website & Spotube is an app. Also Settings Page & Home Page are completely different things. They have different kind of aesthetics. Putting one's design to the other will end up making the whole thing absurd
I understand & respect your choice but there are thousand more users who might completely dislike this approach

**Comment by RomanJos** [comment]
Thats the same things, elements are too far apart for big screen, there is a lot of empty space in between and its not great as pointed previously.
If we were to talk about the home screen I'll say the same things about the media control on the bottom, groups need to be tied in fixed values.
<details><summary>Comparison</summary>

![Spotube](https://i.imgur.com/j8Xr4LM.png)
![Youtube Music](https://i.imgur.com/edg6zF6.png)
![Deezer](https://i.imgur.com/EkAp0WB.png)

</details>

**Comment by KRTirtho** [comment]
What's the resolution & the Aspect Ratio of your Monitor?

**Comment by RomanJos** [comment]
4K and 16/9 at 125% scaling

**Comment by karniv00l** [comment]
Same thoughts as @RomanJos. Also, maximizing the app on startup is not an ideal user experience 😉 

Here's how Spotify is handling this:

![spotify](https://user-images.githubusercontent.com/3144291/161720990-326ad1f1-be61-4058-8f5d-272b1ecf650a.jpg)

**Comment by KRTirtho** [comment]
Yeah @aha999 its too wide. I guess I've to limit both `PlayerControls` & `Settings` to certain width

**Comment by KRTirtho** [comment]
@aha999  This issue has been fixed already. So if your problem got fixed then please close this issue
