### ISSUE TITLE
AppImaga Not Work in Arch Linux ( Arco Linux )

### ISSUE THREAD

**Issue by velan001** [KRTirtho/spotube#513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

App Suddenly Stop working

### Expected Behavior

Play the song 

### Steps to reproduce

I will open the app image using terminal. Spotube will open if I play a song. The app will close immediately and the terminal last output is Segmentation fault ( core dumped )

### Operating System

Linux

### Spotube version

v2.7.1

### Installation source

Website (spotube.netlify.app)

**Comment by KRTirtho** [comment]
There is a `spotube-bin` AUR package or you can try the Flatpak version. AppImage support is broken now and is planned to be removed in favor of Flatpak and Snap

**Comment by KRTirtho** [comment]
Does v3 AppImage work?

**Comment by KRTirtho** [comment]
What's the output to terminal?
Make sure to install `xdg-user-dirs`. I forgot to add it to the deps

**Comment by KRTirtho** [comment]
AppImage support has been deprecated and we no longer support it in favor of Flatpak.
