### ISSUE TITLE
Daily Mix accessible from the app.

### ISSUE THREAD

**Issue by octia** [KRTirtho/spotube#519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

Daily mix playlists do not seem to be accessible from the app anywhere. Those playlists are the main way in which I'm using Spotify, and their lack prevents me from using Spotube for most of my Spotify needs.

### Suggested solution

It'd be amazing if they were added somewhere. Maybe in the personalized tab, maybe in the Library/Playlists tab, anywhere.

Alternatively, if I could just copy a link to the playlist somewhere and have the app open it, that'd be great too.

**Comment by octia** [comment]
Current workaround is to like the daily mix playlist on the website, then view it from the library/playlists tab in the app. It'd be cool if that wasn't neccesary.

**Comment by KRTirtho** [comment]
The changes are available in the [nightly](https://spotube.netlify.app/other-downloads/nightly-downloads)

**Comment by RaptaG** [comment]
Added in 3.0.0

**Comment by pacjo** [comment]
Would it be possible to access other Daily Mixes (3 to 5) without marking them as favorite?
