### ISSUE TITLE
When dragging the volume slider, have volume update in real time, instead of only on release.

### ISSUE THREAD

**Issue by octia** [KRTirtho/spotube#520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

I'm dragging the volume slider, and I don't know what is the volume that I'm gonna end up on, before I release the slider. This means I need to release it and then grab it again to drag it again, to get the volume I want.

### Suggested solution

Have it update on every change, not only on release.

**Comment by KRTirtho** [comment]
Available on nightly

**Comment by RaptaG** [comment]
Fixed in 3.0.0

**Comment by Traace** [comment]
With Version 3.0.0 the volume slider is missing completly....

**Comment by RaptaG** [comment]
> With Version 3.0.0 the volume slider is missing completly....

It is not, not on my end

**Comment by karniv00l** [comment]
@KRTirtho `VolumeSlider` is rendered here: 

https://github.com/KRTirtho/spotube/blob/master/lib/components/root/bottom_player.dart#L119

and default `fullWidth = false`, so it doesn't render full slider on a desktop:

```dart
if (fullWidth) Expanded(child: slider) else slider,
```

also this actually renders app as a blank window for me in debug mode with messages like `RenderBox was not laid out`. Looks like it needs a container here

**Comment by KRTirtho** [comment]
It renders for me though. Also no renderbox exception in both debug and release mode. Is it a mac-only issue then?
![image](https://github.com/KRTirtho/spotube/assets/61944859/a1907706-0589-443f-ae21-4c346a43724e)

**Comment by karniv00l** [comment]
Oh I see: https://api.flutter.dev/flutter/material/Slider/Slider.adaptive.html
creates Cupertino slider, which probably is a culprit 

I would personally stay away from Cupertino widgets when most of the app is material anyway

Just to summarize, currently on mac (release mode) it looks like this:

<img width="221" alt="Screenshot 2023-07-11 at 16 02 44" src="https://github.com/KRTirtho/spotube/assets/3144291/d4325334-028f-4723-8afc-891d95253162">

**Comment by karniv00l** [comment]
so something like this would be nice:

<img width="493" alt="Screenshot 2023-07-11 at 16 05 34" src="https://github.com/KRTirtho/spotube/assets/3144291/dd176168-1604-41cb-8afe-baee1fff3abf">

**Comment by KRTirtho** [comment]
Oh that makes total sense. This is actually why I also dropped `platform_ui` for Spotube primarily :smile: 

Lesson learned, stay away from platform adaptive widgets (for now) :sweat_smile:

**Comment by KRTirtho** [comment]
The app is now alien in all platforms equally :joy:
