### ISSUE TITLE
[FR] Hungry caching

### ISSUE THREAD

**Issue by ildar** [KRTirtho/spotube#522]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

The gap between tracks is huge measured in minutes

### Suggested solution

start caching the next song a couple of minutes before the current ends.

### Additional information

Maybe opt-in

**Comment by KRTirtho** [comment]
It's been fixed it already in the nightly channel

**Comment by ildar** [comment]
Can't test it until the nightly is non-functional (as of a couple of days
ago).

**Comment by ildar** [comment]
The release is awesome! thanks a lot!!!
