### ISSUE TITLE
Missing user interface

### ISSUE THREAD

**Issue by hanweikung** [KRTirtho/spotube#530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I installed Spotube-linux-x86_64.deb on Ubuntu 22.04. I can launch the application, but it missed user interface. 

![Screenshot from 2023-06-24 16-30-37](https://github.com/KRTirtho/spotube/assets/643825/4fcb825f-2229-4ce9-bdf7-50660a30df91)

I also tried the Flatpak package and had the same problem. 

![Screenshot from 2023-06-24 20-33-36](https://github.com/KRTirtho/spotube/assets/643825/543dbada-ccab-4694-a8eb-855bef98180d)

Here is the output of running the Flatpak package:

```
Gtk-Message: 20:29:57.294: Failed to load module "canberra-gtk-module"
Gtk-Message: 20:29:57.295: Failed to load module "canberra-gtk-module"
AudioPlayers: Could not query current duration.
flutter: PathNotFoundException: Cannot open file, path = '/home/hanwei/.var/app/com.github.KRTirtho.Spotube/config/dconf/user' (OS Error: No such file or directory, errno = 2)
```

### Expected Behavior

Spotube shows user interface.

### Steps to reproduce

1. Installed Spotube on Ubuntu 22.04 with either the deb or Flatpak package
2. Spotube turned out to be a blank window without user interface 

### Operating System

Ubuntu 22.04

### Spotube version

v2.7.1

### Installation source

Flathub (Flatpak)

**Comment by KRTirtho** [comment]
This has been fixed by v3.0.0
The flatpak flathub version is still not updated (will be soon. Queued)
