### ISSUE TITLE
User should be able to download the alternative track selected by them

### ISSUE THREAD

**Issue by Aditya149085** [KRTirtho/spotube#535]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

I am very frustrated that you give this **GODLIKE FEATURE** and then didn't complete it. T_T
Please answer my question is it a bug or a missing feature?

### Suggested solution

As said above give the user the ability to change the alt track to download pls.

### Useful resources

I don't have any particular resources but you can also give the option to turn off this feature
**IT JUST NEEDS A MANUAL TRACK SELECTION FOR DOWNLOAD**the

### Additional information

The last thing I would say is to bless you and may you achieve success in your life for creating this masterpiece of an application

**Comment by KRTirtho** [comment]
It's already implemented and available on [nightly](https://spotube.netlify.app/other-downloads/nightly-downloads)

**Comment by RaptaG** [comment]
Available on 3.0.0

**Comment by caburum** [comment]
Has this been broken with the download manager rewrite? Selecting an alternate track and then pressing the download button while on the now playing screen still downloads the original track. (version 3.4.0)
