### ISSUE TITLE
skip song

### ISSUE THREAD

**Issue by senolfndk** [KRTirtho/spotube#537]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

song skips getting stuck or sometimes not skipping at all

### Expected Behavior

song skips getting stuck or sometimes not skipping at all

### Steps to reproduce

song skips getting stuck or sometimes not skipping at all

### Operating System

windows 11 Pro 22H2 22631.1972

### Spotube version

v3.0.0

### Installation source

Scoop (Windows)

### Additional information

https://github.com/KRTirtho/spotube/assets/52818836/9d7327d2-a46d-4b99-8b1f-fb8f6a615138

**Comment by KRTirtho** [comment]
I think old version's cache is conflicting with the new one. Have you tried clearing the queue?

**Comment by senolfndk** [comment]
yes i tried

**Comment by RaptaG** [comment]
Cannot reproduce on Fedora Kinoite 38 on v3.0.0 via Flathub

**Comment by iBavtovich** [comment]
Same issue for me on Ubuntu 22.04 installed from the .deb package. here is stack trace from the logs: 
`------- DEVICE INFO -------
name: Ubuntu
version: 22.04.2 LTS (Jammy Jellyfish)
id: ubuntu
idLike: [debian]
versionCodename: jammy
versionId: 22.04
prettyName: Ubuntu 22.04.2 LTS
buildId: null
variant: null
variantId: null
machineId: c8d2854f839b4cbea8ed228d96261948
------- APP INFO -------
environment: release
version: 3.0.0
appName: spotube
buildNumber: 19
packageName: spotube
---------- ERROR ----------
RangeError (count): Invalid value: Not greater than or equal to 0: -1
------- STACK TRACE -------
#0      RangeError.checkNotNegative (dart:core/errors.dart:383)
#1      _checkCount (dart:_internal/iterable.dart:630)
#2      new EfficientLengthSkipIterable (dart:_internal/iterable.dart:610)
#3      new SkipIterable (dart:_internal/iterable.dart:591)
#4      SetBase.skip (dart:collection/set.dart:208)
#5      IterableExtension.elementAtOrNull (package:collection/src/iterable_extensions.dart:365)
#6      ProxyPlaylistNotifier.updatePalette.<anonymous closure> (package:spotube/provider/proxy_playlist/proxy_playlist_provider.dart:491)
#7      new Future.microtask.<anonymous closure> (dart:async/future.dart:280)
#8      _microtaskLoop (dart:async/schedule_microtask.dart:40)
#9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)
------- CUSTOM INFO -------`
