### ISSUE TITLE
Songs with Cyrillic letters are not played

### ISSUE THREAD

**Issue by siggi1984** [KRTirtho/spotube#538]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I open a playlist with English and Russian songs and Cyrillic letters, respectively.

The English songs are played normally. The Russian songs or with Cyrillic letters are not played.

### Expected Behavior

All songs no matter what language or no matter what country should be played.

### Steps to reproduce

See description

### Operating System

Android 9

### Spotube version

3.0.0

### Installation source

GitHub Releases (Binary)

### Additional information

Would be great if the bug is fixed because the app is not usable for me.

**Comment by siggi1984** [comment]
------- DEVICE INFO -------
id: PPR1.180610.011
board: universal7885
bootloader: A530FXXULCUK6
brand: samsung
device: jackpotlte
display: PPR1.180610.011.A530FXXULCUK6
fingerprint: samsung/jackpotltexx/jackpotlte:9/PPR1.180610.011/A530FXXULCUK6:user/release-keys
hardware: samsungexynos7885
host: 21HHAG06
isPhysicalDevice: true
manufacturer: samsung
model: SM-A530F
product: jackpotltexx
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: A530FXXULCUK6
versionPreviewSdk: 0
versionRelease: 9
versionSdk: 28
versionSecurityPatch: 2021-11-01
------- APP INFO -------
environment: release
version: 3.0.0
appName: Spotube
buildNumber: 19
packageName: oss.krtirtho.spotube
---------- ERROR ----------
Null check operator used on a null value
------- STACK TRACE -------
#0      new ProxyPlaylistNotifier.<anonymous closure>.<anonymous closure> (package:spotube/provider/proxy_playlist/proxy_playlist_provider.dart:178)
#1      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594)
#2      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339)
#3      _DelayedData.perform (dart:async/stream_impl.dart:515)
#4      _PendingEvents.handleNext (dart:async/stream_impl.dart:620)
#5      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591)
#6      _microtaskLoop (dart:async/schedule_microtask.dart:40)
#7      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)
------- CUSTOM INFO -------

**Comment by Ser-Bul** [comment]
Actually I see the similar error in the logs as I try to launch playlist "Sirens (UK)" and nothing plays

------- DEVICE INFO -------
id: TQ3A.230605.010
board: bluejay
bootloader: bluejay-1.2-9894665
brand: google
device: bluejay
display: TQ3A.230605.010.2023062800
fingerprint: google/bluejay/bluejay:13/TQ3A.230605.010/2023062800:user/release-keys
hardware: bluejay
host: grapheneos
isPhysicalDevice: true
manufacturer: Google
model: Pixel 6a
product: bluejay
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: 2023062800
versionPreviewSdk: 0
versionRelease: 13
versionSdk: 33
versionSecurityPatch: 2023-06-05
------- APP INFO -------
environment: release
version: 3.0.0
appName: Spotube
buildNumber: 19
packageName: oss.krtirtho.spotube
---------- ERROR ----------
Null check operator used on a null value
------- STACK TRACE -------
#0      BlackListNotifier.contains (package:spotube/provider/blacklist_provider.dart:61)
#1      IterableExtension.whereNot.<anonymous closure> (package:collection/src/iterable_extensions.dart:54)
#2      WhereIterator.moveNext (dart:_internal/iterable.dart:441)
#3      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202)
#4      new _GrowableList.of (dart:core-patch/growable_array.dart:152)
#5      new List.of (dart:core-patch/array_patch.dart:47)
#6      SetBase.toList (dart:collection/set.dart:119)
#7      BlackListNotifier.filter (package:spotube/provider/blacklist_provider.dart:75)
#8      ProxyPlaylistNotifier.load (package:spotube/provider/proxy_playlist/proxy_playlist_provider.dart:286)
#9      PlaylistView.playPlaylist (package:spotube/pages/playlist/playlist.dart:34)
#10     PlaylistView.build.<anonymous closure> (package:spotube/pages/playlist/playlist.dart:81)
#11     _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1154)
#12     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275)
#13     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:654)
#14     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:311)
#15     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:281)
#16     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:167)
#17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:469)
#18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:445)
#19     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:331)
#20     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:400)
#21     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:363)
#22     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:320)
#23     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:293)
#24     _invoke1 (dart:ui/hooks.dart:158)
#25     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:382)
#26     _dispatchPointerDataPacket (dart:ui/hooks.dart:91)
------- CUSTOM INFO -------

**Comment by KRTirtho** [comment]
Wow, this is a huge Edge case. How come no one found this all time? :sweat_smile:

**Comment by siggi1984** [comment]
> 

Can this error please, please be fixed in a timely manner. So that you can use the app properly, because right now using the app with this error is not fun.

**Comment by siggi1984** [comment]
Will the bug be fixed soon?

**Comment by siggi1984** [comment]
Error still not fixed. Unfortunately the app is unusable

**Comment by siggi1984** [comment]
Works for me again since the last update. 
Thanks Bro
