### ISSUE TITLE
Spotube doesn't remember theme setting

### ISSUE THREAD

**Issue by aha999** [KRTirtho/spotube#54]
**Describe the bug**
When you save your theme preference, and exit the Spotube it goes back to the system theme (which is white for unknown reason).

**To Reproduce**
1. Go to settings
2. Select dark theme
3. exit the app
4. theme will be set again back to System option.

**Expected behavior**
Theme option should be remembered.

**Installation Source/Method**
- Package Manager: flatpak
- Community Repo: idk
- Binary Source: idk

**Desktop (please complete the following information):**
 - OS: EndeavourOS
 - Version KDE Plasma 5.24.4, Kernel: 5.17.1-arch1-1

**Comment by KRTirtho** [comment]
Fixed the issue. Will be available in the next release
