### ISSUE TITLE
Shuffle does not work

### ISSUE THREAD

**Issue by RaptaG** [KRTirtho/spotube#540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I pressed the shuffle button, it is activated, but songs play on their listed order.

### Expected Behavior

Shuffling songs to play them on a random order

### Steps to reproduce

1. Open your Liked Songs
2. Play a song
3. Click the Shuffle button
4. Press the skip button or look at the queue
5. See the issue

### Operating System

Fedora Linux Kinoite 38

### Spotube version

3.0.0

### Installation source

Flathub (Flatpak)

**Comment by KRTirtho** [comment]
Do you've gnome-keyring or KDE wallet configured?

**Comment by RaptaG** [comment]
Thanks @KRTirtho !

**Comment by KRTirtho** [comment]
Fixed in v3.0.1
