### ISSUE TITLE
Default to the kavin.rocks libre instance when using Piped

### ISSUE THREAD

**Issue by RaptaG** [KRTirtho/spotube#542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

Many instances are not reliable due to recent YT attacks towards Invidious and Piped.

### Suggested solution

https://pipedapi-libre.kavin.rocks/ seems to be unaffected from the attacks and it is the most reliable because it is official as well.

**Comment by RaptaG** [comment]
> He is using Kavin rocks as default 

kavin.rocks **libre**, they are different

**Comment by owencz1998** [comment]
I heard this is due to them adding rate limit back into the api or something I could be wrong it's just what iv heard

**Comment by KRTirtho** [comment]
Both are pretty much same & official one seems to be more stable
