### ISSUE TITLE
On the Piped instances, ASCCII caracters are used instead of emojis

### ISSUE THREAD

**Issue by RaptaG** [KRTirtho/spotube#543]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/KRTirtho/spotube/assets/77157639/a0470b0b-9fc2-49ea-9f6b-6b6b07c703a5)

### Expected Behavior

The use of emojis

It also looks broken when the list is collapsed:
![image](https://github.com/KRTirtho/spotube/assets/77157639/22db0d87-b6d3-4325-a3b7-fcf04127b424)

### Steps to reproduce

Head to Settings -> API type -> Piped -> Server instance and see issue

### Operating System

Fedora Linux Kinoite 38

### Spotube version

3.0.0

### Installation source

Flathub (Flatpak)

**Comment by KRTirtho** [comment]
You're missing Emoji fonts

**Comment by RaptaG** [comment]
Installed https://packages.fedoraproject.org/pkgs/google-noto-emoji-fonts/google-noto-emoji-color-fonts alongside with https://packages.fedoraproject.org/pkgs/google-noto-emoji-fonts/google-noto-emoji-fonts, the issue continues to appear even after a system reboot

**Comment by j3bx** [comment]
maybe the flatpak doesn't have access to those? a dirty solution would be to add the fonts as a module in the flatpak itself
