### ISSUE TITLE
[Linux] Transparent or Black window. Libsecret provider not installed

### ISSUE THREAD

**Issue by calm3285** [KRTirtho/spotube#553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when i open spotube it opens transparent, this has never happen to me 

### Expected Behavior

it should open normal

### Steps to reproduce

1. i opened the app

### Operating System

arch linux

### Spotube version

3.0.0.0

### Installation source

Arch User Repository (AUR)

### Additional information

package:media_kit_libs_linux registered.
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.NetworkManager was not provided by any .service files
#0      DBusClient._callMethod (package:dbus/src/dbus_client.dart:1102)
<asynchronous suspension>
#1      DBusClient.callMethod (package:dbus/src/dbus_client.dart:608)
<asynchronous suspension>
#2      DBusRemoteObjectManager.getManagedObjects (package:dbus/src/dbus_remote_object_manager.dart:80)
<asynchronous suspension>
#3      NetworkManagerClient.connect (package:nm/src/network_manager_client.dart:2351)
<asynchronous suspension>
#4      ConnectivityPlusLinuxPlugin.checkConnectivity (package:connectivity_plus/src/connectivity_plus_linux.dart:24)
<asynchronous suspension>
#5      FlQueryConnectivityPlusAdapter.isConnected (package:fl_query_connectivity_plus_adapter/fl_query_connectivity_plus_adapter.dart:10)
<asynchronous suspension>

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.NetworkManager was not provided by any .service files
#0      DBusClient._callMethod (package:dbus/src/dbus_client.dart:1102)
<asynchronous suspension>
#1      DBusClient.callMethod (package:dbus/src/dbus_client.dart:608)
<asynchronous suspension>
#2      DBusRemoteObjectManager.getManagedObjects (package:dbus/src/dbus_remote_object_manager.dart:80)
<asynchronous suspension>
#3      NetworkManagerClient.connect (package:nm/src/network_manager_client.dart:2351)
<asynchronous suspension>
#4      ConnectivityPlusLinuxPlugin._startListenConnectivity (package:connectivity_plus/src/connectivity_plus_linux.dart:64)
<asynchronous suspension>

** (spotube:4313): WARNING **: 11:05:14.368: libsecret_error: B\xb3\x96\x91\x9e\u007f
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Unexpected extension byte (at offset 1)
#0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1747)
#1      Utf8Decoder.convert (dart:convert/utf.dart:351)
#2      StandardMessageCodec.readValueOfType (package:flutter/src/services/message_codecs.dart:503)
#3      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:478)
#4      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648)
#5      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310)
<asynchronous suspension>
#6      PersistedStateNotifier.initializeBoxes (package:spotube/utils/persisted_state_notifier.dart:57)
<asynchronous suspension>
#7      main (package:spotube/main.dart:123)
<asynchronous suspension>

**Comment by KRTirtho** [comment]
You've NetworkManager installed?

**Comment by RaptaG** [comment]
Also could you provide some screenshots?

**Comment by calm3285** [comment]
> You've NetworkManager installed?

no, i use dhcpcd


> Also could you provide some screenshots?

its literary transparent, if i run it in the terminal it opens a transparent window

**Comment by RaptaG** [comment]
Works fine for me on Fedora Kinoite 38 (KDE) with Wayland @calm3285

**Comment by KRTirtho** [comment]
Do you have gnome-keyring or kde-wallet installed and configured?

**Comment by calm3285** [comment]
> Do you have gnome-keyring or kde-wallet installed and configured?

i enabled kwallet an it worked
is kwallet a dependency?
how can i open spotube without it?

**Comment by RaptaG** [comment]
I use Spotube with kwallet disabled

**Comment by luminoso** [comment]
I have kwallet enabled and I have the issue

**Comment by calm3285** [comment]
when i disable kwallet editing the kwalletrc file, i get this error:

package:media_kit_libs_linux registered.

** (spotube:6170): WARNING **: 11:12:02.180: libsecret_error: \xc3\xf4\xcaV\xab\u007f
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Missing extension byte (at offset 1)
#0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1747)
#1      Utf8Decoder.convert (dart:convert/utf.dart:351)
#2      StandardMessageCodec.readValueOfType (package:flutter/src/services/message_codecs.dart:503)
#3      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:478)
#4      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648)
#5      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310)
<asynchronous suspension>
#6      PersistedStateNotifier.initializeBoxes (package:spotube/utils/persisted_state_notifier.dart:57)
<asynchronous suspension>
#7      main (package:spotube/main.dart:123)
<asynchronous suspension>

**Comment by KRTirtho** [comment]
Spotube needs kwallet or any secret service for storing your login information. Without it, spotube can't start as it will try to check if you've credentials for login

**Comment by RaptaG** [comment]
> Spotube needs kwallet or any secret service for storing your login information. Without it, spotube can't start as it will try to check if you've credentials for login

Isn't there any lightweight flutter credential store API or something to build in Spotube without the need of 3rd-parties @KRTirtho ?

**Comment by KRTirtho** [comment]
`libsecret` is a standard desktop feature in Linux. And it's better to use a standard library than making a custom implementation for the same result. So sorry `libsecret` needs to be installed + enabled because it's a dependency for encryption of credentials

**Comment by pidario** [comment]
I have the same issue. I don't use a **keyring**... except that I do! `KeepassXC` configured as a **secret service** provider is enough for `Spotube` to open and do its things. But then, another issue arises (which can be found in the same stack trace in the issue description): application needs `NetworkManager` for some reason (probably some `flutter` library? I cannot find any reference of it in `Spotube` repo).
I normally use `networkd`. Once I install `NetworkManager` and enable it instead of `networkd`, `Spotube` works as expected.
If using a **keyring** might be useful (`KeepassXC` is always open in my system anyway), I believe at least the app should warn the user. But about `NetworkManager`, I don't think that any software should ever make assumptions about how a user configures his/her network devices.

**Comment by KRTirtho** [comment]
_KeepassXC_ is password manager only ig. `gnome-keyring` or `kwallet` these are secret managers (key manager)
`libsecret` is used by applications to store secrets e.g. encryption keys, ssh keys, API keys etc... On the other hand, `KeepassXC`, `Bitwarden` etc are password managers used by users (not application at all) to store credentials. The password manager might use `libsecret` to store their encryption keys. But since most of them are cloud based, nothing is stored locally nowadays

About `NetworkManager`:
Sorry about this. I didn't know it's a dependency of a plugin. Nothing was mentioned in the plugin README so it's kind of confusion of all parties.

**Comment by GiorgosXou** [comment]
It worked just fine, somehow same issue appeared from nowhere:
```
** (spotube:8061): WARNING **: 14:54:12.897: libsecret_error: \xd3_9`D\u007f
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Missing extension byte (at offset 1)
#0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1747)
#1      Utf8Decoder.convert (dart:convert/utf.dart:351)
#2      StandardMessageCodec.readValueOfType (package:flutter/src/services/message_codecs.dart:503)
#3      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:478)
#4      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648)
#5      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310)
<asynchronous suspension>
#6      PersistedStateNotifier.initializeBoxes (package:spotube/utils/persisted_state_notifier.dart:57)
<asynchronous suspension>
#7      main (package:spotube/main.dart:123)
<asynchronous suspension>
```

**Comment by pidario** [comment]
I figured that was the case about NetworkManager.

Anyway, I mentioned keepassxc just because it implements freedesktop secret service and it basically acts as a keyring.
In my case, where I don't have  DE running but just a WM, Keepassxc is a nice alternative. And about not storing anything locally because everything is cloud based: take my piece of advice and don't use a cloud base password manager, even if its self hosted but with this I'm going off-topic.

Thank you for Spotube, I hope this can be fixed soon!

**Comment by GiorgosXou** [comment]
Sorry for spamming, somehow it got fixed after an update

**Comment by livingsilver94** [comment]
I'm facing this issue with the Flatpak edition. There's nothing I can install to fix the issue since it's sandboxed.

**Comment by KRTirtho** [comment]
> I'm facing this issue with the Flatpak edition. There's nothing I can install to fix the issue since it's sandboxed.

You can install gnome-keyring as it implements `org.freedesktop.secrets` which is used by Spotube to store critical information

**Comment by Coburn** [comment]
This behavior happens for me on my laptop after wake from suspend. It also happens if I close the app but leave it running in the taskbar. I believe I am using a Gnome extension for taskbar controls. Basically, Spotube displays in some sort of minimal way after close or suspend, but will no longer play music. I have to log out or restart.
![Screenshot from 2023-07-18 06-51-43](https://github.com/KRTirtho/spotube/assets/2658123/1f979e35-b1dd-4e38-8a45-688698f66157)

**Comment by Coburn** [comment]
Fascinating. A **sudo killall spotube** also fixes it. But even though Spotube is closed, it is glomming 40% of my CPU!
![Screenshot from 2023-07-18 06-54-47](https://github.com/KRTirtho/spotube/assets/2658123/eeb7c1c8-b937-447a-959f-7ffc0de653d2)

**Comment by KRTirtho** [comment]
For now, only way to solve it temporarily is to install `gnome-keyring` as it by default on startup asks to unlock the keyring.
But other libsecret providers doesn't seem do this. As Spotube can't unlock the keyring by it self, it crashes thinking something went wrong

**Comment by qxb3** [comment]
@KRTirtho hello! sorry for the duplicate issue, i did not see this one. Anyway mine seems to work now but when i try to reopen spotube again the black thing i was talking about appear. Is that normal? its not really an issue but i kinda want to reopen it and it will just use the spotube session that is already open.

**Comment by KRTirtho** [comment]
If it's already running in the background, you can't open a new instance. You've to kill the old instance from the task bar or "Show/Hide" from the task bar icon

**Comment by KRTirtho** [comment]
If you don't want to minimize to system tray on close, you can change that behavior from Settings

**Comment by Coburn** [comment]
Sorry this is not a thorough check but my system does report that `gnome-keyring is already the newest version`

**Comment by 875d** [comment]
> _KeepassXC_ is password manager only ig. `gnome-keyring` or `kwallet` these are secret managers (key manager) `libsecret` is used by applications to store secrets e.g. encryption keys, ssh keys, API keys etc... On the other hand, `KeepassXC`, `Bitwarden` etc are password managers used by users (not application at all) to store credentials. The password manager might use `libsecret` to store their encryption keys. But since most of them are cloud based, nothing is stored locally nowadays

KeePassXC can be used as a Secret Service Agent:

![image](https://github.com/KRTirtho/spotube/assets/118444583/1bd8cbca-cd20-4e06-8d04-5f6aaa309764)

I had this problem.

In case there is no Secret Service Agent on the dbus, spotube should show an error to the user, not just crash.

**Comment by KRTirtho** [comment]
The problem is it is not a direct dependency of Spotube and it's actually used by a plugin that we use. But that plugin doesn't expose any API to handle that kind of error. I think I've to report that to plugin author(s)

**Comment by KRTirtho** [comment]
Check https://github.com/mogol/flutter_secure_storage/issues/545

**Comment by KRTirtho** [comment]
Ok until plugin upstream provides any fixes, Spotube will fallback to non encrypted storage. But it will warn the user about the risk

**Comment by KRTirtho** [comment]
v3.0.1 provides a temporary fix. Please check if it works for you

**Comment by calm3285** [comment]
it works now, but the network manager error logs persist

**Comment by AgostinoA** [comment]
[Secret Service Agent:](libsecret-1.so.0: undefined symbol: g_task_set_name)
Now it doesn't work for me anymore

**Comment by Moilleadoir** [comment]
`libsecret` has always been installed, but at some stage Spotube flatpak just started showing a black screen.
Manjaro Linux, Cinnamon desktop.

```
$ /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=spotube --file-forwarding com.github.KRTirtho.Spotube @@u %u @@
Gtk-Message: 16:38:31.384: Failed to load module "xapp-gtk3-module"
Gtk-Message: 16:38:31.384: Failed to load module "canberra-gtk-module"
package:media_kit_libs_linux registered.
flutter: media_kit: WARNING: package:media_kit_native_event_loop not found.
method call InitSystemTray
SystemTray::set_system_tray_info title: , icon_path: /app/spotube/data/flutter_assets/assets/spotube-logo.png, toolTip: (null)
```
