### ISSUE TITLE
Add recommended songs to queue

### ISSUE THREAD

**Issue by AliWhoi666** [KRTirtho/spotube#563]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

Currently when a song is being played, new songs aren't added to queue

### Suggested solution

Similar to how Spotify does it, it'd be nice if recommended songs could be added based on the currently playing song

**Comment by abhisheksharma886** [comment]
Hello, I would like to work on this, can it be assigned to me

**Comment by KRTirtho** [comment]
Of course 😄 
Thanks ❤️

**Comment by KRTirtho** [comment]
Make sure to read [this](https://github.com/KRTirtho/spotube/blob/master/CONTRIBUTION.md#your-first-code-contribution) and make PR against the `dev` branch 😃

**Comment by KRTirtho** [comment]
Duplicate of #285
