### ISSUE TITLE
[ANDROID] The bottom menu bar does not update after login in with Spotify credentials

### ISSUE THREAD

**Issue by alexandre-eliot** [KRTirtho/spotube#569]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After authentication, the sign in modal is still present.
The current page is now "Home" but the selected icon in the bottom menu is still "Settings"

### Expected Behavior

After authentication, a success notification appears.
The current page is now "Home" and the selected icon in the bottom menu is "Home" in accordance.

### Steps to reproduce

- Go to settings
- Press "Login with Spotify"
- Sign in
- The Sign In modal is still present
- Press elsewhere

### Operating System

Android 11, Oxygen OS 11.1.2.2

### Spotube version

v3.0.0

### Installation source

Play Store

**Comment by KRTirtho** [comment]
I guess now this issue isn't relevant anymore as Settings button has been moved to top of the app home screen
