### ISSUE TITLE
Cut-off when too many artists on a song

### ISSUE THREAD

**Issue by meenbeese** [KRTirtho/spotube#573]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

Sometimes when there are too many artists on a given song (maybe like 5+), the list of artists clutter the media player view and make it hard to reach other functions such as lyrics. See below screenshot for example.
![879A453E-4EAB-4C3D-AA46-B70233C7EC46](https://github.com/KRTirtho/spotube/assets/114044633/e1eb9498-6a40-4cbb-82bf-73489ecae9b2)

### Suggested solution

There is no need to actively display every single artist on a song. There should be a hard-coded limit after which artists should not be displayed. (Maybe 5 is a good number, again?) This is also how Spotify does things.

The remaining artists could either be added to a pop-up card somewhere or just completely hidden from the user as they are not absolutely necessary for the core music viewing experience.

### Additional information

At the very least, however, artists should not be justified as it currently is (it just looks bad) and possibly aligned left or right of the media player. This is especially true when there are too many of them.

**Comment by KRTirtho** [comment]
There's always some UI edge cases like this. I mean at this point just form a band :rofl:

**Comment by meenbeese** [comment]
> There's always some UI edge cases like this. I mean at this point just form a band :rofl: 

It's true that this is definitely an edge-case example 😁 You don't see collabs this huge everyday but I managed to find one.

**Comment by KRTirtho** [comment]
Now, Spotube hides artists name if more than 3. It can be expanded to a new track page which will show the full artist details

**Comment by KRTirtho** [comment]
Available in 3.8.0
