### ISSUE TITLE
Autoplay doesn't work

### ISSUE THREAD

**Issue by Vovandr981** [KRTirtho/spotube#574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when I play a playlist after the first song ends, the next one does not play

### Expected Behavior

I expected playing the next song.

### Steps to reproduce

1.  Open app.
2. Play playlist.
3. Wait antil song ends.

### Operating System

Android 

### Spotube version

v3.0.0

### Installation source

Play Store (Android)

**Comment by rootbdfy** [comment]
Same on v2.6 and 2.7.

**Comment by mfgcolour** [comment]
Seems related to [this issue](https://github.com/KRTirtho/spotube/issues/113)

On 3.0.1 the issue is still there, using AUR (source build)
