### ISSUE TITLE
LAG APP, NOT RESPONSIVE 

### ISSUE THREAD

**Issue by MrConqueror** [KRTirtho/spotube#578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When i tap a song it takes 2-3 secs to play
 and when a song is playing and tap other song it takes 2-3 secs before the song changes
 and also i added K-POP in blacklist but still shows in genre. 

### Expected Behavior

.

### Steps to reproduce

.

### Operating System

Android 

### Spotube version

latest 

### Installation source

Play Store (Android)

### Additional information

.

**Comment by KRTirtho** [comment]
> When i tap a song it takes 2-3 secs to play
> and when a song is playing and tap other song it takes 2-3 secs before the song changes

Spotube needs to match the accurate Spotify track with the Youtube/Piped API result. If the track was never matched before it does a complete search. If your internet connection or DNS provider is slow it can sometimes take some time but usually takes less than 1s

> and also i added K-POP in blacklist but still shows in genre.

Spotube doesn't have the ability to blacklist genre. It can only blacklist certain tracks and artists
