### ISSUE TITLE
HTML displayed as plaintext in some auto-generated playlist descriptions 

### ISSUE THREAD

**Issue by TDuffinNTU** [KRTirtho/spotube#579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Certain playlists such as genre mixes (Pop Mix, Rock mix etc.) will display a HTML anchor tag as plaintext in the playlist description. Likely just needs a HTML render widget or some creative parseing.

![Screenshot_2023-07-14-09-35-32-02_1c96baa6fc3a4338d23fd334c3c04599](https://github.com/KRTirtho/spotube/assets/43959652/88f4b217-fb49-490d-a5c0-030098e5c003)

### Expected Behavior

The description is displayed as properly formatted text.

### Steps to reproduce

1. Open app
2. View description for a "genre mix" playlist.

### Operating System

Android 12

### Spotube version

v3.0.0 b19

### Installation source

Website (spotube.netlify.app)

**Comment by KRTirtho** [comment]
This has been fixed in v3.0.1
