### ISSUE TITLE
Spotube freezes in a black screen

### ISSUE THREAD

**Issue by riomccloud** [KRTirtho/spotube#581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to run Spotube, it freezes in a black screen.
I was able to run it a few times, but it didn't play anything and freezes too. I was unable to reproduce it again.

### Expected Behavior

Just work.

### Steps to reproduce

1. I opened the app
2. Done

### Operating System

Linux Mint 21.1 Cinnamon

### Spotube version

v3.0.0

### Installation source

Flathub (Flatpak)

### Additional information

![image](https://github.com/KRTirtho/spotube/assets/32412883/36edb3ab-586e-4ba9-bfa2-f85fe76bf2af)
![image](https://github.com/KRTirtho/spotube/assets/32412883/e7fdfb83-5e0e-4864-880a-a821bb910b76)

**Comment by KRTirtho** [comment]
https://github.com/KRTirtho/spotube/issues/553
