### ISSUE TITLE
[Android] Incorrect name of Album, missing Cover

### ISSUE THREAD

**Issue by AgostinoA** [KRTirtho/spotube#586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After downloading a track, the artwork is not assigned and the metadata is wrong. Assign as "Spotube" Album

### Expected Behavior

After downloading a track, it must match the metadata of the original track.

### Steps to reproduce

1. Open app
2. Download track
3. Info track

### Operating System

Android, other not tested

### Spotube version

3.0.0

### Installation source

Website (spotube.netlify.app)

### Additional information

Good work

**Comment by AgostinoA** [comment]
3.0.1 on Android is missing storage permissions and no longer allows saving

![photo_2023-08-05_11-49-26](https://github.com/KRTirtho/spotube/assets/28324952/56122708-20f3-4068-ac14-0bc3780785ff)

**Comment by KRTirtho** [comment]
v3.1.0 fixed it
