### ISSUE TITLE
Linux not start

### ISSUE THREAD

**Issue by AgostinoA** [KRTirtho/spotube#588]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

embedder.cc (1118): 'FlutterEngineCreateAOTData' returned 'kInvalidArguments'. Invalid ELF path specified.

** (spotube:10631): WARNING **: 19:16:59.372: Failed to start Flutter engine: Failed to create AOT data
package:media_kit_libs_linux registered.

### Expected Behavior

Open

### Steps to reproduce

1. Open

### Operating System

Linux custom: Gblic2.35/X11/Kwin

### Spotube version

3.0.0

### Installation source

GitHub Releases (Binary)

**Comment by RaptaG** [comment]
Could you give us some more detailed information (distro, version etc.)

**Comment by KRTirtho** [comment]
Probably related to this https://github.com/KRTirtho/spotube/issues/553

**Comment by AgostinoA** [comment]
> Could you give us some more detailed information (distro, version etc.)

Sorry if I wrote in a superficial way, I have a custom version of Linux with Gblic2.35/X11/Kwin. The problem is that it remains invisible even with Kwallet disabled

**Comment by KRTirtho** [comment]
Well, kwallet (or gnome-keyring) needs to be enabled and unlocked for applications to let Spotube work. It stores user's valuable Spotify credentials there :sweat_smile:

**Comment by AgostinoA** [comment]
Additionally this causes a problem with Appimage if I use the home and config folder separation. So it invalidates the concept of AppImage

**Comment by KRTirtho** [comment]
Secret service is a standard for all desktop as per Freedesktop specifications. And Spotube like other apps uses the secret service protocol. It doesn't know or needs to know what kind of secret provider is used as long as it's compatible with libsecret. Kwallet and gnome-keyring are such secret service provider/client
AppImage bundles all dependencies in it self but that doesn't mean DE standard/agnostic features like secret service, notification service or glibc should be also bundled. It'd weigh the AppImage too much

**Comment by AgostinoA** [comment]
I know perfectly how it works and the freedesktop standard, in fact I advise you to embed everything, like other apps do, but not because they like weighing down the appimage, but simply to have the whole situation under control and have all versions of programs compatible between They.
I'm not saying the entire operating system, mind you but only what is needed. This means embedding, like emulators and other apps do, you have everything under control, you save yourself a lot of issues on GitHub

**Comment by KRTirtho** [comment]
What about v3.8.0? Does it work now?

**Comment by KRTirtho** [comment]
Closing as stale
