### ISSUE TITLE
Clickable Lyrics

### ISSUE THREAD

**Issue by demirdegerli** [KRTirtho/spotube#590]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Pain

I can't jump to the specific time of the song when the lyric I clicked is said.

### Suggested solution

Making lyrics clickable would be cool.

**Comment by KRTirtho** [comment]
That could be an interesting feature. Let me add this to the bucket

**Comment by KRTirtho** [comment]
Added in v3.1.1
