### ISSUE TITLE
Support for local library

### ISSUE THREAD

**Issue by vico93** [KRTirtho/spotube#595]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

Newcomer from Windows Media Player, is there any way we can "import" our local music library to the app, WMP style?

Even the original Spotify App allows that (except for .flac files).

### Suggested solution

Basically, implement a way reminiscent of Windows Media Player and Winamp to scan the system Music folder and register the songs found to always prefer to play the local copy instead of fetch the remote (or the cached download).

**Comment by KRTirtho** [comment]
Spotube can detect any songs available in it's Download location ("Settings" > "Download Location" which by default Download/Spotube folder). If you move your tracks there or change the spotube download location to your music library it will show the tracks on the "Library" > "Tracks" Tab

**Comment by vico93** [comment]
> Spotube can detect any songs available in it's Download location ("Settings" > "Download Location" which by default Download/Spotube folder). If you move your tracks there or change the spotube download location to your music library it will show the tracks on the "Library" > "Tracks" Tab

would it scan subfolders as well?

**Comment by KRTirtho** [comment]
Unfortunately no

**Comment by vico93** [comment]
That could be a nice addition, rs

**Comment by vico93** [comment]
Bump, any chance of this feature (or at least a proper support of Music folder to achieve #223 ) to be implemented?

**Comment by radstevee** [comment]
![1000015148.png](https://github.com/KRTirtho/spotube/assets/96977790/1cd57e10-4a47-460e-8d17-046a72f27534)

I've found that the colour scheme is a bit messed up for tracks without thumbnail.

**Comment by Kev1n121** [comment]
> Spotube can detect any songs available in it's Download location ("Settings" > "Download Location" which by default Download/Spotube folder). If you move your tracks there or change the spotube download location to your music library it will show the tracks on the "Library" > "Tracks" Tab

But they are not local acces only with wifi on.

**Comment by timkgh** [comment]
> Unfortunately no

Please add subfolder support. Thank you.

**Comment by mansoorkhan96** [comment]
+1 for this feature. Some Android music apps have a feature to let you scan the all local songs available in your storage and then it lists them all.

This will be huge.

**Comment by XargonWan** [comment]
I would love this feature, +1

**Comment by KRTirtho** [comment]
Closed it as library support was implemented
