### ISSUE TITLE
it can not load any playlists

### ISSUE THREAD

**Issue by Adkimsm** [KRTirtho/spotube#597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

it is like this:
![Screenshot_2023-07-23-11-24-22](https://github.com/KRTirtho/spotube/assets/75924586/46453ddd-3e59-4881-b27b-e835399a9f55)
 
![Screenshot_2023-07-23-11-24-14](https://github.com/KRTirtho/spotube/assets/75924586/45c2674b-30fc-45a8-96ff-28274f286bef)
![Screenshot_2023-07-23-11-24-07](https://github.com/KRTirtho/spotube/assets/75924586/59f031ce-8b8a-4113-9c67-edefe2034a23)

i have loged and it can search any songs and listen to them, but it doesn't load playlists

### Expected Behavior

it should load a playlist(i only have one playlist)

### Steps to reproduce

1. i opened the app
2. i loged
3. i touch the playlists tab

### Operating System

android 8

### Spotube version

3.0.0

### Installation source

GitHub Releases (Binary)

**Comment by Adkimsm** [comment]
i use the nightly build and it is also like this.

**Comment by KRTirtho** [comment]
I think you have a lot of personal playlists. But unfortunately, spotube pulls all the Playlists at once
Pagination will be added in future to prevent this from happening

**Comment by qxb3** [comment]
Same on mine.

![Screenshot_20230813_060810](https://github.com/KRTirtho/spotube/assets/59109346/7935bcae-3e4c-4221-83af-47558da95ed5)

<br>

**OS:** Arch Linux x86_64

**Comment by KRTirtho** [comment]
@qxb3 you might not have `networkmanager` configured thus spotube is assuming you're offline & retrying to get the playlist

**Comment by qxb3** [comment]
@KRTirtho ohh, it cant work with connman? its what i currently use rn

**Comment by KRTirtho** [comment]
Currently no

**Comment by qxb3** [comment]
I see, is there any plan on supporting it?

**Comment by KRTirtho** [comment]
It's not in my hand
 The plugin used by spotube needs to support it fiest

**Comment by qxb3** [comment]
sorry i'm not really familiar with the code base, what plugin?

**Comment by KRTirtho** [comment]
I think connectivity_plus

**Comment by Adkimsm** [comment]
> 我认为你有很多个人播放列表。但不幸的是，spotube 会立即拉出所有播放列表 将来将添加分页以防止这种情况发生

no, i only have one.i think that is because my webview is too old.after update,i have already solve this problem.

**Comment by KRTirtho** [comment]
f23e871 removes the `connectivity_plus` dependency & now Spotube uses a pure dart library `internet_connection_checker` which resolves this issue

**Comment by qxb3** [comment]
Thanks!

**Comment by KRTirtho** [comment]
Fixed in v3.1.1
