### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by M0rtiferr** [KRTirtho/spotube#6]
I have no sound when audio is playing below 99%< ONLY plays when 100%. No clue why, i'm using Manjaro Budgie.

**Comment by M0rtiferr** [comment]
Here are logs if that could help
So from what i saw this 3x JS ERROR is whenever i change music

** (spotube:104499): CRITICAL **: 09:39:10.304: size_t fl_value_get_length(FlValue *): assertion 'self->type == FL_VALUE_TYPE_UINT8_LIST || self->type == FL_VALUE_TYPE_INT32_LIST || self->type == FL_VALUE_TYPE_INT64_LIST || self->type == FL_VALUE_TYPE_FLOAT32_LIST || self->type == FL_VALUE_TYPE_FLOAT_LIST || self->type == FL_VALUE_TYPE_LIST || self->type == FL_VALUE_TYPE_MAP' failed

** (spotube:104499): CRITICAL **: 09:39:10.306: size_t fl_value_get_length(FlValue *): assertion 'self->type == FL_VALUE_TYPE_UINT8_LIST || self->type == FL_VALUE_TYPE_INT32_LIST || self->type == FL_VALUE_TYPE_INT64_LIST || self->type == FL_VALUE_TYPE_FLOAT32_LIST || self->type == FL_VALUE_TYPE_FLOAT_LIST || self->type == FL_VALUE_TYPE_LIST || self->type == FL_VALUE_TYPE_MAP' failed

** (spotube:104499): CRITICAL **: 09:39:10.306: size_t fl_value_get_length(FlValue *): assertion 'self->type == FL_VALUE_TYPE_UINT8_LIST || self->type == FL_VALUE_TYPE_INT32_LIST || self->type == FL_VALUE_TYPE_INT64_LIST || self->type == FL_VALUE_TYPE_FLOAT32_LIST || self->type == FL_VALUE_TYPE_FLOAT_LIST || self->type == FL_VALUE_TYPE_LIST || self->type == FL_VALUE_TYPE_MAP' failed

** (spotube:104499): CRITICAL **: 09:39:10.306: size_t fl_value_get_length(FlValue *): assertion 'self->type == FL_VALUE_TYPE_UINT8_LIST || self->type == FL_VALUE_TYPE_INT32_LIST || self->type == FL_VALUE_TYPE_INT64_LIST || self->type == FL_VALUE_TYPE_FLOAT32_LIST || self->type == FL_VALUE_TYPE_FLOAT_LIST || self->type == FL_VALUE_TYPE_LIST || self->type == FL_VALUE_TYPE_MAP' failed
[ERROR:flutter/shell/common/shell.cc(94)] Dart Unhandled Exception: type '_Smi' is not a subtype of type 'PlayerErrorCode', stack trace: #0      LWM.receivePort.<anonymous closure> (package:libwinmedia/src/internal.dart:113)
#1      _RootZone.runUnaryGuarded (dart:async/zone.dart:1620)
#2      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#3      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
#4      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733)
#5      _StreamController._add (dart:async/stream_controller.dart:607)
#6      _StreamController.add (dart:async/stream_controller.dart:554)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192)

CONSOLE JS ERROR Unhandled Promise Rejection: NotSupportedError: The operation is not supported.
[ERROR:flutter/shell/common/shell.cc(94)] Dart Unhandled Exception: type '_Smi' is not a subtype of type 'PlayerErrorCode', stack trace: #0      LWM.receivePort.<anonymous closure> (package:libwinmedia/src/internal.dart:113)
#1      _RootZone.runUnaryGuarded (dart:async/zone.dart:1620)
#2      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#3      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
#4      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733)
#5      _StreamController._add (dart:async/stream_controller.dart:607)
#6      _StreamController.add (dart:async/stream_controller.dart:554)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192)

CONSOLE JS ERROR Unhandled Promise Rejection: NotSupportedError: The operation is not supported.
[ERROR:flutter/shell/common/shell.cc(94)] Dart Unhandled Exception: type '_Smi' is not a subtype of type 'PlayerErrorCode', stack trace: #0      LWM.receivePort.<anonymous closure> (package:libwinmedia/src/internal.dart:113)
#1      _RootZone.runUnaryGuarded (dart:async/zone.dart:1620)
#2      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#3      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
#4      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733)
#5      _StreamController._add (dart:async/stream_controller.dart:607)
#6      _StreamController.add (dart:async/stream_controller.dart:554)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192)

CONSOLE JS ERROR Unhandled Promise Rejection: NotSupportedError: The operation is not supported.
[ERROR:flutter/shell/common/shell.cc(94)] Dart Unhandled Exception: type '_Smi' is not a subtype of type 'PlayerErrorCode', stack trace: #0      LWM.receivePort.<anonymous closure> (package:libwinmedia/src/internal.dart:113)
#1      _RootZone.runUnaryGuarded (dart:async/zone.dart:1620)
#2      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#3      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
#4      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733)
#5      _StreamController._add (dart:async/stream_controller.dart:607)
#6      _StreamController.add (dart:async/stream_controller.dart:554)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192)

**Comment by KRTirtho** [comment]
This is quite weird. Do you have [webkit2gtk](https://archlinux.org/packages/extra/x86_64/webkit2gtk/) & [gtk3](https://archlinux.org/packages/extra/x86_64/gtk3) installed in your manjaro?

What audio server you're using, pulseaudio/pipewire?

To check pipewrie run:
`ps -e | grep pipewire`

To check pulseaudio run:

**Comment by KRTirtho** [comment]
Also please follow the ISSUE_TEMPLATE for Bugs while creating a bug related issue

**Comment by KRTirtho** [comment]
Due to inactivity & no further response, closing this issue
