### ISSUE TITLE
Reaction delay everywhere 

### ISSUE THREAD

**Issue by Mldshirali** [KRTirtho/spotube#601]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

The android app is very slow on reaction
It took about 5seconds to play songs after tapping on song, or tapping next/previous, but play/pause works welly phone is S9+ and i don't have any RAM or CPU issue.

### Expected Behavior

Smooth and fast reaction on request.

### Steps to reproduce

Search song
Tap on song
Delay for at least 4-5 seconds
Song get play
Tap on next
Delayed response again
Play/pause tap
Works smooth and fast just for play/pause 

### Operating System

Android

### Spotube version

V3.0.0

### Installation source

F-Droid (Android)

**Comment by KRTirtho** [comment]
F-Droid v3 isn't released yet. You're probably using the older version

**Comment by Mldshirali** [comment]
> F-Droid v3 isn't released yet. You're probably using the older version

Thank you for your answer
But I double checked it now
No it is v3 
I send you screenshot of f-droid page
Thank you again 🙏🙏🙏🙏
![Screenshot_20230728_081244](https://github.com/KRTirtho/spotube/assets/132843999/3ef4d07f-66c4-4963-916a-d5cca906f348)

**Comment by alxrdn** [comment]
> F-Droid v3 isn't released yet. You're probably using the older version

How can it be possible that v3 has been released 3 weeks ago and the repo 'owner' not even knowing it?!!!

What's happening here?

**Comment by Mldshirali** [comment]
> > F-Droid v3 isn't released yet. You're probably using the older version
> 
> How can it be possible that v3 has been released 3 weeks ago and the repo 'owner' not even knowing it?!!!
> 
> What's happening here?

IDK why actually.
This is about section of my app.
![Uploading Screenshot_20230728_134048.jpg…]()

**Comment by KRTirtho** [comment]
> > F-Droid v3 isn't released yet. You're probably using the older version
> 
> How can it be possible that v3 has been released 3 weeks ago and the repo 'owner' not even knowing it?!!!
> 
> What's happening here?

Lol don't worry. There was some error in the build process and the F-Droid team and I were trying to figure that out. I think they fixed it before me (I was busy for some days so couldn't work on the fix) :smile:

**Comment by KRTirtho** [comment]
Delay can sometime happen because of the Spotify to YouTube track matching. But good news, you can change youtube to piped (alternative faster youtube API) from the _"Settings > Playback > Youtube API Type"_

**Comment by tanmaytez** [comment]
> Delay can sometime happen because of the Spotify to YouTube track matching. But good news, you can change youtube to piped (alternative faster youtube API) from the _"Settings > Playback > Youtube API Type"_

It's still the same I changed it to youtube api and force stopped the app, it just takes time to load the song.. it plays after some seconds!

**Comment by KRTirtho** [comment]
> And will I face any issue in future by logging in Spotify account in this app?.. I just don't know, so asking

**Comment by KRTirtho** [comment]
v3.1.0 fixed this issue thus closing it
