### ISSUE TITLE
Permanent notification

### ISSUE THREAD

**Issue by LawsuitLigament** [KRTirtho/spotube#602]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The notification persists even after closing the app from background and/or stopping the song and unable to clear it.

### Expected Behavior

Expected the notification for the player will close after closing the app or pressing on the stop button in the notification.

### Steps to reproduce

1. Open the app
2. Play a song
3. Go to home screen
4. Stop the song from notifications or close app from recents
5. Notification is still there, unable to remove it without disabling app notifications

### Operating System

Android 10

### Spotube version

3.0.0

### Installation source

Play Store (Android)

**Comment by KRTirtho** [comment]
Can you share a short screen recording about the issue?

**Comment by KRTirtho** [comment]
Can you try "force stop"? It usually doesn't stay in the background. I wonder what could be the reason

**Comment by Aro320x** [comment]
> ### Gibt es hierfür ein bestehendes Problem?
> * [x] Ich habe die vorhandenen Probleme durchsucht
> 
> ### Aktuelles Verhalten
> Die Benachrichtigung bleibt auch dann bestehen, wenn die App im Hintergrund geschlossen wird und/oder das Lied angehalten wird und es nicht gelöscht werden kann.
> 
> ### Erwartetes Verhalten
> Es wird erwartet, dass die Benachrichtigung für den Player geschlossen wird, nachdem die App geschlossen oder in der Benachrichtigung auf die Stopp-Schaltfläche gedrückt wurde.
> 
> ### Schritte zum Reproduzieren
> 1. Öffnen Sie die App
> 2. Spiel ein Lied
> 3. Gehen Sie zum Startbildschirm
> 4. Stoppen Sie den Song aus den Benachrichtigungen oder schließen Sie die App aus den letzten
> 5. Die Benachrichtigung ist immer noch vorhanden und kann nicht entfernt werden, ohne die App-Benachrichtigungen zu deaktivieren
> 
> ### Betriebssystem
> Android 10
> 
> ### Spotube-Version
> 3.0.0
> 
> ### Installationsquelle
> Play Store (Android)
> 
> ### Weitere Informationen
> _Keine Antwort_
I can reproduce exactly the same behaviour with myself! 
The song even seems to continue playing in the notification, although it has long since stopped working in the app and is no longer displayed...! 
The notification badge can only be closed again with "Force stop".

**Comment by Aro320x** [comment]
![Screenshot_2023-08-15-21-54-30-281_oss krtirtho spotube](https://github.com/KRTirtho/spotube/assets/121295790/24c9fa1d-71e9-41d3-b78b-70858ed30a51)
![Screenshot_2023-08-15-21-54-41-397_com miui home](https://github.com/KRTirtho/spotube/assets/121295790/d976e06b-06f7-4573-9490-56663a3de945)
![Screenshot_2023-08-15-21-58-06-188_oss krtirtho spotube](https://github.com/KRTirtho/spotube/assets/121295790/5f26a3a1-6343-4b85-b0a9-611be3991ae0)
![Screenshot_2023-08-15-21-58-44-665_com miui securitycenter](https://github.com/KRTirtho/spotube/assets/121295790/ce9e6e98-1828-4caf-bcb2-acf867ee70dd)

**Comment by KRTirtho** [comment]
Finally fixed this issue in 470addca8319b33e740d8c11889efba5b5e1ddee 😅
