### ISSUE TITLE
Add a button to "Small Window" make user can exit the mode to normal

### ISSUE THREAD

**Issue by xiaozhangup** [KRTirtho/spotube#618]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

when i enabale the small window mode, i can't exit it directly
![图片](https://github.com/KRTirtho/spotube/assets/68374769/e8ac6062-8dbf-46ad-ae29-f3bfd8f6b584)
but if i click the button, the window will become the same size of small windows like this
![图片](https://github.com/KRTirtho/spotube/assets/68374769/7727c60b-dcdc-41d2-b042-40d3104f6a03)

### Suggested solution

exit to normal window size

**Comment by KRTirtho** [comment]
It should have resized the window back to last size. It wasn't doing due to a bug. It has been fixed now

**Comment by KRTirtho** [comment]
Fixed in v3.1.1
