### ISSUE TITLE
Album description showing not displaying correctly 

### ISSUE THREAD

**Issue by niranjan-md** [KRTirtho/spotube#620]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

All album descriptions are showing the href code instead of the description as shown in the screenshot.
![IMG_20230807_212811](https://github.com/KRTirtho/spotube/assets/107424211/8d7c7c9c-c08b-42d0-9275-06d7e16d9ae0)

### Expected Behavior

The description should show the actual description of the album.

### Steps to reproduce

1. Opened the app

### Operating System

Android

### Spotube version

v3.0.0

### Installation source

F-Droid (Android)

**Comment by KRTirtho** [comment]
This has been fixed in v3.0.1
