### ISSUE TITLE
Put a song to next in ques from playing playlist.

### ISSUE THREAD

**Issue by iamkake** [KRTirtho/spotube#626]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

While I was using the original Spotify app I used to play my liked songs playlist on shuffle and then press on the options of any songs (within the same playlist) I wanted to hear and press on the option to add to queue so that that songs would be brought to 1st position in the queue and then the playlist would continue in shuffle. But in Spotube there is no options to do the same which frustrate me a lot.

### Suggested solution

You could add an option to bring a song (Included in 'Playlist X') as the next one in the queue even while shuffle playing 'Playlist X'.

### Useful resources

https://drive.google.com/file/d/1qv1uC3wUC_xArneK6Cwc4wp4mS_OXMmR/view?usp=drivesdk

**Comment by KRTirtho** [comment]
You can reposition tracks in Queue. Just open the queue, drag the desired track right after the currently playing track & done
