### ISSUE TITLE
Add option to log in with YT music.

### ISSUE THREAD

**Issue by HelderRocket** [KRTirtho/spotube#635]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

I use the YT music service more than Spotify, and I was wondering if it is possible to add the login option to customize the experience.

### Suggested solution

Add the YT Music login option, along with the Spotify login option.

### Useful resources

Use Google Sign-In API. I don't know how this is done, so I asked Bing chat to show me a way, according to Bing IA, it can be done through Google Cloud Platform, and enable Google Sign-In API:

- Create a Google Cloud Platform project and enable the Google Sign-In API.

- Obtain the OAuth 2.0 credentials for your application, such as the client ID and client secret.

- Add the Google Sign-In SDK to your application, either by using a client library or by making direct HTTP requests to the API.

- Implement the authentication flow in your application, which consists of requesting user consent, obtaining an authorization code, exchanging it for an access token and ID token, and validating the ID token to obtain the user's information.

- Use the user's information to personalize and enhance the experience of your app, such as displaying their name, photo and email, or accessing other Google services with the access token.

### Additional information

These are the links cited by Bing:

https://support.google.com/accounts/answer/12849458?hl=es

https://www.bing.com/search?q=c%C3%B3mo+integrar+inicio+de+sesi%C3%B3n+con+google+en+una+aplicaci%C3%B3n+para+pc&form=SKPBOT&toWww=1&redig=0942ECEBF216495085183F489C459179

https://www.digitaldot.es/integrar-el-inicio-de-sesion-con-google-en-una-app-android/

**Comment by KRTirtho** [comment]
https://developers.google.com/youtube/v3/guides/quota_and_compliance_audits

**Comment by timkgh** [comment]
+1 to being able to play my own music I had uploaded to YTM in higher quality and music I had purchased previously under Google Play Music.

**Comment by KRTirtho** [comment]
Sorry but we've decided to keep Spotube strictly a Spotify client so we won't be adding support for other Music streaming platforms.
To migrate from YoutTube Music to Spotify (Spotube) you can use tools like [tunemymusic](https://www.tunemymusic.com/transfer/spotify-to-youtube-music) and [soundiiz](https://soundiiz.com/tutorial/spotify-to-youtube-music)
