### ISSUE TITLE
[Suggestion] Improved logo, more themes, and compare YT length with Spotify song length

### ISSUE THREAD

**Issue by notBradPitt** [KRTirtho/spotube#64]
1. I feel like the logo doesn't match up with the quality of the app. A more simplistic icon would match the app better
2. Would be great to have more option on the theme settings. The "dark" mode is still a bit too bright to me. A color picker would be a great alternative too
3. Compare song length from Spotify to YT to make sure the streamed songs are not from the music video or some sort that might have added sounds/clips. Could be done by making sure the YT song is +/- withing couple a seconds of the Spotify song length

On an unrelated note, I found a bug where some of the playlist suggestion wouldn't load and I can't scroll past it because it'll pull me back to that section

**Comment by JakeHL** [comment]
To add to this, being able to tweak the matching settings would be good. Some people might prefer a higher tolerance for matching songs based on length than others.

**Comment by KRTirtho** [comment]
Following state:
- [x] Would be great to have more option on the theme settings. The "dark" mode is still a bit too bright to me. A color picker would be a great alternative too
- [x] Compare song length from Spotify to YT to make sure the streamed songs are not from the music video or some sort that might have added sounds/clips. Could be done by making sure the YT song is +/- withing couple a seconds of the Spotify song length

> I feel like the logo doesn't match up with the quality of the app. A more simplistic icon would match the app better

We need good designers. Anyone willing to contribute to the project with their own icon design can create a Discussion in "Design" category for submitting their designs & getting votes in it
