### ISSUE TITLE
Windows media controls still not working

### ISSUE THREAD

**Issue by BloodRaven0** [KRTirtho/spotube#641]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When playing, windows doesn't recognize Spotube as a media application, therefore media buttons like pause/play, next and previous (found on most keyboards) don't work.

### Expected Behavior

It should be detected as a media application.
https://github.com/KRTirtho/spotube/commit/ae5edd17ef24f2a38ec1cc9c9623868b6ee9e352 claims to have fixed this, but I'm using 3.1.0 on Windows 10 21H2 and it doesn't seem to work still.

### Steps to reproduce

1. Open the app and start playing a song
2. Try to use media keys for pause, next or previous song
3. Realize they don't seem to do anything
4. Go to github to report the issue

### Operating System

Windows 10 21H2

### Spotube version

3.1.0

### Installation source

GitHub Releases (Binary)

**Comment by BloodRaven0** [comment]
Update:
It seems to work when you manually switch to a song, but as soon as it automatically switches to the next song, it isn't recognized by windows as a media application (until you manually switch again). Tried it on two PC's so far, the other is win10 22H2.

**Comment by BloodRaven0** [comment]
Update 2:
Also when manually switching songs, the windows media overlay shows the song you switched FROM instead of the one you switched TO, which introduces weird behavior if you try to switch via the media controls.

**Comment by DrVektor** [comment]
very good process. Health to your hands.

**Comment by michaelhenson** [comment]
I can confirm this is 100% replicable on Windows 11 21H2. As in the media controls simply do not function for me and never have.

**Comment by Keltskiy** [comment]
I'm having this issue as well currently.
Just installed spotube, Media keys don't work, it does show up in the media overlay.

Might be a windows issue with media keys getting locked to another application?
