### ISSUE TITLE
AppImage on Gentoo - Cannot find libmpv at the usual places

### ISSUE THREAD

**Issue by patomas** [KRTirtho/spotube#643]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After attempting to launch the AppImage file, it outputs the following message:

`package:media_kit_libs_linux registered.

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Cannot find libmpv at the usual places. Depending upon your distribution, you can install the libmpv package to make shared library available globally. On Debian or Ubuntu based systems, you can install it with: apt install libmpv-dev.

#0      NativeLibrary.ensureInitialized (package:media_kit/src/player/native/core/native_library.dart:73)
#1      nativeEnsureInitialized (package:media_kit/src/player/native/player/real.dart:48)
#2      MediaKit.ensureInitialized (package:media_kit/src/media_kit.dart:25)
#3      main (package:spotube/main.dart:80)
#4      _runMain.<anonymous closure> (dart:ui/hooks.dart:129)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296)
#6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189)

`

### Expected Behavior

The app should open

### Steps to reproduce

1. Downloaded the AppImage from the link on github ( https://github.com/KRTirtho/spotube/releases/latest/download/Spotube-linux-x86_64.AppImage )
2. Made the image executable with chmod +x
3. On the console, on the same folder as the appimage file, as a normal user  executed ./Spotube-linux-x86_64.AppImage
4. Got the error posted before
5. (just for testing) As a root got the same message

### Operating System

Linux 6.1.28-gentoo #6 SMP PREEMPT_DYNAMIC Fri Aug 11 09:39:20 +08 2023 x86_64 12th Gen Intel(R) Core(TM) i5-12600K GenuineIntel GNU/Linux

### Spotube version

3.1.0

### Installation source

GitHub Releases (Binary)

### Additional information

Packages installed related to this software:
1. mpv
    - mpv 0.35.1 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
2. fuse
    - 2.9.9-r2
3. libmpv locations
     - /usr/lib64/libmpv.so
     - /usr/lib64/libmpv.so.2
     - /usr/lib64/libmpv.so.2.0.0

Other appimage files work fine.

There seems to be a similar situation with Fedora reported, [Can't install on Feodra 38](https://github.com/KRTirtho/spotube/issues/614) but since it is a different OS with some differences to Gentoo, I'm making a new report.

I tried the solution mentioned by [RTTEXFile about a symbolic link](https://github.com/KRTirtho/spotube/issues/614#issuecomment-1666451013) but it didn't work. I tried copying the files to other common library folders, but that didn't work either.

**Comment by servusdei2018** [comment]
@patomas try this:

```sh
./Spotube-linux-x86_64.AppImage --appimage-extract
cp /usr/lib64/libmpv.so squashfs-root/lib/libmpv.so
```

And then to start it: `./squashfs-root/AppRun`

**Comment by servusdei2018** [comment]
@patomas 

Upon inspection, the spotube AppImage appears to overwrite LD_LIBRARY_PATH with `usr/lib`, which is unfortunate. Until this issue is fixed, you can try the following:

1. Extract the AppImage: `./Spotube-linux-x86_64.AppImage --appimage-extract` (extracts contents into `squashfs-root`)
2. Edit `squashfs-root/AppRun` and change `export LD_LIBRARY_PATH=usr/lib` to `export LD_LIBRARY_PATH=usr/lib64`
3. Launch spotube by executing `./squashfs-root/AppRun`

**Comment by servusdei2018** [comment]
Also, building on my prior comment, this highlights a discrepancy in your system that could continue to bug you down the road with other apps. If `usr/lib` does not exist, I would recommend symlinking it to `usr/lib64` (this would also allow you to use the default AppImage without the modification I mentioned above).

To symlink `usr/lib64` to `usr/lib`, run `# ln -s /usr/lib64 /usr/lib`. This may potentially impact your system if you have a multilib setup. However, since you're running gentoo, you *should* be knowledgeable enough to figure this part out for yourself.

**Comment by KRTirtho** [comment]
Oops sorry, I wrote that part of code & made that mistake 😅. But `usr/lib` is inside AppImage which isn't equivalent of `/usr/lib` if I'm not wrong

So how does /usr/lib64 affect AppImage? Also libmpv is shipped with the AppImage including many other shared objects (.so) so it shouldn't even require one to install libmpv or mpv at all

**Comment by KRTirtho** [comment]
Weird thing is libmpv.so & libmpv.so.2 is already embedded in the appimage

**Comment by duckwoqei** [comment]
Same error here: 
Spotube 3.1.1
Linux tux 5.15.52-gentoo-dist #1 SMP Sun Jul 3 05:21:48 -00 2022 x86_64 AMD Phenom(tm) II X4 965 Processor AuthenticAMD GNU/Linux

SOLVED:
Following suggestion by @servusdei2018:
1. Extract the AppImage: ./Spotube-linux-x86_64.AppImage --appimage-extract (extracts contents into squashfs-root)
2. Edit squashfs-root/AppRun and change export LD_LIBRARY_PATH=usr/lib to export LD_LIBRARY_PATH=usr/lib64
3. Emerging dev-libs/libappindicator
4. Launch spotube by executing ./squashfs-root/AppRun

is now working for me

**Comment by KRTirtho** [comment]
Btw there's a .tar.xz available which you use to manually install the app

**Comment by KRTirtho** [comment]
These are the AUR dependencies `'mpv' 'libappindicator-gtk3' 'libsecret' 'jsoncpp' 'libnotify'`
Make sure to include Gentoo equivalent of these deps

**Comment by KRTirtho** [comment]
Can anyone contribute with a `ebuild` script for Spotube? It'll be better than AppImage

The aur PKGBUILD can followed https://github.com/KRTirtho/spotube/blob/master/aur-struct/PKGBUILD

**Comment by KRTirtho** [comment]
Yea sure give it a try. It'll be a helpful for a lot of users & kind of a milestone for this app :muscle: 

I mean how many flutter apps are there that are installable on Gentoo without manual work?! :smile:

**Comment by xAlpharax** [comment]
I encountered this problem as well:

media_kit: ERROR: MediaKit.ensureInitialized
This indicates that one or more required dependencies could not be located.

Refer to "Installation" section of the README for further details:
GitHub  : https://github.com/media-kit/media-kit#installation
pub.dev : https://pub.dev/packages/media_kit#installation

TIP: Copy-paste required packages from the above link to your pubspec.yaml.

If you recently added the packages, make sure to re-run the project ("hot-restart" & "hot-reload" is not sufficient for native plugins).
--------------------------------------------------------------------------------

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Cannot find libmpv at the usual places. Depending upon your distribution, you can install the libmpv package to make shared library available globally. On Debian or Ubuntu based systems, you can install it with: apt install libmpv-dev.
#0      NativeLibrary.ensureInitialized (package:media_kit/src/player/native/core/native_library.dart:78)
#1      nativeEnsureInitialized (package:media_kit/src/player/native/player/real.dart:47)
#2      MediaKit.ensureInitialized (package:media_kit/src/media_kit.dart:26)
#3      main (package:spotube/main.dart:43)
<asynchronous suspension>

I have yet to try the guide from @servusdei2018.

**Comment by KRTirtho** [comment]
We dropped support for AppImage as it has become a burden for us to maintain both the AppImage packager and format for flutter_distributor which hinders the actual development of the app.

Spotube is available for all Linux distro through Flathub.
