### ISSUE TITLE
System tray icon is an empty space

### ISSUE THREAD

**Issue by helsingi** [KRTirtho/spotube#645]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I enable the "Show System tray icon" option in Settings, it shows an empty tiny space in the system tray

### Expected Behavior

show Spotube icon in the system tray when enabling this option

### Steps to reproduce

1. I installed the Spotube app from my Linux Mint distro "Software Manager" where it says the app is a flatpack
2. Followed instructions to log in my spotify account and worked fine
3. In Spotube Settings, I enabled the option to "Show System tray icon"
4. In my system tray, I saw a small space added but not an actual icon

### Operating System

Linux Mint 21.2 Cinnamon

### Spotube version

v3.1.0 build 21

### Installation source

Flathub (Flatpak)

### Additional information

I am not very techie but I think it has to do with Spotube compatibility with XApp Status Applet, because the empty space added is located in this applet

**Comment by KRTirtho** [comment]
> Is there an existing issue for this?
> [x] I have searched the existing issues

This is not for just checking. You've to make sure you've checked previous issues at least once before creating a new one

**Comment by KRTirtho** [comment]
If it isn't closed that means it still not fixed or implemented
