### ISSUE TITLE
RayCast extension

### ISSUE THREAD

**Issue by Liquefy7822** [KRTirtho/spotube#646]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

I usually use Spotify because I can use the ray cast extension to pause playing music, thus removing the need to switch windows on my Mac. 
![Screenshot 2023-08-21 at 7 38 43 PM](https://github.com/KRTirtho/spotube/assets/127311695/ff50c81e-1d2d-48ad-9848-93a336d3711d)

### Suggested solution

You could make try to make a raycast extension to allow for better control of your app. 

### Useful resources

how to make raycast extensions:[https://developers.raycast.com]( https://developers.raycast.com)

### Additional information

Would appreciate if it was available but I would still use spothub over spotify anyways

**Comment by KRTirtho** [comment]
Sorry this is a 3rd party implementation request. We don't make extensions or  unable implement features for other 3rd party apps 😅

**Comment by Liquefy7822** [comment]
Do you have anything I could use to see if I can do it myself?

**Comment by KRTirtho** [comment]
Sorry I'm not a macOS user & never used RayCast myself so I've no idea about it

**Comment by karniv00l** [comment]
https://developers.raycast.com/examples/spotify-controls

**Comment by Liquefy7822** [comment]
does spotube support applescript?

**Comment by KRTirtho** [comment]
Not sure what it is. Actually, macOS is barely supported & that's due to Apple's restrictive nature. It becomes harder to support anything from the Apple eco-system for Open Source project. I hope you understand

**Comment by KRTirtho** [comment]
Btw Spotube supports basic system media play/pause, prev/next/end track etc. controls

**Comment by KRTirtho** [comment]
Closing this is a 3rd party app implementation unrelated to Spotube
