### ISSUE TITLE
hours in counter

### ISSUE THREAD

**Issue by MatteoDelOmbra** [KRTirtho/spotube#648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When song is played, counter showing total time and current time of song displays only seconds and minutes - in case of podcasts it make sense to add hours also

### Expected Behavior

If hour > 0 display it the same as minutes and seconds

### Steps to reproduce

Play any podcast or song that is longer than hour
Move time cursor to something after 60minutes
Time display is broken
Ex. If podcasts is 2h10min long and you go to 1h30min, display will show you that you are on minute 30 and total time is 10min
Playlists that works like that and have such long tracks
https://open.spotify.com/playlist/4YS0rqjTdzkqFrUHnSxM74

### Operating System

android

### Spotube version

v3.1.0

### Installation source

Play Store (Android)

**Comment by KRTirtho** [comment]
Fixed in v3.1.2
