### ISSUE TITLE
Can't download .m4a File into Music Folder

### ISSUE THREAD

**Issue by 42ajakob** [KRTirtho/spotube#649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently I am not able to download my .m4a files into the Music folder. The reason for it beeing that the files it wants to download are .temp0 filles which GrapheneOS blocks for that folder.
https://grapheneos.org/usage#storage-access

So in order to download it I can put them into the Documents directory. The annyoing part about it would be to transfer them afterwards to the music folder.

### Expected Behavior

The expected behavior would be to creating a .m4a file without having to use a .temp0 file first in Order to get the permission from GrapheneOS to create the file.

### Steps to reproduce

1. install GrapheneOS :D
2. install spotube
3. give it permissions to use the Music Folder
4. download a song
5.  complete. failed install because permission is denied for other files then audios

### Operating System

GrapheneOS

### Spotube version

v3.1.0

### Installation source

F-Droid (Android)

### Additional information

I didn't know where else to put this issue.

**Comment by KRTirtho** [comment]
Now spotube downloads tracks in tmp folder and gets moved into the downloads folder. So it's been already fixed for a long time
