### ISSUE TITLE
Some songs stuck at starting when playing

### ISSUE THREAD

**Issue by jtzf520** [KRTirtho/spotube#651]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

When i skip to other songs, it will become stuck as it keeps repeating the same verse. 

### Expected Behavior

Song will play as normal

### Steps to reproduce

1. Opened Spotube
2. Played some songs
3. Run as normal
4. Skip to other song
5. Stuck on the same verse

### Operating System

Android 12

### Spotube version

v3.1.0

### Installation source

GitHub Releases (Binary)

**Comment by KRTirtho** [comment]
Duplicate of https://github.com/KRTirtho/spotube/issues/580
