### ISSUE TITLE
1000 songs cut off

### ISSUE THREAD

**Issue by glitch-228** [KRTirtho/spotube#654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

More than 1000 tracks display incorrectly (probably cut off)

![sp](https://github.com/KRTirtho/spotube/assets/66838958/35863e15-70ff-4014-9d05-d6b428e2462f)

### Expected Behavior

Should display full number

### Steps to reproduce

1. open app
2. open playlist with 1000+ songs
3. scroll to 999

### Operating System

windows

### Spotube version

v3.1.0

### Installation source

GitHub Releases (Binary)

**Comment by KRTirtho** [comment]
Also if the playlist is public, please share the link

**Comment by Robin-Sch** [comment]
> 1000 tracks long playlist 💀
> 
> How much time (approximately) it took to load all the tracks? Pagination is not implement thus I'm asking 😄 You're one patient person 😃

I have a 900 ish playlist and loading takes 23 seconds. I just googled "long spotify playlist" and got this playlist: https://open.spotify.com/playlist/6yPiKpy7evrwvZodByKvM9 (with 10,000 songs).

**Comment by GaucovyAero** [comment]
same issue here, my playlist also takes like 30 seconds to load https://open.spotify.com/playlist/4Z2E60JJwbiEEXQvOugOCj
and year, cant really sort stuff from date added cause it gets stuck at 1000 and doesnt continue to the actual latest stuff

**Comment by Robin-Sch** [comment]
Loading a big playlist is fixed for me with the latest update. In my playlist no numbers are shown, so I can't confirm whether this issue still exist.

**Comment by KRTirtho** [comment]
Yup, it only doesn't show for mobile for spacing issues. In desktop or tablet the index is shown and it works as expected now last time I checked.

**Comment by GaucovyAero** [comment]
sorting from newest still doesnt seem to work tho (android version)

**Comment by KRTirtho** [comment]
Yes, it works. I tested on 3.3.0 (latest)

**Comment by Robin-Sch** [comment]
For me it does not work.

1. Open a big playlist
2. Click "Sort Tracks" and "Sort by newest added"
3. Check the top song(s)
4. Go to spotify playlist on the spotify app
5. Scroll all the way down

The "newest" songs are not the same for me, not even close

**Comment by KRTirtho** [comment]
@Robin-Sch and @GaucovyAero this is a different issue. Create another issue for that or continue discussion in any issue similar to your problem. I'll hide your comments here as they're not related to this issue.

**Comment by glitch-228** [comment]
> 1000 tracks long playlist 💀
> 
> How much time (approximately) it took to load all the tracks? Pagination is not implement thus I'm asking 😄 You're one patient person 😃

Sorry for not answering for so long, I totally forgot github exists💀 
It took ~30 seconds to load the playlist
I don't think I can share the playlist, because it's my liked songs playlist
Also it's still like this at v3.4.0
![image](https://github.com/KRTirtho/spotube/assets/66838958/9964f6bc-bda1-4d66-b370-6f817e99bdad)

**Comment by KRTirtho** [comment]
![Image](https://github.com/user-attachments/assets/f141884d-a6e2-41ef-8710-165b1897c568)
Does not cut anymore and has room for upto 100k.

If someone's playlist has more than 100k tracks, bro's just immortal.
