### ISSUE TITLE
Unable to Install .deb package on Debian 12 Bookworm

### ISSUE THREAD

**Issue by AnnoyedLeek** [KRTirtho/spotube#657]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am unable to install the current release package on Debian 12. I get a dependency resolution failure upon installing the package, citing "gir1.2-appindicator3-0.1" as a non-installable package. I believe this is because that package has been obsoleted in this new version of Debian.

### Expected Behavior

An apt install should install the package without issue.

### Steps to reproduce

1. I ran a sudo apt install of the downloaded package.
2. I received the following readout:
3. sudo apt install ./Spotube-linux-x86_64.deb 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'spotube' instead of './Spotube-linux-x86_64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 spotube : Depends: gir1.2-appindicator3-0.1 but it is not installable
E: Unable to correct problems, you have held broken packages.

### Operating System

Debian 12

### Spotube version

v.3.1.0

### Installation source

GitHub Releases (Binary)

**Comment by KRTirtho** [comment]
A fix was applied. See if works for you
Download from the [nightly release](https://spotube.krtirtho.dev/other-downloads/nightly-downloads)

**Comment by KRTirtho** [comment]
Fixed in v3.1.1
