### ISSUE TITLE
Program does not launch

### ISSUE THREAD

**Issue by InterLinked1** [KRTirtho/spotube#665]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There are several open issues for "crash on launch", but this is slightly different; I'm not sure if the program is crashing per se, it doesn't even launch correctly.

Whenever I open the program, I get this:

![image](https://github.com/KRTirtho/spotube/assets/24227567/8509833e-74a3-4216-97fd-08333283f969)

I do have vc_redist as has been suggested on several other issues, so that is not the issue.

I do not see any log files in any obvious locations and no instructions are provided on where these might be found, so none are attached.

### Expected Behavior

Program should open

### Steps to reproduce

1. Install program
2. Try running the program

### Operating System

Windows 7 Enterprise x64

### Spotube version

3.1.0+21

### Installation source

GitHub Releases (Binary)

**Comment by KRTirtho** [comment]
Windows 7 is not supported :'(

**Comment by InterLinked1** [comment]
> Windows 7 is not supported :'(

Then this should be stated in the README. Right now it says Windows is supported, which is logically interpreted to mean all versions of Windows NT, since there is no qualifier. There should be some minimum system requirements posted.

**Comment by KRTirtho** [comment]
In general "Windows supported" translates to Windows versions that are officially supported & not discontinued 
If any discontinued version of Windows is supported that is what usually gets listed
Sorry for the confusion

**Comment by InterLinked1** [comment]
> In general "Windows supported" translates to Windows versions that are officially supported & not discontinued If any discontinued version of Windows is supported that is what usually gets listed Sorry for the confusion

I disagree, due to Windows having pretty good backwards-compatibility, most software works on Windows 7 even if not specifically intended to. If there is a specific minimum requirement that is known (which there is), it should be stated explicitly. That's how most projects and software operate.

Regardless, it's *always* good to specify a minimum version. It will spare users and superfluous issues in the future, saving everyone time. "Windows" clearly is ambiguous and will never mean the same thing to everyone.
