### ISSUE TITLE
App whitescreenes and freezes when launched on a second monitor

### ISSUE THREAD

**Issue by MerkomassDev** [KRTirtho/spotube#666]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Whenever i launch spotube, i move  it to my secondary screen. Sometimes i accidentaly launch it again from the taskbar and it opens as a whitescreen that can only be closed from the taskbar/taskmanager (and it also freezes the previously working window, but right now i can't replicate the freeze...)
<img width="2240" alt="Screenshot_56" src="https://github.com/KRTirtho/spotube/assets/70111455/552f7d1f-171d-441f-a83c-dd3426958008">

### Expected Behavior

Either should not launch the second window or shouldn't whitescreen

### Steps to reproduce

1. Open Spotube on main monitor 
2. Move Spotube window to the second monitor
3. Open Spotube again on main monitor without closing first window
4. Second Spotube window launches and whitescreens

### Operating System

Windows 10 Pro 22H2

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev)

**Comment by KRTirtho** [comment]
This is expected. Spotube is single instanced. So if you try to multiple instances it'll fail
Although the window should've closed
