### ISSUE TITLE
Full Playlist or Album Download ?

### ISSUE THREAD

**Issue by suga-daddy** [KRTirtho/spotube#67]
**Is your feature request related to a problem? Please describe.**
How to download an entire Album or Playlist ? afaik the download button only downloads one single track. 

**Describe the solution you'd like**
maybe a download button for the entire playlist somewhere on the top of the playlist page

**Describe alternatives you've considered**
alternative is to use ytdlp to download the playlist. 

**Additional context**

**Comment by KRTirtho** [comment]
It'd be abusive for the YouTube public API
When we use it for single track search & download a track at a time (this is what Spotube does) that doesn't put that much pressure on the YouTube API. But if we do it for 50-100 tracks at once, YouTube API will immediately block your IP & you won't be able to watch youtube videos (even if you're logged in) for at least a month

But if you really want to do this, you can use https://soundiiz.com to convert your Spotify playlists into YouTube playlist & than using a Playlists Downloader (e.g. youtubemultidownloader.net) to download all the NON-copyright song from there

**Comment by KRTirtho** [comment]
Well, I changed my mind and now full playlist albums can downloaded
