### ISSUE TITLE
Personal created playlist unable to load or play 

### ISSUE THREAD

**Issue by rdlr88** [KRTirtho/spotube#670]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to open a created playlist of mine is unable to load it just shows a grey space and doesn't load the playlist

### Expected Behavior

To load the playlist and be able also to rearrange order correctly and play the songs

### Steps to reproduce

I open the app 
Navigate to library, opening a personal created playlists and then it just stuck on a grey space

### Operating System

Android and windows

### Spotube version

3.1.1

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev)

**Comment by youlebret** [comment]
Hi, i Have same behavior on v3.1.1
I think it has something to do with the number of songs in the playlist, because for "short playlist" i got ( < 120 songs) spotube has no issue to load my playlist.

**Comment by KRTirtho** [comment]
@youlebret u r right. Currently, fetches all tracks at once without any pagination
Most of the time it loads after waiting for sometime. But it can also fail if the playlist is huge

**Comment by rdlr88** [comment]
Well for my case it's a big playlist , over 1000 songs so it just won't load at all

**Comment by victj99** [comment]
Hi. I have same problem, but my playlist has 163 songs.

This is the log.
------- DEVICE INFO -------
computerName: DESKTOP-5AJ03HP
numberOfCores: 12
systemMemoryInMegabytes: 8192
------- APP INFO -------
environment: release
version: 3.1.1
appName: spotube
buildNumber: 
packageName: spotube
---------- ERROR ----------
Null check operator used on a null value
------- STACK TRACE -------
#0      PlaylistView.build.<anonymous closure>.<anonymous closure> (package:spotube/pages/playlist/playlist.dart:75)
#1      ListBase.any (dart:collection/list.dart:114)
#2      PlaylistView.build.<anonymous closure> (package:spotube/pages/playlist/playlist.dart:75)
#3      _MemoizedHookState.value (package:flutter_hooks/src/primitives.dart:82)
#4      _MemoizedHookState.build (package:flutter_hooks/src/primitives.dart)
#5      HookElement._use (package:flutter_hooks/src/framework.dart:484)
#6      Hook.use (package:flutter_hooks/src/framework.dart:139)
#7      use (package:flutter_hooks/src/framework.dart:18)
#8      useMemoized (package:flutter_hooks/src/primitives.dart:61)
#9      PlaylistView.build (package:spotube/pages/playlist/playlist.dart:72)
#10     _ConsumerState.build (package:flutter_riverpod/src/consumer.dart:477)
#11     StatefulElement.build (package:flutter/src/widgets/framework.dart:5198)
#12     ConsumerStatefulElement.build (package:flutter_riverpod/src/consumer.dart:538)
#13     HookElement.build (package:flutter_hooks/src/framework.dart:436)
#14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5086)
#15     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:4805)
#17     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2780)
#18     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:903)
#19     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358)
#20     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284)
#21     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1214)
#22     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1072)
#23     _invoke (dart:ui/hooks.dart:142)
#24     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359)
#25     _drawFrame (dart:ui/hooks.dart:112)
------- CUSTOM INFO -------

**Comment by rramirezg22** [comment]
Pagination hasn't solved large playlists issues...

**Comment by pl1nk** [comment]
I have this issue, still not fixed 1000+ tracks playlist

**Comment by rramirezg22** [comment]
I gave up on Spotube and large playlists.

My current alternative: export with "spotify_to_ytmusic" and play with InnerTune

**Comment by KRTirtho** [comment]
Do you guys have local tracks in those `Playlist`? If the playlist is public, please share.

**Comment by rramirezg22** [comment]
> Do you guys have local tracks in those `Playlist`? If the playlist is public, please share.

no local tracks.

Please try with this playlist that I made public temporally:

https://open.spotify.com/playlist/2iPo2COjAR4N0wz783bcNS?si=a574b231f5ca4dd0

**Comment by KRTirtho** [comment]
First of all, dude, that was like the best playlist ever.

And I see the problem, because it consists of over 1200+ songs while you try to play the whole playlist, it takes time to fully fetch the entire playlist.
Imo, it should start playing the available tracks and should fetch the rest of 'em in the background. The API latency needs to be taken into account as well. It's generally lower for the official Spotify client compared to the API they provide for 3rd party applications.

**Comment by rramirezg22** [comment]
> First of all, dude, that was like the best playlist ever.
hey! thanks! glad you like Rock!

> And I see the problem, because it consists of over 1200+ songs while you try to play the whole playlist, it takes time to fully fetch the entire playlist. Imo, it should start playing the available tracks and should fetch the rest of 'em in the background. The API latency needs to be taken into account as well. It's generally lower for the official Spotify client compared to the API they provide for 3rd party applications.

And that's the problem... most of the time it simply does not play. A few times it plays but after a really long wait time.
Any chance you could implement a delay background update and start immediate playing with the last version of the playlist stored locally?

**Comment by KRTirtho** [comment]
My solution is:
Fetch few songs (e.g. first 100 tracks) at first and start to play it immediately. Then, in the background, load up the rest of the playlist while the loaded up tracks are being played.

**Comment by rramirezg22** [comment]
> My solution is: Fetch few songs (e.g. first 100 tracks) at first and start to play it immediately. Then, in the background, load up the rest of the playlist while the loaded up tracks are being played.

Thank you! Please let us know when your solution is implemented and merged to try it.

**Comment by FreezyEx** [comment]
Same issue here.

**Comment by rramirezg22** [comment]
> My solution is: Fetch few songs (e.g. first 100 tracks) at first and start to play it immediately. Then, in the background, load up the rest of the playlist while the loaded up tracks are being played.

Hello KRTirtho! Any updates on this issue ?

**Comment by KRTirtho** [comment]
Sorry, I forgot add it to the Project board. Thus the delay.
I'm working on this currently
