### ISSUE TITLE
Click target to open maximized song view

### ISSUE THREAD

**Issue by fm-sys** [KRTirtho/spotube#680]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![Screenshot_20230831_231635](https://github.com/KRTirtho/spotube/assets/64581222/b23bfe20-09d2-4ef7-8849-5fcc36c60d0b)

When clicking in the green area the song view is opening correctly. However, this will not happen when clicking somewhere in the red area. 

### Expected Behavior

View should open as well when clicking in the red area. 

### Steps to reproduce

Just play a song with a short title and click beside it. 

### Operating System

Android 

### Spotube version

3.1.0

### Installation source

F-Droid (Android)

**Comment by KRTirtho** [comment]
Fixed in v3.1.2
