### ISSUE TITLE
Can't browser all the albums in artist page in PC

### ISSUE THREAD

**Issue by devanarayanan44** [KRTirtho/spotube#683]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It only shows the first five albums in the artist page in PC.
![Screenshot 2023-09-01 122526](https://github.com/KRTirtho/spotube/assets/142968550/9e5122d4-514e-4a4c-a911-419ad50a7dad)

### Expected Behavior

Shows all the albums.

### Steps to reproduce

1. Opened the app.
2. opened artist page.

### Operating System

Windows

### Spotube version

v3.1.1

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev)

**Comment by KRTirtho** [comment]
Just swipe from right to left on top the albums. Common user interaction

**Comment by devanarayanan44** [comment]
oh thanks.
