### ISSUE TITLE
New releases section

### ISSUE THREAD

**Issue by devanarayanan44** [KRTirtho/spotube#685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There is nothing under the new releases section in the home page.

### Expected Behavior

Some songs or playlists under new releases section.

### Steps to reproduce

1. I opened the app.

### Operating System

Windows

### Spotube version

v3.1.1

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev)

### Additional information

NO

**Comment by KRTirtho** [comment]
You've to be logged in order to get your Artist's specific releases

**Comment by devanarayanan44** [comment]
It works now.
