### ISSUE TITLE
Downloaded songs play online.

### ISSUE THREAD

**Issue by devanarayanan44** [KRTirtho/spotube#688]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Download songs play online when played from artist page or playlist.

### Expected Behavior

downloaded songs play offline when played from playlists or artist page.

### Steps to reproduce

1. open the app
2. download a song
3. play it from a playlist.

### Operating System

Windows

### Spotube version

v3.1.1

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev)

**Comment by mdnfiras** [comment]
I can confirm this with spotube on MacOS.

Downloaded tracks can only be played offline if you play it from the downloaded tracks page. we can do that as a workaround, but that page is mixed with different tracks from different playlists and the experience is bad.

I never worked on this repo but I can try to implement a fix if a get a tip or two on where to start looking :D
