### ISSUE TITLE
[Bug] Song timer cannot go down when skipping around in a song, only can go up or to 0:00.

### ISSUE THREAD

**Issue by octia** [KRTirtho/spotube#695]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When playing a song, and skipping backwards, the current time doesn't change - unless the skip was to 0:00.
After skipping to a previous point in the track, the displayed time remains the same - until the pre-skip point was reached again, then it resumes normally. It also resumes counting properly when skipping ahead of the point that it's displaying at the moment.

### Expected Behavior

If I skip backwards in a song, I'd like to know what exact time in the song it is.

### Steps to reproduce

1. Play anything.
2. Wait so that the song timer is above 0:02 - doesn't really matter much how much. (above 0:02, because if it was 0:01, the only possible skip would be to 0:00. And 0:00 is a magic value where correct behaviour happens).
3. Move the slider that displays the current time in the song, backwards - effectively skipping backwards in the song. (Again, do not skip to 0:00)
4. Notice that the song timer has not skipped along with the track - it still displays the same value. For example if at 1:00 you skipped to 0:30, the timer would display 1:00 for 30 seconds, then resume going forward, together with the song).
5. Now optionally skip to 0:00. Notice how the timer gets properly set to 0:00, and increments every second, along with the song, properly.

### Operating System

Tested on Linux. Not tested on anything else.

### Spotube version

3.1.1

### Installation source

Arch User Repository (AUR)

### Additional information

![image](https://github.com/KRTirtho/spotube/assets/74676459/12df187a-45eb-4015-a9a3-ab7b50f86558)

This is clearly not 03:19 in a song that lasts 03:31. 

It should be noted that the song is skipping backwards properly. Simply the timer is displaying the wrong thing.

**Comment by KRTirtho** [comment]
OMG how the hack that gone unnoticed all this time :sweat_smile: 
Thanks for opening the issue :+1:

**Comment by KRTirtho** [comment]
It's been fixed
