### ISSUE TITLE
Have some sort of indication when app is waiting on other APIs

### ISSUE THREAD

**Issue by lemonJumps** [KRTirtho/spotube#696]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

When you want to play any song, or sometimes search for something the app appears to not do anything for a second or two (I'm pretty sure it's waiting for the api to answer)

### Suggested solution

having visual feedback that the app is waiting would be cool :D 
i think having 3 dot animation next to the element, like the play button next to the song would be sleek enough and not disruptive.

like you'll be able to see the press worked, and the app is just waiting.

### Additional information

i like the ui very much! and i think more apps should look like this.

**Comment by KRTirtho** [comment]
Implemented in b9d5c70301dd33ec26332e5e9a456ce5bfe73da0 & d12ea48b97596205d6309012d561ce83e5cbc9c1

**Comment by RokeJulianLockhart** [comment]
> https://github.com/KRTirtho/spotube/issues/696#issuecomment-1713173434

@KRTirtho, then shouldn't this be closed?

**Comment by KRTirtho** [comment]
Thanks for reminding
