### ISSUE TITLE
It give me "INVALID_CLIENT: Invalid redirect URI" when I submit to login with Spotify 

### ISSUE THREAD

**Issue by khaled-farahat** [KRTirtho/spotube#70]

**Comment by KRTirtho** [comment]
You missed a step. Read the docs carefully before submitting an issue

Give the app a name & description. Then Edit settings & add http://localhost:4304/auth/spotify/callback as Redirect URI for the app. Its important for authenticating step-3

![image](https://user-images.githubusercontent.com/61944859/166861757-eeaaa7a2-3e7a-4616-9c04-267c6551460c.png)

**Comment by OrdinaryGecko** [comment]
Also make sure that you have`http` and not `https` in the Redirect URI.

**Comment by KRTirtho** [comment]
Long time no reply. Assuming issuer issue got resolved. Closing issue

**Comment by KRTirtho** [comment]
@OrdinaryGecko @khaled-farahat see https://github.com/KRTirtho/spotube/issues/152#issuecomment-1265625104
