### ISSUE TITLE
Missing dependency in debian package

### ISSUE THREAD

**Issue by twilight1794** [KRTirtho/spotube#703]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In order to work, Spotube needs libmpv2 package as a dependency, however it is not listed in the Debian package.

### Expected Behavior

Spotube should run.

### Steps to reproduce

1. Install .deb package.
2. Execute the application.

### Operating System

Debian Bookworm unstable

### Spotube version

v3.1.1

### Installation source

GitHub Releases (Binary)

**Comment by Razuuu** [comment]
+1

**Comment by meenbeese** [comment]
Can be closed with #704 being merged
