### ISSUE TITLE
PostgrestException(message: duplicate key value violates unique constraint "tracks_youtube_id_spotify_id_idx")

### ISSUE THREAD

**Issue by 96fps** [KRTirtho/spotube#711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm running the appimage version on desktop linux.

Spotube froze during playback, and now freezes on every launch, with the console including the following exception:
```
flutter: PostgrestException(message: duplicate key value violates unique constraint "tracks_youtube_id_spotify_id_idx", code: 23505, details: Conflict, hint: null)
```

full console printout.
```
$ ./Spotube-linux-x86_64.AppImage 
package:media_kit_libs_linux registered.
ALSA lib conf.c:4002:(snd_config_hooks_call) Cannot open shared library (null) (/usr/lib/x86_64-linux-gnu/alsa-lib/usr/lib/libasound.so.2: cannot open shared object file: No such file or directory)
ALSA lib conf.c:4623:(snd_config_update_r) hooks failed, removing configuration
method call InitSystemTray
SystemTray::set_system_tray_info title: , icon_path: /tmp/.mount_SpotubVEMWzE/data/flutter_assets/assets/spotube-logo.png, toolTip: (null)
method call InitSystemTray

SystemTray::set_system_tray_info title: , icon_path: /tmp/.mount_SpotubVEMWzE/data/flutter_assets/assets/spotube-logo.png, toolTip: (null)
method call CreateContextMenu
value_to_menu_item type:label, label:Show/Hide
value_to_menu_item type:label, label:Play/Pause
value_to_menu_item type:label, label:Next
value_to_menu_item type:label, label:Previous
value_to_menu_item type:label, label:Quit
method call CreateContextMenu
value_to_menu_item type:label, label:Show/Hide
value_to_menu_item type:label, label:Play/Pause
value_to_menu_item type:label, label:Next
value_to_menu_item type:label, label:Previous
value_to_menu_item type:label, label:Quit
method call SetContextMenu
method call SetContextMenu
method call DestroySystemTray
method call InitSystemTray
SystemTray::set_system_tray_info title: , icon_path: /tmp/.mount_SpotubVEMWzE/data/flutter_assets/assets/spotube-logo.png, toolTip: (null)
method call CreateContextMenu
value_to_menu_item type:label, label:Show/Hide
value_to_menu_item type:label, label:Play/Pause
value_to_menu_item type:label, label:Next
value_to_menu_item type:label, label:Previous
value_to_menu_item type:label, label:Quit
method call SetContextMenu
flutter: PostgrestException(message: duplicate key value violates unique constraint "tracks_youtube_id_spotify_id_idx", code: 23505, details: Conflict, hint: null)
flutter: #0      PostgrestBuilder._parseResponse (package:postgrest/src/postgrest_builder.dart:345)
flutter: #1      PostgrestBuilder._execute (package:postgrest/src/postgrest_builder.dart:202)
flutter: <asynchronous suspension>
flutter: #2      PostgrestBuilder.then (package:postgrest/src/postgrest_builder.dart:422)
flutter: <asynchronous suspension>
```
Spotube's UI is briefly interactive while loading before becoming frozen, unable to even resize the window.

let me know what other information I can provide.

### Expected Behavior

The application to not lock up immediately on re-launch.

### Steps to reproduce

Somewhat unclear, as app is completely unresponsive seconds after every launch now.

I was skipping to play the next song the time it first froze, but that action worked without issue before then.

I can re-install and see if i can find the steps to reproduce, but I don't want to clear any internal program logs if they may be useful.

### Operating System

Linux (ubuntu 22.04)

### Spotube version

v3.1.1

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev)

**Comment by KRTirtho** [comment]
PostgrestException(message: duplicate key value violates unique constraint "tracks_youtube_id_spotify_id_idx") has nothing to do with freezing. It's a API response & expected to be shown

**Comment by KRTirtho** [comment]
Try the Flatpak or .deb version. AppImage can be unstable with all static linking of Flutter so it's planned to be removed in future in favor of Flatpak

**Comment by KRTirtho** [comment]
Since it's fixed automatically, I'm assuming this was an environment configuration error. Thus closing the issue
