### ISSUE TITLE
Wrong lyrics, redux

### ISSUE THREAD

**Issue by hackerb9** [KRTirtho/spotube#717]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I was playing an instrumental track, [Ethanopium](https://open.spotify.com/track/3BAFRaavwQiUoVABnrT8gF), and was curious what the Lyrics tab would show. Surprisingly, it showed lyrics for some random song I've never heard of. It also kept scrolling them on the screen over and over. (This was in plain format as the timed option was grayed out).

____
I mention the following for completeness since I'm not sure if it was related to trying to look at the lyrics: Although the song is only 4:36 long, it kept playing silence after it finished and counting up time. The duration on the meter said the song was 8 minutes 50 seconds long. I skipped to the next track and have not had that problem again. 

~~One possible confounding factor is that I logged out of the Spotify account while the song was playing and perhaps that caused the silence problem?~~ [Tested a second time and the bug occurs without logging out]

### Expected Behavior

I expected to see a blank page for lyrics. And I expected the page to not be jumping up and down frenetically. 

### Steps to reproduce

1. I logged into a premium Spotify account using the Android version of Spotube (F-droid app store), Version 3.1.1 build 23.
2. I searched for "dengue fever" and clicked on the first [play list](https://open.spotify.com/playlist/37i9dQZF1DZ06evO236k1G) that came up.
3. The first song was Ethanopium, which has no lyrics.
4. As it played I clicked on the bottom right tab for the Lyrics.

### Operating System

Android OSP (GrapheneOS)

### Spotube version

3.1.1

### Installation source

F-Droid (Android)

### Additional information

Thank you. I can't believe Spotube actually works. When Spotify Premium broke on the open source mobile browsers (it now gives a widevine error), I gave up on it. You rock!

**Comment by hackerb9** [comment]
I tried again and the bug is reproducible. Here is a screen shot of the "lyrics" for Ethanopium, which has no lyrics.

![Screenshot_20230914-181024](https://github.com/KRTirtho/spotube/assets/10174223/67856dcd-a5bf-4bff-9a68-fdef108cd82b)

**Comment by singhh9596** [comment]
I'm couldn't even find a single song that has lyrics available. I guess dev need to change the lyrics provider.

**Comment by KRTirtho** [comment]
It's all official Spotify lyrics. (Make sure you're logged in btw)

**Comment by singhh9596** [comment]
I'm definitely logged in. And if that's the case It maybe caused by the new
spotify update where lyrics are reserved for the subscribed users only.

**Comment by hackerb9** [comment]
I do see lyrics for some songs, so I think @singhh9596 may have a different issue. 

I don't have Spotify anymore, just a Spotify account. @KRTirtho, are you saying that when you look at [Ethanopium] (https://open.spotify.com/track/37bD7wEkP1171bmlacMb0i) with the official app, you see the bogus lyrics? And it plays for 8 minutes 50 seconds despite the music ending at 4:36? If so, then I apologize for wasting your time.

**Comment by singhh9596** [comment]
> I do see lyrics for some songs, so I think @singhh9596 may have a different issue.
> 
> I don't have Spotify anymore, just a Spotify account. @KRTirtho, are you saying that when you look at [Ethanopium](https://open.spotify.com/track/37bD7wEkP1171bmlacMb0i) with the official app, you see the bogus lyrics? And it plays for 8 minutes 50 seconds despite the music ending at 4:36? If so, then I apologize for wasting your time.

No never had such experience with spotify and I'm saying that spotify doesn't show lyrics to free users anymore.

**Comment by KRTirtho** [comment]
> I do see lyrics for some songs, so I think @singhh9596 may have a different issue.
> 
> I don't have Spotify anymore, just a Spotify account. @KRTirtho, are you saying that when you look at [Ethanopium](https://open.spotify.com/track/37bD7wEkP1171bmlacMb0i) with the official app, you see the bogus lyrics? And it plays for 8 minutes 50 seconds despite the music ending at 4:36? If so, then I apologize for wasting your time.

Not sure why's this specific song has wrong lyrics. But if you don't believe me it's from the official endpoint [check this file](https://github.com/KRTirtho/spotube/blob/master/lib/services/queries/lyrics.dart#L66-L113)

You can check with a cURL or Postman or any HTTP client to check if it's returning the same lyrics for the same track

**Comment by KRTirtho** [comment]
@hackerb9 Sometimes multiple versions of a same song is uploaded in to Spotify. Check the id of official app's track & the track you're playing on Spotube
If they are different then chances are the lyrics will be different as well

**Comment by KRTirtho** [comment]
> No never had such experience with spotify and I'm saying that spotify doesn't show lyrics to free users anymore.

@singhh9596 Don't worry we got you bro. Singing should be free. The lyrics are submitted by users & synced by community. We deserve to sing the song with correct lyrics. So even if Spotify doesn't support, Spotube will always support synced lyrics one way or another

**Comment by KRTirtho** [comment]
> > Singing should be free.
> 
> Yes!
> 
> Thank you for the clear explanation and curl example. Is there some way, as a Spotube user, to copy the URLs used for retrieving the lyrics?
> 
> I apologize for wasting your time on a problem which Spotify itself suffers from. Spotube is better than Spotify in many ways, but I do not expect it to be magic.
> 
> Are there plans for Spotube users to be able to submit lyrics and corrections?

You can use the Share button to copy the url

**Comment by singhh9596** [comment]
Lyrics have returned even for the free users.
