### ISSUE TITLE
Library Albums Page Does Not Load

### ISSUE THREAD

**Issue by hl2guide** [KRTirtho/spotube#726]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Library Albums Page Does Not Load

![Library ➡ Albums](https://github.com/KRTirtho/spotube/assets/17044982/bb52743d-f0d3-468a-8019-24b140bcc1a6)

### Expected Behavior

Library Albums Page Loads

### Steps to reproduce

1. Open app
2. Go to Library
3. Go to Albums tab

### Operating System

Windows 10 Pro

### Spotube version

3.1.2

### Installation source

GitHub Releases (Binary)

**Comment by KRTirtho** [comment]
Try close/reopening the app
