### ISSUE TITLE
Cannot verify credentials

### ISSUE THREAD

**Issue by yuckyrat** [KRTirtho/spotube#73]
Running Mull on a Samsung Galaxy S10 (with the security features off, so it's not caused by those.) Everything works until I press the agree button, at which point it stops loading and times out. It seems to be an issue with the localhost, but if it's an issue with Spotify itself, I apologize.

**Comment by maxsubs** [comment]
It also times out to me after I click on agree on Android. On that screen my account name doesn't show up it just says "you have logged in as ((AccountName)). I have added http://localhost:4304/auth/spotify/callback as redirect url.
I have tried with two browsers Lightning and PrivacyBrowser and also have tried stable (Fdroid) version and nightly apk, what can I do? thanks

**Comment by maxsubs** [comment]
solved! it works using Chrome on Android, don't know why

**Comment by maxsubs** [comment]
so I got logged off on the same day I could log in and for a week I've been trying to log in again with no success, times out on different android browsers. no way to log in. Spotube appears on my linked apps on Spotify, but not on Spotube android app. Any help?

**Comment by KRTirtho** [comment]
The issue of automatically logging out has been fixed already & will available on the next update

But the timing out issue on the OAuth process should be fixed by just re-installing the app with fresh downloaded copy
