### ISSUE TITLE
Add Arabic language to Spotube

### ISSUE THREAD

**Issue by muhammadbahaa2001** [KRTirtho/spotube#732]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

I understand English but I would like to see Arabic Language

### Suggested solution

I can add Arabic language, but I want to know where to start from?
Strings.xml file or something...?

**Comment by KRTirtho** [comment]
Please follow this https://github.com/KRTirtho/spotube/blob/master/CONTRIBUTION.md#submit-translations

**Comment by KRTirtho** [comment]
#740
