### ISSUE TITLE
Wrong Song Playing

### ISSUE THREAD

**Issue by clubberduck** [KRTirtho/spotube#737]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

For example, I want to listen to Amon Amarth's 7th song from their first album, Once Sent From The Golden Hall. I press the button for the song 'Amon Amarth', and I get 'Heidrun' instead. I understand that the songs playing get searched on youtube, but my recommendation would be to search the name of the song, then artist, then album, kinda like: 
%song name% %album name% %artist name%, instead of %song name% like it seems to be right now.
For a sillier example, on the bonus edition of the same album, there is a live version simply titled 'Amon Amarth (Live)'.
The result, a 50-minute concert that begins with the end of Iron Maiden's 'Run To The Hills'.
![image](https://github.com/KRTirtho/spotube/assets/145443881/b7910065-2291-4687-984e-786dca89d8d2)

### Expected Behavior

When I click on Amon Amarth I want Amon Amarth, not Heidrun or Guardians Of Asgaard

### Steps to reproduce

1. Open Spotube
2. Enter the album page of "Once Sent From The Golden Hall" by using the search function.
3. Press either "Amon Amarth" or "Amon Amarth (Live)"

### Operating System

Android, Linux

### Spotube version

v3.1.2 on linux, v3.1.1 on android

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev), F-Droid (Android)

### Additional information

I really hope this can be fixed, as the app itself is wonderful, and miles better at **not** consuming battery than regular spotify.
I have also tested it with 'In Flames'. Their song named after the band also has the same issue. It plays 'Meet Your Maker'

**Comment by KRTirtho** [comment]
> . I understand that the songs playing get searched on youtube, but my recommendation would be to search the name of the song, then artist, then album, kinda like:
%song name% %album name% %artist name%, instead of %song name% like it seems to be right now.

Nope it's already using <cleaned Song Name> - <all artist name separated by comma>

But the problem with `Amon Amarth` is while cleaning the title Spotube removes any artist's name from the title to avoid duplication of Artist's name. That's why the entire track name is getting removed

[ ] Looks like we've to make sure to check if title is not empty string after cleaning
    - If it's empty "" don't clean the title

**Comment by clubberduck** [comment]
Thanks man, I can't wait to see this fixed!

**Comment by clubberduck** [comment]
And by the way, why does any list start with 0?

**Comment by clubberduck** [comment]
Well I thought the discussion was over, so I assumed I should close it

**Comment by clubberduck** [comment]
I just realized what alternate sources does... I feel I should just post here that this can be fixed on a song by song basis with alternate sources.

**Comment by MatteoDelOmbra** [comment]
Another example of that bug (maybe can be useful during testing) is almost whole album https://open.spotify.com/album/2ItrzcwLrygr4I6wlZ3HGU
My guess it that problem occurs when "#" char or any polish letter (ż,ó,ł,ć,ę,ś,ą,ź,ń) is used, because problem exists only in such tracks here.
