### ISSUE TITLE
Spotify Account connection

### ISSUE THREAD

**Issue by mattish91** [KRTirtho/spotube#744]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the tutorial it says sp_key as the second value, but in my case this value was "__secure-TPASESSION" and not "sp_key" like tutorial said. 

### Expected Behavior

1. expected "sp_key" to be located in my cookie session.
2. Or that the tutorial would suggest "__Secure-TPASESSION" as a alternative.

### Steps to reproduce

1. I opened the app
2. went trough the Spotify connect tutorial
3. Saw that i needed "sp_dc" and "sp_key".
4. Realized that "sp_key" must have been renamed by Spotify to "__Secure-TPASESSION" (Or this could be becaus i use Google SSO).
5. Pressed "Connect" And it all worked out just fine. 

### Operating System

Windows

### Spotube version

v3.1.2

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev)

### Additional information

"sp_key" or "__Secure-TPASESSION" in tutorial as this obviously was the case here. See attached picture (Sensitive data hidden).

![image](https://github.com/KRTirtho/spotube/assets/6743307/a86128d7-c617-4fb8-a097-cb9be442a9b8)

**Comment by KRTirtho** [comment]
Interesting

**Comment by mattish91** [comment]
Interestingly enough for both my kids it was something else, for one it was sp_key and for the other kid it was sp_gaid, so i suppose this is the third option of them 🤔

**Comment by KRTirtho** [comment]
Yeah, thanks for the suggestion. Does the account with Google SSO work in mobile as well?

**Comment by mattish91** [comment]
Actually yes

**Comment by mattish91** [comment]
Today the account had been logged out from my browser session and i had to log out and in again in order to get the connection working, but now i did have both sp_dc and sp_key, just tought i'd let you know with some kind of update in this thread. :) Still working fine with Google SSO tho :)

**Comment by AleJavierHY** [comment]
Hello, I have installed the Windows version of Spotube v3.4.0 but when I try to log in with my Spotify account by pasting the values of **sp_dc** and **sp_key** and try to log in I am getting this error:

```
HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../third_party/boringssl/src/ssl/handshake.cc:393))
```

**Comment by KRTirtho** [comment]
@AleJavierHY  Follow #905 

Also update your Windows. It's generally outdated certificates.

**Comment by KRTirtho** [comment]
@mattish91 so I discovered that sp_key or sp_gaid is not even necessary so if you even put "lmao" for sp_key field, it'll work. The sp_dc is the only required one. And it must not be shared with anyone as it's top secret.

I've removed the sp_key field in the Nightly version and there should be no more confusion in the upcoming versions.

**Comment by mattish91** [comment]
> @mattish91 so I discovered that sp_key or sp_gaid is not even necessary so if you even put "lmao" for sp_key field, it'll work. The sp_dc is the only required one. And it must not be shared with anyone as it's top secret.
> 
> I've removed the sp_key field in the Nightly version and there should be no more confusion in the upcoming versions.

Alright, thats pretty cool. Then i know why it worked then 😅
