### ISSUE TITLE
Clicking on quit button doesn't actually quit it.

### ISSUE THREAD

**Issue by qxb3** [KRTirtho/spotube#746]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When minimizing spotube to be in the system tray and clicking the quit button doesn't actually quit it.

https://github.com/KRTirtho/spotube/assets/59109346/237740b0-faec-4be3-80ea-4641a191d503

### Expected Behavior

Clicking on the quit button should quit it.

### Steps to reproduce

1. Open the app
2. Make the app minimize to system tray by clicking the x button
3. left or right click the app icon on the system tray and click quit

### Operating System

Arch Linux v6.4.12-arch1-1 (KDE Plasma)

### Spotube version

Spotube v3.1.2-1

### Installation source

Arch User Repository (AUR)

### Additional information

After you click the quit button and click the icon again it doesn't do anything or show the options

**Comment by KRTirtho** [comment]
I checked this on multiple systems. Sorry, couldn't replicate it
Does it happen all the time?

**Comment by qxb3** [comment]
The problem might be on my side and not the spotube since other applications that can closed with similar fasion as spotube is not exiting either. closing this
