### ISSUE TITLE
Spotube keeps getting logged out of my spotify each time I close the app.

### ISSUE THREAD

**Issue by Kyouma960** [KRTirtho/spotube#751]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Spotube keeps getting logged out of my spotify each time I close the app.

### Expected Behavior

Spotube should not keep getting logged out of my spotify each time I close the app.

### Steps to reproduce

I installed the app, signed in using the cookies, nothing else modified.

### Operating System

Archlinux

### Spotube version

3.1.2-1

### Installation source

Arch User Repository (AUR)

**Comment by KRTirtho** [comment]
Show us the logs?

**Comment by KRTirtho** [comment]
Closing as stale
