### ISSUE TITLE
Add headset detection

### ISSUE THREAD

**Issue by mascaldotfr** [KRTirtho/spotube#753]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

As soon as i power off my bluetooth/wired earbuds, the music plays through my phone loudspeaker if i forget to pause before that. Other medias apps like newpipe or VLC are pausing.

### Suggested solution

It would be nice to make spotube pauses playing music when a headset is removed, and playing music again when inserted, and making it optional, as VLC does (**see below**).

### Useful resources

**VLC options dialog**
![image](https://github.com/KRTirtho/spotube/assets/116852972/1fd4e883-bf49-4017-872b-fa08514783a0)

**Third party plugins**
Flutter has a number of 3rd party plugins dealing with such events, for example https://pub.dev/packages/headset_connection_event, but since i don't know the framework i'm indeed not recommending anything :wink:

**Comment by KRTirtho** [comment]
It has been fixed recently  15d466a04538ec70c3a0c132f2baaaf8690f8d4e

**Comment by mascaldotfr** [comment]
I tested the latest nightly build apk, it works fine on my Android phone, thanks a lot :) I'm closing.
