### ISSUE TITLE
Unable to install new update

### ISSUE THREAD

**Issue by nsrahmad** [KRTirtho/spotube#756]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On latest Linux mint, I am currently using Spotube 3.1.1 without issues. When trying to install the new version 3.1.2 x64 deb package, I get :
![image](https://github.com/KRTirtho/spotube/assets/10996250/2529a049-93b5-4d8c-9ce5-579bd9d139ed)

### Expected Behavior

able to install new version

### Steps to reproduce

Try to install newest version

### Operating System

Linux Mint 21.2

### Spotube version

3.1.2

### Installation source

GitHub Releases (Binary)

**Comment by KRTirtho** [comment]
5115e041e78c20fce798a80f1d844bfc60746958 fixed it already. Check out the nightly
