### ISSUE TITLE
responsiveness issue on Z Fold 3 in the smaller display

### ISSUE THREAD

**Issue by owencz1998** [KRTirtho/spotube#76]
When creating a playlist on the z fold 3 it doesn't show unless I use the app in tablet mode also the setting when creating playlist the bottom option letters go over the cancel button and doesn't allow me to tick the option.

Samsung Z fold 3

**Comment by KRTirtho** [comment]
When creating Github issues please keep the title proper & concise
Provide details of the problem in the description part with devices info , way to reproduce (optional) & if possible provide some screenshots too
Its best recommended to use the provided ISSUE TEMPLATEs to fill out description with structure

**Comment by owencz1998** [comment]
Sorry haha not used to this I might off messed the other issue up aswell

**Comment by RaptaG** [comment]
Added in 3.0.0
