### ISSUE TITLE
Changing song issue

### ISSUE THREAD

**Issue by owencz1998** [KRTirtho/spotube#77]
Changing song issue  When changing a song it doesn't change to the correct song but shows the chosen song in the player with the incorrect audio playing.  Z fold 3 Version 2.1.0

**Comment by KRTirtho** [comment]
There's no guarantee it will always grabe the exact song all the time especially when some songs are less known/popular. Spotube just searches Spotify song in youtube & plays the best possible match. There is no way to find a 100% match. The probability of finding right track is somewhat near 80~85%
Its kind of a limitation & a known fact but not an issue

**Comment by owencz1998** [comment]
Ahhh I understand no worries dude

**Comment by KRTirtho** [comment]
To overcome this issue I added a customizable track match algorithms option in Settings. The user from now on will be able to choose from following 3 ways of how Spotube would match a YouTube track with a Spotify one:

- Popular (Ranked by views & title)
- Authentic Popular (Ranked by views, title but from only Artist's channel)
- YouTube's choice is my choice (Selects the first non-live result found from YouTube)

**Comment by KRTirtho** [comment]
It'll be available in the next  update

**Comment by owencz1998** [comment]
Thanks for the update mate 👊

**Comment by KRTirtho** [comment]
Update released
