### ISSUE TITLE
AMOLED Mode doesn't stay after app closed 

### ISSUE THREAD

**Issue by MerkomassDev** [KRTirtho/spotube#778]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After you turn AMOLED mode on and close the app, it reverts back to basic dark mode

### Expected Behavior

Amoled mode staying on after app being closed 

### Steps to reproduce

1. Switch to dark theme
2. Turn on Amoled mode
3. Close app
4. Open app
5. Amoled gone

### Operating System

Android 12

### Spotube version

3.1.2-nightly 148

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev)

**Comment by MerkomassDev** [comment]
Also there's a typo in the description![Screenshot_2023-10-03-22-48-43-146-edit_oss.krtirtho.spotube.nightly.jpg](https://github.com/KRTirtho/spotube/assets/70111455/61167f49-1c90-4a84-a3f6-30e1f4402fee)

**Comment by RUDRANSHFLY** [comment]
Hi, @MerkomassDev  can you assign this issue to me? I want to work on this issue.

**Comment by MerkomassDev** [comment]
@RUDRANSHFLY i don't seem to have the ability to do that unfortunately

**Comment by KRTirtho** [comment]
@RUDRANSHFLY go ahead

**Comment by KRTirtho** [comment]
It's fixed and it's bug report on nightly so closing
