### ISSUE TITLE
Add subtitles/lyrics delay option 

### ISSUE THREAD

**Issue by ShinjuSenju** [KRTirtho/spotube#78]
Umm an option for lyrics delay would be fine so that we can manually sync the lyrics

**Comment by KRTirtho** [comment]
Please use the feature request template to provide brief explanation for the feature/enhancement you're requesting 

This will not fix the issue of out of sync at all. We've to find a better way to implement Synced Lyrics for Spotube. Manually syncing lyrics is really tempting & will make the end user experience horribly poor
