### ISSUE TITLE
Media Duration

### ISSUE THREAD

**Issue by ibrahimashraf** [KRTirtho/spotube#782]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

song duration not appearing 
<img width="960" alt="image" src="https://github.com/KRTirtho/spotube/assets/16999985/41b9619b-dc2e-4d76-9759-9896784702ef">
play button not working
<img width="603" alt="image" src="https://github.com/KRTirtho/spotube/assets/16999985/a01d2625-f655-4bd7-925c-da9106672b17">

### Expected Behavior

bugs

### Steps to reproduce

bugs

### Operating System

win11

### Spotube version

latest

### Installation source

GitHub Releases (Binary)

**Comment by KRTirtho** [comment]
Looks like it only happens when queue is reloaded from cache
