### ISSUE TITLE
Download location picker returns invalid path (Android)

### ISSUE THREAD

**Issue by DirkDuesentrieb** [KRTirtho/spotube#787]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the settings tab there is an option to change the folder where to download the songs. The default location is **/storage/emulated/Download/Spotube**. Saving songs here **works**.
After manually changing the location e.g to the same folder, the path seems broken. It now says (after selecting the same folder as before)
**content://com.android.externalstorage.documents/tree/primary%3ADownload%2FSpotube** and downloading songs **does not work** anymore.

### Expected Behavior

Manually choosing the (default) folder should return **/storage/emulated/Download/Spotube** as location.

### Steps to reproduce

1. download a song after a clean installation 
2. go to the settings tab
3. search for the option to change the download location
4. look at the current setting
5. press the icon to change the location
6. the location picker should show you the current location with the song just downloaded
7. select this same location by pressing the button
8. the download location should be the same as before, if not, you reproduced this bug

### Operating System

Android 12  and Android 11

### Spotube version

v3.1.2

### Installation source

F-Droid (Android)

### Additional information

Great app!

**Comment by DirkDuesentrieb** [comment]
![Screenshot_2023-10-06-12-10-29-11_1c96baa6fc3a4338d23fd334c3c04599_121202](https://github.com/KRTirtho/spotube/assets/31920026/777e707d-4d96-4f1f-9132-ffbee8e2f9b7)

**Comment by KRTirtho** [comment]
Already fixed
