### ISSUE TITLE
not logged in

### ISSUE THREAD

**Issue by senolfndk** [KRTirtho/spotube#79]
:(
![Ekran görüntüsü 2022-05-12 052618](https://user-images.githubusercontent.com/52818836/167979973-32ad20fd-f225-40d3-adae-80c933394c53.png)
![öo](https://user-images.githubusercontent.com/52818836/167979976-bf480fdd-7ca2-4aee-9511-9268ae7aaf39.png)

**Comment by KRTirtho** [comment]
Already discussed https://github.com/KRTirtho/spotube/discussions/49https://github.com/KRTirtho/spotube/discussions/49

**Comment by senolfndk** [comment]
😒
![Ekran görüntüsü 2022-05-12 113107](https://user-images.githubusercontent.com/52818836/168029385-c375f10b-0aaa-42cd-b8aa-1e26b34aaf3a.png)
![kmn](https://user-images.githubusercontent.com/52818836/168029393-6bdcf9a7-1cd4-4424-805e-78275bbd2475.png)
![pkoko](https://user-images.githubusercontent.com/52818836/168029396-7dc46fd1-84fd-40f9-8439-03aea5185e4a.png)
