### ISSUE TITLE
Can't tell live and studio versions apart

### ISSUE THREAD

**Issue by yephny** [KRTirtho/spotube#80]
**Describe the bug**
There is no distinction between live and studio versions of a song.

**To Reproduce**
1. Play a studio recording.
2. Chances are the app plays a live version it found on Youtube.

**Expected behavior**
I don't know how but there needs to be a way for the app to tell apart live and studio recordings. The former has the word "live" in the title for the most part.

v.2.1.0 on Android 10.

**Comment by KRTirtho** [comment]
Please provide the track you're facing problem with. Spotube can distinguish between Live & Official version of a track

**Comment by yephny** [comment]
I have this issue with multiple tracks, one of which is Katyusha. @

**Comment by KRTirtho** [comment]
It should be fixed and available from v2.4.0
