### ISSUE TITLE
Taskbar won't unhide 

### ISSUE THREAD

**Issue by Jimmy70022** [KRTirtho/spotube#800]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Context: I've set the taskbar to hide automatically like so:
![image](https://github.com/KRTirtho/spotube/assets/68635802/fc190624-c1bb-4a9b-89cc-e23c47b0c131)

Current Behavior: When I move my mouse to the bottom of the screen, the resize arrow replaces my mouse arrow but the doesn't show.

### Expected Behavior

The taskbar should pop up when I move my mouse to the bottom of the screen

### Steps to reproduce

1. Set the taskbar to automatically hide: 
![image](https://github.com/KRTirtho/spotube/assets/68635802/ead48bcd-50ec-4f29-94e0-2e02a45185ad)

2. Open the app
3. Maximise the app
4. Move the mouse to the bottom of the screen
5. Observe

### Operating System

Edition	Windows 11 Home | Version	22H2 Installed on ‎16/‎10/‎2022 | OS build	22621.2283 | Experience	Windows Feature Experience Pack 1000.22662.1000.0

### Spotube version

v3.1.2

### Installation source

GitHub Releases (Binary)

### Additional information

Workaround: Press the windows key to show the taskbar

**Comment by KRTirtho** [comment]
How's this related to Spotube?

**Comment by Jimmy70022** [comment]
Spotube is one of the few apps that have this problem

**Comment by Jimmy70022** [comment]
Microsoft edge does not have this problem, i.e. the taskbar will unhide when I move the mouse to the bottom of the screen even though the window is maximised and focused

**Comment by KRTirtho** [comment]
I don't think this is related to Spotube. Seems like more of bug from the windows taskbar or maybe Flutter framework
Because we are not managing stuff like this which are quite low-level

**Comment by Jimmy70022** [comment]
Okay
