### ISSUE TITLE
dynamic music source switch

### ISSUE THREAD

**Issue by Djtrip83** [KRTirtho/spotube#801]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

As a user, I prefer Piped YouTube Music as quality of music source. Some songs, perhaps rare ones, may not be found on YouTube Music and therefore playlists get stuck or skipped. To listen to it, I would need to pause and change source mid-playlist.

### Suggested solution

The settings should allow an order of preference/priority when picking the music source so that if YouTube Music cannot find it or it is unreachable it switches to normal YouTube automatically.  Same if Piped is down. This switch is temporary for the one song only.

### Useful resources

--

### Additional information

YouTube Music sometimes does not have all the music because it is not out yet on that platform. But it may be on normal YouTube already for promotional reasons.

**Comment by KRTirtho** [comment]
This was added in 3.5.0. It'll switch the sources in tracks are not found
