### ISSUE TITLE
Ability to select/copy lyrics

### ISSUE THREAD

**Issue by MerkomassDev** [KRTirtho/spotube#802]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

It would be cool if the lyrics in the plain lyrics tab were selectable so I could easily copy them

### Suggested solution

Add the ability to select/copy lyrics

### Useful resources
can't select :(
<img width="1092" alt="Screenshot_65" src="https://github.com/KRTirtho/spotube/assets/70111455/c9fe9194-5726-43a4-bd72-69dbe65b7af2">

**Comment by Jimmy70022** [comment]
In the meantime, you can use the [text extractor](https://learn.microsoft.com/en-us/windows/powertoys/text-extractor) included in [Microsoft PowerToys](https://learn.microsoft.com/en-us/windows/powertoys/install)
