### ISSUE TITLE
Version displayed in file name of the package

### ISSUE THREAD

**Issue by MerkomassDev** [KRTirtho/spotube#803]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

I tend to use/jump between different nightly (and non nightly) versions, but every file looks basically the same
<img width="218" alt="Screenshot_66" src="https://github.com/KRTirtho/spotube/assets/70111455/6763afed-f091-4558-af44-9b9088ed0882">

### Suggested solution

It would be dope to be able to easily know which version each file contains and it would make version troubleshooting easier too.
Add a version text to each installer file 
<img width="137" alt="Screenshot_67" src="https://github.com/KRTirtho/spotube/assets/70111455/38d26cc8-6371-415d-9b5f-18eed2bef86e">

**Comment by KRTirtho** [comment]
We'll lose the ability to download the app using the same link. That's why it was never done this way

**Comment by MerkomassDev** [comment]
makes sense
