### ISSUE TITLE
(Debian 12, deb) Getting logged out at system restart

### ISSUE THREAD

**Issue by SSUPII** [KRTirtho/spotube#807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After a system restart, I am requires to insert my login tokens again.

### Expected Behavior

I should be automatically reconnected when loading the software after a system restart.

### Steps to reproduce

1. Open application
2. Login into your Spotify account
3. Close the application and restart the system
4. Reopen the application

### Operating System

Debian GNU/Linux 12 (bookworm) x86_64

`uname -a`:
Linux debian 6.1.0-11-amd64 # 1 SMP PREEMPT_DYNAMIC Debian 6.1.38-4 (2023-08-08) x86_64 GNU/Linux

### Spotube version

3.1.2

### Installation source

GitHub Releases (Binary)

### Additional information

Just restarting or killing the application doesn't log you out. Only restarting does.

**Comment by KRTirtho** [comment]
`~/.local/share/oss.krtirtho.spotube/` is the folder used for storing all your info. Please check if this folder persists across restarts, and it contains `spotube*.hive` and `spotube*.lock` files

**Comment by SSUPII** [comment]
The folder exists, and is filled with many .hive and .lock files like this:
```
spotube-1e6bb827-f3fe-46e8-89e5-196940bf5c0f.hive
spotube-1e6bb827-f3fe-46e8-89e5-196940bf5c0f.lock
spotube-4259ccb0-b927-44ff-b386-0e38170771a0.hive
spotube-4259ccb0-b927-44ff-b386-0e38170771a0.lock
spotube-7ff7f5d2-b481-4aa8-96a3-0c78ff67706b.hive
spotube-7ff7f5d2-b481-4aa8-96a3-0c78ff67706b.lock
spotube-8744c47c-ca53-4cdd-94b8-97124c54a9dd.hive
spotube-8744c47c-ca53-4cdd-94b8-97124c54a9dd.lock
spotube-9d6c6bb9-c247-4300-a948-166d97a8abec.hive
spotube-9d6c6bb9-c247-4300-a948-166d97a8abec.lock
spotube-b43d39a2-d312-401c-86f7-b229bcba034f.hive
spotube-b43d39a2-d312-401c-86f7-b229bcba034f.lock
spotube-c3e8805e-4976-4495-bec1-eb6562e9e413.hive
spotube-c3e8805e-4976-4495-bec1-eb6562e9e413.lock
```

Restarting and opening Spotube will generate a new pair.

**Comment by KRTirtho** [comment]
Do you've KDEWallet or Gnome-keyring installed?

**Comment by SSUPII** [comment]
Both `kwalletmanager` and `gnome-keyring` are installed

**Comment by KRTirtho** [comment]
Turns out it's an underlying plugin issue https://github.com/mogol/flutter_secure_storage/issues/643
