### ISSUE TITLE
language support

### ISSUE THREAD

**Issue by senolfndk** [KRTirtho/spotube#81]
Can you add Turkish language option?

**Comment by airon90** [comment]
I'd translate the app in Italian so I follow this request

**Comment by KRTirtho** [comment]
There's already an ongoing discussion to Add Translations https://github.com/KRTirtho/spotube/discussions/66

**Comment by KRTirtho** [comment]
Translations are supported starting from v3.0.0

@senolfndk you can add turkish translations following https://github.com/KRTirtho/spotube/blob/master/CONTRIBUTION.md#submit-translations

**Comment by senolfndk** [comment]
I'm not an expert on this

**Comment by KRTirtho** [comment]
No worries. Anyone else might add
I'm no expert in Turkish either :smile:

**Comment by senolfndk** [comment]
> Endişelenme. Başkası da ekleyebilir, ben de Türkçe konusunda uzman değilim 😄

ok
