### ISSUE TITLE
Missing Mpris Properties

### ISSUE THREAD

**Issue by Batwam** [KRTirtho/spotube#811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently, the app doesn't appear to provide the DesktopEntry and Identity information as part of the Mpris data it is giving. Extensions relying on this info display blank info. See below, info correctly provided by the Spotify app:
![image](https://github.com/KRTirtho/spotube/assets/56710655/c58c46b3-2ecd-4a17-a0c8-1e6311136f6b)

![image](https://github.com/KRTirtho/spotube/assets/56710655/bb4aa358-e931-49df-9b47-f98f6a124d70)

On the other hand, Spotube doesn't provide these properties:
![image](https://github.com/KRTirtho/spotube/assets/56710655/7d4295f9-83d5-49cd-acc0-0b6888bb90b2)

### Expected Behavior

Please add Identity 'Spotube' and DesktopEntry 'Spotube to the list of Mpris properties.

### Steps to reproduce

open the app
check mpris data using a D-Bus inspection app like [D-Feet](https://wiki.gnome.org/Apps/DFeet).

### Operating System

Linux

### Spotube version

v3.1.2

### Installation source

Flathub (Flatpak)

**Comment by KRTirtho** [comment]
Yeah we're already providing these properties https://github.com/KRTirtho/spotube/blob/master/lib/services/audio_services/linux_audio_service.dart#L57-L171

**Comment by Batwam** [comment]
Thanks for the quick response! This is quite strange then, I wonder why the info is not getting recognised... for clarity, the rest (play/pause, metadada, album cover,...) all work fine.

**Comment by Batwam** [comment]
Could it be because `Identity` and `DesktopEntry` are meant to be Properties and not Methods?

**Comment by Batwam** [comment]
I'm just noticing that these Properties are meant to be part of `org.mpris.MediaPlayer2` which doesn't appear to exist for spotube. Only `org.mpris.MediaPlayer2.Player` is listed.

**Comment by KRTirtho** [comment]
Fixed in e29cc2578cab36729e235b117c1b5489c3452902

**Comment by Batwam** [comment]
amazing, looking forward to the next release!

**Comment by Batwam** [comment]
I can confirm that this is now working fine with v3.2.0
![image](https://github.com/KRTirtho/spotube/assets/56710655/871e388e-fb17-4777-9641-eb988df0f3d7)
