### ISSUE TITLE
Navigating to settings, redirects to home page

### ISSUE THREAD

**Issue by fxzxmicah** [KRTirtho/spotube#812]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the current page is on the playlist page, clicking on the bottom action bar to switch to the settings page will cause a jump back to the homepage.

### Expected Behavior

Switch to the settings page.

### Steps to reproduce

1. Open app
2. switch to the playlist page
3. click on the settings icon
4. suddenly jump back to the homepage

### Operating System

Android 13

### Spotube version

v3.2.0

### Installation source

Play Store (Android)

### Additional information

v3.1.2 is normal.

**Comment by AR-C05** [comment]
I can confirm this.
Additionally, this sudden jump similarly occurs when scrolling (both vertically or horizontally) through playlists or genres on the homepage

v3.2.0
Android 13
Installed through F-Droid

**Comment by ethical-haquer** [comment]
I can also confirm this. It happens from the library _and_ the search page.

v3.2.0
Android 13

It also happens in compact mode on:
v3.2.0
Linux (Debian 11)
