### ISSUE TITLE
Regression: no playback whatsoever on flatpak from flathub

### ISSUE THREAD

**Issue by dimitris-personal** [KRTirtho/spotube#816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Pressing play does nothing.  No sound output (verified no spotube stream under GNOME settings → Sound → Volume levels).

This stack trace appears in the logs multiple times:

```
============================== CATCHER 2 LOG ==============================
------- DEVICE INFO -------
name: GNOME
version: 44 (Flatpak runtime)
id: org.gnome.Platform
idLike: null
versionCodename: null
versionId: 44
prettyName: GNOME 44 (Flatpak runtime)
buildId: null
variant: null
variantId: null
machineId: f8acc9d32ed64189ad529cd6360db66a
------- APP INFO -------
environment: release
version: 3.2.0
appName: spotube
buildNumber: 25
packageName: spotube
---------- ERROR ----------
PathNotFoundException: Cannot open file, path = '/home/d/.var/app/com.github.KRTirtho.Spotube/config/dconf/user' (OS Error: No such file or directory, errno = 2)
------- STACK TRACE -------
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381)
<asynchronous suspension>
#2      GVariantDatabase._loadRootTable (package:gsettings/src/gvariant_database.dart:30)
<asynchronous suspension>
#3      GVariantDatabase.lookup (package:gsettings/src/gvariant_database.dart:20)
<asynchronous suspension>
#4      DConfClient.read (package:gsettings/src/dconf_client.dart:82)
<asynchronous suspension>
#5      GSettingsDConfBackend.get (package:gsettings/src/gsettings_dconf_backend.dart:23)
<asynchronous suspension>
#6      GSettings.get (package:gsettings/src/gsettings.dart:124)
<asynchronous suspension>
#7      getTheme (package:titlebar_buttons/src/get_theme.dart:12)
<asynchronous suspension>
------- CUSTOM INFO -------
```

Edit: also getting these:

```
============================== CATCHER 2 LOG ==============================
------- DEVICE INFO -------
name: GNOME
version: 44 (Flatpak runtime)
id: org.gnome.Platform
idLike: null
versionCodename: null
versionId: 44
prettyName: GNOME 44 (Flatpak runtime)
buildId: null
variant: null
variantId: null
machineId: f8acc9d32ed64189ad529cd6360db66a
------- APP INFO -------
environment: release
version: 3.2.0
appName: spotube
buildNumber: 25
packageName: spotube
---------- ERROR ----------
Error Code: 403
Forbidden.
------- STACK TRACE -------
#0      SpotifyApiBase.handleErrors (package:spotify/src/spotify_base.dart:238)
#1      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:212)
<asynchronous suspension>
#2      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:178)
<asynchronous suspension>
#3      Pages.getPage (package:spotify/src/endpoints/endpoint_paging.dart:236)
<asynchronous suspension>
------- CUSTOM INFO -------
```

### Expected Behavior

Previous versions would start playing, at least on a freshly started application.

### Steps to reproduce

1. Started spotube
2. Selected a playlist and pressed play

### Operating System

Fedora 38, GNOME, Wayland

### Spotube version

3.2.0

### Installation source

Flathub (Flatpak)

**Comment by AndreiSva** [comment]
I am having the same issue

**Comment by kuba1909** [comment]
You can workaround the issue by:

1. Killing the process (I had to do it manually, since closing the window would not end the process)
2. Granting unlimited access to the D-Bus session of your user (--socket=session-bus, [see this reference](https://docs.flatpak.org/en/latest/sandbox-permissions-reference.html#sandbox-permissions-reference)). Easiest way to do so is by using Flatseal.

**Comment by KRTirtho** [comment]
I think the --own-name is not correct thus having this problem.

**Comment by steamboatslinky** [comment]
Please tell me there’s a way to fix this

**Comment by xAlpharax** [comment]
> You can workaround the issue by:
> 
> 1. Killing the process (I had to do it manually, since closing the window would not end the process)
> 2. Granting unlimited access to the D-Bus session of your user (--socket=session-bus, [see this reference](https://docs.flatpak.org/en/latest/sandbox-permissions-reference.html#sandbox-permissions-reference)). Easiest way to do so is by using Flatseal.

For me it was enough to launch it via command line with dbus-run-session:

`dbus-run-session flatpak run com.github.KRTirtho.Spotube`

**Comment by xAlpharax** [comment]
> Fixed it already. Will be available soon

good.
