### ISSUE TITLE
Setting to revert the scrollbar to it's original shape before 3.2.0

### ISSUE THREAD

**Issue by clubberduck** [KRTirtho/spotube#819]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

The bigger scrollbar is painful on mobile. It means I have to wait a good while before I can tap on the context menu of a song. It makes the app horrible to use.

### Suggested solution

There should be an option to revert it to the way it was in 3.1.2.

**Comment by KRTirtho** [comment]
:facepalm:

**Comment by clubberduck** [comment]
I know

**Comment by clubberduck** [comment]
It is a bit stupid

**Comment by Fxsch** [comment]
I'm just trying out the app and I don't like the scrollbar either tbh

**Comment by clubberduck** [comment]
I was talking about the fact that the only reason the bad scrollbar exists is because someone requested that

**Comment by mandeep1305** [comment]
True

**Comment by KRTirtho** [comment]
https://github.com/KRTirtho/spotube/issues/374

You guys/gals decide first which one do you want. I'm confused man/girl. 
![image](https://github.com/KRTirtho/spotube/assets/61944859/abd793a3-de7e-4ba3-bde3-313ae5896e73)

**Comment by KRTirtho** [comment]
> I was talking about the fact that the only reason the bad scrollbar exists is because someone requested that

It can be useful for navigating long lists. But I think I overdid it

**Comment by clubberduck** [comment]
I just hope for an option to revert it

**Comment by Fxsch** [comment]
An option to have a regular scrollbar or this new one would be nice. I never use the scrollbar on a phone but some people might find it useful.
