### ISSUE TITLE
[Android] Notification about battery optimization

### ISSUE THREAD

**Issue by s4msy** [KRTirtho/spotube#82]
**Is your feature request related to a problem? Please describe.**
The android battery optimization has to manually set to "disable" because the app stops playing music in idle mode.

**Describe the solution you'd like**
A banner at first start with a link to the battery optimization part of android settings would be helpful for people, who doesn't know how to get rid of this "issue"

**Comment by KRTirtho** [comment]
I don't think that's an issue with battery optimization. Can you explain the issue you're facing in your smartphone with proper details?

**Comment by KRTirtho** [comment]
Starting from v3.0.0 Spotube now prompts the user to disable all sort of battery optimizations (custom Android e.g. MIUI, RealmeUI, One UI etc) for smoother playback
