### ISSUE TITLE
pure amoled not stay in 

### ISSUE THREAD

**Issue by trebrr** [KRTirtho/spotube#821]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when i select pure amoled theme and close the app... when i re-launch  the theme amoled disapear 

### Expected Behavior

amoled pure black stay in

### Steps to reproduce

i restart the device but the  problem still there

### Operating System

android 13

### Spotube version

3.2.0

### Installation source

GitHub Releases (Binary)

### Additional information

.......

**Comment by MerkomassDev** [comment]
Are you sure you have the latest version? It was fixed in the recent update. (Issue #778)

**Comment by trebrr** [comment]
yess 3.2.0 instaled.... when i close the app... and reopen.. the theme amoled desapear

**Comment by MerkomassDev** [comment]
After testing it myself, the issue still persists

**Comment by KRTirtho** [comment]
Fixed in 3.4.0
