### ISSUE TITLE
Minimize to tray not working

### ISSUE THREAD

**Issue by agolks** [KRTirtho/spotube#825]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

on windows 10 desktop in settings i have set the close behaviour to "minimize to try", but on close spotube closes.

### Expected Behavior

spotube should minimize to tray.

### Steps to reproduce

1. open spotube
2. verify the "minimize to tray" setting
3. start playing something
4. close 

now spotube is closed instead of continueing playing and visible in tray.

### Operating System

windows 10

### Spotube version

v3.0.0, v3.0.2

### Installation source

GitHub Releases (Binary)

**Comment by KRTirtho** [comment]
Please upgrade to latest version `3.2.0`

**Comment by agolks** [comment]
it works good, on my ubuntu 22.04.
but must not use "use system title bar".
