### ISSUE TITLE
Android App Stops playing audio

### ISSUE THREAD

**Issue by xAlpharax** [KRTirtho/spotube#826]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the user clicks on any media control (forward backward pause) or even maximizes the media player the sound stops yet the media bar is still going (ie the song is playing but there is no audio output playing anymore)

### Expected Behavior

Obviously this is a bug that shouldn t be happening at all and it probably was just overlooked.

### Steps to reproduce

I am using the version up on F-Droid

I open the app
I play a song
It plays and outputs audio
I click on any of the aformentioned controls or try to maximize the player
The music stops but the progress bar is still going

### Operating System

Android via F-Droid

### Spotube version

3.2.0 aka latest as of now

### Installation source

F-Droid (Android)

**Comment by KRTirtho** [comment]
I tried to reproduce this behaviour but was unable to. Can you try using the GitHub or PlayStore version to check if the issue also persists there?

**Comment by xAlpharax** [comment]
> I tried to reproduce this behaviour but was unable to. Can you try using the GitHub or PlayStore version to check if the issue also persists there?

Huh, apparently google play versions and gh versions work, as well as the F-Droid version after reinstalling. Weird..

Regardless, I fixed my problem, maybe Android just decided to revoke audio access silently or smth.

**Comment by xAlpharax** [comment]
I guess this can be closed then.. If I or anyone else encounters this just try reinstalling the app.
