### ISSUE TITLE
The system tray icon is not displayed

### ISSUE THREAD

**Issue by xankletas** [KRTirtho/spotube#827]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I activate the icon on the system tray, it is activated but the icon bottom is transparent and therefore the icon is not displayed.

### Expected Behavior

The icon should be displayed on the system tray, if it is a dark theme, the icon should be clear and if it is a clear theme the icon should be dark.

### Steps to reproduce

1. Enable system tray

### Operating System

Linux (Mageia 9)

### Spotube version

v3.2.0

### Installation source

Flathub (Flatpak)

**Comment by callegar** [comment]
Same as 541? Maybe ayatana may help?
