### ISSUE TITLE
[Feature] copy & share spotify links of songs

### ISSUE THREAD

**Issue by m-koushan** [KRTirtho/spotube#83]
**Is your feature request related to a problem? Please describe.**
Unfortunately the app only downloads mp3 format, I want to download FLAC format and for that I use external bots. so basically I need to send the spotify link to the bot for downloading them in FLAC quality. 

**Describe the solution you'd like**
Adding a share button in song playing page.

**Describe alternatives you've considered**

**Additional context**

**Comment by KRTirtho** [comment]
Great thing. I completely missed that part. Thanks for the suggestion

**Comment by KRTirtho** [comment]
Great news, this feature has been implemented & will be available in the next release

**Comment by m-koushan** [comment]
@KRTirtho I'm not seeing it in song playing area or even in song list, its only in playlist area for the playlist

**Comment by KRTirtho** [comment]
You will find it inside playlist/album tracks 3 dots

**Comment by m-koushan** [comment]
I don't see any 3 dots
![2.jpg](https://user-images.githubusercontent.com/50526840/172111156-1d247ada-7807-4f1f-803f-2c0720572cfc.jpg)
![1.jpg](https://user-images.githubusercontent.com/50526840/172111182-957e5052-376f-4522-adad-3e1db68f9a3d.jpg)

**Comment by KRTirtho** [comment]
I guess its a responsiveness issue. Try rotating the screen to landscape mode you will see the 3 dots
Guess I've to fix this responsiveness issue too

**Comment by KRTirtho** [comment]
No actually that is happening because you're not logged in. Try logging in with Spotify Account
It supposed to be not hidden when not logged in but I forgot to do that part

**Comment by m-koushan** [comment]
In v2.2.1 it got fixed. Thanks!
