### ISSUE TITLE
Application name on FDroid build  os "App Killer Manager"

### ISSUE THREAD

**Issue by dhardy92** [KRTirtho/spotube#830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When FDroid suggest to Upgrade installer Spotube app on my device it rename it as "App Killer Manager" app seams behave normale.

### Expected Behavior

Keep the name "Spotube"

### Steps to reproduce

1. Open FDroid
2. Go tu "Updates" tab
3. See "Spotube" and click
4. Click on "Update"
5. See FDroid modal suggest install "App Killer Manager"
6. Click "Install"
7. App name is now "App Killer Manager"

### Operating System

Android

### Spotube version

3.2.0

### Installation source

F-Droid (Android)

**Comment by dhardy92** [comment]
![Screenshot_20231022-085004](https://github.com/KRTirtho/spotube/assets/898473/314700be-577e-49c1-98d7-ff1308987894)

**Comment by Info-BC** [comment]
Hello, same problem after install from google play store

**Comment by AYnonyme971** [comment]
Same with the .apk on the website

**Comment by KRTirtho** [comment]
No idea how the hack this can happen :sweat_smile:

**Comment by Go-rom** [comment]
Hi

Just an update : 3.3.0 is also affected by this bug

**Comment by j0nattend** [comment]
Hi !

I'm a new french user (like @dhardy92 i guess).
I have the same problem : 
> i have installed Spotube by F-droid (v 3.3.0)
> the app works correctly but the name of app is wrong : "App Killer Manager".
i'm on Android 13 with Samsung phone A52S (One UI version : 5.1).

If my post can help ... ;)

**Comment by j0nattend** [comment]
Bonjour,
Why my comment was marked as spam ? :'(

**Comment by KRTirtho** [comment]
Oops, wrong issue comment. Sorry sorry
