### ISSUE TITLE
LastFM Authentication failed

### ISSUE THREAD

**Issue by nixmax90** [KRTirtho/spotube#839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If i try to login into my LastFM Account the follwing error occured;

Error Authentication failed
[LastFMException]=>[Code 10]: Invalid API key - You must be granted a valid key by last,fm

I found this error code on last.fm docu here; https://www.last.fm/api/errorcodes

`Some indicate errors you may encounter in development (e.g. "10: Invalid API key")`

`10 : Invalid API key - You must be granted a valid key by last.fm`

The APP is really nice. Hope you can fix this issue. 

BR

### Expected Behavior

Login to LastFM with account credentials is working.

### Steps to reproduce

1. Type in you login credentials of your last.fm account
2. Error occurs

### Operating System

Android 13

### Spotube version

v3.2.0 Build 25

### Installation source

F-Droid (Android)

**Comment by ASHBORN2003** [comment]
Same issue

**Comment by KRTirtho** [comment]
Looks like only happens on F-Droid. Try using the GitHub release for now

**Comment by KRTirtho** [comment]
It has been fixed in FDroid
