### ISSUE TITLE
Alternative Track Sources don't save after a while

### ISSUE THREAD

**Issue by dPandl** [KRTirtho/spotube#840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I specify an alternative source, it will also play after restarting the app. But if I open the app again after a few days, all alternatives are reset to default.

### Expected Behavior

The app should play the alternative source no matter when I play the song again, regardless of whether I haven't opened the app for a few days.

### Steps to reproduce

1. Open app
2. Play Track
3. Choose alternative
4. Exit app
5. Wait a few days without opening the app
6. Play the changed song
7. Default selection is played

### Operating System

Android

### Spotube version

v3.2.0 build 25

### Installation source

Play Store (Android)

### Additional information

I have a OnePlus 9 Pro with Android 13 if that's relevant.

**Comment by remclean** [comment]
Does not work on Linux Ubuntu or Android.
