### ISSUE TITLE
Scrobbling doesn't work for individually played tracks

### ISSUE THREAD

**Issue by jtmr05** [KRTirtho/spotube#842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've logged in to my last.fm account in the app but no track gets scrobbled as one would expect. Running it from the terminal using the `-v` doesn't provide any insightful help either.

### Expected Behavior

It would be expected that tracks would be submited to last.fm as scrobbles.

### Steps to reproduce

1. Open the map
2. Settings -> Connect to Last.fm
3. Login to account
4. Play some music (no track gets scrobbled!)

### Operating System

Manjaro GNU/Linux

### Spotube version

3.2.0-1

### Installation source

Arch User Repository (AUR)

**Comment by KRTirtho** [comment]
The track doesn't get scrobbled immediately. You've to at least listen to it for 30 seconds according to LastFm
If it still doesn't work, re-login with lastfm, clear the queue and try again playing any playlist/album/track

**Comment by jtmr05** [comment]
I've listened to full songs before and no scrobbles whatsoever on Last.fm. I've also tried what you suggested, to no avail. Should I use my regular account credentials or do I need to create an API account?

**Comment by KRTirtho** [comment]
Regular account should work fine and I can confirm it is working in my devices and accounts

**Comment by jtmr05** [comment]
It seems like it is working now.
I didn't really try anything else but the scrobbles are indeed showing up on Last.fm.

**Comment by jtmr05** [comment]
Ah, I've managed to reproduce it now. If you play music from your library (e.g. a playlist or album) it scrobble normally. However, if you search for individual tracks and play them, they won't get scrobbled.

**Comment by Vjay15** [comment]
It didn't work well for me in pc, only picks up some songs and not others even if it's in library :(
