### ISSUE TITLE
Doesn't close with keyboard shortcuts

### ISSUE THREAD

**Issue by forteller** [KRTirtho/spotube#843]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Neither Alt+F4 or Ctrl+Q closes the application

### Expected Behavior

They should close the application :)

### Steps to reproduce

1. Open the app
2. Try to close it with one of the standard keyboard shortcuts

### Operating System

Linux

### Spotube version

3.2.0

### Installation source

Flathub (Flatpak)

### Additional information

Thank you for a great application!

**Comment by POGnator** [comment]
I have this issue too. I'm using the latest AUR version and am on Wayland/Hyprland.

**Comment by Crunchylol** [comment]
I have this issue too, although Spotube just crashes and then closes itself for me. I'm using the latest AUR version and am on KDE (Wayland).

**Comment by forteller** [comment]
Alt+F4 works for me now in v3.8.0, but not Ctrl+Q

**Comment by KRTirtho** [comment]
I actually fixed that issue long ago. Forgot to close it lol

**Comment by forteller** [comment]
Thanks for fixing Alt+F4!

But I don't understand why you say Ctrl+Q is not standard in Linux. It is. At least in Gnome. Try it with Firefox, Gnome Software, Text Editor, Audacity, Gnome Settings, System monitor, etc.

You don't have to do it of course, but at least I expect it from all applications. Thanks again! :)

**Comment by forteller** [comment]
Just found this, btw :) https://developer.gnome.org/hig/reference/keyboard.html
