### ISSUE TITLE
Adnroid 13 severe issues (causes system lag)

### ISSUE THREAD

**Issue by Dae-Hang-Sook** [KRTirtho/spotube#845]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using the app, it takes far to long to load. It also lags my entire system when it does load. Downloads do NOT work for anything. Typically kicks me back to the home screen when something loads. Also shoots me right to the home screen when clicking the setting icon.

### Expected Behavior

I expect it to load within at least 15-30 seconds, no insane lag spikes that lag my system, and downloads to work without immediately having an error upon clicking the download button for zero reason. It doesn't give a reason for it. I also expect it to NOT shoot me to the home screen every time I click something.

### Steps to reproduce

Opened app
Signed in
Clicked on Playlist
Took 55-75 seconds to load it, and did not load all the music in the list at one time. Only a few
Lagged my entire device when clicking anything from this point and the individual songs load slowly as well.
Downloading instantaneously gives an error but doesn't say what and just doesn't work.

### Operating System

Android

### Spotube version

v3.2.0

### Installation source

F-Droid (Android)

### Additional information

I can understand slower loading times, but too much is ridiculous. The extreme lag spikes is insane and is not something any app should ever experience for any reason. Running the latest version of Android 13.

**Comment by AndrejPatak** [comment]
I am also having issues on android my 13 nothing phone (1), I installed the app from F-Droid. My phone is not rooted.

I can't download any songs, it only shows a triangle next to the restart button. Tapping the triangle yields no result and no error message is shown on screen.

The app takes too long to load, but it's not more than a minute like it is for OP, it's more like 10 seconds. That is a lot given that every app on my phone loads basically instantly or it takes 1-2 seconds to load.

All the music takes at least 5-10 seconds to actually play while on Spotify and YouTube any song is played instantly with my internet connection. I ran a network speed test on my phone, here's the result: https://www.speedtest.net/my-result/a/9662226093

**Comment by PigDan20** [comment]
I have the same exact slowdown issue. I can't elaborate anymore because it's already been described excellently above.

**Comment by Dae-Hang-Sook** [comment]
> I am also having issues with the app on my Nothing Phone (1), it is running on android 13. I installed the app from F-Droid. My phone is not rooted.
> 
> I can't download any songs, it only shows a triangle next to the restart button. Tapping the triangle yields no result and no error message is shown on screen.
> 
> The app takes too long to load, but it's not more than a minute like it is for OP, it's more like 10 seconds. That is a lot given that every app on my phone loads basically instantly or it takes 1-2 seconds to load.
> 
> All the music takes at least 5-10 seconds to actually play while on Spotify and YouTube any song is played instantly with my internet connection. I ran a network speed test on my phone, here's the result: https://www.speedtest.net/my-result/a/9662226093
> 
> Edit: improved wording.
> 
> 
> Edit 2: I went into the logs and the error said spotube had no write permissions. I couldn't give it the permission through regular app settings so I used "app ops" to give the permission. Download seemed to start now but another error came to be. 
> 
> This time related to the network in some way?
> Here:
> ============================== CATCHER 2 LOG ==============================
> ------- DEVICE INFO -------
> id: TKQ1.221220.001
> board: Spacewar
> bootloader: 00872-LAHAINA-2.487493.1
> brand: Nothing
> device: Spacewar
> display: T2.0-231006-1014
> fingerprint: Nothing/SpacewarEEA/Spacewar:13/TKQ1.221220.001/2310061014:user/release-keys
> hardware: qcom
> host: nothing123
> isPhysicalDevice: true
> manufacturer: Nothing
> model: A063
> product: SpacewarEEA
> tags: release-keys
> type: user
> versionBaseOs: 
> versionCodename: REL
> versionIncremental: 2310061014
> versionPreviewSdk: 0
> versionRelease: 13
> versionSdk: 33
> versionSecurityPatch: 2023-09-01
> ------- APP INFO -------
> environment: release
> version: 3.2.0
> appName: Spotube
> buildNumber: 25
> packageName: oss.krtirtho.spotube
> ---------- ERROR ----------
> DioException [bad response]: The request returned an invalid status code of 503.
> ------- STACK TRACE -------
> #0      DioMixin.fetch.<anonymous closure> (package:dio/src/dio_mixin.dart:507)
> #1      _RootZone.runUnary (dart:async/zone.dart:1661)
> #2      _FutureListener.handleError (dart:async/future_impl.dart:174)
> #3      Future._propagateToListeners.handleError (dart:async/future_impl.dart:852)
> #4      Future._propagateToListeners (dart:async/future_impl.dart:873)
> #5      Future._completeError (dart:async/future_impl.dart:649)
> #6      _SyncCompleter._completeError (dart:async/future_impl.dart:60)
> #7      _Completer.completeError (dart:async/future_impl.dart:26)
> #8      Future.any.onError (dart:async/future.dart:620)
> #9      _RootZone.runBinary (dart:async/zone.dart:1666)
> #10     _FutureListener.handleError (dart:async/future_impl.dart:171)
> #11     Future._propagateToListeners.handleError (dart:async/future_impl.dart:852)
> #12     Future._propagateToListeners (dart:async/future_impl.dart:873)
> #13     Future._completeError (dart:async/future_impl.dart:649)
> #14     Future._chainForeignFuture.<anonymous closure> (dart:async/future_impl.dart:550)
> #15     _microtaskLoop (dart:async/schedule_microtask.dart:40)
> #16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)
> ------- CUSTOM INFO -------

Is it IoException or Dioexception?

**Comment by Dae-Hang-Sook** [comment]
> > I am also having issues with the app on my Nothing Phone (1), it is running on android 13. I installed the app from F-Droid. My phone is not rooted.
> > 
> > I can't download any songs, it only shows a triangle next to the restart button. Tapping the triangle yields no result and no error message is shown on screen.
> > 
> > The app takes too long to load, but it's not more than a minute like it is for OP, it's more like 10 seconds. That is a lot given that every app on my phone loads basically instantly or it takes 1-2 seconds to load.
> > 
> > All the music takes at least 5-10 seconds to actually play while on Spotify and YouTube any song is played instantly with my internet connection. I ran a network speed test on my phone, here's the result: https://www.speedtest.net/my-result/a/9662226093
> > 
> > Edit: improved wording.
> > 
> > 
> > Edit 2: I went into the logs and the error said spotube had no write permissions. I couldn't give it the permission through regular app settings so I used "app ops" to give the permission. Download seemed to start now but another error came to be. 
> > 
> > This time related to the network in some way?
> > Here:
> > ============================== CATCHER 2 LOG ==============================
> > ------- DEVICE INFO -------
> > id: TKQ1.221220.001
> > board: Spacewar
> > bootloader: 00872-LAHAINA-2.487493.1
> > brand: Nothing
> > device: Spacewar
> > display: T2.0-231006-1014
> > fingerprint: Nothing/SpacewarEEA/Spacewar:13/TKQ1.221220.001/2310061014:user/release-keys
> > hardware: qcom
> > host: nothing123
> > isPhysicalDevice: true
> > manufacturer: Nothing
> > model: A063
> > product: SpacewarEEA
> > tags: release-keys
> > type: user
> > versionBaseOs: 
> > versionCodename: REL
> > versionIncremental: 2310061014
> > versionPreviewSdk: 0
> > versionRelease: 13
> > versionSdk: 33
> > versionSecurityPatch: 2023-09-01
> > ------- APP INFO -------
> > environment: release
> > version: 3.2.0
> > appName: Spotube
> > buildNumber: 25
> > packageName: oss.krtirtho.spotube
> > ---------- ERROR ----------
> > DioException [bad response]: The request returned an invalid status code of 503.
> > ------- STACK TRACE -------
> > #0      DioMixin.fetch.<anonymous closure> (package:dio/src/dio_mixin.dart:507)
> > #1      _RootZone.runUnary (dart:async/zone.dart:1661)
> > #2      _FutureListener.handleError (dart:async/future_impl.dart:174)
> > #3      Future._propagateToListeners.handleError (dart:async/future_impl.dart:852)
> > #4      Future._propagateToListeners (dart:async/future_impl.dart:873)
> > #5      Future._completeError (dart:async/future_impl.dart:649)
> > #6      _SyncCompleter._completeError (dart:async/future_impl.dart:60)
> > #7      _Completer.completeError (dart:async/future_impl.dart:26)
> > #8      Future.any.onError (dart:async/future.dart:620)
> > #9      _RootZone.runBinary (dart:async/zone.dart:1666)
> > #10     _FutureListener.handleError (dart:async/future_impl.dart:171)
> > #11     Future._propagateToListeners.handleError (dart:async/future_impl.dart:852)
> > #12     Future._propagateToListeners (dart:async/future_impl.dart:873)
> > #13     Future._completeError (dart:async/future_impl.dart:649)
> > #14     Future._chainForeignFuture.<anonymous closure> (dart:async/future_impl.dart:550)
> > #15     _microtaskLoop (dart:async/schedule_microtask.dart:40)
> > #16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)
> > ------- CUSTOM INFO -------
> 
> DioException error 503 is a server unavailable error. This is completely and entirely on the developers side of things. Not ours.

**Comment by Dae-Hang-Sook** [comment]
@hexdump0815

mkfs -t ext4 -O ^has_journal -m 0 -L bootemmc /dev/${TGTDEV}p3

Returns this:

The file /dev/mmcblk0p3 does not exist and no size was specified


Using the dd method just tells me the file *direct link to it* is kot in gzip format

**Comment by Dae-Hang-Sook** [comment]
> I am also having issues with the app on my Nothing Phone (1), it is running on android 13. I installed the app from F-Droid. My phone is not rooted.
> 
> I can't download any songs, it only shows a triangle next to the restart button. Tapping the triangle yields no result and no error message is shown on screen.
> 
> The app takes too long to load, but it's not more than a minute like it is for OP, it's more like 10 seconds. That is a lot given that every app on my phone loads basically instantly or it takes 1-2 seconds to load.
> 
> All the music takes at least 5-10 seconds to actually play while on Spotify and YouTube any song is played instantly with my internet connection. I ran a network speed test on my phone, here's the result: https://www.speedtest.net/my-result/a/9662226093
> 
> Edit: improved wording.
> 
> 
> Edit 2: I went into the logs and the error said spotube had no write permissions. I couldn't give it the permission through regular app settings so I used "app ops" to give the permission. Download seemed to start now but another error came to be. 
> 
> This time related to the network in some way?
> Here:
> ============================== CATCHER 2 LOG ==============================
> ------- DEVICE INFO -------
> id: TKQ1.221220.001
> board: Spacewar
> bootloader: 00872-LAHAINA-2.487493.1
> brand: Nothing
> device: Spacewar
> display: T2.0-231006-1014
> fingerprint: Nothing/SpacewarEEA/Spacewar:13/TKQ1.221220.001/2310061014:user/release-keys
> hardware: qcom
> host: nothing123
> isPhysicalDevice: true
> manufacturer: Nothing
> model: A063
> product: SpacewarEEA
> tags: release-keys
> type: user
> versionBaseOs: 
> versionCodename: REL
> versionIncremental: 2310061014
> versionPreviewSdk: 0
> versionRelease: 13
> versionSdk: 33
> versionSecurityPatch: 2023-09-01
> ------- APP INFO -------
> environment: release
> version: 3.2.0
> appName: Spotube
> buildNumber: 25
> packageName: oss.krtirtho.spotube
> ---------- ERROR ----------
> DioException [bad response]: The request returned an invalid status code of 503.
> ------- STACK TRACE -------
> #0      DioMixin.fetch.<anonymous closure> (package:dio/src/dio_mixin.dart:507)
> #1      _RootZone.runUnary (dart:async/zone.dart:1661)
> #2      _FutureListener.handleError (dart:async/future_impl.dart:174)
> #3      Future._propagateToListeners.handleError (dart:async/future_impl.dart:852)
> #4      Future._propagateToListeners (dart:async/future_impl.dart:873)
> #5      Future._completeError (dart:async/future_impl.dart:649)
> #6      _SyncCompleter._completeError (dart:async/future_impl.dart:60)
> #7      _Completer.completeError (dart:async/future_impl.dart:26)
> #8      Future.any.onError (dart:async/future.dart:620)
> #9      _RootZone.runBinary (dart:async/zone.dart:1666)
> #10     _FutureListener.handleError (dart:async/future_impl.dart:171)
> #11     Future._propagateToListeners.handleError (dart:async/future_impl.dart:852)
> #12     Future._propagateToListeners (dart:async/future_impl.dart:873)
> #13     Future._completeError (dart:async/future_impl.dart:649)
> #14     Future._chainForeignFuture.<anonymous closure> (dart:async/future_impl.dart:550)
> #15     _microtaskLoop (dart:async/schedule_microtask.dart:40)
> #16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)
> ------- CUSTOM INFO -------

Don't change download location after install. This breaks it. The download method is app specific, not device specific. The files are cloud files until moved out of the folder.
