### ISSUE TITLE
Improvements to "Mini Player"

### ISSUE THREAD

**Issue by fallsdevil** [KRTirtho/spotube#851]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

A possibility of having the Mini Player without the song lyrics, just with the action buttons and album art.

### Suggested solution

It could be inspired by the Windows OS app "ModernFlayout" which is a more pleasant interface when lowering/increasing the volume, I think it would be a solution for the miniplayer to work without the lyrics depending on the user's choice, and also appear when we down or up the volume, it would be something interesting.

### Useful resources

This is the [link](https://www.microsoft.com/store/productId/9MT60QV066RP?ocid=pdpshare) of the App mentioned above from the Microsoft Store, and a screenshot showing both software together as an example of demonstrating the position of what the mini player would look like without letters.

![image](https://github.com/KRTirtho/spotube/assets/142761950/573f7d95-9196-4eb9-b7da-2a0a871f47d9)

In this case, the album art could be in the center and the media buttons above or below it, and it would appear whenever you down/up the volume.

### Additional information

Currently ModernFlyouts no longer shows the media preview, but previously in Windows 10 it did, so if you use this software for testing or something like that you will have this difference in the update.

**Comment by JotaRata** [comment]
I think the extremely large playlist header could be minimized/hidden when using adaptive layout mode
![imagen](https://github.com/KRTirtho/spotube/assets/36273501/164a6c6e-003a-4857-8c6c-954e33b450bf)

**Comment by fallsdevil** [comment]
yes, indeed I discovered this after changing the window size. but are there any keyboard shortcuts to pause, fast forward and rewind the song? I didn't find anything about it
