### ISSUE TITLE
songs not appearing or showing and soundcloud be added together within the search for more song availability

### ISSUE THREAD

**Issue by rheno911** [KRTirtho/spotube#86]
i am searching for a song that only youtube and soundcloud will show and shows up only like spotify . Could soundcloud be added within the search so more songs specific would appear and the option to enable audio player from the device so i can listen to already downloaded songs. 
## bug on player when trying to press pause it wont do so and when closing app the audio keeps playing.

**Comment by KRTirtho** [comment]
Please open any feature request using the [ISSUE TEMPLATE](https://github.com/KRTirtho/spotube/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=) filling all the details asked there
