### ISSUE TITLE
Quits when it is supposed to minimize to tray

### ISSUE THREAD

**Issue by richardkwo** [KRTirtho/spotube#866]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/KRTirtho/spotube/assets/4409730/a3aa3e86-49fb-4cfa-b445-cbe5e5c664b7)

When I click [x] or Show/Hide from the tray icon, it quits. 

### Expected Behavior

It is supposed to minimize to tray.

### Steps to reproduce

1. Open the App.
2. Set "close behavior" to "minimize to tray"
3. Click [x] 

### Operating System

macOS 12.1

### Spotube version

v3.2.0

### Installation source

GitHub Releases (Binary)

**Comment by agolks** [comment]
for me it worked both on linux and windows with 3.2.0.
but i needed to *not* use the system title bar.
