### ISSUE TITLE
TUI feature

### ISSUE THREAD

**Issue by Windshield-Viper** [KRTirtho/spotube#868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

I'd like to use a free tui for spotify such as https://github.com/Rigellute/spotify-tui but without the premium. Could I do it using spotube?

### Suggested solution

Perhaps you guys could add an option to use a terminal to control the app?

**Comment by KRTirtho** [comment]
Sorry, this is not something we're planning to support

**Comment by KRTirtho** [comment]
Yes

**Comment by RokeJulianLockhart** [comment]
Probably best to do that then, or it'll give the wrong impression.

**Comment by KRTirtho** [comment]
Sorry, but if anyone wants to voluntarily contribute with such thing, it is welcomed. But I wouldn't want 2 completely different project to be tied in a single app. That means I'll publish them as separate package.

> probably best to do that then, or it'll give the wrong impression.

It's an Open source project, if anyone likes/loves it, then thanks a lot. If not, still, I'll thank you for giving a look. Impression only matters for companies/corporate :smile:

**Comment by RokeJulianLockhart** [comment]
> https://github.com/KRTirtho/spotube/issues/868#issuecomment-1810422389

I think you're misunderstanding me, @KRTirtho. If you close this issue as completed, that means that it's implemented. That's why you should close it as not planned.

**Comment by KRTirtho** [comment]
Dude, please tell more clearly. I lost my FOSS maintainer speech moment :rofl:
Anyway, thanks man :heart: .  My bad, I thought it meant something else lol :joy:
