### ISSUE TITLE
Make Spotube work better with slow connections

### ISSUE THREAD

**Issue by Hidetoshi6721** [KRTirtho/spotube#882]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

Currently, the way Spotube plays a song is by _temporary downloading the entire song first_, and then playing it. How may you verify this? By turning off the internet after the song starts playing.

This is a problem, because for a song of 7-8 MB, Spotube takes ages on a 30 kB/s connection (yes, I have such slow connections after I finish my daily data quota from my ISP).

Contrary to this, Spotify Lite loads the song segment-by-segment, which makes it play much smoother or shall I say, it does end up even playing it, which at the time Spotube can't.
With fast or decent connections, this of course is not a problem.

### Suggested solution

Please add the ability to Spotube to function like YouTube, Spotify, etc., such that it downloads and plays the song segment-by-segment simultaneously.

**Comment by KRTirtho** [comment]
> Currently, the way Spotube plays a song is by temporary downloading the entire song first, and then playing it. How may you verify this? By turning off the internet after the song starts playing.

Uhm, no. Spotube uses mpv which streams the audio chunk by chunk. You can even see the secondary "buffer ready" progress behind the main progress, just like YouTube or Spotify. It'll try to download as much as it can just to start playing. At a point while playing a certain part of the track, it'll try to download rest of the stream slow as the track progress. So even if you lose connection, at least this song will keep playing.

**Comment by KRTirtho** [comment]
If you have a slower network, just use the lower audio quality. It'll work better.
But Spotube doesn't automatically switch to the lower quality stream.

**Comment by Hidetoshi6721** [comment]
I am using Low quality, sorry I forgot to mention that. It is just unable to play the track.

Spotify Lite can play the track at Basic quality with no issues on the same network, the only stutter occurs while seeking which is totally fine...

**Comment by Hidetoshi6721** [comment]
Update: I finally managed to get it working!

Turning Data Saver on makes it work after like 2 mins of waiting, which is acceptable for a slow network like mine.

But Spotify (Lite) somehow is very fast, taking only 30 to 40 s... can Spotube not be optimised further to be a _little more_ - faster?? ^_^

**Comment by KRTirtho** [comment]
Can you try the nightly build, it offers a new audio source named JioSaavn which offers 48kbps m4a (AAC) which is super low quality but can be good for you
