### ISSUE TITLE
Only the section of the track

### ISSUE THREAD

**Issue by Alliba** [KRTirtho/spotube#89]
Hey bro, great app but sometimes a track only finds the snipped one that lasts about 30 seconds.

And sometimes the app plays the sound of the associated music clip.

Is there any way to adjust this or is day still a general problem? Please help me.
Greetings

**Comment by KRTirtho** [comment]
Please re-create the issue by using [bug issue template](https://github.com/KRTirtho/spotube/issues/new?assignees=&labels=bug&template=bug_report.md&title=) & close this one
