### ISSUE TITLE
Normalize audio turns itself back on after a restart

### ISSUE THREAD

**Issue by thompson937** [KRTirtho/spotube#891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After turning 'normalize audio' off "closing" the app (often I have to kill the process because the app just hangs) I find the option turned on again.

### Expected Behavior

Spotube should remember this setting between sessions.

### Steps to reproduce

1. Open the app
2. Turn normalize audio off
3. Close the app
4. Relaunch it (issue should occur here)

### Operating System

Fedora 38, Gnome 45, X11

### Spotube version

v3.2.0 build number 25

### Installation source

Flathub (Flatpak)

### Additional information

Strangely enough all other options on the settings page seem to keep their values between sessions. I'm only having trouble with this one.

**Comment by KRTirtho** [comment]
This is happening for the same reason as #821 and has been fixed

**Comment by KRTirtho** [comment]
It's not a duplicate but similar issue exists
