### ISSUE TITLE
Can't download playlists

### ISSUE THREAD

**Issue by fireproofblaze** [KRTirtho/spotube#893]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Menu for playlists have all options greyed out and unselectable

### Expected Behavior

Be able to select download on playlist menu

### Steps to reproduce

Select the dot menu on a playlist
The options are all greyed out

### Operating System

Android

### Spotube version

v.3.2.0

### Installation source

F-Droid (Android)

**Comment by fireproofblaze** [comment]
Nevermind... I was operating it wrong

**Comment by writeblankspace** [comment]
hi, I have the same issue

how did you solve this problem?
