### ISSUE TITLE
macOS Support

### ISSUE THREAD

**Issue by highjeans** [KRTirtho/spotube#9]
I was looking to install this on my Mac but there is binary available. There is a Mac folder at the root of the repository, so it shouldn't be that hard to compile and add the binary to the releases.

**Comment by KRTirtho** [comment]
I'm working on it currently & in the next release MacOS binary will be available

**Comment by highjeans** [comment]
Is there a way you can make the app a universal app (aka add support for m1) instead of only an intel app?

**Comment by highjeans** [comment]
Also I can't login. My browser is unable to find localhost:4304. I tried all browsers and none of them worked.

**Comment by highjeans** [comment]
Even weirder I see the windows minus square and x buttons for some reason. Look at the screenshot below.
<img width="1624" alt="Screen Shot 2022-02-01 at 7 01 40 PM" src="https://user-images.githubusercontent.com/77588045/152086733-8febf1b9-b9e3-41a0-a761-861b9a6f97a8.png">

**Comment by KRTirtho** [comment]
> Even weirder I see the windows minus square and x buttons for some reason. Look at the screenshot below. <img alt="Screen Shot 2022-02-01 at 7 01 40 PM" width="1624" src="https://user-images.githubusercontent.com/77588045/152086733-8febf1b9-b9e3-41a0-a761-861b9a6f97a8.png">

That's happening because I'm using custom title_bar instead of the OS specific ones. I forgot that mac has a different button layout😅. That's my bad. Will fix this in the next release

**Comment by highjeans** [comment]
> > Even weirder I see the windows minus square and x buttons for some reason. Look at the screenshot below. <img alt="Screen Shot 2022-02-01 at 7 01 40 PM" width="1624" src="https://user-images.githubusercontent.com/77588045/152086733-8febf1b9-b9e3-41a0-a761-861b9a6f97a8.png">
> 
> 
> 
> That's happening because I'm using custom title_bar instead of the OS specific ones. I forgot that mac has a different button layout😅. That's my bad. Will fix this in the next release
> 
> 

Everything works now but I see the windows button after I log in.
