### ISSUE TITLE
Linux arm64 build

### ISSUE THREAD

**Issue by franklinprakash1090** [KRTirtho/spotube#901]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

I tried to install on raspberry pi in flatpak there is no aarch64 support 

### Suggested solution

Build for aarch64/arm32 Linux and windows

**Comment by KRTirtho** [comment]
Duplicate of #715

> Is there an existing issue for this?
> - [x] I have searched the existing issues

Clearly haven't 🙂
