### ISSUE TITLE
Failed host lookup; unable to log in (Win11, v3.3.0)

### ISSUE THREAD

**Issue by Cabbagejinx** [KRTirtho/spotube#906]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Slight hunch this may be related to #905 but I wasn't sure so created a new one. If it's a duplicate feel free to close.

I am unable to login on Spotify through the app on Windows 11. When the app first opens, it tells me that I am offline, despite my internet connection working perfectly, and the previous version of Spotube being able to connect and run.

When I try to log in on Windows in the new version, however, whenever I enter my credentials and click the submit button, nothing happens; the button just blinks and I can't log in. My internet connection is working, though.

### Expected Behavior

On entering login credentials and clicking submit, I should have been able to log in.

### Steps to reproduce

1. Open the app (v3.3.0) on Windows 11
2. Go to settings
3. Click the "Connect with Spotify" Button
4. Enter login credentials
5. Click submit

### Operating System

Windows 11, 22H2

### Spotube version

v3.3.0

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev)

### Additional information

============================== CATCHER 2 LOG ==============================
------- DEVICE INFO -------
computerName: DESKTOPDEVICE
numberOfCores: 16
systemMemoryInMegabytes: 16384
------- APP INFO -------
environment: release
version: 3.3.0
appName: spotube
buildNumber: 
packageName: spotube
---------- ERROR ----------
ClientException with SocketException: Failed host lookup: 'accounts.spotify.com' (OS Error: No such host is known.
, errno = 11001), uri=https://accounts.spotify.com/api/token
------- STACK TRACE -------
#0      IOClient.send (package:http/src/io_client.dart:119)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93)
<asynchronous suspension>
#2      clientCredentialsGrant (package:oauth2/src/client_credentials_grant.dart:71)
<asynchronous suspension>
#3      SpotifyApiBase._getImpl.<anonymous closure> (package:spotify/src/spotify_base.dart:179)
<asynchronous suspension>
#4      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:212)
<asynchronous suspension>
#5      SpotifyApiBase._getImpl (package:sp------- CUSTOM INFO -------

**Comment by KRTirtho** [comment]
Is Spotify available in your region? Also, check if it's accessible using any browser. Looks like it is failing to lookup address

**Comment by Cabbagejinx** [comment]
Yes, Spotify is available in my region. I can access it with both Brave and Firefox. I can even use the Android version (though there's a small issue with the android version too) and log in and stream perfectly. In fact, v3.2.0 is working perfectly and I can sign in without problems on the previous version. It's v3.3.0 specifically that has this issue.

Also, I don't know if this would be of any use, but when I was installing v3.3.0 I was blocked by Smartscreen because it had an "unknown publisher". The previous version did not have this problem and it was signed. Just extra info.

**Comment by Cabbagejinx** [comment]
Strange. The issue just magically resolved itself just now. Even half an hour ago I was not able to log in despite being able to use Spotify on web, and now I can suddenly log in. I'm closing this issue since it's resolved now, and I guess I'll never know what happened.

**Comment by KRTirtho** [comment]
Maybe DNS cache related issue. Who knows! Glad to know it got resolved by itself
