### ISSUE TITLE
remote control

### ISSUE THREAD

**Issue by SilPan** [KRTirtho/spotube#908]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

I would like to listen to music on my media machine, but remote control it from my phone.

### Suggested solution

Like have the full spotube UI on the phone and the playback happen on the media computer.

You can probably already imagine which direction I am going with, something like spotify-connect.
I see the problem with needing a central server so that it can work over the Internet, but how about local network only?
I am certain you guys already thought about this, but I can not find anything in the issues and the discussion.
The only issue I find is about "listen along" #8, but that is not the same.

One could define an API how spotube can get remote controlled, with only few functions
* play/{song-id}
* pause|play
* and some queuing

and leverage the search functionality and everything on the device that is remote controlling.

A running spotube that is ready to be remote controlled could advertise itself via UPnP on the local net.

I would be surprised if that functionality was not already on your minds?
Is there something that is very difficult about it?
Is it more complex than I am imagining it?

### Useful resources

https://en.wikipedia.org/wiki/Universal_Plug_and_Play
https://pub.dev/packages/upnp2

This is another project where they got the discovery of devices on the local net really figured out, I was gonna add it as a UPnP example, but to my suprise they don't use it. So there are also other ways.
https://github.com/KDE/kdeconnect-kde

### Additional information

Thanks for creating spotube!

**Comment by KRTirtho** [comment]
Support added in 68374ef
