### ISSUE TITLE
Alternative track selection on manual search not working (Android13 + Win11, v3.3.0)

### ISSUE THREAD

**Issue by Cabbagejinx** [KRTirtho/spotube#909]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Suppose an alternative track for a song needs to be selected, and because you cannot find it in the list that's presented by the default search query, that track needs to be manually searched for using a different query.
In such cases, the alternative track is simply not selected at all. Instead, the old track continues to play, and the alternative track cannot be changed at all.
Seems to be specific to 3.3.0 on Android, because 3.2.0 did not have this issue. I can select the alternative track I need on 3.2.0 but not on 3.3.0. The tracks are not region-blocked either.
Happens on Youtube, Piped (tried two or three instances, problem persists) and JioSaavn.

### Expected Behavior

Alternative track for a song can be selected, and the selected alternative track can be played.

### Steps to reproduce

1. Play a track
2. Tap on the alternative track button
3. Change the search query for the alternative track
4. Wait till the search results change
5. Select any of the search results to change the alternative track (ensure track is not blocked in your region)
6. The alternative track is not changed; instead, the previous track keeps playing

### Operating System

Android 13

### Spotube version

v3.3.0

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev)

### Additional information

Device: Oneplus Nord 3, if that's of any use.

**Comment by Cabbagejinx** [comment]
Update: The Windows 11 version is facing the same issue. And there's nothing in the logs either that's related to it.

**Comment by KRTirtho** [comment]
Fixed in 3.5.0
