### ISSUE TITLE
Error Authentication Failure when trying to log in (Ubuntu 23.10)

### ISSUE THREAD

**Issue by BlueFoxx** [KRTirtho/spotube#913]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After following the instruction, when I try to ﻿log in, a window pops up with this error message

```
Error Authentication Failure
FormatException: Unexpected character (at line 2, character 1)
<html>
```
![Screenshot from 2023-11-29 03-48-29](https://github.com/KRTirtho/spotube/assets/45783062/85d57eaf-0852-49f7-a171-664cb730ed40)

### Expected Behavior

I expect to open the app without any issue after entering 

### Steps to reproduce

1. I open the app
2. I then followed the instructions and added my Spotify cookie credential and on clicking submit, that error pops up.

### Operating System

Ubuntu 23.10

### Spotube version

v3.0.0

### Installation source

Flathub (Flatpak)

### Additional information

Here is the log 

```
============================== CATCHER 2 LOG ==============================
------- DEVICE INFO -------
name: GNOME
version: 44 (Flatpak runtime)
id: org.gnome.Platform
idLike: null
versionCodename: null
versionId: 44
prettyName: GNOME 44 (Flatpak runtime)
buildId: null
variant: null
variantId: null
machineId: 2fb4a9b6993a4246a51e9fa347bf2909
------- APP INFO -------
environment: release
version: 3.3.0
appName: spotube
buildNumber: 26
packageName: spotube
---------- ERROR ----------
FormatException: Unexpected character (at line 2, character 1)
<html>
^
------- STACK TRACE -------
#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1250)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:915)
#3      _parseJson (dart:convert-patch/convert_patch.dart:35)
#4      JsonDecoder.convert (dart:convert/json.dart:610)
#5      JsonCodec.decode (dart:convert/json.dart:216)
#6      jsonDecode (dart:convert/json.dart:155)
#7      AuthenticationCredentials.fromCookie (package:spotube/provider/authentication_provider.dart:39)
<asynchronous suspension>
#8      TokenLoginForm.build.<anonymous closure> (package:spotube/components/desktop_login/login_form.dart:69)
<asynchronous suspension>
------- CUSTOM INFO -------
```

**Comment by KRTirtho** [comment]
@BlueFoxx please specify your region. I'm unable to reproduc this

**Comment by KRTirtho** [comment]
Also please check if the latest version works?

**Comment by BlueFoxx** [comment]
Am now able to log in without issues... Thanks.

**Comment by fybx** [comment]
> Am now able to log in without issues... Thanks.

![image](https://github.com/KRTirtho/spotube/assets/41127439/a197140e-d8c2-4a89-a6f7-c8c7f4e9acd6)

How have you managed to fix it? I have a similar problem, and read through #930, #943, #905, #972 without any solutions... I'm on Arch Linux.

**Comment by GeekYwl** [comment]
> > Am now able to log in without issues... Thanks.
> 
> ![image](https://private-user-images.githubusercontent.com/41127439/301848469-a197140e-d8c2-4a89-a6f7-c8c7f4e9acd6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNzgzMzQsIm5iZiI6MTcxMzI3ODAzNCwicGF0aCI6Ii80MTEyNzQzOS8zMDE4NDg0NjktYTE5NzE0MGUtZDhjMi00YTg5LWE2ZjctYzhjN2Y0ZTlhY2Q2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDE0MzM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhZTdkYzY1OTliM2U0NWM5ZjAwOWExNTk3NTU3YWQzNDMyZmQyMDAzNjkwMDQ3YjdkNzNiMGZmYTExN2I0M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.umCDXDe1FipG1Ox4ftpK8cnLuVpXtZ7W9SsPGrC0K5I)
> 
> How have you managed to fix it? I have a similar problem, and read through #930, #943, #905, #972 without any solutions... I'm on Arch Linux.

I'm in the same situation as you.

**Comment by KRTirtho** [comment]
Just log out and login. The cache structure was changed so the old login isn't working anymore.
