### ISSUE TITLE
Playlists cannot be created/imported

### ISSUE THREAD

**Issue by ALongToe** [KRTirtho/spotube#92]
Steps to reproduce the bug:

Importing playlists:

> Connect to spotify account following the steps on github page but without adding genius token

> Observe the bug (it happens even after a reboot)

Creating playlists :

> After logging in, I click on create playlists

> I give the playlist a name and made sure it's private and not collaborative

> Observe the bug

**Comment by KRTirtho** [comment]
The issue has been fixed & will be available in the next release

**Comment by KRTirtho** [comment]
Fixed in latest release
