### ISSUE TITLE
Playback resumes even when it wasn't playing before

### ISSUE THREAD

**Issue by rramirezg22** [KRTirtho/spotube#926]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After a call or some other media events playback resumes even when it wasn't playing before

### Expected Behavior

Not resume

### Steps to reproduce

...

### Operating System

Android

### Spotube version

3.3.0

### Installation source

Play Store (Android)

**Comment by carefulcomputer** [comment]
Similar issue. Playing of song automatically starts without any user interaction. Last night, the phone was on charger and playback automatically started twice. Had to uninstall the app to be able to sleep.
