### ISSUE TITLE
Spotube not available for FEDORA on aarch64 (nothing provides libmpv.so.1)

### ISSUE THREAD

**Issue by 4kz** [KRTirtho/spotube#929]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I believe this might be a duplicate but I cannot find the original thread, in any case, with fedora asahi remix becoming the flagship distro for linux on apple silicon I think it's time to bring this issue into the spotlight once again, the flatpak version presents the same exact issue with this one missing library
```
tizianods@fedora:pts/2-> /home » tizianods » Downloads (0) 
> sudo dnf install ./Spotube-linux-aarch64.rpm 
Last metadata expiration check: 3:08:12 ago on Mon 04 Dec 2023 03:14:11 AM CET.
allow_vendor_change is disabled. This option is currently not supported for downgrade and distro-sync commands
Error: 
 Problem: conflicting requests
  - nothing provides libmpv.so.1()(64bit) needed by spotube-3.1.1+23-23.aarch64 from @commandline
(try to add '--skip-broken' to skip uninstallable packages)

```

### Expected Behavior

for the app to install

### Steps to reproduce

1. download the binary
2. type sudo dnf install name-of-the-file
3. error

### Operating System

Fedora Asahi Remix

### Installation source

GitHub Actions (Nightly Binary)

**Comment by franchioping** [comment]
what version of fedora are u running? does installing the mpv-libs and mpv-devel packages fix this?

**Comment by 4kz** [comment]
No, it did not fix that, and I'm on the latest fedora asahi remix which
whould be fedore 39 as far as I remember

Il giorno sabato 30 dicembre 2023, franchioping ***@***.***>
ha scritto:
> what version of fedora are u running? does installing the mpv-libs and
mpv-devel packages fix this?
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.<
https://ci4.googleusercontent.com/proxy/b1imXGWQTr4FcnhPnSUKIIfgRpeXRHYb-y80vsWGd5h9t8GqtVxKy_KBmrMDnYtXeSjf_R4M40_-u2E1hJPwjQf6sLaoeC-qpPWRWH8uv4J1MBAj_H1o9zv6UyyZNhdhMjzZM7NxEVHB2K65uaqsjl17_76zJ-yfm_1TcChMxPklwAZbA6-ROo_2cVx7wk65KDQIF4GVOeKtkW-58wVMaEMU-DkEkCxXmIpAJWms2wWdk8vmtA=s0-d-e1-ft#https://github.com/notifications/beacon/AILKCLDQLL5MR2LFSBC2JB3YL5ZZ5A5CNFSM6AAAAABAFMU4SSWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTTPTL5OA.gif>Message
ID: ***@***.***>

**Comment by franchioping** [comment]
does it run under AppImage?

**Comment by 4kz** [comment]
It prints the same error

Il giorno sabato 30 dicembre 2023, franchioping ***@***.***>
ha scritto:
> does it run under AppImage?
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.<
https://ci3.googleusercontent.com/proxy/6eaZBZYW3lQv0_GFgVgid9jzmt0IzY8pwsc5iLqAR4BfwUuXyHb810DtdsgylSBK-lamSpspkFXAMR4uwI0nfWzeBFXACgps29ThJNK8TjMC5X6tOfKLAk7HOVwmSuFj90o73RyNc5C8PsnePcOwvjPUWYOzichPOdGMTDfNYIa7MqZsx9p3egsudUgmsI7uAAqg7u3FFUZIE0URZJyrpghXZnMexil27Q2wNaKaqLBAo0lQEg=s0-d-e1-ft#https://github.com/notifications/beacon/AILKCLDOTPBKB4KBVWEQVXLYMBY45A5CNFSM6AAAAABAFMU4SSWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTTPTWIZ4.gif>Message
ID: ***@***.***>

**Comment by mohammadhzp** [comment]
I am experiencing the same issue on Fedora Linux 39 (Workstation Edition)

**Comment by tomodachi** [comment]
This problem is not only on Fedora on aarch64 the same issue exists  when install on  Fedora 39 on X86_64

I've installed the following mpv packages

🐧 rpm -qa |grep mpv
mpv-0.36.0-3.fc39.x86_64
mpv-libs-0.36.0-3.fc39.x86_64
mpv-devel-0.36.0-3.fc39.x86_64

It does not satisfy the requirement for libmpv.so.1

🐧 fd  libmpv.so
usr/lib64/libmpv.so.2.1.0
usr/lib64/libmpv.so.2
usr/lib64/libmpv.so

**Comment by fpauser** [comment]
Same on Fedora 38

**Comment by KRTirtho** [comment]
Closing this as aarch64 is now supported through Flatpak

**Comment by universish** [comment]
Same on fedora workstation 40 x86_64
#1931

**Comment by universish** [comment]
Same on fedora workstation 40 x86_64
[https://github.com/KRTirtho/spotube/issues/1931](url)

**Comment by Acosta01-dev** [comment]
Same issue
