### ISSUE TITLE
search suggestion

### ISSUE THREAD

**Issue by senolfndk** [KRTirtho/spotube#93]
Can you add suggestions while searching?

**Comment by KRTirtho** [comment]
As far as I know the Spotify Web API still doesn't support word suggestions but playlist/track/artist/album suggestions can be done

**Comment by senolfndk** [comment]
> Bildiğim kadarıyla Spotify Web API hala kelime önerilerini desteklemiyor ancak çalma listesi/parça/sanatçı/albüm önerileri yapılabiliyor.

ok

**Comment by developer861** [comment]
> As far as I know the Spotify Web API still doesn't support word suggestions but playlist/track/artist/album suggestions can be done

how about using youtube music's search suggestions?
