### ISSUE TITLE
Unable to turn on app notifications.

### ISSUE THREAD

**Issue by fxzxmicah** [KRTirtho/spotube#932]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Unable to turn on notification permissions for app.

### Expected Behavior

App notifications can be turned on and displayed.

### Steps to reproduce

1. Turn on app notifications in Android settings.
2. Failed.

### Operating System

Android 13

### Spotube version

v3.3.0

### Installation source

Play Store (Android)

### Additional information

This may be caused by the loss of this permission `android.permission.POST_NOTIFICATIONS`.

**Comment by KRTirtho** [comment]
Spotube doesn't require any notification permission. That's why `android.permission.POST_NOTIFICATIONS` is not in the `AndroidManifest.xml` thus you're unable to turn on notifications.

**Comment by fxzxmicah** [comment]
> Spotube doesn't require any notification permission. That's why `android.permission.POST_NOTIFICATIONS` is not in the `AndroidManifest.xml` thus you're unable to turn on notifications.

So Spotube can't control media playback from notification center?
But I see here, the Spotube displays notifications.
https://github.com/KRTirtho/spotube/issues/602#issuecomment-1679534534

**Comment by fxzxmicah** [comment]
![Screenshot_20231205_140321](https://github.com/KRTirtho/spotube/assets/48860358/b40fc93c-3ec8-4e00-8d18-d2244c810743)
![Screenshot_20231205_140328](https://github.com/KRTirtho/spotube/assets/48860358/1e32a139-7e55-4347-b0d4-e1e81e5569be)

**Comment by KRTirtho** [comment]
That’s not notifications. It's media session control. And yes, it's supported.

**Comment by fxzxmicah** [comment]
What should I do on my phone? My phone doesn't seem to support this "media session control". Can't I control playback outside of the app?

**Comment by fxzxmicah** [comment]
> Does this happen for other music players?

They display a notification to control playback.

**Comment by soyelmismo** [comment]
Sorry, I didn't see if there's another issue about this... But I also can't see the media controls in CrDroid / LineageOS Android 13, ofc I can see media controls from another apps as normal.


And when I'm listening music in background the app closes too much, I needed to force pin it into ram to not getting the playback stopped (I don't need to do this with other apps also)

**Comment by Bowarc** [comment]
Same issue on andoid 14, I have the media control panel only when my phone is unlocked, and notifications are "blocked"
