### ISSUE TITLE
Lyrics are not working

### ISSUE THREAD

**Issue by sanju-suresh** [KRTirtho/spotube#934]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Both synced and plain lyrics doesnt load for most songs
Just shows : "Exception: Unable to find lyrics"

### Expected Behavior

Wanted to see lyrics

### Steps to reproduce

1. Clicked lyrics for different songs

### Operating System

Ubuntu 20.04

### Spotube version

v3.3.0

### Installation source

Flathub (Flatpak)

**Comment by KRTirtho** [comment]
It says, there were no lyrics found for that song. Spotube can't do anything if Spotify doesn't have lyrics.
