### ISSUE TITLE
UnimplementedError: disposeAllPlayers() has not been implemented

### ISSUE THREAD

**Issue by Krusty27** [KRTirtho/spotube#94]
**Describe the bug**
Spotube interface doesn't start and raises error: `flutter: UnimplementedError: disposeAllPlayers() has not been implemented.`

**To Reproduce**
1. Start spotube from the terminal

**Expected behavior**
Spotube should start

**Installation Source/Method**
- Package Manager: pacman/yay
- Community Repo: AUR

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version 5.18.1-arch1-1 (Spotube v2.1.0-1)

**Additional context**
Running Wayland

**Comment by KRTirtho** [comment]
Provide the logs with by running `ERROR=true VERBOSE=true DEBUG=true spotube` in your terminal

**Comment by Krusty27** [comment]
I'm sorry can you tell me where can I find the logs? By running that command it still gives the same error

**Comment by KRTirtho** [comment]
Just run Spotube with:
```bash
ERROR=true VERBOSE=true DEBUG=true spotube
```
Then 
- play a track/playlist/album
- Skip To Next/Prev track
- Play/Pause the track

Finally copy all the terminal output and paste them here with comment

**Comment by Krusty27** [comment]
Oh, okay than I can't say much more since it's the same thing: the error gets printed on the terminal and nothing happens, the interface doesn't even appear, just the icon in the taskbar.

**Comment by KRTirtho** [comment]
Can you give details about what display manager, Desktop Environment & Window manager you're using? Also are you using pipewire or Pulseaudio?

**Comment by KRTirtho** [comment]
`flutter: UnimplementedError: disposeAllPlayers() has not been implemented.` is an internal library related error & it is shown always but it shouldn't bother Spotube to start. So there's something else wrong in your case

**Comment by Krusty27** [comment]
Ok I'm using sddm, Wayland, Mutter with PipeWire

**Comment by KRTirtho** [comment]
Your Desktop environment?

**Comment by Krusty27** [comment]
Sorry, GNOME

**Comment by KRTirtho** [comment]
Can you check with latest version of Spotube v2.3.0 (which was just released) and see if it works or not?

**Comment by Krusty27** [comment]
Yes now it works :D
