### ISSUE TITLE
Segmentation fault with AppImage

### ISSUE THREAD

**Issue by UlyssesZh** [KRTirtho/spotube#942]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```sh
LD_LIBRARY_PATH=/opt/glibc/lib AppImageLauncher ~/apps/Spotube-linux-x86_64_5e2a626051021efe1854ff5f66d6602f.AppImage
```
```
[1]    1978221 segmentation fault (core dumped)  LD_LIBRARY_PATH=/opt/glibc/lib AppImageLauncher
```

### Expected Behavior

Runs.

### Steps to reproduce

Use AppImageLauncher to launch the appimage.

### Operating System

Ubuntu 20.04

### Spotube version

v3.3.0

### Installation source

GitHub Releases (Binary)

### Additional information

- glibc 2.35 (compiled by myself)
- AppImageLauncher 2.2.0

**Comment by KRTirtho** [comment]
Closing it as we stopped supporting AppImage.
Please use Flatpak from now on
