### ISSUE TITLE
Last.fm Invalid API Key

### ISSUE THREAD

**Issue by tyronetheqt** [KRTirtho/spotube#946]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When i try to log in with last.fm I get "Code 10 Invalid API Key"

### Expected Behavior

I should have been able to log in with my last.fm account

### Steps to reproduce

1. I went to settings
2. I clicked on "Login with last.fm"
3. I inputted my username and password
4. Profit

### Operating System

Android

### Spotube version

v3.3.0

### Installation source

F-Droid (Android)

### Additional information

I believe this is due to the last.fm key being expired. You can apply for a new one at
"https://www.last.fm/api/account/create".

**Comment by HEPOSHEIKKI** [comment]
I'm experiencing this too on android v.3.3.0 from F-droid

**Comment by jstnhd1** [comment]
Same issue for me as well

**Comment by KRTirtho** [comment]
This was fixed in fdroid repo but MR is blocked for a new version update (twice) 😅 
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14143

**Comment by KRTirtho** [comment]
Fixed in 3.4.0
