### ISSUE TITLE
Add a switch for UI design

### ISSUE THREAD

**Issue by momobobe** [KRTirtho/spotube#95]
Currently on my phone (Android), navigation bar is on the left, however, it's showed there is/was a design that the bar is at the bottom as below

![](https://github.com/KRTirtho/spotube/raw/master/assets/mobile-screenshots/mobile-combined.jpg) 

I'm a new user and not sure if that's an old design, but I feel it more comfortable and suitable especially for a small screen, so even if you have a new design, please provide a switch for fall back.

Or maybe it's the responsive design, but obviously not working correctly here, since my device is a phone instead of tablet. In this case, please also add a switch to allow users to decide whether to choose manually.

Thanks for your attention.

**Comment by KRTirtho** [comment]
Your phone must be really wide vertically. Can you state the resolution of your Android Smartphone?

**Comment by KRTirtho** [comment]
Currently we have a feature to manually select UI adaptation.

Settings > Appearance > Layout Mode
