### ISSUE TITLE
Incorrect scrobbling with Last.fm

### ISSUE THREAD

**Issue by gebbet** [KRTirtho/spotube#958]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Song names, artists are somehow scrobbled incorrectly to Last.fm, even if the names are correct. 

For example I have listened "[Illuminate - Sub Focus & Wilkinson](https://www.last.fm/music/Sub+Focus/_/Illuminate+-+Sub+Focus+&+Wilkinson)" 21 times from Spotify so far and the song has 190k total listens. However, when I listen with Spotube, it is scrobbled as "[Illuminate - Sub Focus & Wilkinson](https://www.last.fm/music/Sub+Focus,+Wilkinson/_/Illuminate+-+Sub+Focus+&+Wilkinson)" but on Last.fm it is displayed as I have listened to the song only once and it has only 1034 total listens. 

This applies to all songs I have listened so far; while the names are same, it is as if I am listening the songs for the first time. I am not sure what is causing this but I feel like it has something to do with the way Spotube handles tags (or the actual song source is not Spotify as one of the songs from my playlist has a different ending somehow); it is not identical to Spotify apparently. By the way, I have logged in with Spotify premium.

I just wanted to mention this but please disregard it if this is the expected behaviour.

### Expected Behavior

The songs scrobbled to last.fm from Spotube should match with the ones that are scrobbled with Spotify.

### Steps to reproduce

1. Listen a song with Spotify
2. Check the scrobbled songs page & stats on Last.fm
3. Listen the same song with Spotube
4. Check Last.fm to see that the pages & stats mismatch

### Operating System

Wİndows 10

### Spotube version

v3.3.0

### Installation source

GitHub Releases (Binary)

**Comment by KRTirtho** [comment]
I see the problem here,
https://github.com/KRTirtho/spotube/blob/2b0d17e9cad742a6e651bc48752ff7cfd2782c32/lib/provider/scrobbler_provider.dart#L45-L53

Here, we're passing all artist's combined name as artist string. But, it looks like we're supposed to only supply the main artist's 
name there. Unfortunately, anything related to this wasn't written in the lastfm docs, or if it's written, it went unnoticed.

Thanks for submitting the issue.

**Comment by KRTirtho** [comment]
Fixed in 3.4.0
