### ISSUE TITLE
New v3.3.0 release causes downloads to not have the album cover

### ISSUE THREAD

**Issue by TheHighGroundWins** [KRTirtho/spotube#964]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Downloaded songs don't have an album cover.

### Expected Behavior

Downloaded songs will be downloaded with an album cover.

### Steps to reproduce

1. Open the app
2. Download a song

### Operating System

Android

### Spotube version

v3.3.0

### Installation source

GitHub Releases (Binary)

### Additional information

The previous version v3.2.0 doesn't have this problem, which I tested again by downgrading and downloading a song. The v3.2.0 version has the correct album cover.

**Comment by KRTirtho** [comment]
It's already fixed. Use the nightly version to test it out
