### ISSUE TITLE
Russian song not playing

### ISSUE THREAD

**Issue by tjarross** [KRTirtho/spotube#968]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Cannot play the first two songs of the album "Прорицание" of band "Fferyllt"

### Expected Behavior

The songs should be played

### Steps to reproduce

- Open the app
- Search for band Fferyllt
- Click the band
- Go to albums
- Click the album "Прорицание"
- Try to play one of the first two songs

### Operating System

Android

### Spotube version

v3.3.0

### Installation source

F-Droid (Android)

**Comment by franchioping** [comment]
That song also doesn't work on linux, but other russian songs do (for example "Прорицание Вёльвы" from "The Legend of Stone")

**Comment by franchioping** [comment]
in the function "static SourceMap toSourceMap(StreamManifest manifest)" (line 81 of lib/services/sourced_track/sources/youtube.dart) there is an exception because the weba list is empty

**Comment by franchioping** [comment]
@tjarross 
Created a pull request that fixes this issue, until its approved you can mitigate this by changing the preferred audio codec for streaming in settings -> playback -> streaming music codec to M4a
This will fix this song, but might break others that don't have the M4a codec available

**Comment by tjarross** [comment]
Thank you @franchioping !
