### ISSUE TITLE
Music won't start playing

### ISSUE THREAD

**Issue by Jack-Chou-HZ** [KRTirtho/spotube#97]
**Describe the bug**
I tried both AppImage & .deb version: 2.1.
Successuflly login with client id/secret, my playlists are displayed.
But I cannot play any of the songs/music in my playlists or any other channels.
The Play/Stop icons says "playing", but no the paly-time stays at 0s, and no sounds played.
My audio device is OK, I can play music via Rhythembox.

**To Reproduce**
1. Go to 'spotube desktop client Home page'
2. Click on 'Library'
3. Scroll down to 'any of my listed song' & 'click play'
4. No error messages pop up, but no sound is heard.

**Expected behavior**
I want the music I "played" to be bufferred and echoed.

**Screenshots**
![image](https://user-images.githubusercontent.com/90299353/171772377-cd2a4c08-a546-46c3-aad7-2616b97ad3b9.png)

**Installation Source/Method**
AppImage & deb from github.

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux
 - Version: 21.04 LTS

**Additional context**

**Comment by KRTirtho** [comment]
Run `ERROR=true VERBOSE=true DEBUG=true spotube` in your terminal & provide the logs it outputs when you start playing a track/playlist

**Comment by Jack-Chou-HZ** [comment]
$ ERROR=true VERBOSE=true DEBUG=true spotube
flutter: UnimplementedError: disposeAllPlayers() has not been implemented.
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   _SpotubeLogger.log (package:spotube/models/Logger.dart:27)
flutter: │ #1   Playback.setCurrentPlaylist= (package:spotube/provider/Playback.dart:153)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ [TrackTile] [Current Playlist Changed] Liked Tracks - user-liked-tracks
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   _SpotubeLogger.log (package:spotube/models/Logger.dart:27)
flutter: │ #1   Playback.setCurrentTrack= (package:spotube/provider/Playback.dart:147)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ [TrackTile] [Setting Current Track] 吻和淚 - 2FNOdCQmp64S66T97kWTdQ
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   _SpotubeLogger.log (package:spotube/models/Logger.dart:27)
flutter: │ #1   Playback.startPlaying (package:spotube/provider/Playback.dart:218)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ [TrackTile] [Track Playing] null - null
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   _SpotubeLogger.log (package:spotube/models/Logger.dart:27)
flutter: │ #1   toSpotubeTrack (package:spotube/helpers/search-youtube.dart:17)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ [toSpotubeTrack] [Track Search Artists] [周子寒]
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   _SpotubeLogger.log (package:spotube/models/Logger.dart:27)
flutter: │ #1   toSpotubeTrack (package:spotube/helpers/search-youtube.dart:26)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ [toSpotubeTrack] [Track Search Title] 吻和淚
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   _SpotubeLogger.log (package:spotube/models/Logger.dart:27)
flutter: │ #1   toSpotubeTrack (package:spotube/helpers/search-youtube.dart:31)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ [toSpotubeTrack] [Youtube Search Term] 周子寒 - 吻和淚 
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = www.youtube.com, port = 37264
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ #0   _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:682)
flutter: │ #1   _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1817)
flutter: │ #2   RawSocket.startConnect (dart:io-patch/socket_patch.dart:27)
flutter: │ #3   RawSecureSocket.startConnect (dart:io/secure_socket.dart:237)
flutter: │ #4   SecureSocket.startConnect (dart:io/secure_socket.dart:60)
flutter: │ #5   _ConnectionTarget.connect (dart:_http/http_impl.dart:2438)
flutter: │ #6   _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2834)
flutter: │ #7   _HttpClient._getConnection (dart:_http/http_impl.dart:2839)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ ⛔ [PlayerActions] startPlaying
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

**Comment by Jack-Chou-HZ** [comment]
btw I live in China Mainland, I'm blocked from accessing www.youtube.com

**Comment by Jack-Chou-HZ** [comment]
I used http proxy resolved the problem, now I can play my playlist normally, thanks!
btw, it will be great if Spotube could support socks5 proxy via passing arguments in CLI.
