### ISSUE TITLE
Error Authentication Failure

### ISSUE THREAD

**Issue by jeec** [KRTirtho/spotube#972]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

![Screenshot 2023-12-30 at 12 12 02](https://github.com/KRTirtho/spotube/assets/10796826/89c7d726-3250-441a-a05e-995afacbf347)

### Expected Behavior

log in

### Steps to reproduce

follow the instruction

### Operating System

Mac OS  14.1.2 

### Installation source

GitHub Releases (Binary)

**Comment by happyeverydays414** [comment]
me too same problem with macos 12.6.7 with m1max 
my spotube version is v3.3.0

**Comment by happyeverydays414** [comment]
but on intel mac with os catalina this problem can be solved through clash x pro(enhanced mode)

**Comment by QiKe-007** [comment]
I had the same problem with Windows 10

**Comment by KRTirtho** [comment]
@QiKe-007 follow this thread for your issue #905 
It's usually outdated ssl certificates and you probably need to update Windows

**Comment by KRTirtho** [comment]
Duplicate of #930

**Comment by tychoon** [comment]
me too. Authentication Failure

**Comment by ushishishishishi** [comment]
same error here with macos 12.3 M1
