### ISSUE TITLE
Nightly Build Bug: Discord Rich Presence Elapsed Time Not Pausing

### ISSUE THREAD

**Issue by abhinavanand-fed** [KRTirtho/spotube#979]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The issue is that when the music is paused, the elapsed time continues to increase.

![elapsed](https://github.com/KRTirtho/spotube/assets/110715459/edf31031-64a4-4031-93c6-8255c7ad1d3c)

### Expected Behavior

What should have been implemented is that when the music is paused, the elapsed time should also be paused.

### Steps to reproduce

1. Install Spotube Nightly Build
2. Enable Discord Rich Presence
3. Play music and pause it
4. Check the elapsed time in the status

### Operating System

Windows

### Spotube version

v3.0.0

### Installation source

GitHub Releases (Binary)

**Comment by KRTirtho** [comment]
This is fixed in 3.8.0
