### ISSUE TITLE
Discord RPC Feature

### ISSUE THREAD

**Issue by batuhantrkgl** [KRTirtho/spotube#98]
like this: 
![image](https://user-images.githubusercontent.com/76158371/171862978-82d29c23-8f3b-4b9c-a224-17aa7192069c.png)
![image](https://user-images.githubusercontent.com/76158371/171863027-2abb5584-99dc-4613-8fb9-b0d6b2c0d28f.png)

**Comment by KRTirtho** [comment]
This is now possible using https://github.com/alexmercerind/dart_discord_rpc

**Comment by xexnoob420** [comment]
Can we please make this toggleable? I really don't like people knowing what I'm listening too! lol
