### ISSUE TITLE
Close button closes the application ignoring settings

### ISSUE THREAD

**Issue by kikorb** [KRTirtho/spotube#983]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hit the close button on the player closes the application.

### Expected Behavior

The player is hidden as any macos Application, specially consdiering there is a setting to control this.

### Steps to reproduce

1. Open the application
2. Check settings for close button, make sure the behavious is to minimize to tray

![Screenshot 2023-12-31 at 17 01 48](https://github.com/KRTirtho/spotube/assets/1625191/8aa8e44b-96fd-4a29-bbfc-ce8e087d273b)

3. Click close

### Operating System

macOS

### Spotube version

3.4.0 (27)

### Installation source

GitHub Releases (Binary)

**Comment by karniv00l** [comment]
Incoming fix: https://github.com/KRTirtho/spotube/pull/1001

**Comment by KRTirtho** [comment]
Fixed so closing

**Comment by kikorb** [comment]
Thanks
