### ISSUE TITLE
Proposal for Stunning UI Design of Your Music Player App

### ISSUE THREAD

**Issue by Banana021s** [KRTirtho/spotube#984]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

i congratulate u guys that someone thinks about this useful project finally.
i think this project can be more productable , it has some problems about the UI and the applications's website so i said to myself it would be good if u guys give me a permission to redesign the application :)

### Suggested solution

I am a useful designer and front end developer who can help u guys to have the best application design **`JUST FOR FUN AND FREE`**.
i can change your color palette and make it more shiny and beautiful and give you the sample of music player that i wanna design 
so if u guys wanted to contact me for the Ui please send me an answer or email to `arash.k021@yahoo.com`

**Comment by KRTirtho** [comment]
Yes, sure. It's an open source project, anyone is welcome for contribution. You can go ahead and create new designs while conversing with us and updating it to fit the needs for the project.

**Comment by MrConqueror** [comment]
ngl this app UI sucks also the Player

**Comment by Banana021s** [comment]
> Yes, sure. It's an open source project, anyone is welcome for contribution. You can go ahead and create new designs while conversing with us and updating it to fit the needs for the project.

because of some reasons i have decided to dont work in front end programming anymore so yah i just can show u the design we wanna create for u and my team will dedvelope it. even my team and my friends have lots of idea about this project :))) 
it can be more challenging for us and useful for users
so do u wanna see this design and where we can talk about this toppic ?

**Comment by Banana021s** [comment]
> ngl this app UI sucks also the Player
> except explore genre it's nice design😜

:) i can design it better but for u guys as a developer will be hard to develop my designs so i have to contact to the team 
even my friend can create a tui app and better api which can we Web Scraping all the musics in the global internet

so yah we can call it _Better-Spot_ or _Better-Spotify_

**Comment by Banana021s** [comment]
finally i talked to my friend and yah we will work on your design but at least please text me in Telegram or discord
which one u can do ?

**Comment by KRTirtho** [comment]
We can use Discord. We've separate design channel there.
https://discord.gg/MpRTDAgvD8

**Comment by Banana021s** [comment]
tnx bro
