### ISSUE TITLE
Local Downloaded Tracks

### ISSUE THREAD

**Issue by Tabigarasu5939** [KRTirtho/spotube#987]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

Lets say i have a lot of mp3's and m4a's downloaded on my phone and i want to use it alongside Spotube.

### Suggested solution

Scan the phone or desktop designated locations for local tracks, folders, etc. Replace the similar/duplicates with the newly downloaded songs in Spotube. get rid of the duplicates.
and if its possible let us add them cross song(local and Spotify) to the playlist.

**Comment by KRTirtho** [comment]
Duplicate of #595
