### ISSUE TITLE
Show new releases of Followed Artists

### ISSUE THREAD

**Issue by IplaygamesIhate** [KRTirtho/spotube#99]
**Is your feature request related to a problem? Please describe.**
Spotify desktop app does not show the new releases of artist I follow. I get the notifications on the mobile app and all new releases are show there. Hope you can make a new section showing all the releases that I can see on the mobile app

**Describe the solution you'd like**
A separate tab just shewing new releases, the home page seems like it scrolls infinitely long without loading properly. 
Would be better if I can find the stuff I'm interested on the top with a separate songs and albums differentiation. if that can be made

**Describe alternatives you've considered**
The main reason I've found this app is when I was searching for a desktop client for spottily that offers new release feature. Like Cider for apple music, hope you can grow this app the same way

**Additional context**
Also the scrolling isn't working correctly

**Comment by RaptaG** [comment]
Added in 3.0.0
