### ISSUE TITLE
Unable to install spotube .deb on LMDE5

### ISSUE THREAD

**Issue by clmaes** [KRTirtho/spotube#990]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you try to install the .deb file, you get an error.
![Schermafdruk van 2024-01-01 16-22-01](https://github.com/KRTirtho/spotube/assets/155369597/91bae110-7292-4102-ae88-b05381ad2825)

### Expected Behavior

No error.

### Steps to reproduce

1. Install de .deb file. with the installer.

### Operating System

LMDE5

### Spotube version

3.3.0, 3.4.0

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev)

**Comment by KRTirtho** [comment]
The .deb version works only for Debian >= 12
