### ISSUE TITLE
The screen freezes and a gray window is displayed

### ISSUE THREAD

**Issue by hosseinakbari-liefermia** [KRTirtho/spotube#991]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The screen freezes and a gray window is displayed

### Expected Behavior

get the next step and load the data

### Steps to reproduce

1. I installed the app on Ubuntu
2. I opened the app
3. I fix my dark theme on the setting
4. I log in to Spotify and copy cookie values on token inputs
5. I clicked on the done key

### Operating System

Linux Ubuntu 22.04

### Spotube version

v3.4.0

### Installation source

GitHub Releases (Binary)

### Additional information

After receiving this problem, I deleted and reinstalled the software, but the problem was not solved
This content is related to the log file:

============================== CATCHER 1 LOG ==============================
Crash occurred on 2024-01-01 19:09:29.907791

------- DEVICE INFO -------
name: Ubuntu
version: 22.04.3 LTS (Jammy Jellyfish)
id: ubuntu
idLike: [debian]
versionCodename: jammy
versionId: 22.04
prettyName: Ubuntu 22.04.3 LTS
buildId: null
variant: null
variantId: null
machineId: 140d68ac67ba4e4a8836784719db8ed1

------- APP INFO -------
environment: release
version: 3.4.0
appName: spotube
buildNumber: 27
packageName: spotube

---------- ERROR ----------
Bad state: Stream has already been listened to.

------- STACK TRACE -------
#0      _StreamController._subscribe (dart:async/stream_controller.dart:686)
#1      _ControllerStream._createSubscription (dart:async/stream_controller.dart:836)
#2      _StreamImpl.listen (dart:async/stream_impl.dart:471)
#3      useDeepLinking.<anonymous closure> (package:spotube/hooks/configurators/use_deep_linking.dart:64)
#4      _EffectHookState.scheduleEffect (package:flutter_hooks/src/primitives.dart:229)
#5      _EffectHookState.initHook (package:flutter_hooks/src/primitives.dart:209)
#6      _extension#0._createHookState (package:flutter_hooks/src/framework.dart:338)
#7      HookElement._use (package:flutter_hooks/src/framework.dart:480)
#8      Hook.use (package:flutter_hooks/src/framework.dart:139)
#9      use (package:flutter_hooks/src/framework.dart:18)
#10     useEffect (package:flutter_hooks/src/primitives.dart:191)
#11     useDeepLinking (package:spotube/hooks/configurators/use_deep_linking.dart:20)
#12     SpotubeState.build (package:spotube/main.dart:190)
#13     StatefulElement.build (package:flutter/src/widgets/framework.dart:5583)
#14     ConsumerStatefulElement.build (package:flutter_riverpod/src/consumer.dart:542)
#15     HookElement.build (package:flutter_hooks/src/framework.dart:436)
#16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5471)
#17     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#18     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#19     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2895)
#20     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:984)
#21     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457)
#22     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325)
#23     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255)
#24     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113)
#25     _invoke (dart:ui/hooks.dart:312)
#26     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383)
#27     _drawFrame (dart:ui/hooks.dart:283)

------- CUSTOM INFO -------
======================================================================

**Comment by hamkg** [comment]
Fixed, see https://github.com/KRTirtho/spotube/issues/978#issuecomment-1873413726
