### ISSUE TITLE
Continuing discussion about Ui Design

### ISSUE THREAD

**Issue by Banana021s** [KRTirtho/spotube#997]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

hey bro!
in this [issue](https://github.com/KRTirtho/spotube/issues/984) we talked about the design as i told u i need to contact u cause i just can give u the design that my team or your team will create so yah
we need to talk if you want 
please send back me an answer :)

### Suggested solution

The design would be something like this <br>
![image](https://github.com/KRTirtho/spotube/assets/89915857/dacb315e-997a-4ac5-8fb7-094db0780e18)<br>
but i need to change it a little bit because i think u need some changes, besides that i have to know is this design easy to implement for u guys?

**Comment by KRTirtho** [comment]
Let's continue discussion in https://github.com/KRTirtho/spotube/issues/984. No need to create another issue.
